### ISSUE TITLE
Website is pointing to the wrong Git repository

### ISSUE THREAD

**Issue by scranen** [json-schema-org/json-schema-spec#10]
The json-schema.org homepage points to [json-schema/json-schema](http://github.com/json-schema/json-schema), where it should point to [json-schema-org/json-schema-spec](http://github.com/json-schema-org/json-schema-spec).

**Comment by Acubed** [comment]
This would be an issue to file with https://github.com/json-schema-org/json-schema-org.github.io probably

**Comment by Acubed** [comment]
This issue duplicates <https://github.com/json-schema-org/json-schema-org.github.io/issues/3> so I'll close this out.
