### ISSUE TITLE
Arrays with multiple dimensions

### ISSUE THREAD

**Issue by eirikeve** [json-schema-org/json-schema-spec#1003]
Hi,

Are there any practical approaches to representing higher dimensional arrays using JSON Schema?  

I see in the 2019-09 specification [section 6.4.1](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.4.1) that `minItems` / `maxItems` should be integers > 0. In OAI/OpenAPI-Specification#273 nested arrays are suggested, e.g. for a `[64, 1024]` array of floats:
```json
{
  "type": "array",
  "minItems": 64,
  "maxItems": 64,
  "items": {
    "type": "array",
    "minItems": 1024,
    "maxItems": 1024,
    "items": {
       "type": "number"
    }
  }
}
```
For arrays with multiple dimensions, that approach is pretty verbose.

I'm wondering if it's possible to express it a bit more compactly. E.g. if `minItems` / `maxItems` could be lists, we could express array shapes this way: 
```json
{
  "type": "array",
  "minItems": [64, 1024],
  "maxItems": [64, 1024],
  "items": {
    "type": "number"
  }
}
```
Or something like the following if the first dimension can be of arbitrary length:
```json
{
  "type": "array",
  "minItems": [0,    1024],
  "maxItems": [null, 1024],
  "items": {
    "type": "number"
  }
}
```

If there are any good existing approaches to this, it would be great to know. 😄 
Otherwise, something like the above could be a practical approach to defining nd-arrays compactly.

**Comment by Relequestual** [comment]
The verbose structure matches how the rest of JSON Schema works. The value of `items` is a schema and is applied at the current instance location.

There are a lot of things in JSON Schema some consider verbose. That's OK. We could make a shorthand for many parts, but it would make the processing model harder, and make it harder to read and understand Schemas for humans.
