### ISSUE TITLE
"unevaluated" vocabulary not included in draft2019-09 meta-schema

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#1012]
https://github.com/json-schema-org/json-schema-spec/blob/2019-09/schema.json

It is correct in master, but it would be good to update the branch as well.

**Comment by epoberezkin** [comment]
ah, it's not split in this branch

**Comment by Relequestual** [comment]
Hey @epoberezkin 
A separate vocabulary for `unevaluated` doesn't exist in 2019-09.
Remember, the master branch is work in progress ONLY.
Note the commit message for that change: 

https://github.com/json-schema-org/json-schema-spec/commit/dc2352bc99169aabbf6fa5e655eb569dc088003b

For published meta-scheams, used tagged locations in the repo, or (I think) releases, or the website.

**Comment by epoberezkin** [comment]
Yes, I got it. I was just looking at two different places by mistake.

**Comment by handrews** [comment]
You could add a vocabulary for 2019.  As long as it's documented to declare the same syntax and semantics for those keywords as the spec, then any implementation that recognizes it could use it to check for whether those keywords are needed.  It would just overlap unlike the 2020 set which has them totally separate, but overlapping compatible vocabularies are intentionally allowed.

**Comment by Relequestual** [comment]
I guesssss you could do that.

**Comment by handrews** [comment]
I mean, you don't *have* to, I'm just pointing out more ways that vocabularies provide options for features even when the spec didn't think of it (yet). 🙂

**Comment by handrews** [comment]
(and the "you" was "other people", not "spec team retrofits 2019-09 and confuses people about how that works")
