### ISSUE TITLE
Confirm if output schema needs updating

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#1014]
Hey @gregsdennis 
In the 2019-09 spec: http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.4.5

> For convenience, JSON Schema has been provided to validate output generated by implementations. Its URI is: <https://json-schema.org/draft/2019-09/output/schema>. 

Does this schema need updating for 2020-11?
It LOOKS like it might do, for example, it still uses `recursiveRef` as opposed to `$dynamicRef`.

Can you handle this? Looking to get things out pretty soonish.

**Comment by gregsdennis** [comment]
Output schema _does_ need updating, but only in that regex.  PR forthcoming.

**Comment by Relequestual** [comment]
Thanks for checking and making a move on it!
