### ISSUE TITLE
Property name restriction based on values of array

### ISSUE THREAD

**Issue by ASnow** [json-schema-org/json-schema-spec#102]
I want get validation schema for something like this:
```
{
  "base_keys_collection": [
    {"name": "key1"}, // "keyN" is just for example it could be any string
    {"name": "key2"},
    {"name": "key3"}
  ],
  "base_values_collection": [
    {"name": "value1"}, // "valueN" is just for example it could be any string
    {"name": "value2"},
    {"name": "value3"}
  ],
  "target_validated_collection": {
    "key1": ["value1", "value2"],
    "key2": ["value1", "value3"]
  }
}
```
it should validate `target_validated_collection` properties by `base_keys_collection/*/name` and `target_validated_collection` property's values by `base_values_collection/*/name`

I think it could be done by definitions. We should define `Keys` and `Values` and use them as templates  for object properties.

**Comment by Relequestual** [comment]
I don't understand how what you are suggesting is beyond what `definitions` already provides. Could you elaborate?

**Comment by awwright** [comment]
@ASnow Can you please provide an example of how the keyword might work?

**Comment by ASnow** [comment]
{
  brands: [
   "Lada",
   "BMW",
   "Opel",
   "Audi"
  ],
  transport: [
   'car',
   'motorcycle'
  ],
  products: {
    "BMW": ['car', 'motorcycle'],
    "Lada": 'car'
  }
}

I need to verify `products` by `brands` and `transport`

**Comment by awwright** [comment]
@ASnow An example of the schema keyword, used in a schema. How would it work?

**Comment by epoberezkin** [comment]
@ASnow I think what you want would be covered by propertyNames #70 (which allows to validate keys against any schema, so you would be able to use enum).

**Comment by epoberezkin** [comment]
And if you want to have dynamic value of enum it is covered by @data proposal: https://github.com/json-schema/json-schema/wiki/$data-(v5-proposal)

**Comment by ASnow** [comment]
@epoberezkin,  thanks. Those features will cover this problem.
