### ISSUE TITLE
Identify a list of changes in master branch that were done after 2019-09-01 

### ISSUE THREAD

**Issue by derberg** [json-schema-org/json-schema-spec#1031]
To make sure changelog contains the list of all the changes in the core, all changes to master need to be reviewed. @Relequestual needs a list of commits that require manual review against current changelog.

Assumption is I work on a script that will create a list of commits + full commit message for commits that were pushed to master after 2019-09-01:
- and commits did not go through PR flow
- and commits comes from a merge of PR that is part of `draft-08-patch1 (draft 2020-NN)` milestone

**Comment by derberg** [comment]
Task completed from my side:
- commits that you need to now modify manually https://derberg.github.io/json-schema-changelog-script/index.html
- commits that were excluded by my script https://derberg.github.io/json-schema-changelog-script/excluded.html

Project that I created for this is here https://github.com/derberg/json-schema-changelog-script/. There is an instruction how to run it with npx easily at anytime, you just need to get GitHub personal token for it.

@Relequestual Feel free to let me know that some things need improvement

**Comment by Relequestual** [comment]
Thanks. I Think you only highlighted a few issues but they all help

**Comment by derberg** [comment]
@Relequestual you mean there was something wrong with the script?

**Comment by Relequestual** [comment]
No no, it looks accurate.
I meant, as a result of using the data you generated, I added only a few items to the change log. I was expecting it might be more!

**Comment by derberg** [comment]
😌 
that is good, at least you could easily make sure not much is missing

**Comment by karenetheridge** [comment]
FWIW, the list of changes that I identified for myself that I need to pay attention to in my implementation are:


- $recursiveRef and $recursiveAnchor are gone, replaced by $dynamicRef and $dynamicAnchor with new semantics
- changes to array applicators (items split into items+prefixItems; additionalItems is gone; contains now produces annotations) and interactions between them
- $anchor syntax has changed
- output representation has changed (instanceLocation, keywordLocation)
- unevaluated* is now in its own vocabulary; unevaluatedItems also uses annotations from contains
- format vocabulary split into two, with some semantic changes

**Comment by Relequestual** [comment]
I beliece all but the last 2 items are covered in the changelog in one way or another.
Thanks for checking on this!

**Comment by Relequestual** [comment]
I beliece all but the last 2 items are covered in the changelog in one way or another.
Thanks for checking on this!
