### ISSUE TITLE
compact "rel" URIs

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#104]
LDO `rel` values currently need to be either IANA-registered or full URIs.  This gets extremely cumbersome and unreadable in a system that has a lot of non-standard relations.  While this is a good motivation to focus on standard relations in new projects, that is not always practical.

I propose either that `base` be applied to `rel` resolution as well as `href`, or that we add a new keyword, `relBase`, to independently set the relation resolution base.

The only difficulty is how to disambiguate a non-standard URI Reference vs an IANA-registered name without actually having to somehow look up the IANA registry.  Anyone have any ideas on this?  Assuming this is considered a good idea at all.

**Comment by awwright** [comment]
You have to be able to distinguish between a URI and a registered link relation name, so you can't have URI References.

There are other solutions for compacting custom link relations, see https://www.w3.org/TR/curie/ and https://www.w3.org/TR/html-rdfa/ for some examples.

**Comment by handrews** [comment]
> You have to be able to distinguish between a URI and a registered link relation name, so you can't have URI References.

Yes, I did in fact point out that problem and ask for help solving it, and acknowledging what I write instead of being as critical as possible would make this sort of exchange much more enjoyable.

> The only difficulty is how to disambiguate a non-standard URI Reference vs an IANA-registered name without actually having to somehow look up the IANA registry.

As for Curies, they look great, but using them will require some specification work on our part:

> CURIEs and SafeCURIEs map to IRIs, but neither a CURIE nor a Safe_CURIE is an IRI or URI. Accordingly, CURIEs and Safe_CURIEs MUST NOT be used as values for attributes or other content that are specified to contain only URIs, IRIs, URI-references, IRI-references, etc. Specifications for particular attribute values or other content MAY be written to allow either CURIEs or IRIs (or URIs, etc.). The specifications for such languages MUST provide rules for disambiguation in situations where the same string could be interpreted as either a CURIE or an IRI. One way to do this is to require that all CURIEs be expressed as Safe_CURIEs, implying that all unbracketed strings are to be interpreted directly as IRIs.

I would be in favor of this- I don't care about them being URI references with a schema-specified base, I just care about them being less awkward.

**Comment by handrews** [comment]
Upon further examination, the CURIE specification identifies itself as a draft that should not be cited as any sort of stable format, and I don't see how RDFa, which is a mechanism for adding machine-readable content to human-oriented content, is relevant to a media type that is already machine-oriented.

So I don't see a solution here.  Is there something I'm missing?

If we just don't care about the readability of link relations, that's fine, I can always write a preprocessor that fixes it when converting from YAML (I've found it's much better for humans to write schemas in YAML and then convert to JSON as a build step).  I don't meant to insist that this _must_ be solved within JSON Hyper-Schema, just that it seemed compatible with mechanisms we already have for making other URIs more convenient to work with.

**Comment by handrews** [comment]
Closing this because the CURIE "standard" is a draft, RDFa does not seem to apply, and no one else seems to care about this topic anyway.
