### ISSUE TITLE
JSON Schema 2020 release 

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#1040]
Tasks for the release process of draft 2020, and related proceeding tasks.
Once the specification documents are published, the issue will be removed from the milestone and further tasks will be carried out.

- [x] Set up test folder for 2020-12
- [x] Final review:  Verify that the meta-schema and specification match
- [x] Final review:  Overall spelling, grammar, and wording consistency check
- [x] Final review:  Verify that all examples make sense and match current specs
- [x] Final review:  Verify that all notable changes are in the changelog section
- [x] Submit drafts to IETF (https://github.com/json-schema-org/json-schema-spec/wiki)
- [x] Update the web site
- [x] Announce on twitter / slack / open collective / google group mailing list

**Comment by karenetheridge** [comment]
Also needed: the release notes pages (linked from https://json-schema.org/specification.html)

**Comment by Relequestual** [comment]
@jdesrosiers has "volunteered" for this work as part of his docs update work.
I don't know where he wants to track this specific aspect though.
