### ISSUE TITLE
Missing apostrophe in “contains”; strange sentence

### ISSUE THREAD

**Issue by ssilverman** [json-schema-org/json-schema-spec#1043]
https://github.com/json-schema-org/json-schema-spec/blob/803ce7dd3e08e02596477814f49d6908602e77ad/jsonschema-core.xml#L2378

Suggested sentence changes (first pass):
If the instance array to which this keyword’s  subschema is applicable is empty, the annotation value MUST NOT be missing.

To clarify: is this supposed to be saying that a “contains” annotation MUST be there if the instance array is empty?

Suggested changes, second pass:
The annotation value MUST be present if the instance array to which this keyword’s subschema applies is empty.

**Comment by ssilverman** [comment]
To add to my editing thoughts: negative logic in prose is harder to follow than positive logic.

**Comment by Relequestual** [comment]
> To clarify: is this supposed to be saying that a “contains” annotation MUST be there if the instance array is empty?

Yes.

And yeah go ahead and PR that =]
