### ISSUE TITLE
2020-12-rc1 changelogs contain empty bullet points

### ISSUE THREAD

**Issue by rjmill** [json-schema-org/json-schema-spec#1045]
The changelogs for the 2020-12-rc1 drafts have empty bullet points. For example in the validation spec:
![image](https://user-images.githubusercontent.com/12422195/100771521-80ab7f80-33cc-11eb-86b0-329b939b8ffb.png)

The empty bullet points are present in the [core spec](https://json-schema.org/draft/preview/2020-12-rc-1/jsonschema-core.html#rfc.appendix.G) and the [validation spec](https://json-schema.org/draft/preview/2020-12-rc-1/jsonschema-validation.html#rfc.appendix.C)

Also, thank you for all the hard work that went into this draft!

**Comment by rjmill** [comment]
Oh, looking at the [git history](https://github.com/json-schema-org/json-schema-spec/commit/499a5bc8), the empty bullet points appear to be intentional. They're meant to help prevent merge conflicts when updating the changelog.

Feel free to close this ticket, since it sounds like the issue is already being tracked :slightly_smiling_face:

**Comment by Relequestual** [comment]
yeaaah =]
