### ISSUE TITLE
concerns with order of evaluation with unevaluated* keywords

### ISSUE THREAD

**Issue by karenetheridge** [json-schema-org/json-schema-spec#1047]
The spec (https://json-schema.org/draft/preview/2020-12-rc-1/jsonschema-core.html#rfc.section.11.1) says, regarding unevaluatedItems:

> This means that "prefixItems", "items", "contains", and all in-place applicators MUST be evaluated before this keyword can be evaluated. Authors of extension keywords MUST NOT define an in-place applicator that would need to be evaluated before this keyword. 

If I wanted to create a new applicator keyword "twoOf", and it is evaluated after unevaluatedItems, then any annotations collected by its subschemas will not be visible to unevaluatedItems. So therefore, shouldn't this wording be "..would need to be evaluated **after** this keyword"?

**Comment by Relequestual** [comment]
I think this is intentional, just like you can't define a keyword that interfears with say `additionalProperties`.  What must be checked before `additionalProperties` is fixed and known, and another vocabulary can't modify an existing one.

**Comment by gregsdennis** [comment]
I agree with @karenetheridge.  `unevaluated*` should be evaluated *last* always.

**Comment by karenetheridge** [comment]
> What must be checked before additionalProperties is fixed and known

But it [the line of the spec in question] is not restricting what can be run before additionalProperties, but what can be run before unevaluatedItems.

**Comment by gregsdennis** [comment]
To expand on my agreement on this, the intended purpose of `unevaluated*` was to aggregate annotations from subschemas of applicator keywords.  If a user adds an applicator keyword, and that keyword is processed _after_ `unevaluated*`, then `unevaluated*` isn't being processed in accordance with that intent.

Section 11 leads out with a statement declaring this purpose clearly:

> The purpose of these keywords is to enable schema authors to apply subschemas to array items or object properties that have not been successfully evaluated against _any dynamic-scope subschema of any adjacent keywords_.

To process `unevaluated*` _before_ any applicator keyword would be contrary to this purpose.

I think it would help clarify things to explicitly state that `unevaluated*` MUST be processed _at a minimum_ after all applicator keywords.  However, it _should_ (not SHOULD) be fine to let non-applicator validations be processed after `unevaluated*`.

**Comment by Relequestual** [comment]
> > What must be checked before additionalProperties is fixed and known
> 
> But it [the line of the spec in question] is not restricting what can be run before additionalProperties, but what can be run before unevaluatedItems.

Right, I was using that as an example.

I remember the original discussion, but I'm also inclined to agree.
I'd say go for PR.

First sentence should probably say something like "...including any defined by other vocabularies"

**Comment by handrews** [comment]
@karenetheridge 🤦 
yeah, it should be after and not before.

@gregsdennis what you say is correct except restricted to in-place applicators, not all applicators.  For example it doesn't matter whether `items` is evaluated before or after `unevaluaedProperties` (but `items` has to be evaluated before `unevaluatedItems`, which is a keyword-specific rule, not a classification-based rule).
