### ISSUE TITLE
npm/bower support

### ISSUE THREAD

**Issue by brettz9** [json-schema-org/json-schema-spec#105]
Because JSONSchema is itself defined in JSONSchema, there are uses for importing the spec into other repos, such as generating a UI to allow users to edit JSON schemas where the spec itself would be used to define what was allowable in the editing interface.

Please consider npm/bower support to allow for easy utilization within other projects.

**Comment by awwright** [comment]
I don't think it's really in-scope for this project to be pushing packages to package managers. But I suppose I could do that personally. I would have to think how to do that, the meta-schemas are fixed files that don't change.

So probably the best option is just to bundle the meta-schemas with the package.

**Comment by brettz9** [comment]
If it can be kept up to date, a separate package would be great.

**Comment by handrews** [comment]
Since this is not in-scope for this project, can we close it and track it somewhere else where work is likely to happen?  If we want to document the stance of the project with respect to Bower, that would be a json-schema-org/json-schema-org.github.io issue or pull request.

**Comment by epoberezkin** [comment]
I'd say bower is dead by now... 80k daily installs vs 85m daily npm downloads. I don't see much reason to publish this on npm too, as we would kind of show more connection to JS-land than is beneficial to the standard. Just an opinion, I am not precious about it.

**Comment by epoberezkin** [comment]
npm cli perfectly works with github, it supports short names ("org/repo"). So maybe we just need a page to explain how to integrate in different platforms rather than maintain all sorts of repositories in all the languages.

**Comment by brettz9** [comment]
Using Github URLs doesn't work with versioning support (except where one adds in a specific commit or branch for each version in which case I think one may as well just publish to npm).

**Comment by awwright** [comment]
@brettz9 I would strongly suggest bundling the meta-schemas that you support with whatever package you're deploying. New schemas are going to be given new URIs, so there's not too much point in having a central authority, since it's not going to change.

Nonetheless, I created <https://www.npmjs.com/package/json-metaschema> for your convenience.

**Comment by brettz9** [comment]
Thank you very much, @awwright ...
