### ISSUE TITLE
Degree of formality for third-party vocabularies

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#1058]
*This may be more appropriate for https://github.com/json-schema-org/json-schema-vocabularies, but I'm adding it here because this is where we define vocab requirements.  Feel free to move it.*

Do we expect that third-party vocabularies need to be written as formal specifications (like this spec is), or will any simple, published document (e.g. a Google doc or a blog post) suffice as long as it's specific enough for an implementor to write behavior for its keywords?

**Comment by jdesrosiers** [comment]
I think we should make it as easy as possible for people to make vocabularies. Something as informal as a README on a Github repo is good enough for me.

**Comment by handrews** [comment]
I might write a vocabulary for private use within a company, so there should not even be a requirement for a publicly published document.  If an implementation supports dynamically loadable extension modules, I should be able to write a module for my private vocabulary and use it internally (b/c the implementation knows to connect the URI to the module) without having to publish anything outside of the company.

**Comment by handrews** [comment]
Fixed by PR #1103.  I always use the wrong words for the auto-close.
