### ISSUE TITLE
prohibit $ keywords outside of the core vocabulary

### ISSUE THREAD

**Issue by karenetheridge** [json-schema-org/json-schema-spec#1061]
Currently the spec just RECOMMENDS that $-prefixed keywords be avoided: https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-8

Given that we expect to see some new vocabularies springing into existence soon, now is the time to strengthen that restriction to a MUST NOT.

**Comment by Relequestual** [comment]
I'm going to say nope on this.
I already have some ideas of where I'd want to use $-prefixed keywords for other vocabularies.
I think it's fine as is.

**Comment by jdesrosiers** [comment]
I think it's good idea to reserve a namespace ("$") where we can add core keywords without risk of conflicting with someone else's vocabulary. I'd rather go with a SHOULD NOT than MUST NOT tho. I prefer to reserve MUST NOT for things that will definitely break things, and use SHOULD NOT for things that are likely to break things.

**Comment by handrews** [comment]
We avoided MUST NOT because people have `$`-prefixed fields out in the wild, and it did not seem like a good idea for them to suddenly become invalid.  SHOULD NOT should encourage people to migrate away from that without immediate breakage.

**Comment by handrews** [comment]
It seems like we still think SHOULD is better than MUST here (even if, were we starting from a clean slate, we probably would have gone with MUST).  Since RECOMMENDED has the same effect as SHOULD, that means there would be nothing to do for this.  

@karenetheridge is there more you want to discuss here?  If not, can we close this?

**Comment by karenetheridge** [comment]
Ok. I wonder if we should clarify the definitions of MUST, RECOMMENDED, SHOULD etc (yes, I know there is an RFC for this, but perhaps we can clarify what this means in the context of our specification). Especially in the light of recent discussions about spec compliance, it seems that this might not be as clear as it could be.

**Comment by handrews** [comment]
@karenetheridge I don't understand how this is unclear?  RECOMMENDED has, as you noted, an RFC-defined meaning, and we are using it in a normal way.  If you feel that the more common "SHOULD NOT" would be better than "NOT RECOMMENDED", I have no objection to changing that.
