### ISSUE TITLE
Override $ref in external reference

### ISSUE THREAD

**Issue by unional** [json-schema-org/json-schema-spec#1076]
When I'm writing some json schema and try to organize them, I notice current we cannot override the reference of external references, resulting limitation in extending the schema.

For example, I have define this little functional programming language `just-func`: https://github.com/justland/just-func-json/blob/main/json-schema/just-func.jsonc

In the schema, one of the definition looks like this:

```jsonc
// just-func.jsonc
    "JustUnaryFunctions": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "enum": ["not","ret"],
          "description": "Basic unary functions:\nnot: logical not\nret: retrieve value defined by `let`"
        },
        {
          "$ref": "#/definitions/JustFunc"
        }
      ],
      "additionalItems": false
    }
```

Notice I have a `"$ref": "#/definitions/JustFunc"` here.

When using this language, I would extend it by defining additional functions, e.g.:

```jsonc
// my-app.jsonc
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "description": "Validation schema for my-app written in just-func",
  "definitions": {
    "MyJustFunc": {
      "oneOf": [{
        "$ref": "just-func.jsonc/#/definitions/JustFunc"
      }, {
        "$ref": "#/definitions/MyExtensions"
      }]
    },
    "MyExtensions": {
      // ... snip ...
    }
  }
}
```

The problem is, if I use one of the default definition provided in `just-func.jsonc`,
they does not recognize the functions I defined in `MyExtensions` because their reference is `(just-func.jsonc)#/definitions/JustFunc` instead of `(my-app.jsonc)#/definitions/MyJustFunc`.

To solve this, we need a way to override the reference something akin to:

```jsonc
{
  "$override": {
    "just-junc.jsonc": {
      "#/definitions/JustFunc": "/#/definitions/MyJustFunc" // using `/#` to indicate it is a local reference
    }
  }
}
```

🌷

**Comment by gregsdennis** [comment]
@unional it looks like you might be using https://github.com/tcorral/JSONC, is that right?  I think your question might be more specific to that library than JSON Schema in general.

JSON Schema doesn't define functions or a way to reference them.  `$ref` for JSON Schema is merely a pointer to another schema object.

**Comment by unional** [comment]
Not using that. I think the question is about json schema. It is about how to override the reference because in these use case we need to extend or modify the reference. 

It's similar to the concept of generics or composition, where the reference need to be open for extension. 

One way to do that is by providing an overriding mechanism. 

Hope this helps. 🤗

**Comment by unional** [comment]
The `jsonc` in the example is just json with comments. It can be json or yaml.

**Comment by unional** [comment]
The function in the OP is referring to the function defined in `just-func`. Just think of it as an array or simply data structure. What I'm defining is a simple functional programming similar to `clojure` and `lisp`, where code (function) is just data. 

E.g.:

`['or', 1, 2]` evaluates to `false`

**Comment by unional** [comment]
The current workaround is to copy the content of `just-func.jsonc` to `my-app.jsonc` and modify all `$ref` of `JustFunc` to `MyJustFunc`. 

That means the `just-func.jsonc` can only be used as a template.
It cannot be referenced and reused.

**Comment by gregsdennis** [comment]
It still seems there's some project-specific knowledge that you have that isn't pertinent to JSON Schema.

> It's similar to the concept of generics or composition

JSON Schema is not designed for object-oriented concepts.  It's a constraints system, which is effectively the opposite of ideals like polymorphism.  Composition of schemas creates a more constrained object; it can't extend objects.

> Just think of it as an array or simply a data structure.

But as I said, in JSON Schema, `$ref` can only point to another schema object.  It can't point to random data.

I think what you want is to define a new vocabulary with a new keyword that can reference data.  (Or better yet, implement [mine](https://gregsdennis.github.io/json-everything/usage/vocabs-data.html) in JS.)

(Finally, as a side note, you may want to checkout [JSON Logic](https://jsonlogic.com/).  It does some of the things you're mentioning, but not references.)

**Comment by unional** [comment]
Thanks for the JSON Logic link. 

It is similar concept. 
The question is about extensibility. 


Another difference is that we are talking about defining a JSON schema that describes the data structure, e.g. `{ 'var': 'temp' }` in JSON logic. 

It will have the same problem if it opens the system and make it extensible.

**Comment by unional** [comment]
> But as I said, in JSON Schema, $ref can only point to another schema object. It can't point to random data.

It is pointing to a schema object, as in `"$ref": "#/definitions/JustFunc"`. 

The situation I'm describing is that the reference needs to be overridden (or "extends" with `oneOf`) in order to be reusable.

**Comment by unional** [comment]
> Composition of schemas creates a more constrained object; it can't extend objects.

May be this is the limitation.
I can't reuse it by composition and extend it at the same time.

**Comment by unional** [comment]
Just want to point out that this is not necessary a edge case.
Today it is not possible to extend schema for plugin configuration due to the same limitation.
For example, `babel` supports plugins and each plugin can have their addition settings.

```json
{
  "presets": [
    ['@babel/preset-typescript', {
      "allowNamespaces": true // cannot specify schema for this
    }],
  ]
}
```

Today the only way to do this is to "pollute" the base `babel` json schema with all the plugin's setting, which is not ideal.

The same thing happens to other configs, such as `tsconfig.json` for TypeScript.

**Comment by karenetheridge** [comment]
Having a need to "override `$ref`" is something that you might be able to fulfill with the `$recursiveRef` and `$recursiveAnchor` keywords in draft 2019-09, or `$dynamicRef` and `$dynamicAnchor` in draft 2020-12. The metaschemas themselves use these keywords to dynamically extend the definition of the overall schema (which is recursively referenced by all applicator keywords such as `not` and `allOf`).

**Comment by unional** [comment]
Thanks. That's would be great.
I saw the draft but maybe because it is too new, I can't find any additional examples of it.

I looked at the example there but not sure if I grasp the idea. 😛 .

Do you know of any additional writeup about that feature?

thx

**Comment by Relequestual** [comment]
> 
> 
> Thanks. That's would be great.
> I saw the draft but maybe because it is too new, I can't find any additional examples of it.
> 
> I looked at the example there but not sure if I grasp the idea. 😛 .
> 
> Do you know of any additional writeup about that feature?
> 
> thx

It is one of the most tricky aspects of JSON Schema, but once you grasp it, it makes total sense.
It's probably easier to look at the example in the appendix of the specification itself...

https://tools.ietf.org/html/draft-bhutton-json-schema-00#appendix-C

It's likely that you may need to read it 3 or 4 times, and draw diagrams.
We're happy to help on our slack server (or here) should you have follow up questions.

---

As an aside, there was recently a webinar on OpenAPI 3.1 where they showed using `$ref` and overriding specific properties. Unfortunately, this was inaccurate, and can only be done in OpenAPI 3.1 when using a "Reference Object" and not a "Schema Object". I don't know is this has contributed to your confusion here or not.

**Comment by unional** [comment]
Thanks. Yes I joined that webinar too.
The `$ref` override mentioned there is about override specific properties like you said.
This is about extending the definition of the referenced Schema Object. So I think we are good. :)

> https://tools.ietf.org/html/draft-bhutton-json-schema-00#appendix-C
Yes, that's what I saw too.

Let me try to give it a shoot to explain that in my own words to see if it make sense.

To simplify things, I refer the strict-tree schema as `strict-tree.json` and the tree schema as `tree.json`.

Since `strict-tree.json` has:
```json
{
  "$ref": "tree",
  "unevaluatedProperties": false
}
```
It stated the whole `strict-tree.json` is "extending from `tree.json` while restricting any unevaluated properties.

Then, in the `/children/items` in `tree.json`, it has `$dynamicRef: #node` which is defined by `$dynamicAnchor: node` in the same document.

If `$dynamicAnchor: node` was not defined in `tree.json` and it actually defined like this:

```jsonc
// tree.json
{
  "type": "object",
  "properties": {
    "children": {
      "type": "array",
      "items": {
        "$ref": "#definitions/node"
      }
  },
  "definitions": {
    "node": { "type": "string" } // just for example
  }
}
```

Than it is referencing the `definitions/node` schema object.

One question: if the `$dynamicAnchor: node` was not defined in `tree.json`, i.e.:

```jsonc
{
  "properties": {
    "children": {
      "type": "array",
      "items": { "$dynamicRef": "#node" }
    }
  }
}
```

This would be invalid due to the missing `$dynamicAnchor`?

The spec then mentioned:

>    In this case, the outermost resource also has a "node" fragment defined by "$dynamicAnchor".  Therefore instead of resolving the "$dynamicRef" to "https://example.com/tree#node", we resolve it to "https://example.com/strict-tree#node".

So my guess is that the `$dynamicAnchor: node` defined in `strict-tree.json` is saying:

"Hey, the `tree.json` schema I based on has this dynamic anchor `node`, so as I also defining this anchor here, when `tree.json` try to use `$dynamicRef` to look up `node`, use me instead of what's originally in `tree.json`.

With that said, then my use case can be implemented like this (simplified to just demonstrate the key points):

```jsonc
// just-func.jsonc
{
  "definitions": {
    "JustFunc": {
      "$dynamicAnchor": "definitions/JustFunc",
      "oneOf": [{
        "$dynamicRef": "#definitions/JustEq"
      }]
    },
    "JustEq": {
      "$dynamicAnchor": "definitions/JustEq",
      "type": "array",
      "items": [{
         "type": "string",
         "const": "eq"
      }, {
        "$dynamicRef": "#definitions/JustFunc"
      }, {
        "$dynamicRef": "#definitions/JustFunc"
     }],
    "additionalItems": false
  }
}
```

And in an application (`my-app.jsonc`) where I add a new definition called `JustParamGet`:

```jsonc
// my-app.jsonc
{
  "definitions": {
    "JustFunc": {
      "$dynamicAnchor": "definitions/JustFunc",
      "oneOf": [{
        "$dynamicRef": "#definitions/JustEq"
      }, {
        // don't need to be `$dynamicRef` because this is application specific,
        // and will not be extended or overridden by others.
        // but if this is a library that will be used by other applications,
        // this need to be `$dynamicRef`, and
        // the `definitions/JustParamGet` needs to declare `$dynamicAnchor`
        "$ref": "#definitions/JustParamGet"
      }]
    },
    "JustParamGet": {
      "type": "array",
      "items": [{
        "type": "string",
        "const": "param/get"
      }, {
        "$dynamicRef": "#definitions/JustFunc"
      }]
    }
  }
}
```

In this attempt, I have to (and assume):

- repeat everything in `just-func.json#definitions/JustFunc` because I lost the ability to reference to original schema, or else it will be an infinite loop.
- All references in `just-func.jsonc#definitions/JustFunc` needs to use `$dynamicRef` so that they can be referenced in `my-app.jsonc`

If both of the points above is not correct, maybe the following will work?

```jsonc
// just-func.jsonc
{
  "definitions": {
    "JustFunc": {
      "$dynamicAnchor": "definitions/JustFunc",
      "oneOf": [{
        // just regular reference
        "$ref": "#definitions/JustEq"
      }]
    },
    "JustEq": {
      "type": "array",
      "items": [{
         "type": "string",
         "const": "eq"
      }, {
        "$dynamicRef": "#definitions/JustFunc"
      }, {
        "$dynamicRef": "#definitions/JustFunc"
     }],
    "additionalItems": false
  }
}
```


```jsonc
// just-func.jsonc
{
  "definitions": {
    "JustFunc": {
      "$dynamicAnchor": "definitions/JustFunc",
      "oneOf": [{
        "$dynamicRef": "#definitions/JustEq"
      }]
    },
    "JustEq": {
      "$dynamicAnchor": "definitions/JustEq",
      "type": "array",
      "items": [{
         "type": "string",
         "const": "eq"
      }, {
        "$dynamicRef": "#definitions/JustFunc"
      }, {
        "$dynamicRef": "#definitions/JustFunc"
     }],
    "additionalItems": false
  }
}
```

And in an application (`my-app.jsonc`) where I add a new definition called `JustParamGet`:

```jsonc
// my-app.jsonc
{
  "definitions": {
    "JustFunc": {
      "$dynamicAnchor": "definitions/JustFunc",
      "oneOf": [{
        // This might not work, as it defines `$dynamicAnchor` in there,
        // causing conflict
        // "$ref": "just-func.jsonc#definitions/JustFunc
        //
        // so still have to repeat what's in there, using external reference
        "$ref": "just-func.jsonc#definitions/JustEq
      }, {
        "$ref": "#definitions/JustParamGet"
      }]
    },
    "JustParamGet": {
      "type": "array",
      "items": [{
        "type": "string",
        "const": "param/get"
      }, {
        "$dynamicRef": "#definitions/JustFunc"
      }]
    }
  }
}
```

One more way to improve this is create one more indirection in `just-func.jsonc#definitions/JustFunc` to separate the anchor and the definition:

```jsonc
// just-func.jsonc
{
  "definitions": {
    "JustFunc": {
      "$dynamicAnchor": "definitions/JustFunc",
      "$ref": "#definitions/JustFuncSpec"
    },
    "JustFuncSpec: {
      "oneOf": [{ /* ... snip ... */ }]
     }
  }
}
```

```jsonc
// my-app.jsonc
{
  "definitions": {
    "JustFunc": {
      "$dynamicAnchor": "definitions/JustFunc",
      "oneOf": [{
        "$ref": "just-func.jsonc#definitions/JustFuncSpec",
      }, {
        "$ref": "#definitions/JustParamGet"
      }]
    }
  }
}
```

**Comment by unional** [comment]
I tried to get it working using `$recursiveRef` and `$dynamicRef`.
Currently the schema seems to be valid but the validation fails (using `ajv`).
Not sure what is the right approach yet.

Here is what I have if you are interested:
https://github.com/justland/just-func

The base schema are under `json-schema/draft-2019-09` and `json-schema/draft-2020-12`,
the override are under `spec/draft-2019-09/schema` and `spec/draft-2020-12/schema`.

**Comment by Relequestual** [comment]
I've not read all the above, but worth noting that, as far as I know, ajv doesn't support 2020-12, yet.

**Comment by unional** [comment]
> I've not read all the above, but worth noting that, as far as I know, ajv doesn't support 2020-12, yet.

Thanks. Yeah, they supports 2019-09, but also mentioned that `$dynamicRef` is also supported (at root level only).
Of course, being at the cutting edge, you never know if the failure is a false negative or not. 😛

**Comment by jdesrosiers** [comment]
@unional You can use https://json-schema.hyperjump.io to test your schemas using any JSON Schema draft from 04 to 2020-12. Just make sure to set `$schema` to tell it which draft to use. It looks like you're on the right track, but you might have a few things you need to fix before it works completely. A couple things I noticed are,

1. The `$schema` URIs are using "http". They need to be "https" for 2019-09 and 2020-12
2. The array-form-`items` and the `additionalItems` keywords have changed names in 2020-12. array-form-`items` is now `prefixItems` and `additionalItems` is `items`.

If you have a full example of a just-func extension and a just-func program, I'd be happy to help get the schema right.

**Comment by jdesrosiers** [comment]
Oh, nevermind, I found the examples I just asked for are already in the repo. I'll look through that.

**Comment by unional** [comment]
@jdesrosiers many thanks for looking into it.

btw, does json-schema specify a `version` field that the individual schema can be versioned?
I couldn't find it in the specification, but maybe I overlook it. 😝 

Currently, I can differentiate the schema by looking at which json-schema version it supports (`$schema`).
But other than that, I have to rely on specific formatting for `description` to embed the version. e.g.:

```json
{
  "description": "some description... for 1.0.1"
}
```

and do a parse to get the version number out of it.

I can't embed version in `$id` field as that will break the extension/usage.

**Comment by jdesrosiers** [comment]
We recommend that versioning be done using `$id`. I don't see how that approach would break extension, but It'd be interested in understanding why that might be.

JSON Schema allows custom keywords to be used, so you could just add the keyword `version` to your schema that your tooling can make use of. You could formalize your custom keyword as a JSON Schema Vocabulary, but that's not required.

**Comment by unional** [comment]
Yes you are right. I was thinking backwards. :)
It is good to pin down to a specific version using `$id` so that changes won't automatically picked up by consumer thus causing breaking changes.

🌷

**Comment by jdesrosiers** [comment]
@unional I tried it out your schemas on https://json-schema.hyperjump.io and everything works (with the fixes I mentioned above)! I only tried 2020-12, but there's no reason 2019-09 shouldn't work the same.

**Comment by unional** [comment]
That's great. Many thanks.

I am also able to validate it too. 👏 👏 

One last question regarding the `$id`:

It seems like requiring a protocol, and examples in the web using `https://...`,

should I use `https://github.com/justland/.../tags/v1.0.0/.../just-func.jsonc` as the `$id`?

That seems to be similar to `deno` where using the URL to resolve to the unique reference.

If that is good, then I'm all set. 🌷

**Comment by Relequestual** [comment]
> That seems to be similar to `deno` where using the URL to resolve to the unique reference.

Yeah, I noticed `deno` was using full URIs for packages.
Given recent supply chain attacks, I assume, not having looked into it, it could be more secure.

**Comment by karenetheridge** [comment]
You can also use `$comment` to specify a version for your schema. `$comment` will never be exposed to users (for example in a form generator) and you can put anything you like into it.

**Comment by unional** [comment]
Thanks for all your help and feedbacks. 🍻
