### ISSUE TITLE
Verbiage for `type` could be improved.

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#1080]
[Core Section 6.1.1](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.1)

> An instance validates if and only if the instance is in any of the sets listed for this keyword.

Here a "set" is intended to be a collection, indicating that the value should be contained within that collection.  However "in any of the sets" seems to imply there are multiple collections.

I think that the intent here was to say that the instance is valid if it is a _subset_ of the set of allowable values (which are defined in the preceding sentence), but it still reads weird.

I suggest

> An instance validates successfully if one of the following is true
> - it is a single value from the set above
> - it is an array of distinct values from the array above

This is a bit more verbose but significantly clearer.

**Comment by karenetheridge** [comment]
What does "an instance ... is an array of distinct values from the array above" mean? That makes it sound like this data: `[ 1, true, null ]` would successfully validate against the schema `{"type": [ "integer", "boolean", "null" ]}`.

I suggest:

> An instance validates successfully if one of the following is true:
> * if the value of "type" is a string, and the instance is of the singular type indicated by the "type" keyword, or
> * if the value of "type" is an array, the instance is of one of the types listed by that array

**Comment by gregsdennis** [comment]
oh... yeah 🤦‍♂️

**Comment by jdesrosiers** [comment]
:+1:  Let's fix this!

**Comment by jdesrosiers** [comment]
I'll write this up within the next day or two if there are no objections.
