### ISSUE TITLE
Composing object schemas with additionalProperties: false

### ISSUE THREAD

**Issue by sinclairzx81** [json-schema-org/json-schema-spec#1087]
Hello! I am writing hoping to get a little bit of guidance on producing a schema that allows for the intersection of two object schemas; where each intersected schema specifies `additionalProperties: false`. Below is a small example to illustrate the general intent.

```javascript
const A = {
    type: 'object',
    properties: { a: { type: 'string' } },
    required: ['a'],
    additionalProperties: false // note
}

const B = {
    type: 'object',
    properties: { b: { type: 'string' } },
    required: ['b'],
    additionalProperties: false  // note
}

const C = { allOf: [A, B] }
```
So above, I've tried to combine schemas `A` and `B` into the intersected schema `C` without needing to modify `additionalProperties: false` on each sub schema. This to achieve the following validation behavior.
```javascript
validate(A, { a: 'hello' })                   // ok
validate(A, { a: 'hello', b: 'world' })       // fail
validate(B, { b: 'world' })                   // ok
validate(B, { a: 'hello', b: 'world' })       // fail 
validate(C, { a: 'hello', b: 'world' })       // ok
validate(C, { a: 'hello' })                   // fail
validate(C, { b: 'world' })                   // fail
validate(C, { a: 'hello', b: 'world', c: 1 }) // fail 
```
Unfortunately, schema `C` is actually non validatable due to `additionalProperties: false` on `A` and `B`. 

**unevaluatedProperties**

I have been reading up on `unevaluatedProperties` on draft `2019-9`, however this keyword seems to require that `additionalProperties` is omitted on each sub schema (forcing modification of `A` and `B`). The following would be the `unevaluatedProperties` approach.

```javascript
const A = {
    type: 'object',
    properties: { a: { type: 'string' } },
    required: ['a']
}

const B = {
    type: 'object',
    properties: { b: { type: 'string' } },
    required: ['b']
}

const C = {
    type: 'object',
    allOf: [A, B],
    unevaluatedProperties: false
}
```
Unfortunately, removing `additionalProperties` on `A` and `B` has changed the intended validation behavior of each. So, this does seem to suggest that one should duplicate `A` and `B` (minus `additionalProperties`) just to compose for `C`. But I am not sure.

So i guess my question is, is there way to express the above intersection of `C` by composing `A` and `B` without modification to `A` or `B`? Any guidance or insights into this would be very helpful.

**Comment by jdesrosiers** [comment]
It sounds like you understand the situation perfectly. You aren't missing anything. Using `additionalProperties` or `unevaluatedProperties` effectively locks down a schema so it can't be composed with others. If you need to be able to compose schemas, you can't use these keywords on the schemas being composed. Generally, I would suggest building all of your schemas as open schemas. If you want it to be more strict at the system boundaries, you can always compose those schemas with `unevaluatedProperties`.

JSON Schema can't solve your problem the way you are approaching it because JSON Schema never removes constraints, it can only add them. When you have `"additionalProperties": false` on schema A, it adds the constraint that no properties other than "a" can exist. When you compose that with schema B, there is a conflict between the nothing-but-a constraint and the required-b constraint. I don't think I'm saying anything you don't already understand, but I wanted to walk through that to point out that since constraints can never be removed, I don't think it's even possible for JSON Schema to introduce a keyword that solves this problem the way you are approaching it.

One trick to make your schemas relatively easy to manage when you need your schemas to be both composable _and_ closed is to define both in the same schema.

```json
{
  "$id": "https://example.com/A",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "$ref": "#composable",
  "unevaluatedProperties": false,

  "$defs": {
    "composable": {
      "$anchor": "composable",
      "type": "object",
      "properties": {
        "a": { "type": "string" }
      }
    }
  }
}
```

Then when you want just A, you can reference `https://example.com/A` and when you need the version that's composable you can reference `https://example.com/A#composable`. So, "C" can be built like this,

```json
{
  "$id": "https://example.com/C",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "allOf": [
    { "$ref": "/A#composable" },
    { "$ref": "/B#composable" }
  ],
  "unevaluatedProperties": false
}
```

**Comment by sinclairzx81** [comment]
@jdesrosiers This is brilliant, thank you so much for your excellent write up and clarification around `unevaluatedProperties`. I usually work far upstream from the JSON schema specification; so it's extremely appreciated to get insights from people who work closely in and around the core specification.

Also thank you for the reference schemas. This is actually very helpful and provides some insights into how to approach composition. I did just want to follow up on this mention.

> Using additionalProperties or unevaluatedProperties effectively locks down a schema so it can't be composed with others.

Just to provide a bit of perspective into the original question, I am currently fairly invested in trying to find parity between TypeScript and JSON schema for data type representation. This primarily with a goal of enabling both static (TS) and runtime (JSON schema) type assertions. As of current, I've been able to express much of the TypeScript structural type system as JSON schema, but have been having some challenges adequately capturing `intersection` types as the "locked down" nature of `additionalProperties: false` disallows for composition of types that are otherwise expressible in TypeScript.

I sense there might be quite a few rationales for not supporting composition of previously constrained schemas. With this said, I am wondering if there could be a potential here for some future `compositeOf` keyword which would allow for compositing schemas previously constrained by `additionalProperties: false`.

## CompositeOf

### Example 1
The following would compose schemas `A` and `B` which each specify `additionalProperties: false`. The resulting schema `C`  would inherit the sub schema constraints, resulting in `additionalProperties: false`.

```typescript
const A = { type: 'object', properties: { a: { type: 'string' } }, required: ['a'], additionalProperties: false }
const B = { type: 'object', properties: { b: { type: 'string' } }, required: ['b'], additionalProperties: false }
const C = { compositeOf: [A, B] }

// expansion
const C = {
   type: 'object',
   properties: {
      a: { type: string },
      b: { type: string }
   },
   required: ['a', 'b'],
   additionalProperties: false
}
```

### Example 2
The following would compose `A` and `B`, with `B` allowing additional properties of type `string`. Because `B` permits additional properties, the composited schema `C` must also permit for `additionalProperties`.
```typescript
const A = { type: 'object', properties: { a: { type: 'string' } }, required: ['a'], additionalProperties: false }
const B = { type: 'object', additionalProperties: { type: 'string' }
const C = { compositeOf: [A, B] }

// expansion
const C = {
   type: 'object',
   properties: {
      a: { type: string },
   },
   required: ['a'],
   additionalProperties: { 
     type: string 
   }
}
```
### Example 3
The following would compose `A` and `B` with `B` defined as a `string`. The resulting schema `C` would be non-expressable. This would mandate that sub schemas of `C` be of type `object`
```typescript
const A = { type: 'object', properties: { a: { type: 'string' } }, required: ['a'], additionalProperties: false }
const B = { type: 'string' }
const C = { compositeOf: [A, B] }

const C = /* not expressable */
```
## TypeScript Comparisons

The following are typescript representations of the above schemas for reference purposes.

### Example 1

```typescript
type A = { a: string }
type B = { b: string }
type C = A & B
// expansion
type C = { a: string, b: string }
```

### Example 2

```typescript
type A = { a: string }
type B = { [key: string] : string }
type C = A & B
// expansion
type C = { a: string, [key: string]: string }
```

### Example 3

```typescript
type A = { a: string }
type B = string
type D = A & B 
// expansion
type D = never
```
Would be keen to know if something like this could be worth consideration or if it runs counter to some of the design considerations that went into `unevaluatedProperties`. Would be great to hear your thoughts.

Many Thanks

**Comment by jdesrosiers** [comment]
> I sense there might be quite a few rationales for not supporting composition of previously constrained schemas.

It's not a choice anyone made. It's more of an emergent property. It's a consequence of the core architectural principles of JSON Schema, especially the one that says we never remove constraints, only add them. The `compositeOf` keyword would never be accepted because it violates that rule. The A and B schemas would validate differently when used with `compositeOf` than they would by themselves.

This topic was debated for years. There were many proposals. `unevaluatedProperties` is not a great solution, but it's what we ended up with and it does make a lot of use cases easier to express.

If your goal is to emulate a type system, I'm very surprised that you are so keen on using `"additionalProperties": false`. That's the textbook example of when you _do_ want to allow additional properties. Polymorphism is only possible by allowing additional properties.

```typescript
type A = { a: string };
type B = { b: number };
type C = A & B;

const foo: C = { a: "hi", b: 222 };

const bar: A = foo;
console.log(bar.a);
console.log(bar.b); // Type Error

const baz: B = foo;
console.log(baz.b);
console.log(baz.a); // Type Error
```

Notice that you can use an object that was constructed as a C in a context that only understands A. The B parts are not needed in that context, but they aren't forbidden either. `foo` can be used as an A, B, or C depending on the context. In other words, `foo` is polymorphic. If you forbid additional properties, `foo` can only be used as a C, not an A or B like a typical polymorphic type system would allow.

To emulate TypeScript, the only time you would want to forbid additional properties is when constructing an object of a certain type. If you are validating function arguments or validating against the schema after an assignment, you want to ignore the parts that are not part of the type you are validating.

**Comment by sinclairzx81** [comment]
@jdesrosiers Thanks again for the response.

> It's not a choice anyone made. It's more of an emergent property. It's a consequence of the core architectural principles of JSON Schema, especially the one that says we never remove constraints, only add them. The compositeOf keyword would never be accepted because it violates that rule. The A and B schemas would validate differently when used with compositeOf than they would by themselves.

Fair. However the intent here was not to remove constraints, rather it was to allow for easier composition of schemas with existing constraints. But it's true that sub schemas `A` and `B` would need to be interpreted a little differently when used within a `compositeOf` context (and the validation logic of `compositeOf` would be somewhat inverted). So I appreciate this would go against the grain somewhat. 

> This topic was debated for years. There were many proposals. unevaluatedProperties is not a great solution, but it's what we ended up with and it does make a lot of use cases easier to express.

I had imagined this was probably the case. I'm not aware of all previous proposals to support intersecting schemas, but I can imagine a of reasoning went in prior to settling on `unevaluatedProperties`.

> If your goal is to emulate a type system, I'm very surprised that you are so keen on using "additionalProperties": false. That's the textbook example of when you do want to allow additional properties. Polymorphism is only possible by allowing additional properties.

At this point, it's probably worth linking in the library in question which is trying to reconcile TS to JSON schema which you can find [here](https://github.com/sinclairzx81/typebox). It actually lists all the TS to schema mappings in the readme. But this aside, I do think `additionalProperties: false` is the preference given the following example. 

```typescript
type A = { a: number }
function method(a: A) {} 
method({ a: 1 }) // ok
method({ a: 1, b: 2 }) // Object literal may only specify known properties, and 'b' does not exist in type 'A'.
```
So, this does suggest the appropriate JSON schema representation of `A` would be `additionalProperties: false`. This really gets at the heart of the issue i think. Also, note that this doesn't disallow polymorphism. If the intent was to receive additional properties, you could opt into that with.
```typescript
function method<T extends A>(a: T) {}
```
This aside, I think the expectation for any TypeScript user trying to reconcile the JSON schema representation of a data type would be to disallow unknown properties by default. I think this is the main point of difference with respect to interpreting data types in either system; i.e TypeScript is strict unless explicitly opted out of, in JSON schema the strictness is opt in. 

It seems a little unfortunate (and equal part interesting) that the opt in constraints of JSON schema do make objects with constraints difficult to compose. I do appreciate that something like `compositeOf` is a little against the grain. But somehow it feels like a missed trick when JSON schema can naturally express so much of what TypeScript's static type system with the exception of `intersection` types.

Thanks again for the responses. I think I have enough information here to make better informed calls downstream. Will close off this issue :) 

S

**Comment by jdesrosiers** [comment]
I clearly haven't explained the removing constraints stuff well enough. I'm hoping to write about that and other things in depth in the relatively near future.

I think you missed what is actually happening in your example. The object literal you are passing to the function is implicitly constructed using the type of the function argument. If you extract that construction step, you see that the function happily accepts Cs as well as As just like it should. So, my assertion that only construction is strict in TypeScript still stands.

```typescript
type A = { a: number };
type B = { b: number };
type C = A & B;

function method(a: A) {} 

const foo: A = { a: 1 };
method(foo) // ok

const bar: C = { a: 1, b: 2 };
method(bar) // ok
```

`T extends A` does work, but it's unnecessary to have to use generics to accomplish what is a basic feature of any type system of this kind. To help show that this is standard behavior, here's Java exhibiting the same behavior.

```java
class Main {
  public static void main(String[] args) {
    A a = new A(1);
    method(a);

    B b = new B(1, 2);
    method(b);
  }

  public static void method(A a) {
    System.out.println(a.a);
  }
}

class A {
  int a;

  public A(int a) {
    this.a = a;
  }
}

class B extends A {
  int b;
  
  public B(int a, int c) {
    super(a);
    this.b = b;
  }
}
```

> somehow it feels like a missed trick when JSON schema can naturally express so much TypeScript's static type system but misses on intersection types.

I think I've shown that JSON Schema can naturally express intersection types when expressing them the way a normal type system would. But, even assuming types were strict, my schema examples show that JSON Schema can express that as well with `unevaluatedProperties`. Is there something about those schemas that don't fulfill your need?

**Comment by sinclairzx81** [comment]
@jdesrosiers Thanks again for the write up. I do appreciate the time taken to discuss this particular topic (and it's very difficult to find people to discuss some of the intricacies of JSON schema). So this dialog is very much appreciated.

### Constrained Sub Schemas, Polymorphism and Validation

Yes, I understood the polymorphism perspective, but I feel this is somewhat tangential to the matter of composing constrained schemas. I do feel like there is a implicit association being made here where `unevaluatedProperties` is viewed as the correct way to represent a kind of sub typing in a language (which is very reasonable), but seems at odds to the matter of JSON schema mandating all sub schemas be permissive in order to be composed. (But I do understand why this is the case)

This is probably less of an issue in C# or Java where these languages have a strong type system + deserialization step which could simply ignore non-assignable properties or just `throw`. In JavaScript, deserialization is typically handled via `JSON.parse(...)` and is very permissive. Thus there is a reliance on JSON schema to appropriately disallow unwanted properties entering a program that would otherwise be caught by a strong type system. The following is a typical use case where issues arise.

```typescript
const A = { type: 'object', properties: { a: { type: 'string' } } } // permissive :(
type A = { a: string }

function receive(data: A) {
   store.persist({...data})  // we may persist unwanted data here.   
}

const data = JSON.parse( '{ "a": "hello", "b": "world" }')
if(validate(A, data)) { receive(data) }
```
But just to further elaborate on the preference for `additionalProperties: false`, I've created an example to bring a bit more visibility to what I'm trying to achieve, and hopefully show polymorphism is not implicated by preferencing `additionalProperties: false`, more so, how `additionalPropeties: false` actually results in a JSON schema representation that emulates how a strong type system may interpret unknown property assignment (taking the view that JavaScript cannot adequately filter for all known properties, and thus should reject any object that contains unknown properties). 

TS Playground [Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUFP784JCOxbwAgnAC8iOEMwAuRhBEArDCRgMcYWpljAMLA0gJOdwgw3YBXECIxQGCgocKAwARy8+DAATAwBtBgIGAF0cAmjo4GIlAi4ABRt-YgcDKlyWDApZeUVleAAhTW1dDA8jU3NLOGsIW2LHbRFXFo9vX39AynIQ8MjQ2LgEkRS0jKzgHPzCuxLqcsryaoUlFTgAYSakEcMTMwsrbf7XF2b3ODG-KGC4Idf9d58nyC0zgoQiUQWCSSOAYy1ScHSmWy7FyBV6RXsAzKXAqVSktVO6i0aEwADoAPK3cwACmcBhJGFJADlAf5qQBKCic-EnBpNBkUqkwWk-enCZmsqAcrk8urnfnigCS7Bg-gqNLiqhw9WS7JkcjcmDgRO0Lw+-iqBpacEaWiQv3NX0OVuE8q06gAZDapNaTfgiKQADwtCBUY0APjgBsU4C8quiPtdtrwhGIJGDwlDNsj0boYDjMUTRouWn9aYzmCzZxzNTzBYTR1UXC4cBUwGb3QgLDYIi4GFlpxIBhLpoMAEYcL8AExBAfwF4msgEFjGueim1NJcr+pSAikghR+QQADWUhEpJEh7gJ6kQA)
```typescript
import { Type, Static } from '@sinclair/typebox'

// const A = { type: 'object', properties: { a: { type: 'number' } }, required: ['a'], additionalProperties: false }
// const B = { type: 'object', properties: { b: { type: 'number' } }, required: ['b'], additionalProperties: false }
// const C = { type: 'object', properties: { a: { type: number }, b: { type: number } }, required: ['a', 'b'], additionalProperties: false }

const A = Type.Object({ a: Type.Number() }) 
const B = Type.Object({ b: Type.Number() })
const C = Type.Intersect([A, B])

// type A = { a: number }
// type B = { b: number }
// type C = A & B
type A = Static<typeof A> // computed
type B = Static<typeof B> // computed
type C = Static<typeof C> // computed

// All still possible
const c: C = { a: 1, b: 2 } 
const a: A = c as A
const b: B = c as B
a.a // ok
b.b // ok
```
## More on the Issue

To properly explain the issue I'm facing (which likely results from my strong desire to have constrained schemas), it is helpful to understand that TypeBox is attempting to statically infer (or compute) the appropriate type from an underlying JSON schema representation. The library attempts to derive as much type information as possible encoded in the underlying schema. For example.

### Union

```typescript
// schema
const A = Type.Object({ a: Type.String() }) // an object schema
const B = Type.Object({ b: Type.String() }) // an object schema
const C = Type.Union([A, B])  //  is { anyOf: [A, B] }
```
Above we have two constrained sub schemas. `anyOf` will tests for either `A` or `B`. This is perfect as `A` and `B` are expressed as an array and therefore the sub schemas can be trivially targeted for type inference. TypeBox internally represents unions as.

```typescript
type TUnion<T extends TSchema[]> = { anyOf: [...T] }
                                             ^ variadic tuples can be inferenced
```
Where `anyOf` is computed from the variadic tuple. But the key take away is that it's expressed as an array.

### Intersect

As discussed, the natural representation of a TypeScript intersect type is via `allOf` with an applied `unevaluatedProperties` constraint. As follows.

```typescript
const A = Type.Object({ a: Type.String() }) // additionalProperties: false - problem
const B = Type.Object({ b: Type.String() }) // additionalProperties: false - problem
const C = Type.Intersect([A, B])  //  is { allOf: [A, B], unevaluatedProperties: false }
```
And similarly, this could be represented in TypeScript as follows.
```typescript
type TIntersect<T extends TSchema[]> = { type: 'object', allOf: [...T], unevaluatedProperties: false }
```
To make this work, id need to remove the constraints on `A` and `B` to just make `unevaluatedProperties` possible. This is workable, but there are other kinds of composition I would like to support below.

### Allowing additionalProperties

Inline with TypeScript, I would like to support `opt-in` additionalProperties. Which currently is implemented as follows.

```typescript
const A = Type.Object({ a: Type.String() }) // additionalProperties: false
const B = Type.Dict(Type.String())  // additionalProperties: { type: 'string' }
const C = Type.Intersect([A, B])  // ??

// analogous to
type A = { a: string }
type B = { [key: string]: string }
type C = A & B
```
It's here where the possible permutations of `additionalProperties` on the sub schemas and `unevaluatedProperties` become extraordinarily difficult to reconcile as a computed type. The easiest approach would be to leverage `unevaluatedProperties` that provides the `allOf` array to infer from, but again `additionalProperties` becomes an issue as how does one properly reconcile `additionalProperties: false` with `additionalProperties: { type: string }` under the umbrella of `unevaluatedProperties`.

The most concise expression of `C` would be as follows. (also see examples of `compositeOf` above which shows the expansion for this keyword if implemented)

```typescript
const C = {
   type: 'object', 
   properties: {
      a: { type: 'string' }
   },
   required: ['a'],
   additionalProperties: { type: 'string' }
}
// ^ This is what I want in terms of a representation for C, except that
// we've lost composition, and can no longer infer from an array of
// composed schemas as we could for `allOf` and `anyOf`.
```
It's really the above which prompted the original query with respect to supporting some kind of `compositeOf` keyword which would allow composing constrained schemas and provide well defined rules around the behavior of the composed schema. Potentially using TypeScript as a reference for how `compositeOf` should work.

### Possible Solutions

Part of the reason for me reaching out was to check the status of JSON schema around composition of object types, this mostly to gauge whether it was worth the additional effort in mapping for constrained schemas for intersect types, or if there were future plans in JSON schema further support the composition of constrained schemas. 

As it stands, there are few options afforded to me.

- Preference permissive schemas for `A` and `B` in TypeBox. (as a default)
- Create reduced schemas of `A` and `B` that omits `additionalProperties` and apply `unevaluatedProperties` on intersect only.
- Reconstruct a new idealized schema from `A` and `B` and apply TypeScript intersect rules to the computed type.

At this stage, I think the first and last options are going to lead to the most desirable result for the end user. With the first option leaning more towards the semantics of JSON schema (at the expense of being misaligned with TypeScript's interpretation), and the latter being extremely awkward to develop, but more in tune with TypeScript at the expense of not being able to rely on JSON schema composition.

This is a bit of a long reply, but hopefully I've been able to convey some of reasoning this side. I am still very happy to continue discussing this more. Note that I am purely coming at this with a hope of finding good alignment between TypeScript and JSON schema. All your insights have been extremely helpful. 

Thanks Again!

**Comment by sinclairzx81** [comment]
Just wanted to post a small follow up on things. Have put together a reference implementation `unevaluatedProperties` and am still having some trouble appropriately expressing intersections as JSON schema via `unevaluatedProperties`. 

### Working
The following is all working fine, where I've included both the idealized and unevaluatedProperties representations.
```typescript
// typescript
type A = { a: number }
type B = { b: string }
type C = A & B

// idealized
const C = {
  type: "object",
  properties: { 
    a: { type: "number" },
    b: { type: "string" } 
  },
  required: ["a", "b"],
  additionalProperties: false
}

// unevaluatedProperties
const C = {
  type: "object",
  allOf: [
    { type: "object", properties: { a: { type: "number" } }, required: ["a"] }, 
    { type: "object", properties: { b: { type: "string" } }, required: ["b"] }
  ],
  unevaluatedProperties: false
}
```
### Problem
This case can be expressed in the idealized schema, but doesn't seem possible via `unevaluatedProperties`. 
```typescript
// typescript
type A = { a: number }
type B = { [key: string]: string }
type C = A & B

// idealized 
const C = {
  type: "object",
  properties: { a: { type: "number" } },
  required: ["a"],
  additionalProperties: { type: "string" }
}

// unevaluatedProperties
const C = {
  type: "object",
  allOf: [
    { type: "object", properties: { a: { type: "number" } }, required: ["a"] }, 
    { type: "object", additionalProperties: { type: "string" } }
  ],
  unevaluatedProperties: false // or true?
}
```
This is probably expected, but does implicate composition. Also, I've compared `JSONSchema.NET` and `AJV` validators and they seem to report different errors (the second schema is possibly ambiguous) with `AJV` reporting that property `a` should be a `string`. So I found this somewhat interesting.

**Comment by jdesrosiers** [comment]
> I do feel like there is a implicit association being made here where `unevaluatedProperties` is viewed as the correct way to represent a kind of sub typing in a language

Not really. JSON Schema is just a validation language. It makes no attempt at being able to express types. `unevaluatedProperties` is one tool for composing schemas. In this particular case, it appears to be the best tool for the job, but there is no one correct way to do anything in JSON Schema. If it evaluates the way you want it to, then it's correct.

> but seems at odds to the matter of JSON schema mandating all sub schemas be permissive in order to be composed. (But I do understand why this is the case)

When you say it like that, I'm not convinced that you do understand. There is no such mandate. It's like saying that addition is mandated to be associative. That's not a mandate, that's just the way numbers work. JSON Schema has certain properties. Those properties working together result in some emergent properties, one of them being that it's difficult to compose closed schemas. We can't just all get together and decide we want to change that "mandate" without changing the fundamental nature of how JSON Schema works.

> In JavaScript, deserialization is typically handled via JSON.parse(...) and is very permissive. Thus there is a reliance on JSON schema to appropriately disallow unwanted properties entering a program that would otherwise be caught by a strong type system.

Again, that's the construct part. If you use `JSON.parse` or an object literal, then you should be doing strict validation on that value when it's constructed. From then on you can safely allow it to be permissive like the type system.

> I've created an example to bring a bit more visibility to what I'm trying to achieve

You're generating types (permissive) from closed schemas. I don't see a problem with that until you want to use those schemas for validation. This will pass type check and incorrectly fail runtime schema validation.

```typescript
const method = (a: A) => {
  if (!JsonSchema.validate(A, a)) {
    throw Error("Not an `A`");
  }
};

const c: C = { a:1, b: 2 };
method(c);
```

> As it stands, there are few options afforded to me.
>
> * Preference permissive schemas for `A` and `B` in TypeBox. (as a default)
> * Create reduced schemas of `A` and `B` that omits `additionalProperties` and apply `unevaluatedProperties` on intersect only.
> * Reconstruct a new idealized schema from `A` and `B` and apply TypeScript intersect rules to the computed type.

If you are making things permissive, you probably shouldn't use `unevaluatedProperties` on intersects either because that intersection can't then be intersected with another type. But, there's no reason to have to decide between strict and permissive. As I showed in my original response, you can have a schema that expresses both. Here's the standard intersection example. Each schema defaults to being strict, but also has a hook to allow for easy composition. (The schemas would read much nicer if permissive was the default, but I did it the other way around since your preference is strict.

```json
{
  "$id": "http://typebox.com/A",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "$ref": "#composable",
  "unevaluatedProperties": false,

  "$defs": {
    "composable": {
      "$anchor": "composable",
      "type": "object",
      "properties": {
        "a": { "type": "number" }
      },
      "required": ["a"]
    }
  }
}
```
```json
{
  "$id": "http://typebox.com/B",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "$ref": "#composable",
  "unevaluatedProperties": false,

  "$defs": {
    "composable": {
      "$anchor": "composable",
      "type": "object",
      "properties": {
        "b": { "type": "number" }
      },
      "required": ["b"]
    }
  }
}
```
```json
{
  "$id": "http://typebox.com/C",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "$ref": "#composable",
  "unevaluatedProperties": false,

  "$defs": {
    "composable": {
      "$anchor": "composable",
      "allOf": [
        { "$ref": "A#composable" },
        { "$ref": "B#composable" }
      ]
    }
  }
}
```

> type A = { a: number }
> type B = { [key: string]: string }
> type C = A & B

This is expressible in JSON Schema, but just like the type definition, there is no value that would ever match it because `B` says all values must be strings and `A` says one of the values must be a number. (I tried this in the TS Playground to make sure.) If this worked the way you expected and `B` was constraining only additional properties, that could be expressed with JSON Schema, but `B` isn't composable. You would have to inline (duplicate) it.

```json
{
  "$id": "http://typebox.com/B",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "unevaluatedProperties": { "type": "string" }
}
```
```json
{
  "$id": "http://typebox.com/C",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "type": "object",
  "unevaluatedProperties": { "type": "string" },
  "allOf": [
    { "$ref": "A#composable" }
  ],
}
```

Sorry for the slow response. I hope this was useful.

**Comment by sinclairzx81** [comment]
@jdesrosiers Hey, thanks for the follow up. Also yes, these exchanges are extremely helpful. Honestly, thank you for taking the time to respond. As mentioned, it's really hard to find people to discuss these fairly intricate and subtle details; and especially when compounded with type systems and libraries.  So your help is really appreciated this side.

> When you say it like that, I'm not convinced that you do understand. There is no such mandate. It's like saying that addition is mandated to be associative. That's not a mandate, that's just the way numbers work. JSON Schema has certain properties. Those properties working together result in some emergent properties, one of them being that it's difficult to compose closed schemas. We can't just all get together and decide we want to change that "mandate" without changing the fundamental nature of how JSON Schema works.

Yes, you're quite right. The word mandate was not the correct term to use. Apologies for this. 

> You're generating types (permissive) from closed schemas. I don't see a problem with that until you want to use those schemas for validation. This will pass type check and incorrectly fail runtime schema validation.
```typescript
const method = (a: A) => {
  if (!JsonSchema.validate(A, a)) {
    throw Error("Not an `A`");
  }
};

const c = { a:1, b: 2 };
method(c); // allowed
method({ a: 1, b: 2 }) // not allowed
```
This is a very good point. I guess my view has been that the above `method` should `throw` as there is some expectation that parameter `a` is a of type `A` and nothing more (even if it ignores the relationship `A` has to `C`). 

But note that the second call `method({ a: 1, b: 2 })` raises a static assertion error, so there is some ambiguity here with respect to how TS handles this case. I have previously felt that disallowing the `additionalProperties` provides a more definite and predictable behavior, even if the constraint is artificial from the languages standpoint.

However, I could very well be wrong in this assessment. The following is TypeScript and Csharp expressions of the above, which is very much in tune with what you're suggesting when viewed through a slightly different lens.

#### TypeScript
```typescript
type A = { a: number }
type B = A & { b: number }

const method = (a: A) => { /*...*/ };

const b = { a:1, b: 2 }; 
method(b);                 // allowed (implicit)
method({ a:1, b: 2 } as A) // allowed (explicit)
method({ a:1, b: 2 })      // not allowed (but probably should be?)
```
#### CSharp
```csharp
class A {
    public int a { get; set; }
}
class B: A {
    public int b { get; set; }
}

class Program {

  static void Method(A a) { /* ... */ }

  static void Main(string[] args) {
    var b = new B();
    Method(b);                    // allowed (implicit)
    Method(b as A);               // allowed (explicit)
    Method(new { a = 1, b = 2 }); // not allowed (strong type system, anon type neither A or B). 
                                  // TS behaviour makes more sense (but not really)
  }
}
```
So this is a difficult call to make from TypeBox's standpoint. There really are too many subtleties going on here to really address in a discussion centered on json schema composition (strong vs static / structural type systems). But I guess I am more open to the idea of removing the `additionalProperties` constraint from the schemas. This would align better with how the TypeScript type system currently operates (sort of anyway) and be far more in tune with the nature of JSON schema.

> If you are making things permissive, you probably shouldn't use unevaluatedProperties on intersects either because that intersection can't then be intersected with another type. But, there's no reason to have to decide between strict and permissive. As I showed in my original response, you can have a schema that expresses both. Here's the standard intersection example. Each schema defaults to being strict, but also has a hook to allow for easy composition. (The schemas would read much nicer if permissive was the default, but I did it the other way around since your preference is strict.

Yes, this is something I've been giving some thought to from your original replies. In your examples, you have a permissive inner schema which is constrained by an outer schema. Then you use `$ref` to refer to the permissive inner schema for composition. As you mentioned, this would read a lot nicer if permissive was the default, but it would also likely be easier to statically infer. Actually the use of `$ref` isn't something TypeBox currently does. There are a few suggestions to introduce a `Type.Ref(..)` into the API, so have been thinking about how to reconcile a `$ref` with some of these compositional aspects in general. But that's a whole other story.

Thanks again @jdesrosiers, You've provided me quite a lot to think about here. I feel like many of the composition issues and complexities I've run into have been a direct result of trying to force strict schemas end to end. So this is quite possibly a mistake on my part. I may actually look into removing the `additionalProperties: false` constraint in the library and provide someway for the user to opt into it instead. This should make producing statically inferable schemas more feasible while better aligning with the general design of JSON schema.

**Comment by jdesrosiers** [comment]
I've enjoyed this conversation as well. You've forced me to think deeply about this and I always appreciate that.

> But note that the second call `method({ a: 1, b: 2 })` raises a static assertion error, so there is some ambiguity here with respect to how TS handles this case.

I don't think this is ambiguous at all. It's consistent with construction being strict and assignment being polymorphic (which is permissive). Passing a value to a function is just a specialized way of assigning it to a variable before it executes the function.

```typescript
// This function,
const method = (a: A) => {
  console.log(a.a);
};

// is equivalent to this. (The function syntax exists to allow setting variables and then executing the function block.)
let a: A = /* placeholder */
console.log(a.a);

// Therefore, this function call,
method({ a: 1, b: 2 });

// is actually,
let a: A = { a: 1, b: 2 }; // strict construction will fail
console.log(a.a);

// And, this function call,
const c: C = { a: 1, b: 2 }; 
method(c);

// is actually,
const c: C = { a: 1, b: 2 };  // strict construction will pass
let a: A = c; // polymorphic assignment is ok
console.log(a.a);
```

**Comment by sinclairzx81** [comment]
@jdesrosiers Ah yes, ambiguous wasn't really the right term to use either. Whoops. TypeScript's behavior is well defined and predictable here, but it is a little non-apparent to the casual reader at first glance (well me specifically :P) as to why `method(a)` should succeed and `method({ a: 1, b: 2 })` should fail when passing the same object data. At least when not considering `construction` and `assignment` as two distinct operations (where TypeScript blurs these lines a little with object literals serving as both type and object construction; and where structurally, the parameters `a` and `{a: 1, b: 1}` are the same). So this is quite interesting. 

```typescript
const method = (a: A) => {/*...*/};

let a: A = { a: 1, b: 2 };      // strict construction will fail
let b: A = { a: 1, b: 2 } as A; // ok (construction then assignment)

method({a: 1, b: 2})            // strict construction will fail 
method({a: 1, b: 2} as A)       // ok (construction then assignment)
```
The rule of `construction being strict and assignment being polymorphic (which is permissive)` is a fairly subtle but important thing to consider. I hadn't really thought about things in these terms before to explain why TypeScript behaves in this way, but what you've outlined makes good sense to me and further lends more weight to removing `additionalProperties: false` constraints on the schemas.

Yeah, this conversation has been great! It's actually really good to have a dialog to point to that provides rationales for some of these finer details. Up until this point, the TypeBox project had been attempting to replicate as much of TypeScript's type system in JSON schema as possible, but just being able to assert on my assumptions (something I've not been able to do before) while getting the microscope out on these fine level details around composition and polymorphism has been invaluable.

Thanks again!
