### ISSUE TITLE
Re: How to reference JSON Schema from JSON data

### ISSUE THREAD

**Issue by about-code** [json-schema-org/json-schema-spec#1091]
Unfortunately discussion on #828 is locked but I'd like to contribute a few thoughts to a comment of @glen-84:

> I don't see how this is possible, actually.
> 
> `"$schema"` is a valid JSON key, which means that any existing (or future) system may be using it, for potentially different purposes – it may not reference a JSON schema document, and it may not even reference a URL.
>
> [...]
> 
> The only (somewhat hacky) way of implementing this would be to use a _really_ uncommon/specific key name, like the URL to the JSON schema schema:
>
> ```json
> {
>     "http://json-schema.org/schema#": "https://getcomposer.org/schema.json"
> }
> ```
>
> ... but that's possibly not ideal.
>
> This is just another one of the limitations of the JSON format.
>
> _Originally posted by @glen-84 in https://github.com/json-schema-org/json-schema-spec/issues/828#issuecomment-572626261_

First of all I think the problem of having no upfront context in JSON is the same which JSON-LD had on the one hand and aims to solve on the other. JSON-LD itself decided to standardize the `@context` keyword regardless of other possible uses.

*But* that doesn't mean JSON-Schema must go down the same path and standardize it's own semantically uninterpretable `$schema` attribute. Rather it could consider the *chicken-egg-problem* solved and solve its own *contextual problem* in exactly the "hacky" way Glen-84 proposed - by specifing a property as a URI because *that is exactly how JSON-LD looks at Linked Data and JSON properties*. It maps ambiguous properties into a semantically meaningful context. 

So let's first assume there's `$schema` and many instances use it today to denote a schema location:

```json
{
   "$schema": "https://getcomposer.org/schema.json"
}
```
This completely relies on a non-standarized convention-based *interpretation* of the `$schema` property. JSON-LD first acknowledged that there are a lot of JSON documents and APIs out there with properties that are - technically - not meaningful but interpreted by implicit understanding of their semantics. So the idea to give them explicit unique semantic meaning was to define a standard for mapping/projecting property names onto URIs.

So to make `$schema` semantically meaningful with JSON-LD we would add 

```json
{
   "@context": {  "$schema": "http://json-schema.org/schema#"  },
   "$schema": "https://getcomposer.org/schema.json"
}
```

See [JSON-LD Playground's Compacted View](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22%24schema%22%3A%22http%3A%2F%2Fjson-schema.org%2Fschema%23%22%7D%2C%22%24schema%22%3A%22https%3A%2F%2Fgetcomposer.org%2Fschema.json%22%7D&context=%7B%7D) how this were identical to writing

```json
{
    "http://json-schema.org/schema#": "https://getcomposer.org/schema.json"
}
```

So the message is: you are able to avoid standardizing a *particular* property name like `$schema` whose *implicit* interpretations could change over time or vary from one context to another. Still you can standardize a URI with explicit semantics *of being the link between an instance document and a (JSON-)schema*. It's then up to tooling vendors whether they continue implicitely interpreting `$schema` as an alias for the Standard URI or whether they ask users to become explicit which of their properties semantically stands for a schema reference - either by expecting the property name to be the URI or requiring a JSON-LD contextual mapping from their own arbitrary name onto the standardized URI.

**Comment by Relequestual** [comment]
I've unlocked the issue and added an "on hold" label.
Feel free to migrate your comment there and close this issue.

Sorry for making this more difficult than it needed to be.

Thank you for your valuble thoughts here!

**Comment by about-code** [comment]
Migrated. Thank you for your valuable work.
