### ISSUE TITLE
allOf | use cases.

### ISSUE THREAD

**Issue by ChaitanyaBabar** [json-schema-org/json-schema-spec#1095]
### Question.

As we know `allOf`  construct is used for combining schemas , can it combine `'non array type'` and `'and array type' `?
If yes, how would below object be represented using JSON format.

```
{
 "allOf": [
        { "type": "number" },
        {
            "type": "array",
            "items": {
              "type": "number"
            }
      }
  ]
}
```

**Comment by handrews** [comment]
However, if you change the `allOf` to a `oneOf` (or `anyOf`, in this case it doesn't matter), that would work.  Either `42` or `[42, 43, 44]` would pass validation.  But there is no way for JSON to be both a number and array at the same time.

**Comment by handrews** [comment]
Since it's been a week, I will assume that the previous comments addressed your question.  Please comment/re-open/re-file if this is not the case!
