### ISSUE TITLE
Support for min/maxLength on object property names

### ISSUE THREAD

**Issue by frontierpsycho** [json-schema-org/json-schema-spec#110]
(resubmitting from [here](https://github.com/json-schema/json-schema/issues/193#issuecomment-255453173))

It might be useful to be able to set limits on property names when defining them with `patternProperties`.  

For example, I have an object which should have arbitrary key-value pairs, and I want to constrain the keys to be at most 64 characters. For now, I've resorted to this:

```json
"additionalProperties": false,
"patternProperties": {
   "^\\S{1,64}$" : { ... }
}
```
(resubmitting this, from [here|https://github.com/json-schema/json-schema/issues/193#issuecomment-255453173])

However, the error message generated is very confusing. For example, if I send this object:

```json
{ "SIXTYFOURCHARACTERSYOUSAYWELLALRIGHTTHENLETSNOTEXCEEDTHATSHALLWEIMEANWHONEEDSMORETHANSIXTYFOURCHARACTERSANYWAY":"value"}
```

I get the following error, which is clear to someone familiar with JSON-schema and the additional properties keyword, but not to everyone else:

``` SIXTYFOURCHARACTERSYOUSAYWELLALRIGHTTHENLETSNOTEXCEEDTHATSHALLWEIMEANWHONEEDSMORETHANSIXTYFOURCHARACTERSANYWAY: Additional properties not allowed``` 

I suggest support for something like:

```json
"patternProperties": {
  "^\\S*$": {
    "maxLength": 64,
    ...
  }
}
```

With the corresponding error message:

```
SIXTYFOURCHARACTERSYOUSAYWELLALRIGHTTHENLETSNOTEXCEEDTHATSHALLWEIMEANWHONEEDSMORETHANSIXTYFOURCHARACTERSANYWAY: Property name is too long (110 chars), maximum 64
```

**Comment by epoberezkin** [comment]
@frontierpsycho This is covered by propertyNames proposal that is more generic: https://github.com/json-schema-org/json-schema-spec/issues/70

**Comment by frontierpsycho** [comment]
Indeed it is.
