### ISSUE TITLE
Deprecation Warning even when using draft 2020-12 and pip pre-release 4.0.0a1

### ISSUE THREAD

**Issue by brethvoice** [json-schema-org/json-schema-spec#1109]
Whether I use jsonschema from pip at version 3.2.0 or [4.0.0a1](https://pypi.org/project/jsonschema/4.0.0a1/), I get the following DeprecationWarning despite having "$schema": "https://json-schema.org/draft/2020-12/schema", at the top of my JSON schema file:

`validators.py:770: DeprecationWarning: The metaschema specified by $schema was not found. Using the latest draft to validate, but this will raise an error in the future.`

**Comment by Relequestual** [comment]
Hello. Unfortunately you've ended up in the wrong place. This repo and organisation does not house or develop any implementations. You will need to retarget your issue elsewhere =]
