### ISSUE TITLE
Suggestion: Numeric keywords `minScale` and `maxScale`

### ISSUE THREAD

**Issue by SrikrishnanS** [json-schema-org/json-schema-spec#1113]
Currently, there isn't a keyword to specify minimum scale and maximum scale for number types. Per definition **scale** of a number is the number of digits after the decimal point.
For instance, to specify a currency value in the document, I want to be able to use the following schema:
```
"currency": {
  "type": "number"
  "maxScale": 2
}
```
This would reject numeric values `100.995`, and accept values `100`, `99.95` etc.

So suggest adding `minScale` and `maxScale` in the schema specification.

**Comment by karenetheridge** [comment]
You should be able to achieve that with multipleOf:

```
"currency": {
  "type": "number",
  "multipleOf": "0.01"
}
```

**Comment by WFDexter** [comment]
Given how floating point works, "multipleOf" isn't going to be fully reliable when dealing with fractional amounts. It seems like it mathematically, but floating point representations are imperfect.

**Comment by SrikrishnanS** [comment]
Added #1123 instead
