### ISSUE TITLE
Issue with the Enum in arrays

### ISSUE THREAD

**Issue by agustin-blanco** [json-schema-org/json-schema-spec#1141]
Hi Everyone, we are using json schema and found something weird when using enums in arrays.

For the simple json schema:
`{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "example": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "enum": [
            "1",
            "2"
          ]
        }
      ]
    }
  }
}`

If you put:
{
  "example": ["3","1"]
}
It fails saying that 3 is not in the enum. This behaviour is correct.

But if you put something correct first, then everything else passes the validation:
{
  "example": ["1","3"]
}

Sorry if this is an open issue.
Thanks!

**Comment by Relequestual** [comment]
When you use the `items` keyword in draft-07 or previous, and you use the array value form, it only applies the subschema value to the same index.

If you want your subschema value to apply to all items in the array, your `items` value should just be a single schema object.
