### ISSUE TITLE
same vocabulary meta schema behaviour

### ISSUE THREAD

**Issue by ItsVeryWindy** [json-schema-org/json-schema-spec#1156]
If you have a meta schema that references multiple vocabularies, and say two of them define semantics for the same keyword.

How is the behaviour determined?
* Would both be evaluated, or
* Is it based on the order defined, or
* The schema would be considered invalid, or
* Possibly something I haven't considered

As a bad example, lets say the keyword was minLength, and one vocabulary defines it as being the length of a string, while the other determines it to be the minimum number of items in an array.

**Comment by gregsdennis** [comment]
I think this enters into the namespacing territory that @jdesrosiers has mentioned before.

It's not something that is addressed in the spec, and TBH we haven't had a good case for needing to define it yet.

**Comment by jdesrosiers** [comment]
You can't use two vocabularies with conflicting keyword names in the same dialect. Technically, the spec says the behavior is undefined, so the behavior depends on the implementation and you should never rely on that behavior.

We've talked about enhancements/changes to the vocabulary system that could address this problem, but those discussions are on the back burner for now.

**Comment by handrews** [comment]
I'm closing this as the question has been answered (the undefined explanation is in [Appendix D](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#appendix-D.1), and proposals for change should be their own issues.
