### ISSUE TITLE
prefixItems does not explicitly mention instances arrays shorter than the keyword value length

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#1174]
The [`prefixItems` keyword section](http://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.10.3.1.1) says this:

> Validation succeeds if each element of the instance validates against the schema at the same position, if any. This keyword does not constrain the length of the array. If the array is longer than this keyword's value, this keyword validates only the prefix of matching length.

Note that it explicitly mentions if the instance array is _longer_ but nothing about when it's shorter.  It _does_ say that no length constraints are imposed, but it feels odd that it would mention one without the other.

We do have a [test for this](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft2020-12/prefixItems.json#L22) as well.

**Comment by jdesrosiers** [comment]
The wording does seem confusing. I'm not sure it's wrong, but just that I'm not sure means it should be clearer.

**Comment by gregsdennis** [comment]
Yeah, it's definitely not wrong.
