### ISSUE TITLE
No normative statement in IANA considerations.

### ISSUE THREAD

**Issue by ioggstream** [json-schema-org/json-schema-spec#1176]
## I suggest

to avoid normative statements in media type registration.

## Because

whenever you update the spec, you need to modify the IANA registration too.

**Comment by awwright** [comment]
Can you please quote the parts of the spec you're referring to?

**Comment by ioggstream** [comment]
Hi @awwright 

> Can you please quote the parts of the spec you're referring to?

I'm not sure it's normative, but I've been pointed here once https://datatracker.ietf.org/doc/html/rfc8126#section-1.1

In https://ietf-wg-httpapi.github.io/mediatypes/draft-ietf-httpapi-rest-api-mediatypes.html#name-iana-considerations we addressed it moving the media type registration section outside of the IANA.

While it seems it's not forbidden to have normative statement in media type registration section, we are going to ask  guidance at the next IETF meeting. The goal is to have a neat media type registration that doesn't need to be modified every time the underlying specification changes.

**Comment by awwright** [comment]
@ioggstream Which part of the JSON Schema spec are you proposing to change? I'm still not sure what you're proposing.

**Comment by awwright** [comment]
@ioggstream Can you please clarify?

**Comment by ioggstream** [comment]
Since we are addressing the media type registration in another draft, I expect to split the data format here and the media type there.

We will discuss the topic of media type registration at the next ietf meeting this week, inside the httpapi workgroup.

**Comment by awwright** [comment]
@ioggstream Can you please quote, from the JSON Schema spec, the parts you're talking about and proposing to change?

**Comment by awwright** [comment]
Your initial post is very terse and I don't understand what you're asking. Can you please add a preamble with some background of the issue? Especially for new people casually browsing here.

**Comment by ioggstream** [comment]
Here you can find an example of the direction I think the document should take https://docs.google.com/document/d/1eCqISxrHeyLdzTUMRTuMntVGjC0Vbc0-ZmoLlIx97WE/edit?usp=drivesdk

But it's Jason and Ben that will take care of that. I am just providing some feedback derived from the httpapi mediatype discussion.

After the ietf meeting I will take some time to brush my comments/pr here.

**Comment by awwright** [comment]
Ok, I left many comments on that document. I'm the author of many of the paragraphs you're commenting on.

May I suggest— I'm not opposed to overhauls of a spec document or technology, but it needs to be approached carefully due to scope creep, and because it can leave behind important applications and existing users. If there's problems with the document not related to your vision, work first on getting those clarified, answered, or fixed. (For example, inconsistent usage of technical terms. Fixing these problems first can dramatically simplify the remaining work. And often some of the problems you have solve themselves with minor technical fixes.)

I'm still not sure what you're asking for, that would allow us to close out this issue. I don't see any notes relating to "normative statements in media type registration".

**Comment by handrews** [comment]
Given the lack of further response and the vague omnibus nature of this issue, I'm going to close it.  @ioggstream feel free to continue to raise specific points in new issues, which should include:

* The section(s) / paragraps(s) in the spec that need changing
* The reason for the change, specific enough that we can decide whether we agree with the reasoning or not
* A clear indication of what change we would need to make address the concern

For anything that is specifically tied to IETF processes and expectations, I would recommend waiting until the ADR about whether we are continuing with the IETF is resolved (in the json-schema-org/community repo).

**Comment by ioggstream** [comment]
@handrews sure. I think some of the above points are going to be discussed in the media type registration repo.
