### ISSUE TITLE
Replace all URI resolution manipulation with SafeCURIEs (no more `id` or `base`)

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#118]
In issue #104 @awwright asserts that it is not possible to change the base for values of `rel`, and therefore another mechanism for URL shortening must be used, such as SafeCURIEs.  The [CURIE specification](https://www.w3.org/TR/curie/) makes it clear that CURIEs MUST NOT be used where URIs or URI References are required - a specification must specifically state that CURIEs (or more likely SafeCURIEs which cannot be confused with URIs) are allowed to be used, and provide a way to define CURIE namespaces.

It does not make sense to me to have three separate mechanisms for setting base URIs.  If we were to add SafeCURIEs for #104 , we would end up with:
- `id` for setting the URI base of `$ref`
- `base`within the LDO for changing the URI base of `href`
- SafeCURIEs for accessing different resolution bases for `rel`

That's absurd.  Not the least because `id` attracts more complaints than pretty much all other JSON Schema features combined already.  I propose that we remove `id` and `base` and instead allow SafeCURIEs anywhere a URI or URI Reference is currently specified.  This can accomplish all current functionality of `id` and `base` while making resolution rules more visible and more flexible to apply.

In their place, we would add a `curieNameSpaces` keyword, the value of which is an object mapping namespaces to the corresponding resolution.  This allows defining as many namespaces as needed (for instance, in case you want to use different resolution for `$ref`, `href`, and `rel`, but also any other more flexible arrangement).

A key advantage is that the different resolution base would be apparent at the point of usage, as SafeCURIEs cannot be mistaken for regular URI/IRI References.  It will be easy to provide a migration script which will define a CURIE namespace for each `id` and `base` and convert the appropriate `$ref` and `href` URI References to the matching SafeCURIEs

**Comment by awwright** [comment]
- There's no such thing as a "URI resolution scope" anymore, it's a URI base
- `base` is a LDO property that affects resolution of URI References in the instance, it doesn't interact with the schema keywords
- CURIEs have never been used to replace URI references, only sometimes URIs. JSON Schema still has a valid need for relative URIs in schema documents.
- We would have to carefully consider how we implement CURIE behavior, it would likely represent the first time we need to keep something besides a string as an contextual environment variable.

**Comment by handrews** [comment]
> There's no such thing as a "URI resolution scope" anymore, it's a URI base

I have changed the proposal accordingly.

> base is a LDO property that affects resolution of URI References in the instance, it doesn't interact with the schema keywords

I specifically said that it only affects `href`.  I have changed my description of it to include the term "LDO".

If you would like any other wording changes, please just ask for them.  I am not attached to wording, I only care about the substance of the proposal.

**Comment by handrews** [comment]
> CURIEs have never been used to replace URI references, only sometimes URIs. JSON Schema still has a valid need for relative URIs in schema documents.

What relative URIs are needed other than ones relative to the request URI that fetched the document (the default base URI)?  I am not suggesting that everything *must* be a CURIE, only that if we decide to allow them it seems like we have a few too many ways to shorten URIs.

For that matter, I just looked more closely at the introduction to the CURIE spec, and despite the 1.0 number it apparently is only a draft from 2010 and should not be cited by other standards.  I hadn't really looked for that restriction earlier because of the 1.0 and because you suggested using CURIEs for `rel` in the first place.

So I don't know if using CURIEs is valid at all, in which case we still have the problem from #104.

**Comment by handrews** [comment]
Closing this because the CURIE "standard" is a draft.

**Comment by akuckartz** [comment]
It is not a "draft" but a "W3C Working Group Note". That means that a W3C WG decided to publish that document as a Note. It is less than a W3C Recommendation but more than simply a draft of a document.

**Comment by akuckartz** [comment]
The Note states about itself: "It is considered mature and stable by the working group."

**Comment by handrews** [comment]
@akuckartz thanks for the clarification.  Since the phrasing at one point in the document was like the more prescriptive view on IETF I-Ds, I just went with that.

I'm leaving this closed anyway because even if CURIEs are usable I don't feel like the proposal (either here or in the more limited form about `rel` was particularly welcomed and I'd rather focus on things that are either getting some support or are top priorities for me.

If someone else would like to champion the use of CURIEs in some form, I'd be happy to support it.  I might come back to some version of this idea once some other things are finished.

**Comment by awwright** [comment]
The document is a Note because it's describing a practice that's implemented by existing specifications (though it probably could have made Recommendation).

Most notably, take a look at the `prefixID` and `PrefixedName` productions in [Turtle](https://www.w3.org/TR/turtle/)

**Comment by Relequestual** [comment]
Is there an IETF equivelent of a note?

**Comment by awwright** [comment]
According to <https://www.ietf.org/tao.html>, an RFC can be published as an Internet Standard, Proposed Standard, Best Current Practice document, Informational document, or Experimental document.

I believe only the first two have the endorsement of the IETF (or maybe the WG), the latter three are more similar to notes.
