### ISSUE TITLE
Json schema array define ordering

### ISSUE THREAD

**Issue by Willem-J-an** [json-schema-org/json-schema-spec#1197]
When defining an array in a json schema, I would like to be able to define the items of the array to be in ascending/descending order.
```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "array",
  "additionalItems": false,
>>>>>    "sort": "ascending",
  "items": {
     "type": "string"
}
```
Has this been considered, or could this be considered? In this case I need ordering of json primitives, but I have also seen a request for ordering of objects [here](https://stackoverflow.com/questions/50369646/how-can-i-ensure-alphabetical-order-with-json-schema-of-json-objects-in-json-arr).

**Comment by awwright** [comment]
This is interesting... this is not especially expensive to validate (it can consume unbounded memory, though not in the same complexity as `"uniqueItems"`), and if it's present, you can safely assume the array is describing an unordered set, and not an ordered list.
The biggest problem would be defining a sorting order for non-scalars and between types. IndexedDB defines a sorting order for JSON, which could be adopted.

**Comment by karenetheridge** [comment]
I think I created an issue somewhere sketching out how a vocabulary might look that defined some keywords like "isSorted" for strings, and describing how string sorting semantics should work (because of Unicode, it's straightforward but not intuitive for those living in an ascii world).

**Comment by vcschapp** [comment]
Is this related? https://github.com/json-schema-org/json-schema-vocabularies/issues/21

**Comment by gregsdennis** [comment]
Closing in favor of the vocabularies link above.
