### ISSUE TITLE
How to declare deprecation date and reason

### ISSUE THREAD

**Issue by FrancescoReviso** [json-schema-org/json-schema-spec#1198]
With **JSON-Schema** I can flag a field or my entire document by setting the `deprecated` meta-data attribute to `true`. Besides flagging the field as deprecated I would like to add a **date** and a **reason** (particularly useful when I would like to suggest to use another field replacing the deprecated ones). Is there any way to do it by following JSON-Schema specification? If it is not the case, is there any best practice/pattern to follow? Thanks

**Comment by gregsdennis** [comment]
The latest draft specifies that unknown keywords are to be collected as annotations.  This means that you should be free to add "keywords" that you want (e.g. `deprecation-date`) and you should get their values as annotations in the output.

**Comment by FrancescoReviso** [comment]
> The latest draft specifies that unknown keywords are to be collected as annotations. This means that you should be free to add "keywords" that you want (e.g. `deprecation-date`) and you should get their values as annotations in the output.

thanks for your suggestion. In the document you linked it discusses annotation but it does not explictily state whether you can use custom "keywords". Moreover I use AJV and Newtonsoft validation libraries and none of them seems to support annotations in the output, only `valid` and `errors`. Do you know any existing library that has already implemented support for annotations?

**Comment by gregsdennis** [comment]
I just happen to know of one! Check out mine: https://www.nuget.org/packages/JsonSchema.Net/

**Comment by Afsan751** [comment]
#1194 #1155 #1172 #1197 #1155

**Comment by gregsdennis** [comment]
With the forthcoming draft, custom annotation-only (non-validation) keywords will need to be prefixed with an `x-`.

Closing this as the question seems answered.
