### ISSUE TITLE
Mention +json structured suffix

### ISSUE THREAD

**Issue by ioggstream** [json-schema-org/json-schema-spec#1199]
## I expect

to mention "+json" structured suffix we should also cite RFC 8091 here.

**Comment by awwright** [comment]
@ioggstream Can you please edit this to add some more context? I think I know what you're referring to here (it's a good idea), but contributors who are new to JOSN Schema might not. Specifically: You expect _what_ to mention "+json"? And, where is "here"?

Before you describe your expectation, you can describe the background or what you're trying to accomplish, and then quote what the spec currently says. Also, the headings are a good idea, but they should summarize the purpose of the next paragraph, not begin it. (Splitting a sentence apart between the heading and the next paragraph is kind of confusing.)

**Comment by jdesrosiers** [comment]
I expect that once the media type is registered, any content related to media-types will be removed and be replaced with a reference to the media type registration.

**Comment by awwright** [comment]
@jdesrosiers I believe we're talking about a passage of the specification that references `application/json` as is already registered, and other media types using the "+json" suffix.

With respect to your point, the IANA registry instructions don't necessarily have to be in the same document, but that doesn't mean we have to remove the media type semantics.

**Comment by handrews** [comment]
@ioggstream RFC 8091 is the `+json-seq` suffix, what is its relevance here?  Did you mean to ask for a reference to [RFC 6839](https://datatracker.ietf.org/doc/html/rfc6839) which registers `+json`?  Either way, what exactly is necessary?  I notice that the RFCs for `application/json-patch+json` and `application/merge-patch+json` do not reference 6839 so I do not understand what we need to do here.

**Comment by ioggstream** [comment]
@handrews Probably I was mistakenly referencing  RFC 6839, but now I don't remember :) I'll close, since rfc 6839 is mentioned.
