### ISSUE TITLE
Review the concept of how annotations can impact validation

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#1215]
> I'm wondering if the entire concept of annotations should be revised to something different - @karenetheridge 

> This is the direction I'd like to go. - @jdesrosiers 

> I'm happy to do that, too, but not in a patch to this version of the spec.  Let's open a new issue to discuss that for the next one. - @gregsdennis

_Originally posted in https://github.com/json-schema-org/json-schema-spec/issues/1172#issuecomment-1068698286_

This may be best discussed in a [GH Discussion](https://github.com/json-schema-org/community/discussions). One should be created.

**Comment by handrews** [comment]
I believe that the annotation/assertion interaction aspects were covered by issue #1172 and PR #1203, and the rest is handled by discussion [#204](https://github.com/orgs/json-schema-org/discussions/204).
