### ISSUE TITLE
Section "Keyword independence" is written twice

### ISSUE THREAD

**Issue by awwright** [json-schema-org/json-schema-spec#1218]
The section "Keyword independence" is a short little section that describes how keywords don't (usually) interact with each other, and that this is a design consideration of JSON Schema. It lists some of the exceptions to this rule.

However, somewhere along the lines, this section was duplicated:

10.1. [Keyword Independence](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.10.1)
11.1. [Keyword Independence](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.11.1)

The doppelgänger should be removed.

**Comment by Relequestual** [comment]
It's not identical. The list of exceptions are different and specifically related to the vocabulary, hence being a subsection.

**Comment by awwright** [comment]
Nonetheless, the purpose of the section is to lay down the design considerations of JSON Schema as a whole, it's not necessary to duplicate it for each vocabulary.

**Comment by Relequestual** [comment]
@karenetheridge I had a quick look but coudln't find anything relating to this, closed or otherwise.

**Comment by gregsdennis** [comment]
@karenetheridge I think I found what you were referring to.  The current text now has this:

https://github.com/json-schema-org/json-schema-spec/blob/a29508c37011ca6682934960014f9a791738ca5a/jsonschema-core.md?plain=1#L487-L511

The first part of this seems like it works to resolve this.  What remains is removing the text from the other sections.
