### ISSUE TITLE
validation of a "const" and whether "type" is required

### ISSUE THREAD

**Issue by hashar** [json-schema-org/json-schema-spec#1256]
I am wondering of the type of a `const` should be validated when validating a json against a schema. More precisely, I am wondering if the `const` should require the `type` to be explicitly specified and if not, the spec is a bit unclear how the type should be validated.  

Given a field having a constant value would surely require a strict equality with what is defined in the schema.

Given a schema such as:
```json
{
  "type": "object",
  "properties": {
    "kind": {
      "const": "hello"
    },
   "val": {
     "const": 3,
    }
  }
}
```

When I validate the schema should it requires `"type": "string"` and `"type": "integer"` respectively?  Or should the validator detect the type of the `const`?

**Comment by handrews** [comment]
Each keyword operates independently unless the specification explicitly describes an interaction.

`const` requires the exact value, so it's not possible to match the value and not match the type.  But that doesn't meant that there's an implicit `type` keyword, or that `type` needs to be explicitly present.

**Comment by hashar** [comment]
Indeed from the validation draft at https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-01#section-6.1.3

> An instance validates successfully against this keyword if its value is equal to the value of the keyword.

I guess it is sufficient ;)  Thank you @handrews !
