### ISSUE TITLE
Support Error Code

### ISSUE THREAD

**Issue by jugaadi** [json-schema-org/json-schema-spec#1282]
Since error messages are not standardised across implementations, it is difficult to share the exact error. Moreover, these error messages can change over time(depending on the library), thus, introducing breakages in implementations. Such breakages can break translations, formatting, etc for the end user.

Example: Server validation output format being passed to client validator.

Suggestions:
1. Current `error` node in output format can point to error code instead of the message.
2. `title` and `description` annotations can be used to add more details of the error.
3. Standardise error code format(similar to SQLSTATE).
4. Introduce error code classes(similar to SQLSTATE) for each constraint type.

Prior art:

1. [HTTP Error Codes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)
2. [Typescript Error Codes](https://typescript.tv/errors)
4. [Postgres Error Codes](https://www.postgresql.org/docs/current/errcodes-appendix.html)

**Comment by gregsdennis** [comment]
Can you give an example that knowing the keyword that caused the error doesn't solve that an error code would?

(I realize that "keyword" isn't a property in the output unit, but check out #1249, which restructures the output unit so that the keyword is actually the key in an `errors` property.)

**Comment by jugaadi** [comment]
The motivation here is to depend on a pre-defined(provided in spec) set of error codes rather than implementation specific error language(English) dependent details. In the new format too, the usage of detailed string instead of code(numeric/short string) is prone to the above issue. 

Doubts wrt new format:
1. If a keyword constraint can result in only one type of error, then isn't an array of keywords enough since the keyword location is already available?
2. Can you share an example of error object in the new format which fails `patternProperties` constraint?

**Comment by gregsdennis** [comment]
> The motivation here is to depend on a pre-defined(provided in spec) set of error codes rather than implementation specific error language(English) dependent details.

Again, what's the difference between an "error code" and just using the keyword. (Asked another way, what if the error code _was_ the keyword?)

> If a keyword constraint can result in only one type of error,

Yes, keywords only result in a single type of reportable error (at least so far as we've seen).  Theoretically, a vocabulary could be created which defines a keyword that could fail in multiple ways, but such a thing is generally advised against.

> then isn't an array of keywords enough since the keyword location is already available?

If you want to only look at the keys, then that's fine, but having human-readable messages from implementations (and especially being able to customize them) is frequently requested.  We won't standardize error message wording, but we definitely can require (or strongly suggest) that an implementation provide one or provide means for clients to define their own.  (My implementation [allows customization and even internationalization](https://json-everything.net/json-schema#error-reporting).)

> Can you share an example of error object in the new format which fails patternProperties constraint?

`patternProperties` itself doesn't produce any errors, but its subschemas do.  It's output would be just like `properties`, which you can see in [this sample](https://github.com/json-schema-org/json-schema-spec/pull/1249/files#diff-bda51aab56b4b2e23fc9e7249e80fe6e262dcd552f35c5de69fd4a6bf3e96b50R3112-R3143)

Effectively, for the `hierarchical` (proposed to replace `detailed` and `verbose`), output units have nested units for subschemas.

**Comment by jugaadi** [comment]
> Theoretically, a vocabulary could be created which defines a keyword that could fail in multiple ways, but such a thing is generally advised against.
> ...
> ...
> but we definitely can require (or strongly suggest) that an implementation provide one or provide means for clients to define their own.

This should work out for our use case. 

Thanks @gregsdennis . Shall I close this issue?

**Comment by handrews** [comment]
Since the original filer suggested closing this almost a month ago with no further commentary, I'm going to go ahead and close it.  It looks like the discussion is resolved to me.
