### ISSUE TITLE
Expand plain name fragments to unicode / IRIs

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#1314]
Currently, our plain name fragments are restricted to the US-ASCII subset of the relevant XML plain name fragment syntax.  Now that we support IRIs should we expand this as well?  I believe the actual XML syntax we reference covers a wider set of unicode.  And perhaps we wouldn't need to spell out the syntax in our spec if we use the XML syntax exactly.

**Comment by gregsdennis** [comment]
Checking the current document, we're using IRI now.  The only mentions of URIs are in the change log.

Closing.
