### ISSUE TITLE
Forbid custom keywords that start with `$`

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#1321]
The Core keywords are easily identifiable by the fact that they start with `$`.

The specification [recommends](https://json-schema.org/draft/2020-12/json-schema-core.html#name-the-json-schema-core-vocabu) against defining custom keywords which also start with `$`, but this recommendation seems to be repeatedly ignored by implementations (`$data` seems to be a common violator).

> While the "$" prefix is not formally reserved for the Core vocabulary, it is RECOMMENDED that extension keywords (in vocabularies or otherwise) begin with a character other than "$" to avoid possible future collisions.

Since this recommendation has been in the spec for multiple iterations, maybe it's time to move this to a `MUST NOT` requirement.

**Comment by handrews** [comment]
We avoided doing that because plenty of implementations support weird custom `$`-prefixed keywords.  However, if we remove support for non-vocabulary keywords, I can see forbidding other vocabulary keywords from using it.  Those older cases were non-vocabulary extensions.

**Comment by gregsdennis** [comment]
We've decided that unknown (non-vocab) keywords will be unsupported moving forward (pending some [additional options](https://github.com/orgs/json-schema-org/discussions/329)).
