### ISSUE TITLE
serverless.yml "slimPatterns" wrong

### ISSUE THREAD

**Issue by alanwilter** [json-schema-org/json-schema-spec#1330]
I orginaly reported there https://github.com/serverless/serverless-python-requirements/issues/733 but now I realise the issue may be here with `json-schema`.

The json schema attribute for `slimPatterns` according to the schema is:

```json
        "slimPatterns": {
          "type": "string",
          "description": "https://github.com/serverless/serverless-python-requirements#custom-removal-patterns"
        },
```

But if one follows the documentation, the correct schema should be:

```json
        "slimPatterns": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "https://github.com/serverless/serverless-python-requirements#custom-removal-patterns"
        },
```

**Comment by handrews** [comment]
@alanwilter this repository is for issues with the JSON Schema specification, not with specific JSON Schemas.  You will want to file this with whoever owns or maintains that schema.

**Comment by alanwilter** [comment]
Where do I find then please:

```
"$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Serverless Framework Configuration",
  "description": "Schema for serverless framework configuration files",
  "fileMatch": ["serverless.yml", "serverless.yaml"],
```

**Comment by handrews** [comment]
@alanwilter I have no idea.  The `"$schema": "https://json-schema.org/draft-07/schema#"` just indicates the version of JSON Schema and does not mean that json-schema.org has anything at all to do with this schema.

**Comment by alanwilter** [comment]
It got sorted: https://github.com/lalcebo/json-schema/issues/58
