### ISSUE TITLE
Need help on if/else/then for comparing objects with inner objects 

### ISSUE THREAD

**Issue by Janu1911** [json-schema-org/json-schema-spec#1332]
For example declinfo is mandatory only if date is available or it is equal to some constant value ,Similar way I have to add validations in other inner objects

{ "$schema": "http://json-schema.org/draft/2019-09/schema#", "type": "object", "description": "test", "title": "test", "properties": { "date": { "type": [ "string", "null", "integer" ], "description": "Date", "format": "^[0-9]$", "minLength": 1, "maxLength": 8 }, "declInfo": { "type": "array", "items": { "type": "object", "properties": { "number": { "type": "string", "format": "^[a-zA-Z0-9._\- ]$", "minLength": 1, "maxLength": 19 } } } } } }

**Comment by handrews** [comment]
@Janu1911 could you please format this more clearly?  You can use the [code and syntax highlighting] feature of GitHub Markdown to do so.

Usually, you have to have the `if` above the level of everything involved.  So if you are doing conditionals with object properties, the `if` has to be at the level where you would normally have `properties`.  The `properties` keyword would appear within the `if`/`then`/`else` subschemas.

**Comment by handrews** [comment]
No response for nearly a month, so I'm closing.  Please feel free to re-open with a formatted example and a clarified question.
