### ISSUE TITLE
Identify currently unstable features and resolve those which are required for basic operation

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#1337]
The current feature set of JSON Schema needs to be cataloged so that unstable features can be identified.

Once that is done, any unstable features that are required for basic operation need to be updated so that they can be considered stable for the first release using the new SDLC.

**Comment by handrews** [comment]
I have a catalog... actually I have like three or four, I need to figure out which one makes the most sense.

(this is not to discourage anyone else from publishing one, just noting that I would like to throw mine into the ring but won't have time to do so this week).

**Comment by gregsdennis** [comment]
Superceded by #1444
