### ISSUE TITLE
'type' attribute - only allow string defining the simple type, not an array with several simpleTypes - can be emulated with anyOf

### ISSUE THREAD

**Issue by jschnaitmann** [json-schema-org/json-schema-spec#134]
In my opinion, it would make the schema definition more robust if by default, only one 'type' value would be allowed:
```
"type": {
  "$ref": "#/definitions/simpleTypes"
},
```

If one wants to allow different types, that could be emulated using anyOf:
```
"somePropertyName": {
  anyOf: [ { type: 'string' }, { type: 'number' }, { type: 'boolean' }  ]
},
```

**Comment by awwright** [comment]
The ability to specify multiple types is provided as an author convenience. What would we gain by removing that?

**Comment by jschnaitmann** [comment]
I would argue that it should be recommended to NOT allow different types for one attribute, i.e. to specifically make it inconvenient. Allowing different data types makes handling of such objects more complicated in code and harder to understand by humans, and does not nicely map e.g. to a SQL scheme where you cannot have a column being e.g. both a number and a string.

In addition, it makes the schema definition simpler, also allowing simpler validation code.

**Comment by awwright** [comment]
Do you have any evidence that the "anyOf" usage is easier for people to understand, or easier to map to a storage medium?

**Comment by jschnaitmann** [comment]
Not necessarily, but the anyOf functionality is part of JSON schema either way. Allowing a string or an array as a value for 'type' introduces an additional concept one has to memorize.

Although lots of authors probably do not use or know anyOf, I guess? Still, I'd say that's ok, because allowing different data types for an attribute should not be encouraged anyway, in my mind.

**Comment by handrews** [comment]
> I would argue that it should be recommended to NOT allow different types for one attribute, i.e. to specifically make it inconvenient.

I don't think that the role of JSON Schema should be to impose opinions on how JSON is used.  There are many things for which JSON Schema can be used that are not database-oriented.  Plus, I most often see types like `["integer", "null"]` for nullable fields (although I personally prefer to just leave fields out rather than pass explicit nulls).

**Comment by jschnaitmann** [comment]
Agreed. Let my try to rephrase that sentence:

I would argue that it should not be encouraged to allow different types for one attribute by specifically providing a convenience method to do so.

**Comment by epoberezkin** [comment]
@jschnaitmann I don't think we really need this change. As @handrews pointed out in propertyNames issue, it's not JSON-schema standard role to be opinionated about good/bad data structures (and I agree), and this is what this change is about.

**Comment by jschnaitmann** [comment]
The original intention of the proposal was about reducing the complexity of the schema definition. The behavior of allowing different data types can be accomplished using anyOf(), which is present in the spec anyway, whereas allowing a string or an array of strings for 'type' introduces a new concept.

I agree that this does introduce a kind of opinion - however, in some ways, less than the current specification that, again, encourages allowing different data types by providing the convenience method. It might even push authors towards that direction, as the possibility of doing so is explicitly described in the docs, instead of being implicitly available through anyof().

**Comment by handrews** [comment]
@jschnaitmann this hasn't picked up any support in the last two months.  If no support emerges and no new compelling arguments can be found within the next two weeks-ish, I think it's probably time to close this.  But do feel free to try to round up support if you still want to push for this.

**Comment by Relequestual** [comment]
Just because you can do something stupid, doesn't mean you should. I expect the majority of the time, people will define only one type. If the shcema you're looking at defines more than one, and you have a problem with that, your issue is with the author, and not JSON Schema.

Discouridging something by making it more difficult doesn't feel like a good fit for how we should be changes.

As there hasn't been any further comments, I'm closing this issue.
