### ISSUE TITLE
Update spec to disallow unknown keywords

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#1340]
Following @handrews' discussion on [disallowing non-vocab keywords](https://github.com/orgs/json-schema-org/discussions/241), we decided that this is a feature that we want in order to help guarantee forward compability.

The spec needs to be updated accordingly.

**Comment by handrews** [comment]
We did?  I mean, I'm all for it!  I just didn't realize there was consensus.  There should probably be an ADR first as this is a pretty big deal, and there are some details to nail down.

**Comment by gregsdennis** [comment]
As far as I could tell from the proposal, I felt that we all seemed to agree on doing it.

Others are, of course, encouraged to speak up.

**Comment by handrews** [comment]
I can probably write it up as an ADR easily enough (the conversation wasn't that lengthy so I'll just do a bit of cut/paste/edit) and we can have an official PR for sign-off.  If we're all in agreement it should go quickly anyway.

**Comment by jdesrosiers** [comment]
> There should probably be an ADR

The ADR I'm going to write will cover that we are committing to forward compatibility, but I don't think it will cover the specific changes (like this issue) that need to happen to make that possible. So, if you write an ADR specifically for this issue, I think there would be some overlap, but it could still make sense as a separate ADR.

**Comment by handrews** [comment]
@jdesrosiers sounds good- I'm basically planning to just edit that discussion into a document.  I don't plan on addressing the larger forwards compatibility topic, it would just be assumed from the SDLC and could link to the ADR for that.
