### ISSUE TITLE
Update spec to require unstable features to be disabled by default

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#1341]
Related to #1339, we need to add language that requires implementations to disable unstable features as the default behavior.

**Comment by gregsdennis** [comment]
In conjuction with #1340, does this mean that a schema with an unstable keyword is expected to error by default?

**Comment by jdesrosiers** [comment]
> In conjuction with https://github.com/json-schema-org/json-schema-spec/issues/1340, does this mean that a schema with an unstable keyword is expected to error by default?

Yes. Consumers would need to opt in to using they keywords.

**Comment by gregsdennis** [comment]
Unstable features are being extracted into the feature life cycle.  See #1444
