### ISSUE TITLE
Update spec to require implementations to raise an error if it encounters a dialect it doesn't understand

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#1342]
Similarly to encountering unknown keywords, implementations should raise an error for unknown dialects.

**Comment by handrews** [comment]
This needs an ADR, or possibly needs to be delayed until we figure out bootstrapping more clearly.  Currently, we only error out on vocabularies, not dialects, and my sense is that the granularity of these concepts is in flux.  We should figure out what the actual granularity of control is, and where that control is located, before trying to set the requirements in the spec.

**Comment by jdesrosiers** [comment]
I think the way I used the term "dialect" might have led to some misunderstanding of the purpose of this issue. What I meant was that the implementation must raise an error if it doesn't fully understand what set of keywords are part of the dialect. That should be a concept independent of the details of bootstrapping and the vocabulary system.

I don't remember exactly what the spec currently says about this kind of thing, but I imagine that most if not all of it is already covered. However, my guess is that it's currently written in a way that is coupled to the vocabulary system and should probably be rewritten in a way that's more generic so we don't need to change the wording as the vocabulary system evolves.

**Comment by gregsdennis** [comment]
This needs to be a consideration for whatever vocabularies ends up being.  See #1510
