### ISSUE TITLE
Need a better term than "nested" in basic output

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#1347]
I'm trying to write a blog post using the proposed 2023 **basic** output format, and I find myself having to write an extra paragraph explaining and justifying the use of the property name `"nested"`.

What's worse is that I can't find a way to write a compelling explanation that will work for all or even most readers.  "Strictly typed languages are happier if this field is named the same thing" is not a compelling reason.  For people without a background in strictly typed languages, it's not even a reason that makes sense.

I still object to forcing basic and hierarchical into the same structure to appease strictly typed languages, but if we _must_ do that, then we need to pick a neutral name that is equally tolerable in both basic and hierarchical forms.

`"outputUnits"`, `"units"`, `"output"`, `"details"`, or just `"data"` or `"info"` would all be improvements.

Literally anything that does not imply hierarchy in a format that is _intentionally not at all hierarchical_ would be better.

**Comment by gregsdennis** [comment]
I'm happy to change it to `details`.  I'm not set on `nested`; I just couldn't think of something better that fits both cases.

I'm not sure the strictly typed language argument apples anymore, though.  The only place it's used in `basic` is the root node (which _is_ needed to hold an overall `valid` property).  Also, I already have logic to remove the location properties from the root node for `basic` during serialization, so changing the serialization name of the property for this case wouldn't be hard.  It will just be `nested` or `details` or whatever in my model.

**Comment by handrews** [comment]
Awesome- yeah, I'm fine with the overall `valid` property thing and having the same structure for it at that level.  It's only having the name be hierarchical-ish in basic that I found hard to explain.

**Comment by handrews** [comment]
Anyone object to `details`?  If not we can just go ahead and make that change (and maybe update the "fixing output" blog post to keep it in sync?)

**Comment by gregsdennis** [comment]
@handrews please see ☝️

**Comment by handrews** [comment]
Thanks!  While we're at it, how about calling the new "basic" "flat" instead?  Then we just have two new formats that are standard ("flat" and "hierarchical") and three old ones that are deprecated ("basic", "detailed", and "verbose") and no overlap or breaking conflicts.

**Comment by handrews** [comment]
If we think "flat" is too closed to "flag" I supposed it could be "flattened".  ("smooshed"?  😛 )

**Comment by gregsdennis** [comment]
How about "list"?

**Comment by handrews** [comment]
Yes, "list" works for me!  I like it better than "flat".

**Comment by marksparkza** [comment]
Sorry for jumping in late, I was just wondering why not just plain `detail`? The singular (uncountable) form seems to be more commonly used in code than the plural (taking an admittedly very cursory look at Python libraries), and I think is less prescriptive about the structure of the corresponding value. I think `details` works fine for a flat array as in the `list` output format, but I find `detail` to be somewhat easier on the eyes (and brain!) for `hierarchical`. I also think the plural form kind of precludes the possibility of defining an output format that allows the detailed info to be a scalar.

**Comment by gregsdennis** [comment]
> I also think the plural form kind of precludes the possibility of defining an output format that allows the detailed info to be a scalar.

The `details` property would never be a scalar.  It's always an array, even if it only has a single item.

**Comment by marksparkza** [comment]
OK. I had been thinking of `detail` as being an elaboration/explanation of `valid` - which makes sense when considering an invalid outcome and associated errors [similar to the HTTP `status_code` / `detail` combo in an API framework that I work with - where `detail` can be any JSON-compatible value]. But, `details` does actually sound better when thinking about a valid result node with multiple heterogeneous annotations in its subtree. `details` it is.
