### ISSUE TITLE
"additionalItems" should not be honored if "items" is an object.

### ISSUE THREAD

**Issue by SereneAnt** [json-schema-org/json-schema-spec#135]
As per [json-schema specification](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.9):
> if "items" is not present, or its value is an object, validation of the instance always succeeds, regardless of the value of "additionalItems";

Currently (v 4.0.x), CollectionConstraint makes an extra checks for "additionalItems" if "items" is object and  fails validation.

**Comment by SereneAnt** [comment]
Wrong repo.

**Comment by awwright** [comment]
@SereneAnt Just a heads up that language is a tad bit confusing, the language seems to only apply for "items", "additionalItems" should still fail even if "items" isn't defined. If in doubt check the behavior against the [official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite). If it's all too confusing, please let us know.

**Comment by epoberezkin** [comment]
@awwright:

> "additionalItems" should still be able to fail even if "items" isn't defined

there is no test for such scenario in the test suite you are referring to. The draft says in clear terms that additionalItems are only taken into account when items is array.

**Comment by handrews** [comment]
> The draft says in clear terms that additionalItems are only taken into account when items is array.

Also important is this line in "items":

> If absent, it can be considered present with an empty schema.

This means that "items" is effectively always defined, so "additionalItems" cannot be applied unless "items" is a schema.  The default empty schema value of "items" takes precedence.

**Comment by epoberezkin** [comment]
> "additionalItems" cannot be applied unless "items" is a schema.

I'd say, array of schemas. If it is a schema, additionaltems is ignored.

**Comment by handrews** [comment]
> I'd say, array of schemas. If it is a schema, additionaltems is ignored.

Oops, that was a typo, I'll edit it.
