### ISSUE TITLE
Invalid JSON (Typo)

### ISSUE THREAD

**Issue by watuwo** [json-schema-org/json-schema-spec#1350]
A core specification example contains:

```
...
"pattern": "\d\d\d\d-\d\d-\d\d",
...
```

This is not JSON.

**Comment by gregsdennis** [comment]
Can you provide a link to the section where this is found?

This is partial JSON.  It's commonly understood from the `...` that there is more to the JSON text above and below.

**Comment by handrews** [comment]
I think it needs to be `"\\d\\d\\d\\d-\\d\\d-\\d\\d"` in order to produce the regex `\d\d\d\d-\d\d-\d\d`
