### ISSUE TITLE
Fix a typo in the section “Format-Assertion Vocabulary”

### ISSUE THREAD

**Issue by Markus-Elfring** [json-schema-org/json-schema-spec#1356]
:thought_balloon: I suggest to use the word “specification” instead of “[specificaion](https://github.com/json-schema-org/json-schema-spec/blob/96650071f0c71d2a17403b42015524d23c4f106d/jsonschema-validation.xml#L576 "Typo")”.

**Comment by gregsdennis** [comment]
Thanks for noticing.  Happy to accept a PR.

**Comment by gregsdennis** [comment]
Looks to be done.
