### ISSUE TITLE
Interpretation: Can Arrays be Objects?

### ISSUE THREAD

**Issue by sinclairzx81** [json-schema-org/json-schema-spec#1371]
Hi! I have a question with respect to the interpretation of `"array"` and `"object"` when validating in the context of JavaScript / TypeScript.

Consider the following schema.

```typescript
const T = {
   type: 'object',
   required: ['length'],
   properties: {
     length: { type: 'number' }
   }
}
```
Now, if implementing a JavaScript validator to check a value against this schema, the following two validation checks "could" in theory pass (with note to the second check).

```typescript
validate(T, { length: 42 }) // ok: expected

validate(T, [0, 1, 2]) // ok: because an array is an 'object' and has a 'length' property.
```
So validators (including Ajv) would fail the `[0, 1, 2]` value (because an Object is clearly not an Array), however JavaScript does somewhat blur the lines here as Arrays are actually just Objects (and would lead one to assume the second test would be ok). One could in theory constrain the schema to fail the second check however ....

```typescript
const T = {
   type: 'object',
   additionalProperties: false, // added
   required: ['length'],
   properties: {
     length: { type: 'number' }
   }
}

validate(T, [0, 1, 2]) // fail: the properties '0', '1' and '2' are additional properties.

validate(T, []) // ok: have length, but no properties
```
So, just looking to get some thoughts from the JSON Schema contributors on this aspect; mostly to understand if there is room to interpret the specification in this way. While, I do think the sensible approach is to adhere to the "Arrays are not Objects" standpoint (particularly when considering `validate(T, [])` above, it does run counter to the structural type checks in say TypeScript....

```typescript
function test(value: { length: number }) {}

test([1, 2, 3]) // structurally ok
```
I guess while most languages have a strong distinction between what is and isn't an Array, JSON Schema does seem flexible enough to express the JavaScript/TypeScript interpretation (at least in terms of what it observes from a `JSON.parse()` call). But curious to get some thoughts on this.

Many Thanks!
S

**Comment by gregsdennis** [comment]
> it does run counter to the structural type checks in say TypeScript

Javascript and Typescript have implemented its `Array` type as a descendant of its `Object` type (as many languages do).  This is a language design decision.   The `Object` type is a different thing than what JSON calls "objects."  In JSON's data model, arrays and objects are not related.

I've seen a lot of places where languages have tried to blur the line between the language and JSON's data model.  Most notably is .Net's decision ([link](https://github.com/dotnet/runtime/issues/68128)) to unify JSON's `null` (a valid literal value) with its internal notion of `null` (no value is associated with the variable).  It's important for cases like these to maintain a clear separation between JSON and the language.

**Comment by sinclairzx81** [comment]
@gregsdennis Thank you for the response!

> It's important for cases like these to maintain a clear separation between JSON and the language.

Yes, I actually agree. But it is interesting that in that on one hand you have JSON (a subset of JavaScript), and the other TypeScript (a superset of JavaScript) both with different interpretations of what Objects and Arrays are. When contrasting TypeScript's interpretation of Array with the JSON Schema's interpretation, the JSON Schema interpretation almost seems artificially constrained (at least in a structural sense) to how Arrays are actually observed by JavaScript (of which JSON is derived)

I do think there is bit of a mismatch between how data is encoded in JSON (as a format), and how that data could be ultimately observed by JavaScript. Modern structural interpretations of JavaScript (as implemented in TypeScript) do have some implication on JSON decoded values, but to observe values in a structural sense, one needs to reinterpret what JSON means to JavaScript.

Could you provide a couple of rationales on why such a separation should be maintained in the JavaScript case?

> I've seen a lot of places where languages have tried to blur the line between the language and JSON's data model. Most notably is .Net's decision (https://github.com/dotnet/runtime/issues/68128) to unify JSON's null (a valid literal value) with its internal notion of null (no value is associated with the variable).

This is a good reference case. From memory, C# cannot represent the absence of property in the type system (ignoring the DLR, and with note to `null` being used for absence of value in C#). Reading this issue, it does look like the `System.Text.Json` implementation does take liberties with the spec in order to align to the capabilities of the language. 

I do very much agree that being able to distinguish between `null` and `missing value` is important; but in this particular case, the implementers appear to have taken the pragmatic path. However by doing so, they have set a precedent for other implementers of the specification to interpret the specification in ways specific to the host language. It begs the question, how far can one reasonably re-interpret the specification?

Given C# has interpreted the specification in this way, should this imply there is flexibility to interpret validation checks differently across different languages? Also, given that TypeScript uses a structural type system to describe JavaScript values, would it be reasonable to implement a JSON Schema validator that adopts TypeScript's structural assertions of that value? (noting JSON schema seems capable expressing the schematics to achieve this)

### Structural Array Object in C#

Just musing on a C# implementation of a structural array below.

```typescript
bool Validate(object schema, object any) { 
    throw new NotImplementedException();
}

var T = new {
   type = "object",
   required = new string[]{"Length"},
   properties = new {
     length = new { type = "Length" }
   }
};


Validate(T, new int[]{ 1, 2, 3 }); // true
```

Just for a little bit of context, these questions mostly relate to things happening in [this](https://github.com/sinclairzx81/typebox) project; which is trying to find parity between JSON Schema and the TypeScript type system.

Again thanks for your response! I hope to hear back from you. 
S

**Comment by gregsdennis** [comment]
> you have JSON (a subset of JavaScript)

I would argue that [JSON is its own thing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#javascript_and_json_differences) at this point.

> When contrasting TypeScript's interpretation of Array with the JSON Schema interpretation...

Why do you think JSON Schema has an "interpretation" of JSON's structure?  We use the various JSON specifications' definition of the data types it can contain, all of which state that objects and arrays are different data structures.

> I do think there is bit of a mismatch between how data is encoded in JSON (as a format), and how that data could be ultimately observed by JavaScript.

You still seem tied to this notion that JSON and Javascript function as one; that they're intrinsically linked.  They're not.  In fact it's beneficial that they'er not as this is what makes JSON usable in other languages.  If they were the same thing, other languages would need Javascript interpreters to use JSON.

JSON has four types

- object (a collection of key-value pairs)
- array (a collection of values)
- strings
- numbers

and three literals

- `true`
- `false`
- `null`

(`true`/`false` are often interpreted as "booleans" but per the spec, they are literals.)

That's it.  That's the entire type system for JSON.

> Could you provide a couple of rationales on why such a separation should be maintained in the JavaScript case?

As I mentioned before, Javascript (and Typescript) has made design decisions to help it operate as a functional language (as in it functions, not the programming paradigm).  JSON does not need to "function" in that sense; it's merely data.  As such, an "array" can be a distinct thing from an "object."  However, I'm not on the Javascript team, so I can't speak to why it's designed that way.

> Reading this issue, it does look like the System.Text.Json implementation does take liberties with the spec in order to align to the capabilities of the language.

"take liberties"... not quite.  They've interpreted JSON correctly.  Their parser is very strict.  They've just made a design decision which makes working with JSON `null` as an actual value very difficult.  It has nothing to do with an interpretation of the spec.

> However by doing so, they have set a precedent for other implementers of the specification to interpret the specification in ways specific to the host language.

They are setting no precedent; in fact, quite the opposite.  They're following the example of the vastly popular Newtonsoft.Json library, which was the go-to library for JSON parsing since the early days of .Net.  My parser (Manatee.Json) treated JSON null as a valid value, not merging it with .Net null.

> given that TypeScript uses a structural type system to describe JavaScript values, would it be reasonable to implement a JSON Schema validator that adopts TypeScript's structural assertions of that value?

No, it would not, for the same reasons I listed above:  JSON's types are not Javascript's/Typescript's types.  They are distinct concepts.

---

I see you've described your project as a "JSON Schema Type Builder."  You should really read JSON Schema Type Builder about why JSON Schema is not a type descriptor language.

**Comment by sinclairzx81** [comment]
@gregsdennis Thanks again for the response! I appreciate the detailed reply!

Yes, I pretty much agree with you on these points. However please know, I am trying to take on an alternative point of view to try and represent a couple of trends I've seen recently in the data validation arena (notably attempts to assert data structurally inline TypeScript's structural view of JavaScript). One thing that seems central to this trend; is the idea of expressing some form of schematic (like JSON Schema) that encodes the structural checks performed by TypeScript, enabling 1-1 static / runtime assertions.

The initial enquiry and subsequent responses can be interpreted as me trying to coerce JSON Schema into being this schematic. However, I am quite aware this is a bit of a "square peg in a round hole" scenario (particularly with the understanding that JSON schema is NOT a type descriptor language). But as JSON schema gets so astonishingly close to being one, It does have me wonder if re-interpreting JSON Schema validation to act as some form of general purpose "X Schema" that is decoupled from JSON, and able to validate data across both nominal and structural type systems is a worthwhile thing.

> You still seem tied to this notion that JSON and JavaScript function as one; that they're intrinsically linked. 

Not exactly, I don't believe JSON and JavaScript are intrinsically linked (rather I simply wanted to point out that one was derived from the other). Mostly I wanted to raise TypeScript's structural view of JavaScript (and by consequence it's view of decoded structures read from JSON) and contrast this with JSON Schema (which is purely aligned to the primitives that constitute the JSON format), mostly to find where JSON Schema and TypeScript can (and should) intersect.

> They're not. In fact it's beneficial that they'er not as this is what makes JSON usable in other languages. If they were the same thing, other languages would need Javascript interpreters to use JSON.

Of course, JSON is just an interchange format. 

> No, it would not, for the same reasons I listed above: JSON's types are not Javascript's/Typescript's types. They are distinct concepts.

Yes, I agree. But as noted they are so close to being one in the same. I've been staring at their similarities for over 5 years and do wonder if it's worthwhile just prototyping a new schema representation a little more attune to aligning these concepts. Such a representation would be basically JSON Schema as it today, but with different validation rules and possibly slightly different compositional rules for `additionalProperties` and `unevaluatedProperties`.

On the inverse, I am rather at odds with re-inventing something that has had as much engineering and insight as the JSON Schema specification. But still, tempting none the less.

> I see you've described your project as a "JSON Schema Type Builder." You should really read JSON Schema Type Builder about why JSON Schema is not a type descriptor language.

Not sure if I understood this line, but the library is described so as it provides schema composition API that can infer static TypeScript types. It implements a limited subset of the JSON Schema specification, but what it does implement is very much on spec (i actually test conformance with Ajv)


Well again, thanks for the detailed responses. It's quite hard to find people to talk to about some of the details around the JSON schema specification and some of the rationales, so your responses have been hugely appreciated. Happy to keep discussing in more depth, but I think I'm pretty clear here that JSON Schema validation should treat Arrays and Objects as distinct.

Will close off this issue for now.

All the best! :)
S
