### ISSUE TITLE
Extend the meta-data vocabulary with an "authors" keyword

### ISSUE THREAD

**Issue by jviotti** [json-schema-org/json-schema-spec#1373]
That would record who created the given schema. Has something like this ever being considered?

**Comment by gregsdennis** [comment]
I think this can be covered with a general annotation, which currently is in the form `x-*`, so `x-authors` would be allowed.

The meta-data vocab is generally for annotating the instance, not providing information about the schema.  The core vocab is generally for keywords that describe the schema (e.g. `$comment`).

**Comment by jviotti** [comment]
Makes sense!
