### ISSUE TITLE
Confusing behavior of `$id`

### ISSUE THREAD

**Issue by EmilySeville7cfg** [json-schema-org/json-schema-spec#1398]
Given this JSON schema in VS Code:

```json
{
    "$id": "http://emily.json",
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "first": {
            "$id": "#a",
            "type": "boolean"
        },
        "second": {
            "$ref": "http://emily.json#a"
        }
    }
}
```

and this test file:

```yaml
first: true
```

I obtain: `Problems loading reference 'http://emily.json/#a': Unable to load schema from 'http://emily.json/': Request vscode/content failed unexpectedly without providing any details.` error. While executing `jsonschema-cli validate schema.json test.yaml` works fine. Is it a VS Code YAML Red Hat extension bug, or I am missing something?

**Comment by Relequestual** [comment]
I'd call that a bug.
If you go file an issue, please reference this issue so we can see it easily? =]

**Comment by EmilySeville7cfg** [comment]
> If you go file an issue, please reference this issue so we can see it easily? =]

Sure. :)

**Comment by Relequestual** [comment]
Feel free to suggest they add their implementation to BowTie: https://bowtie-json-schema.readthedocs.io/en/latest/implementers/

Or, if you have the time, feel free to try yourself =D
