### ISSUE TITLE
description of readOnly is ambiguous and refers to property when it should be instance

### ISSUE THREAD

**Issue by DavidBiesack** [json-schema-org/json-schema-spec#1402]
The [2020-12 validation spec](http://json-schema.org/draft/2020-12/json-schema-validation.html#name-readonly-and-writeonly) reads
> attempts by an application to modify the value of this property
This should be changed to
> attempts by an application to modify the value of this instance
since readOnly can apply to an object or array or primitive schema, not just properties on an object.

(I'd also like more clarity here when `readOnly: true` appears on a container instance - i.e. explicitly state whether this constraint does or does not extend to containers within the container. I believe it is local and only applies to the container)

**Comment by gregsdennis** [comment]
Since `readOnly` is merely an annotation, JSON Schema is intentionally non-prescriptive on what its meaning is.  That is for the consuming application to decide.

If two applications are sharing a schema that contains `readOnly`, then they need to agree on its usage.

**Comment by jdesrosiers** [comment]
@DavidBiesack I agree that this wording is awkward at best. The current wording makes it sound like the keyword is only allowed on schemas that describe properties, which is not true. I'd approve a PR with the proposed change.

> (I'd also like more clarity here when readOnly: true appears on a container instance - i.e. explicitly state whether this constraint does or does not extend to containers within the container. I believe it is local and only applies to the container)

I've always thought of it as extending to the entire value. For example, you could put it at the root of your schema to indicate that the entire document is read only.

**Comment by DavidBiesack** [comment]
[PR submitted](https://github.com/json-schema-org/json-schema-spec/pull/1522)

**Comment by DavidBiesack** [comment]
The [PR build failed](https://github.com/json-schema-org/json-schema-spec/actions/runs/9574420681) though I don't know what that rule is, what it means, or how to correct it.

**Comment by gregsdennis** [comment]
We have a two-week minimum open time for spec changes.  That GH Action just keeps us from violating it.
