### ISSUE TITLE
Contributing guide file is outdated

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#1414]
The contributing guide file located at 
https://github.com/json-schema-org/json-schema-spec/blob/main/CONTRIBUTING.md is out of date, and not accurate for how we are proceeding.

We should do one of the following 
- Add a note to the top which states this fact
- Remove the content that is outdated
- Start the file from scratch based on our current understanding

This file will require review again once we publish the next version of the specification.

**Comment by benjagm** [comment]
I just opened a PR with a new version of the contributing guidelines of the Spec and I'd love to get feedback and reviews.
