### ISSUE TITLE
No standard way to define schema for key in "Record-like" objects 

### ISSUE THREAD

**Issue by npdev453** [json-schema-org/json-schema-spec#1448]
**Original issue:**
https://github.com/sinclairzx81/typebox/issues/601

I don't like when Record-like objects used in JSON-related things (API, Generators, Validators), basically, I think it because I have "childhood trauma" about JSONSchema that can't strictly declare left side of it.

**Args:**
- Record-like objects closely woven in JS routine
- no properly way to define its schema of `key` (like `PositiveInt`, `format:'phone'` & etc.)
- no properly way to document it (`title`, `description` & etc.)
- `jsonschema -> ts` (and I think others) generators can't properly generate `key` type, only indirectly
- can be useful with `additionalProperties: true` 
- will be nice to have option to `$ref` that `key`  

**Input Examples:**
```ts
const wasWindy = {
    '2018-11-12': true,
    '2018-11-13': false,
    ...
};
// [key: date] : boolean

const sensors = {
    '4c191b6b-fa2c-4aae-bb2a-26fb365c99b3': { active: true },
    'c8f20fd4-138f-4c50-84f9-2eff76300973': { active: false },
    ...
};  
// [key: UUID] : { active: boolean }
// or nominal: (that also can't be reproduced from schema)
// [key: SensorId] : SensorStatus
```

**I don't see a clear way for now, but for the start:**
Variant 1: 
```ts
{ // some extra keys for left & right side
    type: "object",
    keys?: (string | number | sym) scheme, // or
    indexSignature?:  (string | number | sym) scheme, // maybe
    property?: (any) scheme,
    properties?: {}
}
```
Variant 2:
```ts
{ // new type 
    type: "record",
    key: (string | number | sym) scheme,
    value: ...
}
```
Variant 3:
```ts
{ // new key for left side
    type: "object",
    properties: {},
    additionalProperties: (any) scheme
    additionalKeys?: (string | number | sym) scheme,
}
```

---
**Refs:**
https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type
https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures

**Comment by jdesrosiers** [comment]
I'm not entirely following what you're asking for here, but you might be interested in the [`propertyNames`](https://json-schema.org/understanding-json-schema/reference/object.html#property-names) keyword that allows you to define a schema that applies to all properties in an object. Here's a schema that would describe your first example.

```
{
  "type": "object",
  "description": "Was Windy Record",
  "patternProperties": {
    "": { "type": "boolean" }
  },
  "propertyNames": {
    "description": "The date it was windy",
    "$comment": "'type: string' is implicit because a property name isn't allowed to be anything else in JSON",
    "format": "date"
  }
}
```

**Comment by npdev453** [comment]
Yeah, it is! Thanks!

Sorry for the panic, never seen it before (think because `Swagger` don't support this field)
