### ISSUE TITLE
If-Then-Else supported?

### ISSUE THREAD

**Issue by alc-aardvark** [json-schema-org/json-schema-spec#1468]
I have loaded a schema from json-scema.org ([here](https://json-schema.org/understanding-json-schema/reference/conditionals)) that contains "anyOf" with 3 If-Then conditions.  When I look inside the c# instance for AnyOf, then there are 3 rows but each row is just full of Null values.  This leads me to think that If-Then-Else is not yet supported.

I also looked at the test json files and I do not see any with If-Then-Else conditions.

**Comment by gregsdennis** [comment]
Which implementation are you using? You mention c#, but we have several for .net (including mine, _JsonSchema.Net_, for which they are definitely supported).

**Comment by alc-aardvark** [comment]
I am using Microsoft.Json.Schema

**Comment by gregsdennis** [comment]
From their [project repo](https://github.com/Microsoft/jschema):

> A set of .NET components for working with JSON Schema Draft 4

That's pretty old.  I'd recommend you choose a different implementation.  All of the ones listed on the implementations page (link above) support at least draft 7, which defines `if`/`then`/`else`.

**Comment by alc-aardvark** [comment]
Thanks all.  I am now using JsonSchema.Net .
