### ISSUE TITLE
Core regex should permit "."

### ISSUE THREAD

**Issue by lukem** [json-schema-org/json-schema-spec#1469]
[Core 6.4 Regular Expressions](https://json-schema.org/draft/2020-12/json-schema-core#section-6.4) doesn't explicitly list "." as one of permitted regular expression constructs.

This seems to be an oversight.

I propose adding it to the list of simple quantifiers as:
> "." (any character except line terminator)

**Comment by gregsdennis** [comment]
Closed by ☝️
