### ISSUE TITLE
Validation Regex Description (section 7.3.8) should follow format of other string validation types

### ISSUE THREAD

**Issue by dlemire60** [json-schema-org/json-schema-spec#1474]
re: `draft-bhutton-json-schema-validation-01`:  The defined format descriptions in 7.3.1 - 7.3.7 use consistent language: "A string instance is valid against this attribute if ..."

The language in 7.3.8 is different, simply saying "A regular expression, which SHOULD be valid according to the ECMA 262 regular expression dialect." 

I found this language unclear in describing that the string instance being validated should *be* a regex, rather than *conforming to* a regex. I recommend updating the wording in 7.3.8 to align with the preceding sections.

**Comment by gregsdennis** [comment]
@dlemire60 I'm happy for you to submit a PR for this, but I read "valid according to the ECMA 262 regular expression dialect" as saying "is a regex".  The ECMA 262 regular expression dialect _defines_ regexes.
