### ISSUE TITLE
Enum : Clarification

### ISSUE THREAD

**Issue by LasneF** [json-schema-org/json-schema-spec#1475]
given the illustration there 

https://json-schema.org/understanding-json-schema/reference/enum 

it would be good to add a precision that the enum validation, for string,  is  case sensitive , and so introducing in the sample list  "RED" that would fail the validation 

This would also be nice to  mentionned the precision here 
https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-validation-00#rfc.section.6.1.2 

may be as well as a general rules for the nice understanding json schema documentation ,  propose for each element a link to the core 
json  rfc specification  this would help for traceability and digging into the deatails

**Comment by vr-varad** [comment]
@awwright is this issue under work??

**Comment by vr-varad** [comment]
i would like to work on it

**Comment by gregsdennis** [comment]
I believe this is sufficiently covered by [Core Section 4.2.2](https://json-schema.org/draft/2020-12/json-schema-core#section-4.2.2):

> both are strings, and are the same codepoint-for-codepoint
