### ISSUE TITLE
Build failure due to Relative JSON Pointer specification

### ISSUE THREAD

**Issue by Julian** [json-schema-org/json-schema-spec#1476]
CI appears to no longer run now that it's 2024 but the [relative-json-pointer.xml specification contains a `<date>` element with no month and 2023](https://github.com/json-schema-org/json-schema-spec/blob/4df0f8dd239328dcbf6c2509b9682fe275735a3c/relative-json-pointer.xml#L43)

producing:

> /home/runner/work/json-schema-spec/json-schema-spec/relative-json-pointer.xml(16): Error: Expected <date> to have the current year when month is missing, but found '2023'

on build.

I'm not sure what the intended solution is for this, but ideally it's something we don't need to do every year (i.e. hopefully it's not just "bump to 2024")?

**Comment by Julian** [comment]
For a sample run see e.g. https://github.com/json-schema-org/json-schema-spec/actions/runs/7453007216/job/20277474638 from merging a trivial fix to the website link, though GitHub actions logs won't last forever obviously so that may not work as a link for you Reader in the Future.

**Comment by gregsdennis** [comment]
This has been fixed.
