### ISSUE TITLE
Publish new drafts of expired Specification Documents

### ISSUE THREAD

**Issue by jischr** [json-schema-org/json-schema-spec#1516]
The specification documents mentioned here https://json-schema.org/specification#specification-documents are all expired drafts (expired on 18 December 2022). Are they being actively worked on? Are there plans to move them to v1?

**Comment by gregsdennis** [comment]
Yes.  We're working on it.  Please see the multitude of issues in this repo under the [stable-release milestone](https://github.com/json-schema-org/json-schema-spec/milestone/10) along with discussions under the [specification](https://github.com/orgs/json-schema-org/discussions/categories/specification) and [vision and direction](https://github.com/orgs/json-schema-org/discussions/categories/vision-and-direction) categories.

**Comment by jischr** [comment]
thank you for these links!

> Regarding the "expired drafts", they are regularly used in production systems globally and can still be referenced/implemented. We have republished them on our site as part of our decision to leave the IETF process and self-publish.

Thanks for that background with IETF. Is the document https://json-schema.org/draft/2020-12/json-schema-validation considered stable itself? I know 2020-12 is released. I would like to reference the document directly.

**Comment by gregsdennis** [comment]
On its own, yes, each document is stable in that is not going to change. 

Our current effort for a "stable spec" focuses more on stability between releases, which will start with the next release, whenever that happens.

**Comment by jischr** [comment]
Great thanks for this info. Closing the issue.
