### ISSUE TITLE
Publication of meta-schema

### ISSUE THREAD

**Issue by awwright** [json-schema-org/json-schema-spec#165]
#164 adds a paragraph formalizing the meta-schema URI that identifies the semantics defined in the document.

However, it doesn't provide the meta-schema itself. If we want to normatively publish the schema, it would have to be included in the document text. This is exactly what's done for some XML/XSD schemas.

I'm thinking it's a better idea if we keep the meta-schema as an informative document - it's just a special value that validators recognize, and they can use the one provided informatively by us, or they can even write their own meta-schema, or hard-code the rules in logic... whichever option follows the behavior described in the respective documents.

**Comment by handrews** [comment]
While I'm still learning the more subtle points of normative vs informative pieces, this sounds reasonable to me.  As long as we publish them clearly with the next draft and show that correlation so folks can keep track, I'll be happy.

**Comment by Relequestual** [comment]
I think this is a great idea. We should totally do this.
It would need to apply with draft-6 onwards. I don't feel we can post release the meta-schema after draft-6. As you say, put it in the document itself.

Even if it doesn't end up in the document, it can be bundled in a github tagged release (which if we want, can have a DOI number, if we want to make sure it's kept safe externally.)

**Comment by Relequestual** [comment]
@awwright I'm happy for it to not be part of the document if you feel it isn't required, however I would say it should at the very least be included as part of the release bundle available on github.

**Comment by Relequestual** [comment]
I suggest we keep the schema documents as informative documents.

Because we have a chicken and egg situation with referencing the tagged "release" on github, I suggest in stead we say something like, "The meta-schema/s can be found in the Github tagged release at (link to repo releases)". Thoughts @awwright ?

**Comment by Relequestual** [comment]
@awwright Your comments on this are needed. While this doesn't strictly prevent publication of the document, it does because we want to make the documents in a github release the ones that are uploaded to the IETF site. We need to resolve this issue before we seek publication.

**Comment by Relequestual** [comment]
For now...
After a brief chat with @handrews , we agreed we can, for now at least, just copy over the meta-schema from this repo to the website repo, as needed. Changes to the meta-schema will still be managed from the spec repo.

**Comment by handrews** [comment]
I think the publication of draft-06 with the meta-schemas and documented links as they are answers this, doesn't it?  Please re-open (and take out of the draft-06 milestone) if not.
