### ISSUE TITLE
Project Organisation

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#176]
This project needs organisation. It will happen.
This issue is designed to keep a list of initial organisational tasks that need to be completed in order to feel like the project is organised to a reasonable working standard.

If anyone has an organisation queries or questions, log a new issue and then link to the issue here with a VERY BRIEF description.

Checklist:

- [x] Sensible Github labels and guide
- [x] Contributors Guide
- [ ] Issue and PR template

**Comment by handrews** [comment]
@Relequestual I've encountered some questions on how to use these so far:

* I'm not sure how to use "Status: Available"  Does it mean "we've made a decision and now it's available for PR"?  Or does it mean "This was just filed and no one's looking at it yet"?
    * If it's available for PR can we change that to "Status: Available for PR" or "Status: Needs PR"?
    * If it means "just filed but unassigned" how is that different from using the assignment feature?
* What "Status" is used for issues that are clearly being worked on (even if no one particularly owns them) but have neither reached "Accepted" nor degenerated into a shrug or table flip?
* What qualifies as "In Progress"?
    * The situation above? (in discussion but not resolved, so it would move from "In Progress" to "Accepted" when the discussion settles?)
    * Someone is working on a PR (so it moves from "Accepted" to "In Progress" when someone starts the PR work?, and then to "Needs Review" when the PR is submitted?

**Comment by handrews** [comment]
@Relequestual I notice that the badges on the README show far more issues/PRs than are open.  They seem to keep counting unmerged PRs and closed issues.  Can we fix that?

If not, do we get enough value out of these to keep using them even though they make the work look weird by saying that 28 things need review?  (instead of 2)

**Comment by handrews** [comment]
Also, I can't find documentation on how they are supposed to work- I thought they were a waffle thing but the only badge they seem to talk about is the one for the waffle workflow chart.

**Comment by handrews** [comment]
We have a contributor's guide, and while it could probably use work we don't need to keep this open to track it.

I don't recall anyone ever suggesting an issue or PR template and I don't have any specific ideas on what I'd want from one, myself.  GitHub now links to the Contributor's guide when filing new ones so I think we've more or less addressed the ability to get some instructions in front of people.

I'm going to close this and open a new issue for the badge miscounts.  @Relequestual please re-open if you had something else in mind for what to do with this issue.
