### ISSUE TITLE
Co-Authorship for the spec

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#177]
@awwright I'd like to see @handrews get co-authorship on the next draft document.

He has done a fair amount of work for this draft.

Also, if you should be incompacitated, or unable / unwilling to continue the spec, someone else will need to be able to publish the next draft, with clear succession. I believe you can't get that succession unless it's approved by a previous author, right?

It shows good mitigation and forward planning to do this. Commonly known as increasing the busfactor from 1.

I've been meaning to bring it up on irc, but keep forgetting!

**Comment by Relequestual** [comment]
Oh, and write access to the repo

**Comment by Relequestual** [comment]
Sounds like Co-Authorship has been agreed on. @awwright Feel free to mention this issue when you make the PR required.

**Comment by Relequestual** [comment]
Sounds like Co-Authorship has been agreed on. @awwright Feel free to mention this issue when you make the PR required.

**Comment by handrews** [comment]
Thanks, @awwright !
