### ISSUE TITLE
Support `unique` for integers/numbers or strings

### ISSUE THREAD

**Issue by brettz9** [json-schema-org/json-schema-spec#18]
'Nuff said.  Edit: Well, just to be clear, the intent is for keys.

**Comment by Ixrec** [comment]
I don't understand what you're proposing. Unique relative to what? Other items in an array? (we already have `uniqueItems`) Other properties in an object? (JSON already requires those to be unique) Could you show a simple example perhaps?

**Comment by brettz9** [comment]
@Isrec: I meant this for ensuring that a document property was not present in other instance documents, but on further reflection, I think this would be better covered within PR #17 (under the index `unique`), so I'll close this for now. Thanks for your replies!
