### ISSUE TITLE
http://json-schema.org/draft-05/schema# should return a JSON file

### ISSUE THREAD

**Issue by dwhieb** [json-schema-org/json-schema-spec#192]
Draft 5 contains the following information about the `$schema` keyword:

```
The "$schema" keyword is both used as a JSON Schema version identifier
and the location of a resource which is itself a JSON Schema, which describes
any schema written for this particular version. [...] The current schema MUST
be valid against the meta-schema identified by this URI.
```

However, there is no JSON file available at `http://json-schema.org/draft-05/schema#` which would serve as the resource to validate against. (Other URIs, such as `http://json-schema.org/schema#` or `http://json-schema.org/draft-04/schema#`, do return a JSON document as expected.)

Since Draft 5 is an official IETF draft that users may validate against, there should be a JSON document made available at `http://json-schema.org/draft-05/schema#` as well.

**Comment by handrews** [comment]
See json-schema-org/json-schema-org.github.io#57, which is just hanging out waiting for approval.

**Comment by awwright** [comment]
@dwhieb The intention with the latest release was to be backwards-compatible with the existing meta-schema. This was accomplished with a questionable amount of success in some areas, but JSON Schema Validation should, indeed, be entirely backwards compatible with the draft-04 meta-schema.

Unfortunately, the Validation and Hyper-schema documents never listed a URI to use for a meta-schema, and the latest I-D still doesn't, but this will be fixed when the next meta-schema is released. This is the top item on the priority list, so it's coming soon!

Also I'm obligated to point out, the Internet-Draft is only an individual submission at this point, it doesn't have the endorsement of the IETF until it's released as an RFC. If you need to refer to it in a specification or cite it in a paper, drop me an email so we can discuss options.

Does that address your conserns?

**Comment by dwhieb** [comment]
@awwright Yes, that makes perfect sense. Thanks for taking the time to clarify! And for all the awesome work on this. I'm excited to see JSON Schema on its way to becoming an official RFC again.
