### ISSUE TITLE
"$comment" keyword

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#197]
[EDIT: I changed it from `"comment"` to `"$comment"` as explained in a later... um... comment]

JSON lacks comments.  Comments in complex schemas are good.  The `"description"` keyword, as a general annotation feature that is noted as being usable in interface display is not suitable for schema author-to-schema author comments.

Let's reserve `"$comment"` as a keyword.

Implementations MUST NOT use `"$comment"` in any sort of end user data presentation.

Implementations MAY choose to use the value of `"$comment"` in debugging messages.  Similar, schema editing tools MAY make use of or encourage the use of the comment keyword.

Implementations MAY opt to not store the comment field and its value in memory as an optimization.

There is no restriction on the comment's value.  While a string is the most obvious sort of comment, schema authors may decide to format comments in any way they wish.  Implementations that use comments for debugging or other purposes SHOULD support strings.  Schema authors inventing more complex comment forms MUST NOT assume that peer implementations will be able to understand those forms.

`"$comment"` would also be legal within a `"$ref"` object, and an implementation would still be able to use it for debugging.  All other keywords would still be in the "MUST be ignored" category should they appear in a `"$ref"` object.

[EDIT: originally this suggested the validation spec but as noted below it really belongs in core if we have it at all]

As an obvious use case, the reviews around "jsonReference" and "notJsonReference" in the meta-schema would have been much easier if a comment field is allowed.

**Comment by erosb** [comment]
I'm not sure if it is a necessary feature. I can just hardly imagine any usecase where `"description"` is unsuitable for debugging and I need an other programmer-friendly `"comment"` too.

**Comment by handrews** [comment]
Explaining complex usage of allOf/anyOf/oneOf/not/dependencies is very useful for schema maintainers, but should not be used as a description of anything user-visible.

**Comment by erosb** [comment]
Ah-ha, now it is more understandable.

Well it an optional feature and not too complex to implement, so I don't mind it.

**Comment by handrews** [comment]
> Well it an optional feature and not too complex to implement, so I don't mind it.

Yeah, the idea here is really just to reserve the keyword so that it is not co-opted by extensions.

**Comment by handrews** [comment]
Should probably actually be `"$comment"` in the core spec, just as comments are part of the core syntax of programming languages rather than some sort of library or extension.  If a media type supports comments, that should be in the media type definition.

That will also make clear that it has nothing to do with validation or hypermedia.

**Comment by handrews** [comment]
Here is an example of how comment could be used, direct from all of the confusion that these changes for `"$ref"` in the meta-schema have caused in #168, #188, #194, and json-schema-org/json-schema-org.github.io#57:

```JSON
{
    "$schema": "http://json-schema.org/draft/schema#",
    "id": "http://json-schema.org/draft/schema#",
    "title": "Core schema meta-schema",
    "definitions": {
        "jsonReference": {
            "type": "object",
            "properties": {
                "$ref": {
                    "type": "string",
                    "format": "uriref"
                }
            },
            "required": [ "$ref" ],
            "$comment": "We do not set '\"additionalProperties\": false' because the spec says that other properties MUST be ignored.  It does not forbid their existence."
        },
        "notJsonReference": {
            "not": {
                "required": [ "$ref" ]
            },
            "$comment": "This gets used to ensure that it is never ambiguous whether an object is or is not a JSON Reference."
        },
       "schema": {...}
    },
    "$comment": "This oneOf ensures that everything is either considered a JSON Reference, or a schema, but never both.  This is necessary because $ref requires that all other keywords are ignored, but does not forbid their existence.",
    "oneOf": [
        {
            "$comment": "Including the notJsonReference definition here ensures that if $ref is present, it will validate as a JSON Reference (the other branch of the enclosing oneOf) or it will not validate at all.  This is what we want, as only schemas withouth $ref can be treated as regular schema objects.",
            "allOf": [
                { "$ref": "#/definitions/schema" },
                { "$ref": "#/definitions/notJsonReference" }
            ]
        },
        { "$ref": "#/definitions/jsonReference" }
    ],
    "default": {}
}
```

**Comment by epoberezkin** [comment]
@handrews At the moment only keywords that affect validation start with $. description and title don't have it. Comment also doesn't affect validation - why does it need $ in front of it?

**Comment by handrews** [comment]
> @handrews At the moment only keywords that affect validation start with $. description and title don't have it. Comment also doesn't affect validation - why does it need $ in front of it?

@epoberezkin that's not correct.  Only core keywords have $.  Validation does not.  This is not a meta-data keyword that is part of a vocabulary that is for consumers of schemas.  We already have that with `description`.  This is for notes by and for schema maintainers about technical issues with the schema itself.  You would not put that stuff about "oneOf" in a `description`, as `description` is supposed to be part of the data that an implementation uses (as help text, for instance).

So `$comment` is like `/* .. */` in C-derived languages, or '#' in Perl, Python, etc.  It's something that a debugger can use, but a production compiler just strips it out.

**Comment by handrews** [comment]
A comment feature is only useful if it is independent of all vocabularies, hence putting it in core, hence making it `$comment` with the $ prefix.

**Comment by epoberezkin** [comment]
@handrews I agree only core keywords have $. But all core keywords affect validation now. And you suggest introducing another core keyword that has no effect on validation. I'd rather comment be in the category where there are other keywords not affecting validation...

**Comment by epoberezkin** [comment]
> as we've discussed ad nauseum

lol

**Comment by epoberezkin** [comment]
Yes, $schema does not indeed, but it at least defines what is a valid schema... $id and $ref affect validation, changing them may either break schema or change validation result. comment does absolutely nothing. And yet you want it to be a core keyword.

**Comment by handrews** [comment]
>  comment does absolutely nothing. And yet you want it to be a core keyword.

Do you like having comments in programming languages?

**Comment by epoberezkin** [comment]
No. Never use them

**Comment by epoberezkin** [comment]
Well, almost never. Naming things and making them self-evident is much better, comments usually go out of sync with code and there is no way of checking it.

**Comment by handrews** [comment]
> No. Never use them

Then I'm pretty sure you're not the audience for this keyword.

**Comment by epoberezkin** [comment]
That's why I don't see why it should be part of the core. It's not just me, it's a very common approach to eliminate or at least minimise comments. It encourages making things more complex than they should be, so instead of simplifying people start writing comments (exactly the use case for metaschema in#194).
Why "comment" is not good enough? I may use it once or twice. Why make it so prominent?

**Comment by handrews** [comment]
Why is "$" or putting it in core prominent?  The only relevant question is "is this specific to a vocabulary, or is it universal".  Universal things go in core.  It makes no sense at all in validation or hyper-schema, it's not specific to either.

**Comment by awwright** [comment]
I anticipate that most vocabularies (if we get more than besides hyper-schema) will pull in JSON Schema Validation, so I don't really see a problem with making it a JSON Schema Validation keyword, myself.

**Comment by handrews** [comment]
@awwright I strongly dislike polluting validation with non-validation keywords, and making assumptions on behalf of unknown future users that this validation vocabulary will always be fundamental.  If it's going to be impossible to use JSON Schema without validation, why do we have a core spec at all?

**Comment by awwright** [comment]
That's a question that a lot of people including myself have asked...

I moved forward with the approach on the idea it's useful to separate the media type definition from the idea of a "vocabulary", even if it is one that's going to be subsumed into every single other vocabulary.

**Comment by handrews** [comment]
> I moved forward with the approach on the idea it's useful to separate the media type definition from the idea of a "vocabulary", even if it is one that's going to be subsumed into every single other vocabulary.

I'm in favor of that (the media type definition approach).  While I don't want to bend over backwards on account of hypothetical non-validation vocabularies, I do want to make sure we don't make it difficult to use application/schema+json for something else entirely.  Or for a completely different validation approach- it wouldn't be standard but people should be able to make and use non-standard vocabularies.

**Comment by handrews** [comment]
As far as `$comment`, if enough people like the idea and agree that it is analogous to a programming language comment syntax, then it should go in the media type so it can be used automatically with any vocabulary.

If more people just don't see the need for comments I'm not going to be too upset to drop the idea.  I just really don't want it to be a validation keyword.  I'd rather drop the idea than further clutter validation.

**Comment by epoberezkin** [comment]
Why don't we park it until draft 6 is out?

**Comment by handrews** [comment]
> Why don't we park it until draft 6 is out?

It's not a draft 6 proposal, so if you don't want to talk about it now just don't talk about it.  It will be here when we get to the next draft.

**Comment by awwright** [comment]
I haven't seen anyone clamoring for this ("description" is usually good enough), so it might be prudent to sit on it for a tiny bit longer.

> Should probably actually be "$comment" in the core spec, just as comments are part of the core syntax of programming languages rather than some sort of library or extension. 

Also, this is a very compelling argument

**Comment by handrews** [comment]
@awwright I'm totally in favor of letting this sit and collect more feedback.  No rush on this one.  I think it will become more clear one way or the other as we go, and I'm interested in seeing how often it gets used in projects I'm working on, and it will take a while to get through enough schemas to be clear on that.

**Comment by k42b3** [comment]
I think having a place where users or generators could place meta information is useful. But I would prefer the name `$annotation` instead  of `$comment`. I.e. it could help to build more complex schema cases where `$annotation` may contain additional processing instructions, UI informations or just simply a comment.

**Comment by seagreen** [comment]
@k42b3: I think you're suggesting a different keyword entirely. It might be a good idea, but it doesn't affect whether we want `$comment`.

@epoberezkin: I generally fight as hard as I can to keep things out of Core and Validation, but in this case I do see a good case for having `$comment` in Core. It's relevant every single use of JSON Schema (validation, UIs, etc). Not that I'm set on adding it, I just think there's a good argument for it to go in Core if we do add it.

@handrews: Comment screams `"type": "string"` to me. I actually can see a case for generalizing many other types (not saying we could do this, but would be cool to have object $refs as well as string URI $refs) , but that's because those types are meant to be machine processable. Comments aren't mean to be handled by machines, and restricting them to `string` would encourage this.

**Comment by handrews** [comment]
@k42b3 Annotations are addressed in #136, and UI in #67.

The point of this `"$comment"` proposal is specifically to serve the needs of schema maintainers documenting why they arranged the schema for future schema maintainers.  For instance, a construct like `{"allOf": [A, {"not": B}]}` may not be immediately clear _why_ the schema author arranged the schema like that as opposed to some other way.

This is why the proposal says that `"$comment"` is **not** targeted to end users of any sort.  The annotation and UI schema proposals are for that.

**Comment by handrews** [comment]
@seagreen I could support restricting `"$comment"` to strings.  My inclination is to allow anything but not require support for anything but strings.  But I don't have a clear use case for non-strings, I just take that position because implementations aren't _required_ to do _anything_ with comments at all.  In fact they can just ignore the when reading the schema and never look at them at all.

**Comment by seagreen** [comment]
@handrews: I think it's a small advantage in clarity, but a real one. Also if we realize we've made a mistake later it's easier to go from strings to anything than vice-versa=)

**Comment by fulldecent** [comment]
In the example above at https://github.com/json-schema-org/json-schema-spec/issues/197#issuecomment-269391226 the comment is a description that could be generated entirely automatically.

**Comment by fulldecent** [comment]
If there is truly a need for spec authors to leave themselves comments then perhaps they may be left out-of-band. For example the schema is in `myschema.json` and the notes are in `myschema-NOTES.md`.

Imagine reading `man rsync` (which is hard enough) and finding a note about why the author chose an indentation level of 3 plus a blockquote for a specific command-line argument.

If comments are allowed in the base specification then they WILL be assigned syntactical meaning. That is human nature. We should avoid this and allow the spec to do only what it is supposed to do.

---

Remember, most people will be using tools to create specs. Without comments and other pollution it will be possible to compare if two specs are equal simply by `bc spec1.json spec2.json`. If we allow comments then SOMEBODY will do this:

```
movieActors.json
title: ...
comment: "Only fill in this title if the movie was released in US theaters and leave it blank if it wasn't"
```

And then another spec will not have that restriction.

Therefore you have reduced the usability of specs because data conforming to this spec can no longer be used in applications expecting conformance to another spec that omits that comment.

**Comment by Relequestual** [comment]
I agree that a comment field is needed and dissagree with the assumptions the above comment has made.

Firstly, you're assuming I'm leaving comments for my own benefit. I may want to include them for people using my schemas, generated automatically or otherwise, to better understand the interfaces.

I have instances in my schema where I'm unable to express validation requirements because they are dependant on other objects or values. I can add information to our documentation, but I also want it to be easy to find when they are reviewing the schema.

In addition, @fulldecent you say that adding comments to the spec would hinder the comparative ability between schemas. I actually dissagree, and would say I would WANT someone to know if the comment for a field had changed.

As with my example, I can't express the validation requirements in my schema, and have to use words to explain it. IF those validation requirements change, I can't reflect them in the schema, but I may be able to reflect them with words, and want someone doing a comparsion to see that a change has occured.

I think there are at least two use cases here. Comments for the schema author, and comments for consumers of the schemas. Both are valid. Who are we to say how someone should use a field if it's purly for information, to be read by someone else, and not part of any validation processes or in any way effecting the structure of the document?

**Comment by fulldecent** [comment]
If you can't express validation requirements in the schema then the schema cannot be used to validate data.

**Comment by seagreen** [comment]
@fulldecent: Validation can be a multi-step process. Perhaps a UI is generated from JSON Schema and does some validation, but the final validation is done by language-specific code server-side. In that case it would be perfectly reasonable to have a comment in the schema saying, "We'd like to enforce X here, but currently that can only be done by the server".

But actually I do think we should keep considering the benefits of leaving comments OOB. JSON doesn't have them, and the more we layer things on top of JSON the sadder I get.

**Comment by handrews** [comment]
> they should only be an internal thing for people interested in the guts of a schema, not recommended for use by things like generating docs.

@seagreen I'm just going to quote the *actual proposal under consideration*

> Let's reserve "$comment" as a keyword.
>
> Implementations MUST NOT use "$comment" in any sort of end user data presentation.
>
> Implementations MAY choose to use the value of "$comment" in debugging messages. Similar, schema editing tools MAY make use of or encourage the use of the comment keyword.
>
> Implementations MAY opt to not store the comment field and its value in memory as an optimization.

Oh, hey look, I said "MUST NOT" be used in **any sort of end user data presentation** :-)

@fulldecent given that JSON Schema allows extension keywords which strictly conforming implementation are directed to simply ignore, this proposal actually improves interoperability.  There is nothing stopping anyone right now from doing exactly what you say- adding "$comment" and implementing something that depends on its contents.  That is 100% legal by the spec.

The point of this proposal is to reserve "$comment" and **explicitly forbid** implementations from taking any action other than using it in debugging messages.  That ensures that if I want to include comments, I can rely on other implementations properly ignoring them.  Because if they do not ignore the comments, they are _in violation of the spec_. 

-----

Additionally, JSON Schema is not intended to express every possible validation concept that anyone could imagine.  Some things are better done in code.  Some things are better done through, say, linked data shape expressions.

**Comment by handrews** [comment]
To recap, the proposal here for `"$comment"` is:

* Implementations MUST NOT parse or change behavior based on the value of `"$comment"`
* Implementations MUST NOT display comments to end users
* Implementations MAY display comments as part of debug, warning, or error output
* Implementations MAY simply drop comments as the schema is read into memory, or at any subsequent point

That last MAY also allows that any intermediary that wishes to compress a JSON Schema may strip out comments.  

People are not going to stop commenting schemas.  There are many ways that people get around the limitation in the wild, from using a different format and converting to JSON to defining their own extension keywords.  But extension keywords can collide.  The entire point of this proposal is to **ensure interoperability** by choosing a single keyword for this purpose and strictly prohibiting it from have any actual effect.  Then you can trust that placing a comment in your schema will not cause any conforming implementation to misbehave.

Otherwise, with an extension keyword, the spec explicitly states that you **cannot** rely on other implementations behaving the same.  That includes not being able to rely on other implementations ignoring the field- they SHOULD, but if they chose an extension of the same name it is within the extension boundaries to treat it the way they defined that keyword rather than how you did.

The third option is to add your custom comment keyword to a new meta-schema, but then implementations that do not recognize your meta schema will simply refuse to process your schema at all.

This proposal takes a behavior that **already exists** and **is not going to go away** and ensures that it cannot damage the interoperability of the ecosystem of JSON Schemas.

**Comment by seagreen** [comment]
@handrews: You convinced me, I fully support this now.

**Comment by handrews** [comment]
(as a note to myself- there is probably a bit to put in "Security Considerations" that schema authors should not put sensitive information in the comments as anyone who views the raw file can see them, and a malicious/erroneous implementation could display the strings to users in violation of the spec.)

**Comment by ruifortes** [comment]
Don't you think this should be a case for json preprocessing(/extension) like [json5](http://json5.org/)

**Comment by handrews** [comment]
@ruifortes only if it reaches RFC.  I don't want to staple JSON Schema to another under-development project.  For now, it needs to work within RFC 7159.

There is, of course, nothing stopping you from handing comments some other way, such as by writing in YAML, JavaScript, or some other thing and pre-processing it into JSON.

I have to admit, I'm baffled at the level of resistance to this.  No one is forced to use it, the only impact this has at all is to reserve `"$comment"` and ensure that no one implements conflicting functionality.  Implementations don't even have to do anything with it.  The specification already indicates that unknown keywords should be ignored.  They way I've phrased this proposal, simply treating `"$comment"` as unknown and ignored is a compliant implementation.

**Comment by seagreen** [comment]
@ruifortes: Changing JSON Schema to not actually be JSON would be a huge change.

@handrews: I think people are just touchy about this because people keep advocating a backward-compatibility breaking change to add comments to JSON itself, which has made them irrationally touchy about any kind of issue involving comments. I think that would describe my reaction pretty well. Obviously you won me over though!

**Comment by handrews** [comment]
@seagreen yeah that's actually pretty understandable.  If I thought one of those comments-in-JSON things was actually on the verge of broad adoption/RFC, I wouldn't be bothering with this :-P

**Comment by ruifortes** [comment]
Json5 is sweet though.
Just `require('json5/lib/require')` in node entry point or use `json5-loader` in webpack . :)

**Comment by Relequestual** [comment]
@ruifortes Sure, very nice. As @handrews has said...

> There is, of course, nothing stopping you from handing comments some other way, such as by writing in YAML, JavaScript, or some other thing and pre-processing it into JSON.

I can't see myself being convinced that JSON Schema should use json5 exclusivly. That would be JSON5 Schema, which this spec is not.

**Comment by Anthropic** [comment]
I saw this the other day on reddit somewhere:
`{ "//comment": "I am a comment :)" }`

**Comment by handrews** [comment]
@Anthropic interesting idea!  I do like the reference comments to JavaScript (among other languages).

I went for the dollar sign because it is a prefix we are already using for core keywords.

Since the only point of having a comment keyword is to outright forbid conforming implementations from doing anything else with it, I'm reluctant to block out an entire prefixed namespace.  What if someone has a JSON file where the keys are some sort of filesystem path?  Or for that matter, what if keys are protocol-relative URIs, which start with '//'?

I'm open to further argument, but I think for the specification, we really want to block out the minimal space possible to ensure interoperability.  That would mean a single keyword, and staying with a prefix that is already associated with core keywords.

Does that make sense?

If so, I'm going to submit a PR for this.  But I am open to more discussion first.

**Comment by handrews** [comment]
I have since seen a set of schemas where, depending on who wrote a given file, any one of three different commenting extension keywords may be in use:  two custom keywords, plus `"$comment"` from this proposal.

To me, that's a pretty compelling reason to add this.  People are going to do it anyway, and the issue of multiple keywords doing the same thing will only get more likely if schemas are shared across completely separate organizations.

**Comment by Relequestual** [comment]
Are we waiting for 14 days since PR opened to merge? Any objections?

**Comment by handrews** [comment]
@Relequestual yes, so I'll merge it on Monday or whenever the 14 days is up.

**Comment by handrews** [comment]
PR merged.

**Comment by SaSiNO97** [comment]
Why can't we just have C-style /* */ comments?

**Comment by jdesrosiers** [comment]
@SaSiNO97 I have good news for you. You don't have the write JSON Schemas in JSON. JSON Schema works against the JSON data model, not the JSON text itself. That means you can write your schemas using any format you want as long as it's compatible with what is expressible by JSON. Some options that support comments are JSONC, JSON5, and YAML. You can even write schemas directly in the language you write code in. We see people write schemas in JavaScript or Python all the time. I hope that helps.

**Comment by xtergo** [comment]
I think the $comment isn't optimal. It helps for some scenarios but not for all.

I'd like that the Json standard support comments using something like /* */ even if it doesn't fit the Json standard. This would be more powerful. With this syntax other kinds of metadata could be added on any "node" which could be very useful for utils/tools that would like to extend Json usage.

The Json implementation would just need to strip this of this first and then it would conform to standard format. This leaves room for other tools to work on the Json schema with the comments.

**Comment by awwright** [comment]
> I think the $comment isn't optimal. It helps for some scenarios but not for all.

JSON is pretty fixed in stone at this point. I think JSON should add support trailing commas, and they won't even do that.

The only way we could support this would be with a new media type, like a domain-specific language for expressing a JSON Schema. I think that would be too much scope creep (it's not strictly necessary for our goal), but it could be defined as a separate specification.

There's a few separate projects in this area by others:

* https://orderly-json.org/
* https://github.com/quartzjer/JCOR
* ... or even using TypeScript might be feasible

**Comment by karenetheridge** [comment]
> I'd like that the Json standard support comments using something like /* */ even if it doesn't fit the Json standard

I think this is what you're looking for: http://www.relaxedjson.org/

JSON Schema follows the JSON document model, but you can use any format you like that produces the same data, e.g. yaml or even (for some data structures) csv. You could certainly create a new media type that used relaxed json as its data format -- comments will be stripped though and not visible to json schema.

**Comment by xtergo** [comment]
> JSON is pretty fixed in stone at this point. I think JSON should add support trailing commas, and they won't even do that.
> 
> The only way we could support this would be with a new media type, like a domain-specific language for expressing a JSON Schema. I think that would be too much scope creep (it's not strictly necessary for our goal), but it could be defined as a separate specification.
> 
> There's a few separate projects in this area by others:
> 
> * https://orderly-json.org/
> * https://github.com/quartzjer/JCOR
> * ... or even using TypeScript might be feasible

I understand there are other variants of Json that can solve this. But the problem is that if this doesn't get into the Json core standard many, including me, can't rely on that all tools/IDE:s can handle this. And then we will loose the potential to include cool new features, instead it will be solved with a Json variant that only works for some specific usage. 
It has to be part of the core standard in order to work with the 3pp eco-system.

The comments enable other 3pp:s to place metadata at any place in the Json structure. This could be GUI, model, matching information that otherwise would not be possible. A new Json tool would only need to strip away this info and then it would comply to current standard.

Over the year we have seen so many requests about this that it would be unfortunate to just state that Json is "fixed". 
People might think that comments is some minor thing, I think it's a very big thing and if we don't get this in place we limit the potential of Json more than one might think.

**Comment by gregsdennis** [comment]
> if this doesn't get into the Json core standard...

I think your in the wing place to request this.  We don't control the JSON standard here, just JSON Schema.  We _use_ JSON, and for maximum compatibility, it doesn't make sense for us to use any one variant.

I think your options are down to asking a particular implementation to support a variant that you're interested in using.
