### ISSUE TITLE
Consistent formatting of "format" values

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#207]
As @epoberezkin noted, we're a bit inconsistent about format:

* date-time
* hostname (arguably one word these days)
* uriref
* uritemplate
* jsonpointer

In earlier drafts, there were more formats that used hyphens.  

Notably, as these are strings, we could use spaces.

Furthermore, as this is JSON, we could use camelCase, as we do for keywords.

Setting aside the question of whether "hostname" counts as two words, we should pick one of:

* date-time, uri-ref, uri-template, json-pointer
* datetime, uriref, uritemplate, jsonpointer
* dateTime, uriRef, uriTemplate, jsonPointer

Or we could decide that date-time is grandfathered in and stick with single words going forward?  

I doubt many people have implemented "uriref" yet, so perhaps changing all of them to hyphens is best.  I do *NOT* want to have "uriref" but "uri-template".  That is the one thing I will throw a fit about (it's why I added "uritemplate" spelled the way it is in the first place- I'm not otherwise dogmatic about this).

@awwright @Relequestual @Julian opinions?  Let's pick one and get it in Draft 6 since it's a trivial edit once we decide.

**Comment by epoberezkin** [comment]
@handrews I prefer with hyphens, to be honest, also because at some point we may have "relativejsonpointer" and it breaks my head to read... And "hostname" indeed seems a single word to me :)

**Comment by Relequestual** [comment]
I much prefer hyphens for readability. But that's my personal preference.

**Comment by erosb** [comment]
+1 for using hypens

**Comment by handrews** [comment]
Addressed by #225
