### ISSUE TITLE
Normalize $ref / id behavior

### ISSUE THREAD

**Issue by JanTvrdik** [json-schema-org/json-schema-spec#21]
The draft 5 should (finally!) normalize the behavior of `$ref` and `id`, both in text and in form of language-agnostic test files.

Some of the edge-cases were discussed e.g. in

* https://github.com/json-schema/json-schema/issues/77 
* https://github.com/json-schema/json-schema/issues/83 
* https://github.com/json-schema/json-schema/wiki/$ref-traps
* https://github.com/json-schema/json-schema/wiki/The-id-keyword
* https://github.com/json-schema/json-schema/wiki/The-%22id%22-conundrum

**Comment by awwright** [comment]
A lot of the problems with "id" are a result of very poor definition. #50 should fix a lot of this, please review!

**Comment by awwright** [comment]
Because of recent commits and new related issues I'll close this out, if no existing issue exists feel free to comment or create a new issue. Thanks!
