### ISSUE TITLE
Validation: Keyword to express not: required for multiple properties

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#213]
## Problem

Although it's very simple, people find it very confusing to understand that the schema

```json
{ "not": { "required": ["foo"] } }
```

means that if data is an object it should not have property foo.

It is quite common requirement and every time I get asked how to implement it. Somebody suggested to implement a synonym "present" for "required" which makes it easier to read.

If you want to require that multiple properties are absent, than it becomes even more complex, you need to do either

```json
{
  "allOf": [
    { "not": { "required": ["foo"] } },
    { "not": { "required": ["bar"] } }
  ]
}
```

or

```json
{
  "not": {
    "anyOf": [
      { "required": ["foo"] },
      { "required": ["bar"] }
    ]
  }
}
```

Both are verbose and confusing.

## Suggestion

Keyword prohibited that is not just the negation of required, but that requires that each property in the list is not present in the object. So both big schemas above would be equivalent to

```json
{ "prohibited": ["foo", "bar"] }
```

**Comment by handrews** [comment]
I can support `"prohibited"`.  I also want to point out that we can now do:

`"propertyNames": {"not": ["foo", "bar"]}`

which is more verbose but still pretty readable.

**Comment by epoberezkin** [comment]
you meant not: enum probably...

**Comment by epoberezkin** [comment]
yeah, less valuable with propertyNames.

**Comment by epoberezkin** [comment]
Anyway, I added to [ajv-keywords](https://github.com/epoberezkin/ajv-keywords#prohibited)

**Comment by epoberezkin** [comment]
I am going to close it as the best way to express it now seems to be:

```json
{
  "properties": {
    "foo": false,
    "bar": false
  }
}
```
