### ISSUE TITLE
How can I specify a field as Summary or Detail

### ISSUE THREAD

**Issue by nnanda2016** [json-schema-org/json-schema-spec#218]
I want to understand if the spec allows to specify a particular field as **summary** or **detail**. As an example, schema for a resource (say) **book** has following properties:

```
bookId
title
pageCount
dateOfPublication
```

And, I want to denote `bookId` and `title` as `summary` and treat all the fields as `detail`. How can I specify this?

**Comment by epoberezkin** [comment]
@nnanda2016 how is it related to validation?

**Comment by nnanda2016** [comment]
@epoberezkin I know it is not related to validation. I mistakenly posted this question in schema validation google groups and there I was suggested to post this question in `json-schema-spec` channel; which I believe I did.  Should I post this question somewhere else? Kindly let me know and I will do so.

**Comment by epoberezkin** [comment]
I am just trying to understand why it is needed. How is it going to be used? Where this classification is defined?

**Comment by erosb** [comment]
Same here. I can understand the purpose (more or less), but I don't see how does it fit into anything we have under JSON Schema. It shouldn't be the part of the core spec, and definitely not validation, and also not for hyper-schema or any upcoming UI-related spec. So.. no clue.

**Comment by nnanda2016** [comment]
Let me explain a use case. Let's say I have to define a REST end point for a resource called `User` and it has following properties
```
userId
firstName
lastName
middleInitial
dateOfBirth
sex
... (may be some more)
```

And, for a basic home page UI, let's say I need only `firstName` and `lastName`. So, I can request the `/users/{id}` with a media type like `application/vnd.myorg.user-Summary+json`. This will fetch me all the summary fields of `User` resource. 

It may not be a very general purpose, but we are using this in our current REST endpoints. Why I thought it fits core schema, because core schema defines the properties of a resource like, property name, data type etc.

**Comment by handrews** [comment]
@nnanda2016 are you trying to be able to fetch two different representations of the resource?  One that is summary only and one that is everything?  I would do this by using two different schemas, so you can request something like:

`application/json; profile="http://myorg.com/schemas/user-summary.json"`

vs

`application/json; profile="http://myorg.com/schemas/user-detail.json"`

(you can, of course, use your vendor media type with the profile, I've just never seen the point in them when you can use the profile parameter to express things at a fine-grain level- more things know how to deal with `application/json` than with a vendor media type even with `+json`, but that's just my personal view)

**Comment by handrews** [comment]
@nnanda2016 from some other discussions (see #222 for details) it may not be correct to use 'profile' with 'application/json', so it may actually be much better that you are defining your own vendor-specific media type.  Using `profile` as a media type parameter can only be done if the media type allows it, so you can define your media-type to allow it.

Do you have enough of an answer for your question at this point?  If not, please let us know what else you need.  Otherwise we will close this two weeks after the date of your last comment.

**Comment by nnanda2016** [comment]
@handrews I personally do not prefer `profile` in media type for two reasons:

- Our system is already built with our vendor specific media type and we accept `Summary` and `Detail` as part of this custom media type. Changing to that is a huge effort from us.
- We are improving our system where end consuming apps will define the JSON schema as per their requirements and our system will automatically provision and expose REST endpoints for those resources.  So, we can't force our consumers to define multiple schema; it's confusing!

At this point in time, I do not have any clue how to proceed. We will perhaps use our own customized schema definition instead of standard JSON Schema spec. 

Thank you all for the inputs. I am closing this ticket.

**Comment by handrews** [comment]
@nnanda2016 Just as a reminder, if you want to use JSON Schema for validation or hyper-schema you can always add custom keywords for things like summary/detail rather than replacing JSON Schema entirely.  Good luck with your project!
