### ISSUE TITLE
Disallow fragments in id URIs

### ISSUE THREAD

**Issue by JanTvrdik** [json-schema-org/json-schema-spec#22]
It seems that the some of [problems](https://github.com/json-schema-org/json-schema-spec/issues/21) with `$refs` and `id` could be alleviated by disallowing fragments in `id` URIs.

Currently such fragments

* collide with JSON pointers and
* make strange distinctions between outer-most schema (which currently can not have fragment in `id`) and inner schemas (which can have fragments in `id`)

**Comment by awwright** [comment]
@JanTvrdik Take a look at the changes introduced in #50 and see if any of the problems you describe could still exist, please? I'd like to see examples of problems if you think they're still present.

Thanks!

**Comment by awwright** [comment]
As best as I can tell, I think a pretty good solution is worked out in the repository now.

If after the draft is published, it doesn't seem to address the issue, feel free to raise any concerns you have. Thanks!
