### ISSUE TITLE
Inconsistencies between "core" and "validation" documents

### ISSUE THREAD

**Issue by sverreeh** [json-schema-org/json-schema-spec#227]
The definition of "type" in [http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.21](url) states: 

> String values MUST be one of the seven primitive types defined by the core specification

[http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2](url) defines only 6 types: (null, boolean, object, array, number and string). I guess the seventh type would be "integer", but "integer" does not seem to be defined as a keyword in the "core" document.

**Comment by handrews** [comment]
Thanks for the error report!  
This was fixed in commit d500f70 , we just haven't published a new draft since then.
