### ISSUE TITLE
Construct contributors list for easy notifications

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#235]
I noticed the other day that someone had been added to the contributors list (with write access, which I've now changed...).

Sadly you can't mention the collaborators, but you can mention a team.
I suggest we could make a new team with read only access which includes a list of people who want to be notified when feedback is required. It's expected that these people will often be very busy and probably not keeping an eye on all the projects developments. People could request to be added to the list if they have:

- Made a contribution to the project
- Developed a library
- Have clear vast experience
- Are a notable expert in the field

**Comment by Relequestual** [comment]
Added a few people as read only collaborators, however I've found you can't mention the collaborators as a group... =/

It would HAVE to be a public team. So if there are no objections, I'll create a team with read only permissions, and add people to that. That way those people can be called upon when needed with ease =]

**Comment by awwright** [comment]
I like this idea.

We should maybe document a process for people who want to be on the list
too.

**Comment by handrews** [comment]
I've invited a few more people as read-only collaborators:

@jdesrosiers (for major contributions to hyper-schema discussions)
@geemus (for his use of JSON Schema/Hyper-Schema at Heroku)
@Anthropic (angular-schema-form/json-schema-form)

**Comment by handrews** [comment]
And @epoberezkin because srsly, I didn't realize he wan't already there :-)

**Comment by Relequestual** [comment]
Great, thanks.
After draft-6 is out, I'll begin the post draft-6 cleanup, which includes this issue =]

**Comment by handrews** [comment]
@Relequestual Is this still something we want to do, or do we have enough communication channels with collaborators, IRC, slack, etc?

**Comment by Relequestual** [comment]
I think slak is enough for this issue to be closed.
We could make better use of channles, like having an announce channel, and a private channel, and allow anyone to join the general one. Thoughts?
