### ISSUE TITLE
Profiles are not Schemas

### ISSUE THREAD

**Issue by dret** [json-schema-org/json-schema-spec#26]
the current draft talks about a profile media type parameter, and recommends using it to link to a JSON schema. the existing https://tools.ietf.org/html/rfc6906 about profiles (that also talks about "profile" media type parameters) is not referenced, but at least there is some overlap. please consider that the idea of profiles (as specified in RFC 6906) is not to interlink instances and schemas. instead, the idea is that a profile identifies a set of rules applied to an instance which can be processed with or without knowing the profile-specific processing rules.

**Comment by Acubed** [comment]
I agree the spec should be a bit more clear about this.

The "profile" media type parameter doesn't form a Web link as such, if we want to also provide the path to download the schema, that needs to be done in a Link header.

This also has the effect of allowing schemas to be defined at alternate locations, or allowing you to use schemas that aren't network-addressable (like a URN).

Ideally, it seems, you should use both.

**Comment by Acubed** [comment]
Also, JSON Schema suggests using the "describedby" link relation, but this appears to be overloading POWDER, a vaguely similar specification, as "describedby" is specific to application/powder+xml.

**Comment by dret** [comment]
On 2016-05-03 12:56, Austin Wright wrote:
> Also, JSON Schema suggests using the "describedby" link relation, but
> this appears to be overloading POWDER, a vaguely similar specification,
> as "describedby" is specific to application/powder+xml.

POWDER does not constrain the link target to be POWDER resources (and 
note that RFC 5988 guidelines specifically say that registered link 
relations must not constrain the media type of the context or the target 
resources):

https://www.w3.org/TR/powder-dr/#assoc-linking

"This is a generic relationship type that does not of itself imply that 
the link points to a POWDER document."

but apart from that, i find the definition to be much more about 
providing metadata about a resource (such as "who's the author" and so 
on), but the language is so extremely vague that you can pretty much 
read into it whatever you like.

**Comment by azaroth42** [comment]
Also, the `describedby` link relation was updated by LDP to be explicitly less specific:
    https://www.w3.org/TR/ldp/#link-relation-describedby

**Comment by handrews** [comment]
@azaroth42 , @dret :  I think it's fine for `describedBy` to be vague about what it requires on the other end of the link.  It's not just the `describedBy` relation that tells clients that the target is a schema.  It is the media type `application/schema+json` that is set for the target representation that tells you that you now have a JSON Schema document that you can and should use to validate the data that supplied the `describedBy` link.

**Comment by awwright** [comment]
@dret Does #45 adequately address this issue?

**Comment by dret** [comment]
that's very well written, thanks for doing that.

**Comment by handrews** [comment]
@dret : Good enough to close this?  :-)
