### ISSUE TITLE
What does it take to get the JSON-Schema specification adopted by an IETF working group?

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#27]
This is more a question that needs answering as opposed to an issue. If anyone can shed some light on this, please do comment.

**Comment by handrews** [comment]
I'm pretty sure there are IETF documents (BCPs/Best Common Practices) and the like outlining this.  I do not think we need an issue here to track it, unless you had something specific in mind @Relequestual?

If we want to track getting things ready for working group submission, that seems like something we could use GitHub's "Projects" feature for (or a tag if that is too restrictive)

**Comment by Relequestual** [comment]
Agreed. I had a look at the BCP and working group documents and couldn't find any inforamtion on how one goes from individual submission to working group rfc.

**Comment by handrews** [comment]
> I'm assuming that's our aim here anyway

Yeah, there is documentation for that somewhere, can't remember offhand but I have seen some guidance and I'm sure I can find it again when we need it.

**Comment by Relequestual** [comment]
If anyone happens to pass by here and does know where such a guide is located, please provide a link. thanks.

**Comment by handrews** [comment]
It's RFC 7221, particularly https://tools.ietf.org/html/rfc7221#section-2
