### ISSUE TITLE
Type integer confusing?

### ISSUE THREAD

**Issue by we-zhang** [json-schema-org/json-schema-spec#272]
In the spec, it only list below types:
null,
boolean,
string,
number,
object,
array.

I know number includes integer, but can I define a "type":"integer" explicitly. I mean will this violate the spec?

**Comment by yellottyellott** [comment]
Can we fix this typo? I'm just getting started with json schema and was very confused why everything but the latest official docs reference an `integer` type. 

https://json-schema.org/latest/json-schema-core.html#rfc.section.4.2.1

**Comment by handrews** [comment]
@yellottyellott what that means is that it's fine that the `type` keyword includes "integer" as a value, but in terms of the JSON data model as interpreted by JSON Schema, _based on the [JSON RFC](https://tools.ietf.org/html/rfc8259#section-3)_, "integer" is not a distinct type.

You will see in the [definition of the `type` keyword](https://json-schema.org/draft-07/json-schema-validation.html#rfc.section.6.1.1) that it notes how "integer" is a special case as well.  So the two specification documents are in agreement.

**Comment by yellottyellott** [comment]
Ah, thanks @handrews. The latter link is what I was looking for.
