### ISSUE TITLE
Add logical "if" schema

### ISSUE THREAD

**Issue by TaylanUB** [json-schema-org/json-schema-spec#28]
It would be great if there were a logical `if` schema in the vein of `and`/`or`/`not`. It could look like

```
{ "if": [ conditional, consequent ] }
```

whose semantics would be exactly equivalent to:

```
{ "or": [ { "not": conditional },
          { "and": [ conditional, consequent ] } ] }
```

Thank you!

**Comment by davek2** [comment]
How would this be used?   Schemas are declarative languages, not procedural - there are no variables and no flow of control.  "and" and "or" do not exist in JSON Schema; "not" exists, but not as a logical operator, it is more like unary negation:

       { "not": { "type": "string" } }

validates all values except strings.  An example illustrating how this would be used to accomplish a schema-related task would be helpful.

**Comment by TaylanUB** [comment]
David Kay <notifications@github.com> writes:

> How would this be used? Schemas are declarative languages, not
> procedural - there are no variables and no flow of control. "and" and
> "or" do not exist in JSON Schema; "not" exists, but not as a logical
> operator, it is more like unary negation:
>
>    { "not": { "type": "string" } }
>
> validates all values except strings. An example illustrating how this
> would be used to accomplish a schema-related task would be helpful.

Oops, with 'and' and 'or' I meant 'allOf' and 'anyOf'.

Propositional logic is declarative, and has 'if'.  The proposition

    If cats are blue, then the moon is made of cheese.

evaluates to true, because the proposition "cats are blue" is false.
(See also "vacuous truth".)  The proposition

    If cats have fur, then dogs have four legs.

evaluates to true, because both sub-propositions are true.

Anyhow, here's a useful schema example:

    { "type": "object",
      "required": [ "productType" ],
      "properties":
        { "productType": { "enum": [ "book", "vhs" ] },
          "numberOfPages": { "type": "integer" },
          "duration": { "type": "number" } },
      "allOf":
        [ { "if": [ { "properties": { "productType": { "enum": [ "book" ] } } },
                    { "required": [ "numberOfPages" ] } ] },
          { "if": [ { "properties": { "productType": { "enum": [ "vhs" ] } } },
                    { "required": [ "duration" ] } ] } ] }

This validates

    { "productType": "book",
      "numberOfPages": 242 }

and

    { "productType": "vhs",
      "duration": 9330 }

but not

    { "productType": "book",
      "duration": 9430 }

or

    { "productType": "vhs",
      "numberOfPages": 230 }

which is pretty neat!


To repeat, the semantics of

    { "if": [ conditional, consequent ] }

should be equivalent to

    { "anyOf": [ { "not": conditional },
                 { "allOf": [ conditional, consequent ] } ] }

although if my logic serves me right, this can actually be simplified to

    { "anyOf": [ { "not": conditional },
                 consequent ] }

which is only slightly more verbose than the proposed "if", but the "if"
makes the intent a lot clearer.

Taylan

**Comment by epoberezkin** [comment]
See [switch](https://github.com/json-schema/json-schema/wiki/switch-(v5-proposal)) proposal, implemented in [ajv](https://github.com/epoberezkin/ajv) (with v5 option).

**Comment by TaylanUB** [comment]
Ah, neat! I had searched through the issues a bit but didn't see that. Closing this.

**Comment by awwright** [comment]
@epoberezkin Aside, note that the next release won't be including any new functionality or change in semantics; and probably won't even be named v5 depending on how the IETF accepts the Internet-draft.
