### ISSUE TITLE
Automatic ID generation

### ISSUE THREAD

**Issue by fbedussi** [json-schema-org/json-schema-spec#283]
Is it possible to automatically generate a numeric ID for an object?

For instance in this shema:
````
"questions": {
                "description": "Questions contents",
                "type": "object",
                "properties": {
                    "id": {
                        "description": "The unique identifier for a question",
                        "type": "integer"
                    },
                    "text": {
                        "description": "Question's text",
                        "type": "string"
                    },
                    "images": {
                        "description": "Question's images",
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "minItems": 1,
                        "uniqueItems": true
                    },
                    "options": {
                        "description": "Question's possible answers",
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "minItems": 2,
                        "uniqueItems": true
                    }
                },
                "required": [
                    "id",
                    "text",
                    "options"
                ]
            }
````
the propery ID must be unique, so it would be nice if it could be generated automatically instead of left the burden of checking duplicates to the user. 

Thanks

**Comment by handrews** [comment]
@fbedussi If I understand your question correctly, it is outside of the scope of JSON Schema.

You are asking if, when new instance documents matching this schema are created, that JSON Schema can generate a unique value for the instances' "id" field?

Typically, the server creating the resource handles this, usually with a database auto-increment value or a a cryptographic hash.  A validation implementation cannot know the scope in which the ID needs to be unique, or what ids are already in use, without querying the server anyway.  Even if the validator is on the server, it cannot know if it is running on the only server, or if there are multiple load-balanced servers with a separate component managing the unique ids as a larger namespace.

**Comment by fbedussi** [comment]
@handrews yes, that was my intent, thank you for your explanation.

**Comment by epoberezkin** [comment]
https://github.com/epoberezkin/ajv-keywords#dynamicdefaults

**Comment by fbedussi** [comment]
Thanks, I'll definitely try it, it sounds exactly what I'm looking for.
