### ISSUE TITLE
Register MIME-type with IANA

### ISSUE THREAD

**Issue by adamvoss** [json-schema-org/json-schema-spec#286]
Maybe this is planned or premature, but figure I would report it since it came up in researching json-schema-org/json-schema-org.github.io#31 / json-schema-org/json-schema-org.github.io#32.

I notice that "application/schema+json" (which is specified in the standard) does not appear in [mime-db](https://github.com/jshttp/mime-db) as a known schema.  That project indicates the recommended way to add it there is to [register it with IANA](https://tools.ietf.org/html/rfc6838#section-5), and since JSON Schema already has an Internet Draft it does not seem like it may not be too difficult to register it..

I checked the [IANA registry](https://www.iana.org/assignments/media-types/media-types.xhtml) just to be sure, and it was not there.

**Comment by handrews** [comment]
@vossad01 I don't think we're quite at that point yet.  I don't know if we need to be in RFC for that, but I suspect we should at least have reached working group status before submitting it.

Also, there are a number of media type details that are still being worked out, e.g. #222.

**Comment by handrews** [comment]
Per [RFC §4.10](https://tools.ietf.org/html/rfc6838#section-4.10), a standards-tree media type MUST be published in an an RFC.  This will be a natural part of getting JSON Schema to RFC and we don't need a separate issue to track it.
