### ISSUE TITLE
What is the status of JSON Schema maintainers?

### ISSUE THREAD

**Issue by Anthropic** [json-schema-org/json-schema-spec#30]
@Acubed
I am the current maintainer of **JSON Schema Form** (including the popular **Angular Schema Form**)
https://github.com/json-schema-form

That project has had a **view** definition for years, but recently I have begun working with other form building tool provider to create a **json-ui-schema** to define a universal **view** definition to marry up with a json-schema **model** definition to generate forms with more precision than you could, or perhaps should, with a json-schema definition alone. We have a pure JavaScript core and Angular implementation and potentially React, Node and other ports in the works soon.

I am concerned that some v5 proposals appear to be suggesting more view capability in json-schema (like choices) and I am interested in having discussion with the maintainers as I have not been able to get any email response from the json-schema github org members, @Acubed I would love to talk to you and any other json-schema maintainers about collaboration options. You can reach me at, iamanthropic, at g mail .

**Comment by Acubed** [comment]
@Anthropic Well you've found one of the official places to comment!

If you have a concern with a particular proposal, comment on that proposal and present all your use cases.

A good place for discussion in general is the mailing list, and I'm usually on the IRC channel (check the website for details).

This project, moreso than anything else right now, is mostly a place for implementors to ensure compatibility with each other's implementations, so make yourself at home.

If this answers all your questions, you can close out this issue for me. Feel free to ping me on the IRC channel, we're on #json-schema on Freenode, I'd like to chat!

**Comment by Anthropic** [comment]
Thanks @awwright, we will try to watch further, I will try to ping you through IRC, what timezone are you in?
