### ISSUE TITLE
any plan to add some schema reference to "target JSON file"?

### ISSUE THREAD

**Issue by GongT** [json-schema-org/json-schema-spec#301]
Hello! I'm new here,    
I want to write a small developer tool, use a json config file.

Many many IDEs support JSON Schema, but all of them need a manual config. (maybe I'm worng ?)

Any one trying to make these automatically? maybe something like xml schema ... :thinking:

**Comment by Relequestual** [comment]
Hi @GongT, I'm not quite sure what you mean. Could you give a practical example of what you're asking please? =]

**Comment by GongT** [comment]
sorry for my poor english...

I'm currently working in a company, there are few peoples in my team, but they are in different timezone.    
I'm writing a tool for everyone. this tool using a JSON config file.     
Because of limit of time, I can't write a very detailed document. and this tool is very "young", it update near everyday, sometimes the config file will have some small change.     
I knew "JSON Schema" days ago, its so great, I decide to write a schema file.
But I have a big problem: how to distribute this schema file ?

so I "imagine" I can write something like `{ "$schema": "https://github.com/GongT/myproject/xxxxx.json" }` to somewhere, let every IDE & editor know where to get the schema file, instead of configure everything by hand.

Is that possible ?

**Comment by awwright** [comment]
@GongT The JSON Schema specification doesn't specify any single way of distributing the schema.

How a schema is provided to a JSON Schema validator is up to that validator, and can vary between implementations.

Usually, a schema will be checked into your revision control system, or it might be downloaded over HTTP by following a `rel="describedBy"` link.

This issue tracker is for the specification, you might get better answers on the [mailing list](https://groups.google.com/forum/#!forum/json-schema) or [StackOverflow.com](http://stackoverflow.com/questions/tagged/jsonschema) (see the [JSON Schema website](http://json-schema.org/) for more information).
