### ISSUE TITLE
v4 JSON schema requires non-empty string arrays

### ISSUE THREAD

**Issue by StephenCleary** [json-schema-org/json-schema-spec#316]
The current spec allows [empty `required`](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.17) and [empty arrays in `dependencies`](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.21).

However, the `stringArray` type defined in the [Draft 04 schema](http://json-schema.org/draft-04/schema)  does not:

    "stringArray": {
        "type": "array",
        "items": { "type": "string" },
        "minItems": 1,
        "uniqueItems": true
    }

Since these two places are the only locations in the schema that use `stringArray`, this can be fixed by removing the `minItems` requirement:

    "stringArray": {
        "type": "array",
        "items": { "type": "string" },
        "uniqueItems": true
    }

**Comment by StephenCleary** [comment]
To be clear, we are generating JSON schemas dynamically (based on user input) in our product, and using the official Draft 04 schema to validate these schemas. So this is a "real" issue for us.

We've updated our local copies of the Draft 04 schemas to remove `minItems`, but it would be better if the official copies were fixed so we don't fork.

**Comment by chaffin** [comment]
Also, given that `stringArray` MUST be unique, would also removing `uniqueItems` make any difference? If so, this would this create a validation dependency on a validation keyword, rather than the data the schema is to validate.

**Comment by handrews** [comment]
@StephenCleary the draft-04 meta-schema matches the "draft-04" spec (really draft-fge-json-schema-validation-00 in this case).  Draft-04 does not allow for empty arrays for these keywords, so the meta-schema is correct as-is.

If you want to use empty arrays, you can move to draft-06 which supports empty arrays in its meta-schema.

**Comment by StephenCleary** [comment]
I was under the impression that draft-06 was not yet finalized/released yet. It's good to use?

**Comment by handrews** [comment]
Yes, it's been out for a few weeks and is good to use.  I'm trying to rework the "software" section of the web site to highlight support for draft-06.  So far I think only ajv (and therefore also JSON Schema Lint) support it, but I know several other validators are working on it now that it's out.

The validation changes aren't huge, so hopefully I'll be able to highlight more draft-06 compliant implementations soon (there is a test suite for draft-06 available to help implementors).

Hyper-schema changes are very substantial, but hyper-schema was never as broadly implemented (which is one reason we felt free to change it more drastically).

**Comment by handrews** [comment]
Thanks for filing #317, can this issue be closed with that one tracking the needed fix?

**Comment by StephenCleary** [comment]
Absolutely, thanks!

Part of my confusion doubtless stemmed from us *starting* to use JSON schemas about 6 weeks ago, when draft-04 was current.

**Comment by handrews** [comment]
Nice timing- just in time for the first significant, behavior-changing update to the spec in more than four years!

Here are some guides to the changes:
https://github.com/json-schema-org/json-schema-spec/wiki/FAQ:-draft-wright-json-schema%5B-validation%5D-01
https://github.com/json-schema-org/json-schema-spec/wiki/FAQ:-draft-wright-json-schema-hyperschema-01
