### ISSUE TITLE
Canonical URL points to draft-04 schema

### ISSUE THREAD

**Issue by StephenCleary** [json-schema-org/json-schema-spec#317]
The "latest meta-schema" link for Core/Validation Meta-Schema on [the documentation page](http://json-schema.org/documentation.html) point to `http://json-schema.org/schema`, which downloads `http://json-schema.org/draft-04/schema` rather than `http://json-schema.org/draft-06/schema`.

**Comment by handrews** [comment]
Thanks!  No wonder that was confusing.  Right when we published the spec basically everyone but me (including the person who did most of the web site work) had (good) major real life events happening and I'm scrambling a bit to keep up with the surge of interest.  I fixed the "latest" specs but not the latest meta-schemas.

**Comment by awwright** [comment]
Should this be filed on the website instead?

**Comment by handrews** [comment]
@awwright I already submitted a PR, I didn't see the point of filing (or asking anyone else to file) another issue when we can have it merged as soon as someone stamps it.  It's a purely mechanical change anyway.

**Comment by handrews** [comment]
PR is merged, should be fixed now.

**Comment by handrews** [comment]
Please file any further website issues at json-schema-org/json-schema-org.github.io rather than here
