### ISSUE TITLE
Add `contains` keyword

### ISSUE THREAD

**Issue by BigBlueHat** [json-schema-org/json-schema-spec#32]
Just surfacing this proposal from https://github.com/json-schema/json-schema/wiki/contains-%28v5-proposal%29

It would greatly simplify JSON Schemas such as this one:
https://github.com/w3c/web-annotation-tests/blob/master/common/contextValue.json#L15-L26

It has been implemented in [ajv](https://github.com/epoberezkin/ajv).

/cc @awwright @epoberezkin

**Comment by handrews** [comment]
@BigBlueHat , @awwright : I just realized I re-filed this as issue #63 as I did not think anyone had migrated it over.  Since I copied the full text of the proposal in that issue, can I request that we close this one and keep #63 ?  Or I could copy stuff over here.

**Comment by handrews** [comment]
Done!  Please close unless we missed something (I don't have the permissions to close this).

**Comment by Relequestual** [comment]
Closed as merged.
