### ISSUE TITLE
Ban unknown properties mode

### ISSUE THREAD

**Issue by LukeDefeo** [json-schema-org/json-schema-spec#326]
Hi guys in the other repo you discussed a strict validation mode https://github.com/json-schema/json-schema/wiki/ban-unknown-properties-mode-%28v5-proposal%29

This would be very useful to us, do you have plans to implement this?

**Comment by handrews** [comment]
@LukeDefeo my view on this is that it's outside of the concern of the specification because it is not controlled by anything *in the schema*.  It's simply an optional alternative mode of processing schemas.  Any implementation is free to provide any optional processing that it wants.

For a variety of proposals within the schema intended to produce similar effects, see https://github.com/json-schema-org/json-schema-spec/issues?q=is%3Aissue+is%3Aopen+label%3A%22re-use+%2F+addlProps%22

**Comment by handrews** [comment]
The `"$combine"` proposal in particular implements this, which btw is easy in simple cases but extremely complex to implement generally.  Although if you just drop all `"not"` clauses it gets substantially easier.  I'm not sure it gets less confusing, though.

**Comment by handrews** [comment]
It's been several months with no further comment or new argument in favor of incorporating this into the specification, so I'm going to close this.

Again, I see no reason why implementations can't add this as an extra option just as many implementations offer an option to write defaults into the instance during validation.  Neither of those behaviors technically complies with the specification, but both are useful as opt-in extension features.  Closing this issue does not dismiss that, it just acknowledges that it's outside the scope of the actual specification.

**Comment by jdesrosiers** [comment]
@handrews I agree that this doesn't belong in the spec, but what do you think about reopening it for the Vote-a-rama?  It lets people express the opinion that the spec shouldn't solve the `additionalProperties` "problem".  It's best if `additionalProperties` doesn't exist and let implementations handle it as they see fit.

**Comment by handrews** [comment]
@jdesrosiers perhaps it might be better to open a new issue specifically for voting for doing nothing?  It can reference this as an example of outside-of-the-spec behavior, but then hopefully people wouldn't get too hung up on this approach.  That's what I was trying to avoid when I closed this.
