### ISSUE TITLE
Support for all ISO8601/RFC3339 formats for date & time

### ISSUE THREAD

**Issue by drwharris** [json-schema-org/json-schema-spec#335]
Currently JSON Schema supports "format" : "date-time", however [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6) details a number of other possibilities. 

It would be advantageous if we could specify in addition to "date-time":

"format" : "full-date"
"format" : "full-time"

**Comment by adamvoss** [comment]
For clarification:

The title suggests supporting _all_ RFC3339 formats while the description asks about **full-date** and **full-time**.  Are you looking for all to be added or just the two?

I have used at least one of these additional formats in a JSON Schema, but then enforced it via regular expression.

**Comment by drwharris** [comment]
Patterns are just a shortcut to a validation...a convenience. So yes, we could just use regex instead but patterns are convenient :) and also make it easier for people who font get regex.

As to you clarification, strive for the title but start with the description. The title would give you the ability to say your patterns comply with ISO 8601, etc but full-date and time would likely cover 80-90% of use cases.

**Comment by handrews** [comment]
I'm going to close this in favor of issue #199, which started out as just asking about date and time, but ended up bringing up the idea of using all of the formats as requested here.

There is more discussion in that issue, so let's continue things there.
