### ISSUE TITLE
[draft-6] Ambiguous description of `additionalProperties`

### ISSUE THREAD

**Issue by brendo** [json-schema-org/json-schema-spec#336]
Just hoping to clarify the expected behaviour of [`additionalProperties`](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.20) as I'm expecting it to work in a different way that what I've been able to test using the [jsonschemalint](https://jsonschemalint.com) tool. I'm hoping to discover if my understanding is incorrect, or if it's a bug upstream in validating the schema!

> This keyword determines how child instances validate for objects, and does not directly validate the immediate instance itself.

I take this to mean that `additionalProperties` can be defined at any level of the schema and it's schema will apply to all _child_ `object` schemas.

Therefore in [this example](https://jsonschemalint.com/#/version/draft-06/markup/json?gist=c1d211e7e15772a252c6d934054f6a11), I'd expect it to fail, as the `additionalProperties` declaration in `customAttributes` should apply to the schema under `items` and the value of `count` should be an integer, not a string.

> Omitting this keyword has the same behavior as an empty schema.

I re-read the spec and noticed this last line, which justified the behaviour experienced above. Because the scheme under `items` has no `additionalProperties` property, it essentially is a no-op, and no validation applies.

I [then wondered](https://jsonschemalint.com/#/version/draft-06/markup/json?gist=a05e8aeda06ed9d54cb2e51baaacb47e) if I set `additionalProperties: false` at this level if it would merge from the parent scope, but this wasn't the case.

---

So I'm left wondering about the wording of "child instances" and "does not directly validate the immediate instance itself". With the tool, `additionalProperties` seems to only be applicable for the adjacent context, when it contains the `properties` property.

**Comment by brendo** [comment]
Oh, I had a peek through the [test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft6/additionalProperties.json) but didn't see any tests related to the behaviour.

**Comment by epoberezkin** [comment]
> I take this to mean that additionalProperties can be defined at any level of the schema and it's schema will apply to all child object schemas.

No. Child instances are values of properties of the current data instance, this term has nothing to do with child object schemas. See http://json-schema.org/latest/json-schema-validation.html#rfc.section.4.2

The behaviour of additionalProperties is determined by which properties are present in "properties" keyword and are matching patterns in "patternProperties" keyword in the same schema. It follows from the definition of the schema here: http://json-schema.org/latest/json-schema-core.html#rfc.section.4.4. Maybe @handrews can add something.

**Comment by handrews** [comment]
Take a look at [the latest version of the specification](https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-6.20), as we really hope that is more clear.  The behavior is identical to the version you were reading- the only validation keywords that changed were the exclusiveMinimum/exclusiveMaximum ones.  The others have just gotten wording cleanups (and a few new keywords and formats were added).

**Comment by brendo** [comment]
The new version of the spec is clearer. I needed to read the rest of the document to understand the terminology with child instances in particular. Thanks for the clarification :)
