### ISSUE TITLE
Q: How do instance docs refer to their schema?

### ISSUE THREAD

**Issue by shhQuiet** [json-schema-org/json-schema-spec#338]
In XML, the root element of an instance document can define a namespace with a reference to a schema.  Is there a standard mechanism for JSON instance docs to refer to their schema?  We are considering adding a `schemaLocation` field to a `meta` section in our instance docs but would prefer to do this in a standard way.

**Comment by jdesrosiers** [comment]
Unfortunately, there isn't a standard way.  The XML media type has a built in way to include meta data, but JSON is a much simpler structure and doesn't allow for such things.  The only option is to define a media type that extends JSON to include meta data.  I saw a proposal a while back for something like that, but as far as I know it hasn't caught on.  There were some things I liked about it, but it wasn't perfect.  I post a link if I find it again.

**Comment by jdesrosiers** [comment]
Found it, https://snowplowanalytics.com/blog/2014/05/15/introducing-self-describing-jsons/

**Comment by shhQuiet** [comment]
Thanks for the feedback and the link.  I guess we'll blaze our own trail on this- we usually include a `meta` section in our JSON docs, we can just include a schema property somewhere there.

**Comment by handrews** [comment]
@shhQuiet Yeah, the JSON Schema spec talks about how to connect them via HTTP headers and media types, but if you just have a document that you're not pulling over HTTP that doesn't help.
