### ISSUE TITLE
Specify format of property name

### ISSUE THREAD

**Issue by cheeryfella** [json-schema-org/json-schema-spec#345]
A response will include a json object that is used to help select options; the properties of this object would be the identifier of that option.

e.g.

```
 {
  ...
  "options" : {
    "SPD-06": {
      "ACX-93":"A11",
      "GHT-80":"P46"
    },
    "GPA-25":{
      "JDS-66":"K85",
      "WSE-58":"D18"
    }
  },
  ...
}
```

Is it possible to stipulate that a property must be of a format, say a regex? What is the most effective approach in specifying such an object within a schema? is it the case that simply making "options" an optional object

**Comment by handrews** [comment]
Yes, as of draft-wright-json-schema-valiation-01 (a.k.a. draft-06), the `"propertyNames"` keyword does exactly what you want (unless I am misunderstanding):  https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-6.22

If this is what you were looking for please go ahead and close this :-)

**Comment by handrews** [comment]
Since it's been a week with no response, and I'm about 95% sure that `"propertyNames"` is what you were looking for, I'm going to close this.  Please feel free to re-open if I have misunderstood your question.  Thanks!
