### ISSUE TITLE
Treatment of Boolean as JSON Schema in validations

### ISSUE THREAD

**Issue by 1602** [json-schema-org/json-schema-spec#346]
Recently introduced [change][small-change] regarding allowing boolean to be a valid JSON Schema is not reflected in the [validation][related-spec] spec.

Some generic guidance on how to treat boolean values during validation when valid JSON schema is expected would be nice, even if it suggests something like: "**boolean schemas are not applicable in all validations other than additionalItems and additionalProperties and MUST be ignored**" that would help to avoid deviations in implementations.

[small-change]: https://github.com/json-schema-org/json-schema-spec/commit/ed6078413e9dcc9d855706671577c5a9be1f7220
[related-spec]: http://json-schema.org/latest/json-schema-validation.html

**Comment by handrews** [comment]
The current validation spec intentionally avoids mentioning anything in any keyword about whether subschemas are booleans or objects.  Booleans as schemas are covered in the core specification https://tools.ietf.org/html/draft-wright-json-schema-01#section-4.4 and it is preferable to cover it in exactly one place.  The validation spec clearly builds on the core spec, so everything in the core spec continues to hold true

**Comment by handrews** [comment]
@1602 please let me know if this makes sense or if you see the need for some sort of additional reference from the validation spec to the core spec.  Absent further comments, I'll close this in a week or two.

**Comment by 1602** [comment]
Thank you @handrews now it is clear now why validation spec doesn't mention Boolean schema. In my opinion it worth linking the core spec since validation spec depends on core, which describes core concepts of validation. The reason why I overlooked Boolean schema in core spec was my assumption that validation only covered in validation spec. I wouldn't insist on adding a reference to the core spec, since common sense suggests that every aspect of schema depends on core.

**Comment by handrews** [comment]
@1602 great!  We do have this in the validation spec introduction:

> This specification will use the terminology defined by the JSON Schema core [json-schema] specification.

where that [json-schema] thing is a live link to the core spec, and it listed as a normative reference.  Maybe a bit more wording about the validation spec building on the entire core spec rather than just "terminology" would be reasonable... I'll try to write up a PR and see how it reads.

**Comment by handrews** [comment]
Fixed in #358.
