### ISSUE TITLE
Add more owners to the organisation

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#35]
@awwright It already happened once when the owner of json-schema became unreachable. In this organisation the situation is even worse - you are the only member. Could you maybe add [these people](https://github.com/orgs/json-schema/people) as owners to this org?

**Comment by awwright** [comment]
@epoberezkin I'm one of several members, I'm just the only one with publicly listed membership.

If this issue isn't directly related to the content of the specification in the repository, can you go ahead and close this out?

**Comment by epoberezkin** [comment]
@awwright could we maybe ask them to show it publicly, unless there is a reason not to? That would increase the confidence... Who they are btw?

**Comment by handrews** [comment]
@epoberezkin I agree about the confidence thing.  I do notice that @Julian is now listed as well.  Is that enough to close this?  If not, what is the specific condition we need to meet to close it?
