### ISSUE TITLE
Add "migrated" notice to the old github org

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#36]
Also remove "hopefully temporary" from the tagline of [this org](https://github.com/json-schema-org). What makes you think it is temporary?

**Comment by awwright** [comment]
We say "Hopefully" in that we can get someone restored as an owner to the group, and start using that again.

**Comment by robbie-mac** [comment]
By someone, are you referring to someone specific? or are you just looking for someone to voulenteer as an editor/champion?

**Comment by awwright** [comment]
@robbie-mac Right now the only person with ownership permissions on the original group is MIA. There's no clear way forward on how to change that, and we've tried a lot.

**Comment by robbie-mac** [comment]
Ok, but the .org site points to this group, so why not just proceed forward as is? Adding other owners, or people with owner privileges. That way the spec can move forward and not stagnate.

**Comment by handrews** [comment]
@awwright : I nominate that this be closed to reduce clutter because
A.) we can't do anything about it, and have no idea if we ever will
B.) if we ever can, we'll definitely fix it without needing a bug to remind us

**Comment by awwright** [comment]
Yeah, this issue doesn't seem to propose any changes to this repository, so I'll go ahead and close this out. If there's any further concerns, feel free to leave a comment here, on the mailing list, or drop me an email. Thanks!
