### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by adamvoss** [json-schema-org/json-schema-spec#369]
It would be nice if previous releases were tagged for easy access.

```sh
git tag draft-00 7ea575aef8d5c0183acbe6ff65b4c98ee9c236ec
git tag draft-01 2072feec9fc7a7ff0b2bb5b02c2d6742c554cc4a
git tag draft-02 707f65070d09fe5baa1315bce4d31a66ff124171
git tag draft-03 d6eadbd4fb6c8a4cee0ed8a4b707d5685af5e572
git tag draft-04 d4c5b3a2924370c51b710c8bfd81d3644a92766e
git tag draft-05 88d3cff344e32611e23cfdd44117b28723a8393d
git tag draft-06 4b495a2933b1d6f75298abdd23f018ba6a9d4f4a
```

Then `git push origin --tags`

Note: if #368 is merged then the last two tags would be:

```sh
git tag draft-05 628edaac73a968d61ce37cb1536fa4e931f5e02b
git tag draft-06 2b6b6b668b92ab0517cfe5cf1e54fa1674975c10
```

**Comment by handrews** [comment]
I think I did this without remembering there was a ticket for it.  Releases are tagged with the actual IETF draft name(s), while right now meta-schemas get branches.  I suppose once we push the bug-fixes on the meta-schemas that are broken, we can also add meta-schema tags (in most but not all cases on the same commit as the spec publication).  We probably just want to keep a branch for the most recent meta-schema until we're certain it's seen enough use to flush out bugs (the last three rounds of published meta schemas all contained bugs).
