### ISSUE TITLE
Emphasize context per RFC 5988bis

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#377]
The reworking of text to define things around the instance (or sub-instance) as the link context instead of simple "server-supplied" data was well received in trial balloon change #366.

This issue is for discussing the idea and ensuring we have the concept and wording right, after which point I will file a new PR.  If no one comments I'll just take a pass at it similar to the trial balloon but narrowly focusing on this one concept.

**Comment by handrews** [comment]
Here's a possible reworked organization of JSON Hyper-Schema, both to frame things in 5988bis terms and to introduce the various concepts at the right time.  The sections involved should be either obvious from 5988bis or from the current draft.  Client input description is not part of 5988bis (unless considered a kind of target attribute, I suppose).  It seemed worth putting in its own subsection.

1. Introduction
1. Conventions and Terminology
1. Overview
1. Meta-schema
1. Schema keywords
    1. Interaction with validation
    1. base
    1. links
1. Link description objects
    1. Context
        1. anchor
        1. anchorPointer
    1. Relation type
        1. rel
        1. "self" links
        1. "collection" and "item" links
    1. Target
        1. href
        1. hrefPointers
    1. Target attributes
        1. title
        1. description
        1. targetSchema
        1. targetHints
        1. mediaType
    1. Client input description
        1. Links, operations, and data
        1. hrefSchema
        1. headerSchema
        1. submissionEncType
        1. submissionSchema

**Comment by handrews** [comment]
I think I would like to add a section 7 which would be one or more examples that we would use to illustrate how all of the pieces fit together.  For instance, if the `hrefRequired` proposal from #49, or something like it, is added, then calculating the actual URI goes something like this:

1. Start by combining `base` and `href` to get the full URI template
1. Extract the variable names, which default to reading from fields in the context instance
1. Apply `hrefPointers` to adjust the location within the instance corresponding to each variable
1. If `hrefSchema` is present:
    1. Optionally pre-populate the resolution data set with any instance data matching those variables
    1. Ask the client for input for any variables that do not have an `hrefSchema` value of `false`
    1. Add the client input to the resolution data set, overriding any pre-populated values
    1. Validate the resolution data set against `hrefSchema` (if it fails validation, error out here)
1. For any variables in the resolution data set that still lack values, populate them from the instance as adjusted by `hrefPointers`
1. If `hrefRequired` is present, verify that all variables listed there have values (if not, error out here)
1. Apply the RFC 6570 URI Template resolution algorithm using the full URI Template (`base` + `href`) and the computed resolution data set

While we do need isolated examples demonstrating each possible feature, it is very hard to understand the system without some overall examples that show the order in which to apply the keywords and line them up with various use cases to motivate the structure of the system as a whole.

**Comment by handrews** [comment]
Another good thing to show in the examples section is how to manage application state (via links) vs resource state (via representation).  For example, instead of writing links with verb-ish extension relation types like "pay" and "cancel", write a link with the IANA-registered relation type "payment", and show how to represent the payment's state (unconfirmed, pending, canceled, completed) in the representation.  And how both the client (by setting state to "pending" or "canceled", or maybe by issuing a DELETE to cancel instead of having an explicit canceled state?) and server (by setting state to "completed" on its own) can affect that state through multiple operations defined by a single link.

While we don't want to turn the spec into a how-to guide for APIs, this sort of thing is a very fundamental confusion for people approaching Hyper-Schema, and it would also illustrate the proper use of `targetSchema` (which very few people get right on the first try- I certainly did not).

Thanks to @philsturgeon for the very practical example topic.

**Comment by handrews** [comment]
I think that we should also have an introductory section explaining what an implementation of Hyper-Schema would look like, and what it is called.  For JSON Schema validation, it's pretty clear that the thing one would implement is a validator.  But people do implement other things (code/ui/doc generators) which is where many feature requests arise that do not fit into validation.

For Hyper-Schema, we use terms like "user agent" and "client", but it's pretty vague as to what those mean, exactly, and where Hyper-Schema fits in.  While "user agent" does have a somewhat formal meaning, "client" could mean the user agent, or could mean a client application.

This is particularly important when considering HATEOAS, and discussing what the "application state" is and how it is maintained.  Hyper-Schema should not become a treatise on HATEOAS, but a few pointers defining terminology and explaining how the concepts align would be very helpful.

The "user agent" here is a generic client.  Like a web browser does for interactive hypermedia, the JSON Hyper-Schema driven user agent understands media types and protocols, but not the applications that use those media types and protocols.

The "client application" (unless someone has a better term) sits on top of the "user agent" and is aware of application-specific concepts.  But it does not *necessarily* need to directly understand media types and protocols any more than a human using a browser does.  It can, of course (as JavaScript applications running within the browser often do).  But it should be possible to program an application on top of a Hyper-Schema aware user agent without worrying about how `application/[*+]json`, `application/schema+json`, HTTP, HTTPS, `mailto:` URIs, etc. etc. get used behind the scenes.

**Comment by handrews** [comment]
Note that the intro section would be new, so it would come in as a separate commit or PR from the commit/PR rewriting the existing text.

**Comment by dlax** [comment]
@handrews So if I understand correctly, the "client application" is aware of hypermedia controls but would not care (but could) about their implementation (in terms of media type and protocol) whereas a "user agent" would be responsible for operating the links on behalf of the "client application" under media types and protocol constraints.

> Note that the intro section would be new, so it would come in as a separate commit or PR from the commit/PR rewriting the existing text.

I guess I'd prefer a single PR for the whole rewrite so that progress can be followed and we can have a global vision. No problem with the introduction coming as a single commit. Granted this is a lot of work, thanks for talking this!

**Comment by handrews** [comment]
@dlax this proves that I will never, ever understand how other people want PRs organized.  I anticipated either you or at least one other person demanding that this be split out.

Someone always wants things either split or merged.  I have no idea what I'm going to do with this.  Write it however works for me and post it, I guess.  It's guaranteed that someone will complain no matter what I do, so I'll just do whatever seems easiest for me.

**Comment by dlax** [comment]
Henry Andrews a écrit :
> @dlax <https://github.com/dlax> this proves that I will never, ever 
> understand how other people want PRs organized. I anticipated either you 
> or at least one other person demanding that this be split out.

Not sure what you mean here? I don't think I "demanded" anything. I just 
acknowledged your "warning" and basically said "this is fine by me".

> Someone always wants things either split or merged. I have no idea what 
> I'm going to do with this. Write it however works for me and post it, I 
> guess. It's guaranteed that someone will complain no matter what I do, 
> so I'll just do whatever seems easiest for me.
>

**Comment by handrews** [comment]
Oh, goodness, I apologize, that's not what I meant at all.  I should have let that sit for a while before posting.  You were absolutely not demanding anything and I did not think so even when I was writing that.

**Comment by handrews** [comment]
I just meant that I figured that if I included it, someone would ask that it be split out, so I was trying to get out ahead of it.  And then it turns out that you're fine with that.  I wasn't even angry when I wrote that, not that it comes across correctly :-(

More bemused that I can never seem to guess how to organize my work.

**Comment by handrews** [comment]
Draft of rewrite posted as PR #427.

**Comment by handrews** [comment]
Merged #427
