### ISSUE TITLE
Direct people to StackOverflow for questions that are not discussion based

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#38]
I personally feel that using the Google Group for help is fine, but people who are asking questions which have clear problem statements, I would much rather direct those to StackOverflow (with tag).

I strongly beleve that specific solved problems or questions should be easy to find, and would be much better suited on SO.
If agreed, I'll add a link under "more" on the website, but we will need to add a note about this on the Google Group, and agree that we should direct people there.

(Speaking of which, should we expand those who have admin rights on the Google Group? Myself and @awwright ?)

**Comment by awwright** [comment]
That might be a question to email around

**Comment by Relequestual** [comment]
Email round to who?

**Comment by Relequestual** [comment]
Message sent to owner via https://groups.google.com/forum/#!aboutgroup/json-schema

**Comment by Relequestual** [comment]
Geraint Luff is fine with this. I'll update to reflect.

**Comment by Relequestual** [comment]
Implemented.
