### ISSUE TITLE
Standardize media type field names

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#409]
@philsturgeon observed that the `submissionEncType` is really a media type, unlike `contentEncoding` (formerly`binaryEncoding` within `media`)  which is actually an encoding type.

Let's change it to `submissionMediaType` for consistency with `contentMediaType`, and while we're at it change `mediaType` to `targetMediaType` so that it aligns with `targetSchema` and `targetHints`.

`submissionEncType` is left over from HTML's `encType`, which is completely irrelevant here as a naming convention.  The rationale for `encType` as a name in HTML is itself rather convoluted.  In any event, `submissionEncType` was only introduced in draft-06 so changing it is low-impact.

At different points in earlier drafts, `mediaType` has been used for both what is now `contentMediaType` and what is now `mediaType`, so let's stop using the unqualified name and make the existing one `targetMediaType` so that it is unambiguous.  This is a higher-impact change but a good one for consistency.  And (to the extent that Hyper-Schema has been adopted at all beyond API doc generation), `mediaType` is not one of the most widely used fields anyway.

**Comment by philsturgeon** [comment]
That sounds good to me! So long as things are consistent. With a PHP background I've become really careful about this sort of thing.

**Comment by handrews** [comment]
> With a PHP background I've become really careful about this sort of thing.

LOLOLOLOLOLOL

**Comment by handrews** [comment]
Merged #411.
