### ISSUE TITLE
Hyper schema: readOnly has type boolean, but default is string

### ISSUE THREAD

**Issue by 1602** [json-schema-org/json-schema-spec#429]
http://json-schema.org/draft-06/hyper-schema#/properties/readOnly declared as `boolean` type, and its default has type string. According to validation spec it is recommended that default value is valid agains the schema. Surely, "recommended" is not `MUST`, but still, it makes me curious, what could be a reason for not complying recommendations?

**Comment by handrews** [comment]
@1602 thanks for the bug report!  This was an accident and has already been fixed by @dlax in commit https://github.com/json-schema-org/json-schema-spec/commit/9f2b7989946353f18530133dcf214c576b0242d9

**Comment by handrews** [comment]
There's some debate over whether it's appropriate to re-publish existing meta-schemas.  I thought I'd filed an issue for that but apparently I did not.  I'll cc you on it.
