### ISSUE TITLE
Re-publish bug-fixed meta-schemas?

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#430]
The draft-04 and draft-06 meta-schemas are buggy:

draft-04:
* missing "format"
* incorrectly uses "uri" with "id" and "$schema"
* missing "readOnly"

draft-06:
* "readOnly"'s default value is a string (I can't believe I did that... sigh)

@awwright given that fixing these really should not break any conforming implementations, any reason not to just update them in place?  We just had a 2nd bug report on the draft-06 readOnly default, and we get complaints about the draft-04 stuff from time to time (most recently in the form of confusion over how the test suite treats "uri" formats).

**Comment by dlax** [comment]
This seems eminently reasonable to me as part of a maintenance release process.

**Comment by handrews** [comment]
OK, I've done the following to help us manage release history:

* made a tag of every IETF draft name.  This means that recent releases have three tags on the same commit, but we may start doing independent releases given the very different maturity levels of the core and validation specs vs hyper-schema

* There is also a draft-wright-json-schema-02-base tag for the post-line-wrap commits that were done right after draft-wright-json-schema*-01.  This makes diffs between the releases easier.  id not make three tags for that- the people who need it can figure it out, I assume.  The  multiple tags are for people who just casually drop in and want to look at the history.

* made a branch for every meta-schema that is worth maintaining, meaning draft-04 and draft-06.  I'll post PRs on those branches for the meta-schema fixes.

@adamvoss this is probably relevant to your interests as it will make for slightly different submodule approach in the

**Comment by handrews** [comment]
We'll have to do something to sort out the whole "copy historical drafts into folders in the main repo" thing which TBH has never made sense to me.  It makes sense in the web site repo b/c we need to display them, but... not in the main repo, where they are literally historical artifacts in the change history.  Maybe @Relequestual or @awwright can explain why it is done this way?

**Comment by handrews** [comment]
Both now fixed.
