### ISSUE TITLE
JSON syntax error in json-schema.org/draft-03/hyper-schema

### ISSUE THREAD

**Issue by djmlog103** [json-schema-org/json-schema-spec#439]
There's a json syntax error in line 3. Its missing a comma

{
	"$schema" : "http://json-schema.org/draft-03/hyper-schema#",
	"extends" : {"$ref" : "http://json-schema.org/draft-03/schema#"}
	"id" : "http://json-schema.org/draft-03/hyper-schema#",

**Comment by handrews** [comment]
@djmlog103 thanks!  While we hope everyone is working to move off of draft-03 by now (and preferably to draft-06), I'll post a fix for this shortly.

**Comment by handrews** [comment]
Fixed and deployed, please let us know if you see any further problems.
