### ISSUE TITLE
Keywords minContains/maxContains

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#441]
These keywords will complement the existing keyword `contains` to define minimum and/or maximum number of items that are valid against the schema in `contains` keyword (in the same schema object).

Example:

```json
{
  "$comment": "validate that the array contains >= 2 and <= 4 boolean true values",
  "type": "array",
  "items": {"type": "boolean"},
  "contains": {"const": true},
  "minContains": 2,
  "maxContains": 4
}
```

Meta-schema:

```json
{
  "properties": {
    "minContains": {"type": "number", "minimum": 0, "default": 1},
    "maxContains": {"type": "number"}
  },
  "dependencies": {
    "minContains": ["contains"],
    "maxContains": ["contains"]
  }
}
```

`"minContains": 0` would allow limiting the maximum number of matching elements without requiring one matching element.

**Comment by handrews** [comment]
Removed the [proposal] prefix as I've been removing all of them since we have control over the labels now.  Proposals are labeled with "Enhancement".

**Comment by handrews** [comment]
This came up in https://stackoverflow.com/questions/47348506/json-schema-require-a-specific-array-element

**Comment by handrews** [comment]
This proposal seems pretty reasonable to me.  Any objections?  I'm going to tentatively put it in the draft-08 milestone.  Anyone who feels like submitting a PR is welcome to, otherwise I'll get around to it eventually.

**Comment by mchastain-turner** [comment]
It seems that `minContains` and `maxContains` could allow for schema definitions that would have a count validator. Otherwise you would have to do an `allOf` which seems like it would be unwieldy. 
```
{
  "$comment": "validate that the array has at least one headline and multiple paragraphs",
  "type": "array",
  "contains": {"const": true},
  "minContains": [{"const": "headline", "count":1}, {"const":"paragraph", "count":1}],
  "maxContains": [{"const": "headline", "count":1}]
}
```

**Comment by Relequestual** [comment]
I feel `allOf` would be a more natural way to express the constraint you describe.
Given you can already do this, and it isn't exactly a "shorthand", I don't see any reason to change what's already there to what you describe.

**Comment by mchastain-turner** [comment]
It does seem odd though that `minContains` and `maxContains` are applied as constraints to `contains`.  It seems like you could define the constraints directly in the `contains` schemas:

```
{
  "type": "array",
  "contains": [{"const": "onlyOne", "minCount": 1, "maxCount":1}, {"const": "atLeastOne", "minCount":1}]
}
```
