### ISSUE TITLE
Remove tags 20161011 and 20170309?

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#447]
I've added a bunch of tags for specific releases, do we need these anymore?  It's not entirely clear to me what they represent, as they don't seem to line up with releases.

@awwright I am assuming you added these?

**Comment by handrews** [comment]
20161011 was tagged to "Latest commit d1959a4  on Oct 11, 2016"
and
20170309 was tagged to "Latest commit 4a8708c  on Mar 3, 2017"

Given the lack of response I'm probably going to remove these.  We can easily restore them if necessary, but right now they're just kind of confusing.

**Comment by awwright** [comment]
They're the releases as seen on https://github.com/json-schema-org/json-schema-spec/releases I believe
