### ISSUE TITLE
README badges have incorrect numbers

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#460]
There are currently two issues and two PRs with "Status: Review Needed" but the README badge says 36.  That's rather annoying.

Also, the link for the first badge is a bit different than the others (open issues rather than just the label, which hits both issues and PRs).

I couldn't find documentation for these on Waffle and wasn't sure where else to look.  @Relequestual where did you get these exactly?

**Comment by Relequestual** [comment]
UGH. I think the link is somehow broken. 
I MAY have got notified of this fact, flagged it to do, and got lost in emails.
The badges are using https://shields.io, which has an interface to waffle.

It looks like shields.io now supports number of open issues by label (and PRs by label), which wasn't previously a thing.

It makes sense to dissassociate from waffle and just use the new direct route. I don't think any of us used or wanted to use any of waffles features.

**Comment by Relequestual** [comment]
Sorry about the AGE of this issue... =[

**Comment by handrews** [comment]
@Relequestual no worries, it's not the most urgent thing in the world! :-)

I agree on just using shields.io directly and skipping waffle as we're not really using it.

**Comment by handrews** [comment]
@Relequestual I can't make heads or tails of what's going on at shields.io.  I tried to customize the open issues by label badge and it's neither saying the write thing on the badge nor showing the right number.  Would you be able to fix this anytime soon?

I also wonder if we only want those badges for issues, and then just have a single badge for all open PRs.  The PR list has never, to my knowledge, gotten longer than a page, and has only briefly been over 10 at the height of reworking Hyper-Schema.  I feel like one click is better than multiple for PRs.

**Comment by Relequestual** [comment]
Yeah I'll get on this. I'm most likely to fix this in one weeks time as we have a limited time on Friday morning for work. I'll make a reminder to make sure I do it. =]

**Comment by Relequestual** [comment]
*adds another reminder*
