### ISSUE TITLE
Clarification of "$ref" as a root property referring to "definitions" defined in the same object

### ISSUE THREAD

**Issue by jimmylewis** [json-schema-org/json-schema-spec#479]
Is the following JSON schema valid?  

    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "$ref": "#/definitions/myObject",
      "definitions": {
        "myObject": {
          "type": "object"
        }
      }
    }

In JSON Schema Draft 4, it refers to the [JSON Reference draft][1], which says (emphasis mine):

>  The "$ref" string value contains a URI [RFC3986], which identifies
   the location of the JSON value being referenced.  It is an error
   condition if the string value does not conform to URI syntax rules.
   **Any members other than "$ref" in a JSON Reference object SHALL be
   ignored.**

Similarly, in the [latest JSON Schema draft][2], it says:

>An object schema with a "$ref" property MUST be interpreted as a "$ref" reference. The value of the "$ref" property MUST be a URI Reference. Resolved against the current URI base, it identifies the URI of a schema to use. **All other properties in a "$ref" object MUST be ignored.**

However, in the JSON Schema test suite there is a test validating [this very scenario][3].  

How are these definitions reconciled?  Using Visual Studio's validator, the schema is considered invalid because it ignores the "definitions" property, so the "$ref" doesn't resolve.  Other validators seem to accept it as a valid schema.  Which is the correct behavior?

  [1]: https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-3
  [2]: http://json-schema.org/latest/json-schema-core.html#rfc.section.8
  [3]: https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/9567c588bc9d1705b4840ee9d9f3f268f40c1e68/tests/draft4/ref.json#L121

**Comment by handrews** [comment]
@jimmylewis thanks!  I agree with your (and Visual Studio's) behavior, so this looks like a bug in the test suite.  Could you please file it on that repository so the maintainer there sees it?  This repository is for issues and enhancements of the specification itself.

**Comment by jimmylewis** [comment]
Turns out this issue was already opened on the test repo. https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues/113

**Comment by handrews** [comment]
@jimmylewis so it is!  I've been so focused on getting draft-07 out the door that I haven't been paying much attention to the other repos.  I'll try to get this fixed as soon as I have a moment.  It's not good to have conforming implementations failing the suite.
