### ISSUE TITLE
How to describe subset in json schema?

### ISSUE THREAD

**Issue by VyacheslavMik** [json-schema-org/json-schema-spec#482]
Hello all. Can you help me? How I can describe subset in json schema?

For example, I have following json schema:
```json
{
    "type": "object",
    "properties": {
	"a": {"type": "array" },
	"b": {
	    "type": "array",
	    "subset": { "$data": "1/a" }}
    }
}
```
And this objects is valid:
```json
{
    "a": [1 2 3],
    "b": [3 1 2]
}

{
    "a": [1 2 3],
    "b": [2 1]
}

{
    "a": [1 2 3],
    "b": [1]
}

{
    "a": [1 2 3],
    "b": []
}
```

And this is invalid:
```json
{
    "a": [1 2 3],
    "b": [1 2 3 4]
}
```

**Comment by handrews** [comment]
@VyacheslavMik it looks like you are using `$data` which is proposed but not (yet) accepted as part of JSON Schema.  I am guessing that you are using the Ajv validator as it is the only one that I know of that supports `$data`.  If so, please open this issue at the Ajv repository, as the behavior of `$data` is specific to the implementation at this time.

**Comment by handrews** [comment]
With `subset` are you trying to assert that array "b" should:
1. be treated as a set (unordered)
2. contain only elements from the set {1, 2, 3}

If so, I believe you want:

```JSON
{
    "type": "object",
    "properties": {
	"b": {
	    "type": "array",
	    "items": {
                "enum": [1, 2, 3]
            }
	}
    }
}
```

**Comment by handrews** [comment]
@VyacheslavMik correction, I missed one of your test cases (this is what I get for replying to issues before having a cup of tea in the morning), node the added `maxItems`:

```JSON
{
    "type": "object",
    "properties": {
	"b": {
	    "type": "array",
	    "items": {
                "enum": [1, 2, 3]
            },
            "maxItems": 3
	}
    }
}
```

**Comment by handrews** [comment]
If that works for you please close this, but I'm happy to keep working on ideas if the above schema does not do what you need.

**Comment by VyacheslavMik** [comment]
Thank you very much. It's work fine.
