### ISSUE TITLE
Hyper-Schema examples, ecosystem of datasets

### ISSUE THREAD

**Issue by ppKrauss** [json-schema-org/json-schema-spec#503]
As all datapackages of https://github.com/datasets  project uses a [Frictionlessdata json-schema](http://frictionlessdata.io/specs/data-package/), and there are many  inter-related datasets (must use foregin-keys), we can use them as good example. 
 
See 
* country-codes and its [datapackage.json](https://github.com/datasets/country-codes/blob/master/datapackage.json) 

* br-state-codes and its [datapackage.json](https://github.com/datasets-br/state-codes/blob/master/datapackage.json) 

* language-codes and its [datapackage.json](https://github.com/datasets/language-codes/blob/master/datapackage.json) 

* br-city-codes and its [datapackage.json](https://github.com/datasets-br/city-codes/blob/master/datapackage.json) 

![](https://camo.githubusercontent.com/38c18e4e29b1875125ba9fdeca1f47f700719309/68747470733a2f2f79756d6c2e6d652f37626138663135662e706e67)

See datasets as diagrams:
[ ![](https://yuml.me/8fbb7469.png) ](https://github.com/datasets-br/sql-unifier/tree/master/src#see-datasets-as-diagrams)

**Comment by handrews** [comment]
@ppKrauss are you sure you have the right repository?  This repo is for discussing changes and additions to the JSON Schema IETF Internet-Drafts.

**Comment by ppKrauss** [comment]
Hi @handrews , sorry to pollute here, can I delete (?) or simply close?

I will back  later with a "better glue".
