### ISSUE TITLE
URN values, needs a datatype

### ISSUE THREAD

**Issue by ppKrauss** [json-schema-org/json-schema-spec#504]
URN values need  [URI-templates](https://tools.ietf.org/html/rfc6570) as  its URN-resolver... And need to enphatic that it is a URN, not "any URL" neither "any ID" or "any string"...

----

It is not a "free string", neither an URL. Some standard URLs can provide URN-resolution... But the main reference is the URN-Namespace, and the "official URL template" is the URN-resolver adopted by the community... But can be changed, even when it is a [PURL](https://en.wikipedia.org/wiki/Persistent_uniform_resource_locator) because it is not unique. 

valid for the user-community, not need to be universal... Even about universal URNs, [Uniform Resource Name](https://en.wikipedia.org/wiki/Uniform_Resource_Name)s have a new [RFC 8141](https://tools.ietf.org/html/rfc8141), of 2017... So become to use. 

The usual reference mechanism is like URI-template, 

URN value |  Possible URL-template for resolution | URN-resolution 
-----|----------------|-----
`urn:lex:br:federal:lei:2006-07-24;11326`| `http://www.lexml.gov.br/urn/{urn}`| [link](http://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2006-07-24;11326)
`urn:wikidata:Q5` | `http://wikidata.org/entity/{urn}` | [link](http://wikidata.org/entity/Q5)
`urn:issn:1476-4687` | `http://api.ok.org.br/issn/{urn}/n2ns` | [link](http://api.ok.org.br/issn/1476-4687/n2ns)

----

Other examples: technically [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) is an URN;  Schema.org's Classes and properties; ...

**Comment by handrews** [comment]
@ppKrauss I'm afraid I'm not following what you're trying to say about the JSON Schema / Hyper-Schema specification here.  Is there something you think needs to be changed?  Added?

**Comment by ppKrauss** [comment]
Hi @handrews, I am using old JSON Schema, but to collaborate here need more elaborate connection to the current json-schema version and specifications... So, I prefer to back later, after some review and homework with the current version.

**Comment by handrews** [comment]
@ppKrauss sounds great, thanks!  draft-07 just shipped this week and can be found on the web site, or as draft-handrews-json-schema*-00 on the IETF site
