### ISSUE TITLE
Require a specific array element among others

### ISSUE THREAD

**Issue by tannerli** [json-schema-org/json-schema-spec#506]
As far as I can tell, there is no possibility to require a specific array element among others; Consider the following example:
```
{
  "attributes":[
    {"symbolic-name": "displayName", "value": "Display Name"},
    {"symbolic-name": "attributeXY", "value": "value1"}
    {"symbolic-name": "attributeYZ", "value": "value2"}
  ]
}
```
Is there a way to require the "attributes" to have exactly one "displayName"? I tried combinations of 'oneOf' and 'allOf' which both seem to mutually exclude each other. (See my efforts on [StackOverflow](https://stackoverflow.com/questions/47348506/json-schema-require-a-specific-array-element))

**Comment by handrews** [comment]
@tannerli I answered your question over on stackoverflow, thanks for filing the issue to get my attention.  I'm going to close this but feel free to re-open if you want to have further discussion here about it.  Or you might want to comment on #441 which I referenced from the SO answer.
