### ISSUE TITLE
Is the URI "fragment" meaningful in a $ref URI?

### ISSUE THREAD

**Issue by mikemol** [json-schema-org/json-schema-spec#507]
RFC 3986, taken in the context of JSON-SCHEMA, suggests that having a $ref with a URI value that identifies a fragment indicates that the $ref references only the portion of the target document identified by that fragment.

What's unclear (to me, anyhow, so some clarification would be helpful) is whether or not that means a catalog schema could be constructed, with subsegments identified with either $id or $anchor values equal to the fragment, or with that fragment perhaps constructed as a JSON Pointer.

If definitions refinement is deemed unnecessary, some examples elucidating this scenario (a catalog of schemas under a common URL would be helpful.

**Comment by handrews** [comment]
@mikemol Fragments are common in `$ref` values.  When the URI is only a fragment, it is a reference within the current file (usually to a schema under the `definitions` keyword).

When the URI is for another file with a fragment, then the reference is to a subschema within the file (again, most often under the `definitions` keyword in that file).

So, you can have a JSON Schema that consists solely of a `definitions` keyword and schemas nested under that, and use that as your catalogue.  You can either use JSON Pointer fragments to identify them, or us `$id` to assign plain name fragments (which is nicer if you may re-organize or re-name your definitions).

I'll try to add an example later when I have a bit more time, just wanted to give a basic answer to start and see if it's at all what you are looking for.

**Comment by handrews** [comment]
Note that while there was at one point a proposal for a `$anchor` keyword, it was rejected and was never part of any draft.  JSON Hyper-Schema has an `anchor` (no `$`) keyword in its Link Description Object, but that has nothing to do with identifying schemas.

**Comment by mikemol** [comment]
That's exactly the information I was looking for, and having some examples of remote fragment behavior would be fantastic, thanks!

**Comment by handrews** [comment]
Let's say we have schemas called "library" and "something" in the same directory.  I'm leaving off ".json" as most modern hypermedia systems rely on content-type rather than file extensions, but if you're working with local files you may want the ".json" extensions.

Here's what it looks like in draft-07 (or draft-06, just change the `$schema` URI).
For draft-04, change the `$schema` URI and change the `$id` keyword to `id`.

```JSON
{
    "$id": "https://example.com/schemas/library",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "foo": {"type": "integer"},
        "bar": {"type": "string"}
    }
}
```

```JSON
{
    "$id": "https://example.com/schemas/something",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["foo"],
    "properties": {
        "foo": {"$ref": "library#/definitions/foo"},
        "bar": {"$ref": "library#/definitions/bar"}
    }
}
```

Let me know if you have any questions, I know I'm not going into a lot of detail here.  Or if this is sufficient, please go ahead and close the issue.

**Comment by handrews** [comment]
@mikemol since it's been several weeks with no questions on the example I'm going to assume it is sufficient and close this.  Do feel free to re-open/comment with questions as needed.
