### ISSUE TITLE
Fix hyper-schema

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#516]
See https://github.com/json-schema-org/json-schema-spec/blob/master/hyper-schema.json#L59

It should be `"$ref": "http://json-schema.org/draft-07/hyper-schema#/links"`

**Comment by handrews** [comment]
@epoberezkin thanks, will do!

**Comment by handrews** [comment]
@epoberezkin actually, no, that's correct as it is.  The LDO has its own file (and has for several revisions, now, we just switched the contents around this time).
