### ISSUE TITLE
Question: Draft 7 contentMediaType

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-spec#519]
It seems like this repo could use a Gitter room.  Perhaps that would be a better forum for questions like this.

---

Section 8 of the validation spec defines several properties which appear to be neither assertion nor annotation properties.  One of these is `contentMediaType`.  However, while reading the verbiage, it seems as if implementations should validate that the contents of string values adhere to the specified media type.

Is that correct?  Are implementations encouraged to validate string contents in this way?  My question arises out of the sheer magnitude of this request/requirement.  There are [a lot of media types](https://www.iana.org/assignments/media-types/media-types.xhtml) (even in the RFC2046 listed in the validation spec).  Support for all of these seems overkill, verging on unmanageable.

For instance, while validating `text/json` or `text/xml` are rather trivial, it seems that other formats like `audio/*` would be somewhat more involved.

As a consumer of a schema validator, would I be wrong to expect an implementation to validate a media type if I specified one?

**Comment by gregsdennis** [comment]
I see that section 3.3 identifies both sections 7 & 8 as "useful for annotations", which you would think answers the question, but it goes on to say that they are also useful for assertions...

Note that section 7 defines keywords such as `format`, which Manatee.Json *does* validate to an extent.

**Comment by gregsdennis** [comment]
@handrews It looks like you already made some good comments about this. https://github.com/json-schema-org/json-schema-spec/issues/515#issuecomment-348056506

**Comment by handrews** [comment]
@gregsdennis re: gitter room:  It's easier for me to just work in GitHub issues.  There aren't many people answering these things so the fewer places I have to keep up with to answer questions the better.  I curate GitHub issues usually daily- everything else is whenever I remember it exists.  If someone else will own keeping up with another forum then that might work.  I have no objection to Gitter, I'm just overloaded as it is.

**Comment by gregsdennis** [comment]
I'm going to close this, accepting your comments in #515.

**Comment by handrews** [comment]
Regarding validation requirements, this should have been clear from [Section 7.2](https://tools.ietf.org/html/draft-handrews-json-schema-validation-00#section-7.2) and [Section 8.2](https://tools.ietf.org/html/draft-handrews-json-schema-validation-00#section-8.2), both titled "Implementation Requirements", for `format` and `content*` respectively.

The `format` one is pretty good, I think.  We have been kicking around some ideas about making it more flexible as there are now quite a few defined formats, and they have various use cases.

The `content*` one was supposed to comment that supporting them as assertions did not mean supporting any particular set of media types or encodings, but I guess we either accidentally cut that or never remembered to put it in.

**Comment by handrews** [comment]
Actually I was thinking of something else when you mentioned gitter.  I have a cold, I'm exhausted, and I should probably not be answering GitHub issues right now :-P

I'll rethink that when I have a functional brain sometime.

**Comment by gregsdennis** [comment]
That's fine. Feel better.

**Comment by gregsdennis** [comment]
FYI - https://gitter.im/

Creates a nice general discussion forum for easy questions that don't really deserve an issue.  It integrates into the GH repo, so you can link to PRs and issues as if you were commenting in an issue.  It also allows others to respond when you're not available (more community-centric IMO).

If you think that a topic would be better discussed in an issue, you can always suggest that the asker create one.
