### ISSUE TITLE
A way to descibe enumeration values

### ISSUE THREAD

**Issue by mitar** [json-schema-org/json-schema-spec#520]
So enumeration can be a long list of values, which are often some constants used by a machine. I think there should be a way to attach description to each of those values.

**Comment by dlax** [comment]
One way to achieve this is to use a `oneOf` array with `const` and `title` (and maybe `description`):
```json
{
  "oneOf": [
    {"const": "choice1", "title": "this is choice 1"},
    {"const": "choice2", "title": "this is choice 2"}
  ]
}
```

See #57 for reference.

**Comment by mitar** [comment]
And for v4 JSON schema this probably means I could do something like:

```json
{
  "oneOf": [
    {"enum": ["choice1"], "title": "this is choice 1"},
    {"enum": ["choice2"], "title": "this is choice 2"}
  ]
}
```

No? Hm, maybe this can be an approach. Thanks.

**Comment by handrews** [comment]
@mitar yes, that's the correct option in draft-04.  `const` in draft-06 just makes the intent more clear.  Sounds like we can close this, please LMK if you weren't done with the issue :-)

**Comment by mitar** [comment]
Thanks!
