### ISSUE TITLE
Possibility to have conditional checks

### ISSUE THREAD

**Issue by tommueller** [json-schema-org/json-schema-spec#521]
I have a data-structure where I have a generic field in JSON which can be described by a type, for example "text" or "date" or "number".
The field also can have a value, which's type can by either of type string (text), or date (date) or number etc. Currently I have this in the schema-definition: 

```json
"type": {
   "description": "Short description",
   "type": "string",
   "enum": ["text", "date", "label", "number", "image"]
},
"value": {
  "description": "The value",
  "type": ["string", "number", "array"]
}
```

What I would like to do is, to check the value against the type. So if type is text, value should be of type string. If type is number, the value has to be a number. For certain types I would also like to regex-check the value (image must be an url for example).

Is / will this be possible to represent with JSON-schema?

**Comment by erosb** [comment]
The latest (draft-7) version of json schema [supports if - then - else](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.6). If the implementation you use doesn't support it yet, then you may hack it up using `const` and `oneOf`, eg. 

```
{
    "oneOf" : [
        {
            "properties" : {
                "type" : {"const" : "text"},
                "value" : {"type" : "string"}
            }
        },
        {
            "properties" : {
                "type" : {"const" : "number"},
                "value" : {"type" : "number"}
            }
        }
    ]
}
```

The drawback is that "oneOf" will fail if you have overlapping types (eg. your dates will always be strings too), so maybe you should go with "anyOf" instead.

**Comment by tommueller** [comment]
Great. Thank you @erosb !
