### ISSUE TITLE
Validation fails for nested pattern properties 

### ISSUE THREAD

**Issue by ghsatpute** [json-schema-org/json-schema-spec#531]
I have JSON which looks like this 

```
{
  "dell": {
    "memory": {

      "RAM": {
        "RamType": "DDR",
        "Size": 16
      },I h
      "Graphic": {
        "RamType": "GDDR",
        "Size": 4,
        "dummy": "dummy"
      }
    },
    "dummy": "dummy"
  }
}
```
In above JSON, if someone removes the dummy key-value pairs it should be a valid JSON but with those it should be invalid JSON. 

I have created the JSON schema using Draft-06 as below. 

```
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "properties": {
    "computers": {
      "patternProperties": {
        "additionalProperties": false,
        "^[a-z0-9-_]+$": {
          "properties": {
            "memory": {
              "patternProperties": {
                "^[a-z0-9-_]+$": {
                  "additionalProperties": false,
                  "properties": {
                    "RamType": {
                      "type": "string",
                      "RamSize": {
                        "type": "number"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

But when I try this schema with any [online validator](https://jsonschemalint.com/#/version/draft-06/markup/json) it doesn't validate it. 

What am I missing here?

**Comment by handrews** [comment]
Your top-level "properties" in your schema specifies a "computers" property, which is not present in your instance.  The schema expects everything to be nested under that, and does not restrict any other top-level property.  So since your instance has "dell" as a top-level property, no validation occurs on it.

**Comment by handrews** [comment]
Forgot one bit- the reason nothing happens on "dell" as a top-level property the way your instance is written is that while your schema has `"additionalproperties": false` on the inner two levels, the top/outer level does not set that.  So "dell" appears to be an additional property, and is simply ignored (along with all of its contents).

**Comment by ghsatpute** [comment]
@handrews Thanks for your inputs. 

My bad I shouldn't have written `computers` in the schema file. I've corrected my schema file and JSON file. They are as below 

```
{
   "$schema":"http://json-schema.org/draft-06/schema#",  
   "additionalProperties":false,
   "patternProperties":{
      "^[a-z0-9-_]+$":{
         "additionalProperties":false,
         "properties":{
            "memory":{
               "patternProperties":{
                  "^[a-z0-9-_]+$":{
                     "additionalProperties":false,
                     "properties":{
                        "RamType":{
                           "type":"string",
                           "RamSize":{
                              "type":"number"
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
```

```
{
   "dell":{
      "memory":{
         "RAM":{
            "RamType":"DDR",
            "Size":16
         },
         "Graphic":{
            "RamType":"GDDR",
            "Size":4,
            "dummy1":"dummy"
         }
      },
      "dummy2":"dummy"
   },
   "dummy3":"dummy1"
}
```

Here, `dummy2` is getting caught but `dummy1` and `dummy3` are not getting caught. 

Does JSON schema doesn't work on nested levels?

**Comment by handrews** [comment]
I'm pretty sure this was answered for you on stackoverflow https://stackoverflow.com/questions/48201780/json-schema-strict-typing-in-patternproperties so I'm going to close this, please let us know if there was more to your question.

I thought I'd actually looked it up on stackoverflow and closed this already but I guess I forgot.

**Comment by ghsatpute** [comment]
@handrews apologies for late response. 

The actual reason was the regex (for a reason it's called "write-only language"). My regex was `^[a-z0-9-_]+$"` it should've been `^[a-zA-Z0-9-_]+$`. It was not matching my element, so it was not giving any exception.
