### ISSUE TITLE
Using "contains" for a "VersionContainer"

### ISSUE THREAD

**Issue by mikaelmh** [json-schema-org/json-schema-spec#533]
We want to version our user entered data and just moved to an architecture that places the user entered values (e.g. {Place}) in a version-container.

### Original setup:

Our original schema for an Event.object looked like this, where a valid instance would be one that adhered to our "Place" definition;

**Schema:**

```

  "location": {
    "description": "The event's location",
    "type": "object",
    "$ref": "#/definitions/Place"
  }

```

```
"definitions":

{
  "title": "Place",
  "description": "A geographic point or area.",
  "type": "object",
  "properties": {
    "@type": {
      "description": "The JSON-LD type of the Doc.",
      "default": "Place",
      "type": "string"
    },
    "name": {
      "description": "The location name.",
      "type": "string"
    },
    "address": {
      "description": "The JSON-LD context of the entity.",
      "$ref": "#/definitions/PostalAddress"
    }
  }
}

```

**Instance:**

A valid instance for "location" would be something like this;

```
"location": {
          "@type": "Place",
          "name": "167 West 121th Street",
          "address": {
            "@type": "PostalAddress",
            "addressLocality": "New York City",
            "addressRegion": "NY",
            "postalCode": "10027",
            "streetAddress": "167 West 121th Street"
          }   
        }

```

### New setup

Then we decided to version our user data. We have done this by placing each value (string or object) into a container that includes some meta-data regarding the version. For the example above, the "location"-keyword now takes an array of VersionContainers, each having a "Place" container embedded. A new version (versionContainer) is consequently created and added to the array whenever an updated version is added. Using the container structure, an instance with one the above examples would now look like this;

```
"location": [
{
  "versionContainerId": "74GDS9FD9SD8D342JDJS",
  "createdAt": "2018-10-21T19:00:00-05:00",
  "valueObject": {
    "@type": "Place",
    "name": "167 West 121th Street",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "New York City",
      "addressRegion": "NY",
      "postalCode": "10027",
      "streetAddress": "167 West 121th Street"
    }
  }
}
]
```

To allow this instance to validate againt our schema, we had to change the schema to look like this;

**Schema:**

```
"location": {
      "description": "The event's location",
      "type": "array",
      "items": {
        "$ref": "#/definitions/VersionContainer"
      }      
    }    
``` 

The problem now is that we are not able to specify that "location" should only accept instances of the VersionContainer where the "valueObject" instancw validates against the "Place" definition. (Which is effectively to say that "location" should only accept "Place" here as the VersionContainer is generic). We use versioning for many keywords (location, organizer, time, etc.), and for the validation to go through, they all now basically look like the "location" example;

```
"organizer": {
      "description": "The organizer of the event",
      "type": "array",
      "items": {
        "$ref": "#/definitions/VersionContainer"
      }      
    }    
``` 

This is not ideal, of course, as someone can pass anything inside the```VersionContainer.valueObject``` and it will still validate without checking the embedded object here.

One solution that we have seen people do is to create a new versioned-type of all objects (e.g. {VersionedPlace} in addition to {Place}), but that solution changes the original objects and feels a bit clumsy and verbose.

Is there a way using "contains" - or another method - to tell the JSON validation to **both** validate the "VersionContainer" **AND** validate the embedded object? For our example that would be ```"valueObject": {Place}``` , against one of our JSON schema definitions of "Place".

**Comment by handrews** [comment]
@mikaelmh can you provide an example of a full schema and instance here?  I can't quite figure out what you mean by "every version-container validates against every keyword, not allowing us to clearly indicate what value goes where."  If you can show a schema, an instance, and the exact missing or incorrect behavior we can probably help you better.

**Comment by mikaelmh** [comment]
@handrews thank you for your feedback! Just updated our question with some schema and instance examples. I hope it is a a bit clearer.

**Comment by handrews** [comment]
Thanks, @mikaelmh, and my apologies- I thought I replied to this right away but apparently not.

I think that all you need to do here is separately define the container and then each thing that can go inside the container.  Then you `allOf` them together as needed.

Notice that in the `"VersionContainer"` definition, `"valueObject"` has a blank schema (allowing anything) because you don't know what is being versioned when you define the container.  Then, in the `"Location"`, it also defines `"valueObject"` but as a reference to a specific thing- in this case a `"Place"`:

```JSON
{
  "definitions": {
    "VersionContainer": {
      "type": "object",
      "properties": {
        "versionContainerId": {
          "$ref": "#/definitions/ContainerId"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "valueObject": {}
      }
    },
    "Place": {
      "title": "Place",
      "description": "A geographic point or area.",
      "type": "object",
      "properties": {
        "@type": {
          "description": "The JSON-LD type of the Doc.",
          "default": "Place",
          "type": "string"
        },
        "name": {
          "description": "The location name.",
          "type": "string"
        },
        "address": {
          "description": "The JSON-LD context of the entity.",
          "$ref": "#/definitions/PostalAddress"
        }
      }
    },
    "Location": {
      "allOf": [
        {
          "$ref": "#/definitions/VersionContainer"
        },
        {
          "properties": {
            "valueObject": {
              "$ref": "#/definitions/Place"
            }
          }
        }
      ]
    }
  }
}
```

If this answers your question please go ahead and close (or comment that I can close).  But do let me know if anything is unclear or seems incorrect!
