### ISSUE TITLE
How do I have multiple possible types within an array?

### ISSUE THREAD

**Issue by MartinMuzatko** [json-schema-org/json-schema-spec#537]
Hello! I'm building a schema about GUI modules. That schema allows either objects (that define the module) or strings (that reference other modules) within an array of modules.

How should I document this type of schema? AFAIK JSON schema only allows one distinct type for a sub-field.

I have read in the spec, that it is possible to use regex

> Two validation keywords, "pattern" and "patternProperties", use
   regular expressions to express constraints, and the "regex" value for
   the "format" keyword constrains the instance value to be a regular
   expression. 
> simple grouping ("(...)") and alternation ("|").

But I think with regex I only describe possible values for a field, but not possible types for a field.

The spec for defining array schemas says:

>  If "items" is a schema, validation succeeds if all elements in the
   array successfully validate against that schema.

> If "items" is an array of schemas, validation succeeds if each
   element of the instance validates against the schema at the same
   position, if any.

the second paragraph notes that I am able to establish a 1:1 mapping for array items against a list of schemas. So e.g. I can say "first item has to be string, second item has to be of object" but I can't have an OR condition.

Please let me know if it is possible to implement this use-case in the spec, or if you need me to elaborate the use case.

Thanks!

**Comment by Relequestual** [comment]
Hi @MartinMuzatko 

`type` can be an array, as per http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1.1

So your schema may look like...
```
{
  "properties" : {
    "myArray" : {
      "items" : {
        "type" : [ "string", "object"]
      }
    }
  }
}
```

If you need to specify the object further, you can use `oneOf` http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.7.3 to make something that looks like...

```
{
  "properties" : {
    "myArray" : {
      "items" : {
        "oneOf" : [
          {
            "type" : "string"
          },{
            "type" : "object",
            "properties" : {...},
            ...
          }
        ]
      }
    }
  }
}
```


Does that make sense?

**Comment by MartinMuzatko** [comment]
This should work! Thanks, I wasn't able to find this in the documentation in the first place, because this is not something I was searching for. I will try it out and get back to you with results. I think this should work fine. Until then, the ticket can be closed.
