### ISSUE TITLE
hyper schema test suite missing?

### ISSUE THREAD

**Issue by mokkabonna** [json-schema-org/json-schema-spec#546]
The hyper schema draft mentions a test suite for hyper schema. 

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-hyperschema.xml#L300

and other locations

Is the test suite not published or non-existant? Or have I completely missed it?

I am planning to take a stab at a javascript implementation.

**Comment by handrews** [comment]
@mokkabonna the test suite is missing b/c I'm the only one working on it, and I'm also driving the draft-08 spec work, and I have other stuff to do for my actual job.

Perhaps I should have been more tentative in referencing that in the spec.  I certainly intended to do it immediately but it has not worked out that way.  If you're actually going to try an implementation, though, that would be very motivating.

**Comment by handrews** [comment]
@mokkabonna see also https://github.com/json-schema-org/JSON-Schema-Test-Suite/issues?q=is%3Aopen+is%3Aissue+project%3Ajson-schema-org%2FJSON-Schema-Test-Suite%2F1

**Comment by mokkabonna** [comment]
> @mokkabonna the test suite is missing b/c I'm the only one working on it, and I'm also driving the draft-08 spec work, and I have other stuff to do for my actual job.

I understand completely, I have a list of open source things myself that I plan to get around to. I wanted to check status only. :smile: 

My main goal and idea is to create a library that can generate a javascript client, inspired by https://github.com/philschatz/octokat.js which is a generic client for the github api. But even more generic, so that no out of band information is needed.

And to do that I need to generate the links first.

**Comment by mokkabonna** [comment]
Does this section provide the best "test case" as of now?

> Here are all of the links that apply to this instance, including those that are defined in the referenced individual "thing" schema:

http://json-schema.org/latest/json-schema-hypermedia.html#rfc.section.9.5

**Comment by handrews** [comment]
@mokkabonna also we have a slack channel where you can ask questions along the way:
Here's an invite link https://join.slack.com/t/json-schema/shared_invite/enQtMjk1NDcyNDI2NTAwLTcyYmYwMjdmMmUxNzZjYzIxNGU2YjdkNzdlOGZiNjIwNDI2M2Y3NmRkYjA4YmMwODMwYjgyOTFlNWZjZjAyNjg
