### ISSUE TITLE
attachmentUri vs attachmentPointer

### ISSUE THREAD

**Issue by mokkabonna** [json-schema-org/json-schema-spec#552]
https://github.com/json-schema-org/json-schema-spec/blob/7a6c26cabf2a82cb30f38c2377063239b1823816/jsonschema-hyperschema.xml#L946-L951

This section mentions attachmentUri. I assume it means attachmentPointer. Also that it should be (my emphasis added to changed text)

> The JSON Pointer for the location within the instance to which the 
     link is attached.  By default, **"contextPointer"** and **"attachmentPointer"** are 
     the same, but **"contextPointer"** can be changed by LDO keywords, while 
     **"attachmentPointer"** cannot. 

Am I right? This is the only place anything called **attachmentUri** is mentioned.

**Comment by handrews** [comment]
Thanks, @mokkabonna, you are correct!

**Comment by handrews** [comment]
Merged PR 592
