### ISSUE TITLE
Vocabularies and "format"

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#563]
We have numerous requests for additional formats, or ideas that could be implemented with formats (see #152, #312, #361, #540, #542).

There have also been a number of discussions around the [implementation requirements](https://tools.ietf.org/html/draft-handrews-json-schema-validation-00#section-7.2), particularly 

> they SHOULD implement validation for [all] attributes defined below

which becomes more burdensome as we add more formats.  One idea has been to say that you only need to implement certain subsets (e.g. you could implement the date and time formats but skip the URI/IRI formats, but you shouldn't just implement uri-reference and not uri).  But there's no good way to convey support levels.  Which brings us to:

>  Save for agreement between parties, schema authors SHALL NOT expect a peer implementation to support this keyword and/or custom format attributes.

which makes interoperability very challenging.  `format` is really only *reliably* useful as a semantic annotation, not as validation.

We need a better story here, if for no other reason than to figure out how to manage the endless stream of requests for standardized formats.  Currently, that's the only way to achieve any level of interoperability, so there is a high motivation to push for inclusion.

----

If we go with vocabulary support along the general lines of #561, I feel like this should help manage the variations.  A vocabulary could include specific `format` values (and likewise for `contentType` and `contentEncoding`, I suppose).

I've split this out from #561 because it's not clear how it would work.  Using a meta-schema, as #561 proposes, doesn't work well for `format` values because `enum` is difficult to combine.  The typical `allOf` used to compose vocabularies produces the intersection of `enum`s rather than the union.   But `anyOf`, which would work, would often produce unexpected behaviors otherwise.

Some other mechanism may be required.  Therefore this is filed in the future milestone as a question.  If we come up with a broadly supported proposal quickly, it can be added to draft-08, but otherwise it's fine as a follow-on in a later draft.

**Comment by ralfhandl** [comment]
Formats usually serve the dual purpose of a programming-language-independent code-generation hint for the recipient and a production/validation instruction for the sender or an intermediate validator, so pulling `format` out of validation seems to be the right direction.

Allowing vocabularies to define specific `format` values would certainly reduce the pressure for adding new formats to a central list. 

It would also remove the single point of reference for looking up existing formats and their meaning.

Unless that vocabulary mechanism is accompanied by a central "registry" or "repository" for format definitions.

The "endless stream of requests for standardized formats" just shows how important interoperability is.

**Comment by handrews** [comment]
> The "endless stream of requests for standardized formats" just shows how important interoperability is.

Agreed.  I think for a central list, we should look to the IANA registry model.  For now, we'll keep a small standard set in one of the major specification drafts.

But if vocabularies are identified by URIs, and we define some clear way for a vocabulary to define format values (and similar extensible value sets), then we can probably use vocabulary URIs with fragments to completely identify a format term.

**Comment by ralfhandl** [comment]
Sounds like a plan: 👍

**Comment by awwright** [comment]
The link relations IANA registry has a nice model, either:

* expert review for new entries; or
* anyone define a format by a URI within a namespace they own

Either form can be used by anyone.

**Comment by reitzig** [comment]
If valid values of `format` are not standardized, why should I ever use it? I don't know which validator a consumer of the schema may use while writing the schema!

At the very least, the standard should specify that unimplemented formats should cause a validation error. Otherwise, consumers will get false positives, which contradicts the purpose of using schemas.

**Comment by handrews** [comment]
@reitzig many formats are very expensive to validate, or even impossible to validate in a guaranteed way.  `email` is notoriously difficult (google "regular expression for email addresses"), for example.

The point of this issue is to allow people to say "Please only attempt to process this schema if you understand formats X, Y, and Z."  That's not possible now, but will be in the future.  That will allow those who are happy with best-effort (some people don't expect validation and just want the format to be shown as documentation anyway) to continue to use things as-is, while those who want strict conformance and fail-fast can guarantee that.

**Comment by reitzig** [comment]
I can see that using `format` to hint to parsers/mappers what to do is useful in itself, even if the validation phase ignores it.

Still, inconsistent behaviour concerns me. I don't want tests to fail if runtime is fine, or the other way around, or some clients accept bad replies while others don't. In my mind, it therefore makes more sense to _require_ that `format` not be checked during validation (except in a special mode marked as potentially incompatible), than to allow arbitrary choices in validators.

That's a very pessimistic perspective, of course. Systems that use only a single validation library are completely fine with an "intermediate" situation.

**Comment by gregsdennis** [comment]
> - Vocabularies with true are required- if not recognized, an implementation MUST refuse to to process a schema described by this meta-schema
> - Vocabularies with false are optional- if not recognized, an implementation MAY process a schema described by this meta-schema anyway, and ignore any keywords it does not recognize (which is how unrecognized keywords are handled now)

Just to clarify, implementations should still ignore unrecognized keywords, even if there are no "false" vocabularies, correct?

**Comment by handrews** [comment]
> Just to clarify, implementations should still ignore unrecognized keywords (i.e. keywords not defined by any of the vocabularies), correct?

Correct- this is covered in the PR, at least I think it is.  When in doubt, the PR takes precedence, I just know few people will slog through the PR (thanks again for doing that, btw!), so I summarized it a bit here.

**Comment by reitzig** [comment]
Do I understand correctly that for declaring that validation requires support for certain keywords for a certain (set of) schema(s), I have to write a new meta schema?

That strikes me as odd. The "have to" part, that is. It makes sense if I have a large number of similar schemas and the infrastructure to make a meta-schema available. However, in small use cases -- say I have a schema describing my log format which I use in automated tests -- it would be much more convenient to extend the vocabulary of a standard meta-schema _in the schema_.
Is that something that's on the table?

Regarding formats, a simple convention could be to have one (dummy) URL per format, for example

	https://json-schema.org/draft-08/vocabularies/formats/date-time

Furthermore, I'm thinking about a vocabulary that triggers a strict mode where we require support for all used keywords (imho a very natural choice):

	https://json-schema.org/draft-08/vocabularies/all-used

(_Is_ there something like a strict mode in the spec?)

**Comment by handrews** [comment]
@reitzig Meta-schemas are how implementations are told what behavior to apply, so yes, if you want to change the behavior, you have to change/write a new meta-schema.  This is unlikely to be changed because:

1.  Most people don't need to do this.  Whenever we figure out how we want to handle this, there will be a brief flurry of people writing new meta-schemas and then it will be pretty rare.
2.  We've made it a lot easier to write meta-schemas with `$recursiveRef`, so it's just not that big of a deal anymore.

In case it was not clear from my wording above: I'm not satisfied with any current solution to this problem, including the ones I outlined earlier.  I think that the correct solution involves having a real vocabulary definition format, which is _not_ going to make the cut for draft-08.  I posted this to make sure no one had a better idea before going ahead with punting this to draft-09 (technically it was never in the draft-08 milestone, but I had hoped to pull it in).

> a simple convention could be to have one (dummy) URL per format

The solution I proposed would allow that.

> triggers a strict mode where we require support for all used keywords

That's too magical of a behavior for something that is really a very narrow problem.  Most keywords are either supported or not, `format` and a very small number of others are exceptions.

**Comment by handrews** [comment]
As we've worked with the concept of vocabularies and further tried to figure out what to do with `format`, it's become clear that the keyword should really be replaced by multiple vocabularies focused on specific areas.  

For example, a date-time vocabulary could provide several keywords replacing the `date-time`, `date`, `time`, `duration`, etc. formats with more clarity and flexibility than `format` offers.  This vocabulary would presumably be quite easy to implement (lots of reliable, optimized libraries understand date and time issues), so would probably become widely supported.  Unlike with `format` where supporting easy formats gets bogged down in supporting hard formats.

We're not going to drop `format` unless and until such vocabularies emerge and prove popular.  But we're not going to spend time trying to accommodate keywords with extensible value sets either.  There's a huge pain and don't offer anything you can't do with separate keyword vocabularies.

Therefore, I'm closing this as irrelevant due to a change in direction.   For the current status of `format`, see the [draft 2019-09 release notes](https://json-schema.org/draft/2019-09/release-notes.html#format-vocabulary).

**Comment by sandrina-p** [comment]
> This vocabulary would presumably be quite easy to implement (lots of reliable, optimized libraries understand date and time issues), 

@handrews is there any library that supports `date` validation that you would recommend?
