### ISSUE TITLE
Add format "duration" 

### ISSUE THREAD

**Issue by ralfhandl** [json-schema-org/json-schema-spec#565]
Please add a format for durations in the format defined by ISO 8601 and cited by [RFC3339](https://tools.ietf.org/html/rfc3339#page-12) and [XML Schema 1.1](https://www.w3.org/TR/xmlschema11-2/#duration).

Example values:
* `P15DT1H22M1.5S` fifteen days, one hour, twenty-two minutes, one and a half seconds
* `P30D` thirty days
* `PT5M` five minutes

**Comment by awwright** [comment]
Since we've already got a bunch of other RFC3339 productions, I don't think this is unreasonable.

**Comment by handrews** [comment]
@awwright @ralfhandl PR welcome :-)
