### ISSUE TITLE
Properties order

### ISSUE THREAD

**Issue by mfulton26** [json-schema-org/json-schema-spec#571]
UI generation tools would benefit, I think, from having a way to specify the order of properties.

For simple cases, perhaps `properties` could be optionally defined as an array of objects where at a minimum each object has a `name` property:

```js
"properties": [
  {
    "name": "foo",
    "type": "string"
  },
  {
    "name": "bar",
    "type": "boolean"
  }
]
```

Alternatively a new keyword could be introduced, `propertiesOrder`:

```js
"properties": {
    "bar": { "type": "boolean" },
    "foo": { "type": "string" }
},
"propertiesOrder": ["foo", "bar"]
```

This keyword could also support patterns:

```js
"properties": {
    "bar": { "type": "boolean" },
    "foo": { "type": "string" },
    "num": { "type": "number" }
},
"propertiesOrder": [".*", "foo", "bar"]
```

**Comment by Relequestual** [comment]
Feel free to file that over at https://github.com/json-schema-org/json-schema-vocabularies/issues - Currently this repo is for core and validation. Neither specify any UI generation. There are a few efforts already looking at this outside of official JSON Schema channels, such as https://github.com/json-schema-form and https://github.com/mozilla-services/react-jsonschema-form

**Comment by mfulton26** [comment]
Okay, thank you for redirecting me. As I saw `readOnly` and `writeOnly` I figured this would be an appropriate place. If I wanted to suggest a `disable` and/or `hidden` keyword would that go over there too? Thanks.

**Comment by Relequestual** [comment]
@mfulton26 sorry if I seemed a little heavy handed. I hadn't even noticed `readOnly` and `writeOnly`...

I'd probably want to see some of those annotation keywords moved out of the validation spec... seems kinda weird they are there but have nothing to do with validation.

Any comments @handrews ? =]

**Comment by handrews** [comment]
@Relequestual the question of where the basic meta-data annotation keywords should live comes up regularly.  Once we decide on a vocabulary approach (#561) we'll have a better feel for what the impact of moving or splitting that vocabulary out would be.

Right now, we don't really have a definition of "vocabulary" (it roughly equates to "specification document", except when it doesn't), which makes it hard to figure out what to do with it.

That said, property ordering is less about annotating with data (like a description) or an interaction hint (like `readOnly` or `contentMediaType`) and more about how to display things, so it really does belong in the other repository with the UI vocab proposal.

**Comment by mfulton26** [comment]
I created https://github.com/json-schema-org/json-schema-vocabularies/issues/7. Thanks.
