### ISSUE TITLE
excludedProperties support would be benificial

### ISSUE THREAD

**Issue by barkermn01** [json-schema-org/json-schema-spec#582]
It would be good if we could get support for certain properties to be forbidden.

I was working with someone last night and found a use case where forbidden properties would be useful.
He was unable to disable `additionalProperties` however had 2 difference cases. in the same schema.

this was the end result
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "app_id"
  ],
  "oneOf": [
    {
      "properties": {
        "app_id":{
          "type": "string",
          "pattern": "^[0-9]{10}$"
        },
        "my_id": {
          "type": "string",
          "pattern": "^[0-9]{8}$"
        }
      }
    },
    {
      "properties": { 
        "app_id":{
          "type": "string",
          "pattern": "^[0-9]{10}$"
        },   
        "m_id": {
          "type": "string",
          "pattern": "^[0-9]{9}$"
        }
      }
    }
  ]
}
```

however his test payload caused it to validate against both test payloads.
Payload 1
```
{
  "app_id":"1234567890",
  "my_id":"12345678",
}
```
Payload 2
```
{
  "app_id":"1234567890",
  "m_id":"123456789",
}
```

Idealy there we should have a an exclusions list. `excludeProperties:["propertyName", "property2Name"]` so the inital schema could look like.

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "app_id"
  ],
  "oneOf": [
    {
      "properties": {
        "app_id":{
          "type": "string",
          "pattern": "^[0-9]{10}$"
        },
        "my_id": {
          "type": "string",
          "pattern": "^[0-9]{8}$"
        }
      },
      "excludeProperties":["m_id"]
    },
    {
      "properties": { 
        "app_id":{
          "type": "string",
          "pattern": "^[0-9]{10}$"
        },   
        "m_id": {
          "type": "string",
          "pattern": "^[0-9]{9}$"
        }
      },
      "excludeProperties":["my_id"]
    }
  ]
}
```
This would then allow for easier versions of Schema so if your building an API Endpoint that you then wish to upgrade as your new schema could be in the "oneOf" allowing `addditionalProperties` and still identify easily which one of the `oneOf`'s it is.

This could be added to the schema simply
` "excludedProperties": { "$ref": "#/definitions/stringArray" },`

*Example Specification definition*
```xml
<section title="excludedProperties">
    <t>The "excludedProperties" keyword functions as both an annotation (Section 3.3) and as an assertion (Section 3.2). While no special effort is required to implement it as an annotation conveying semantic meaning, implementing validation is non-trivial.</t>

    <t>Validation with "excludedProperties" applies only to the child values of instance names that do not match any names in "properties", and do not match any regular expression in "patternProperties".</t>

    <t>This keyword determines how child instances validate properties and do not directly validate the immediate instance itself.</t>

    <t>For all such properties, validation fails if the child instance contains a property by name supplied against the "excludedProperties".</t>

    <t>Omitting this keyword has the same behaviour as an empty schema.</t>
</section>
```

**Comment by handrews** [comment]
The syntax to forbid a property is simply to set its schema to the boolean `false` schema.  This works with `patternProperties` as well (and the tuple form of `items`, although the uses for that are rather less common).

So your example becomes:
```JSON
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "app_id"
  ],
  "oneOf": [
    {
      "properties": {
        "app_id":{
          "type": "string",
          "pattern": "^[0-9]{10}$"
        },
        "my_id": {
          "type": "string",
          "pattern": "^[0-9]{8}$"
        },
        "m_id": false
      }
    },
    {
      "properties": { 
        "app_id":{
          "type": "string",
          "pattern": "^[0-9]{10}$"
        },   
        "m_id": {
          "type": "string",
          "pattern": "^[0-9]{9}$"
        },
        "my_id": false
      }
    }
  ]
}
```

which does exactly what you want.

You may also be interested in #556 `unevaluatedProperties` proposed for draft-08, which is similar to `additionalProperties` but works across `oneOf`s like this in the way you probably wanted when you tried to use `"additionalProperties": false` here.  But it's best to use the least powerful tool in general, so for this simple case I'd stick with setting individual properties to `false` where needed.

**Comment by tgoraknath** [comment]
@handrews - let me evaluate above schema whether it fits all permutations. Here is the alternative I utilized to achieve all the permutations to work with.

{
  "$schema":"http://json-schema.org/draft-07/schema#",
  "type": "object", 
  "oneOf":[
        {"$ref": "#/definitions/v0"},
        {"$ref": "#/definitions/v0_1"}
      ],  
  "definitions": {
    "v0": {
      "type": "object",
      "required": ["accountCsn","contact_csn"],
      "properties": {
        "accountCsn": {"type": "string", "pattern":"^[0-9]{10}$"},
        "contact_csn": {"type": "string", "pattern":"^[0-9]{8}$"}  
      }  
    },
    "v0_1": {
      "type": "object",
      "required": ["accountCsn","oxygen_id"],
      "properties": {
        "accountCsn": {"type": "string", "pattern":"^[0-9]{10}$"},
        "oxygen_id": {"type": "string", "pattern":"^[0-9]{9}$"}  
      }  
    } 
  }
}

**Comment by handrews** [comment]
Those will also work with the `oneOf` because of how you have arranged the `"required"` fields.  Often that will be enough, occasionally you will need to forbid a property with a `false`.

**Comment by tgoraknath** [comment]
Hi @handrews, can we avoid duplicate entry of app_id definitions in the schema that you have shared?

**Comment by tgoraknath** [comment]
Hi @handrews, A small modification to the schema that u shared and works fine. however setting attribute to false is something I worried about bcz in ideal world we need to deal with simple and complex elements and developers can go wrong with complex structure and documentation, understanding can go wrong. `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["app_id"],
  "properties": {
    "app_id": {"type": "string", "pattern":"^[0-9]{10}$"} 
  } ,
  "oneOf": [
    {
      "properties": {
        "m_id": {
          "type": "string",
          "pattern": "^[0-9]{8}$"
        },
        "my_id": false
      }
    },
    {
      "properties": {    
        "my_id": {
          "type": "string",
          "pattern": "^[0-9]{9}$"
        },
        "m_id": false
      }
    }
  ]
}`

**Comment by handrews** [comment]
> Let me know if can reach you out on https://json-schema.slack.com.

please do!
