### ISSUE TITLE
Custom namespaced object properties

### ISSUE THREAD

**Issue by brettz9** [json-schema-org/json-schema-spec#587]
I've wanted to add some of my own meta-data within schema files but hesitated due to lack of a formal extension mechanism that would avoid future name clashes (and also allow schema tools the ability to selectively ignore these attributes while reporting errors with any other unexpected attributes).

Can some means be designed (akin to `data-*` attributes in HTML) to reserve a certain category of schema object properties which allows one to add properties without fear of clashes?

**Comment by handrews** [comment]
@brettz9 I believe you're looking for #561 (vocabulary support).  It's a more comprehensive solution to schema extensibility than reserving properties.  TL;DR: vocabularies let you declare what sets of keywords you are using, whether they are from the standard, your own extensions, or a third party's, including both specific keywords and keyword naming patterns.

Informally, we're exceedingly unlikely to break the camelCase with initial lowercase letter (or, for core keywords, initial `$`) convention, so basically anything that doesn't follow that, including anything with hyphens, is safe.
