### ISSUE TITLE
Rel JSON Pointer: How to determine the base pointer?

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#597]
As far as I can tell, the only indications of how this works are a bit in the [introduction](https://tools.ietf.org/html/draft-handrews-relative-json-pointer-01#section-1):

> identification of relative locations from within the document.

and later in the section on [evaluation](https://tools.ietf.org/html/draft-handrews-relative-json-pointer-01#section-4):

> Evaluation of a Relative JSON Pointer begins with a reference to a value within a JSON document

Do we need any wording along the lines of "Applications using Relative JSON Pointers MUST specify how to determine the initial reference."?  We do specify this for each use of relative pointers in the JSON Hyper-Schema spec.

**Comment by handrews** [comment]
I can't think of any particularly useful default base (unlike URI references, which provide an algorithm for determining the current base).  I suppose there could be the case of references within the same document starting from the location of the pointer, but it might be better to just always have it be explicit?

If the default base is the pointer's location, would that mean that a pointer of `0` would resolve to the object property or array index containing the pointer?  I suppose if the document is just a pointer it would resolve to the whole document, but in that case there are no possible other targets for the pointer so it wouldn't make sense to do anyway.

AFAIK we don't have a need for this, but since we'll be publishing another draft due to the JSON RFC update, might as well figure it out now.

**Comment by Relequestual** [comment]
There's a related SO question that I've pingged @handrews with, so I'll wait to see his thoughts on that before making further comments.

**Comment by handrews** [comment]
@Relequestual was there any outcome from that SO question?  I no longer remember what it was.

Given that the spec says:

>  Evaluation of a Relative JSON Pointer begins with a reference to a value within a JSON document

clearly you need to get that initial reference from somewhere.  And i don't think it's the responsibility of the Relative JSON Pointer spec to say where, since that is highly application-specific.

Unless there was some clear need from that SO question, I plan to close this out without further action.
