### ISSUE TITLE
v6 hyper-schema: propertyLinks

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#60]
Originally written by @geraintluff at https://github.com/json-schema/json-schema/wiki/propertyLinks-(v5-proposal)
### Proposed keywords
- `propertyLinks`
### Purpose

Currently, we can describe the format of a parent object (with title/description/etc.), and we can describe the format of a child instance (with title/description/etc.) but we cannot describe the _relationship_ between the two.
##### Motivating example

For instance, say you have an instance representing a programming project:

``` json
{
    "title": "AwesomeNet",
    "author": {
        "name": "Petra the Programmer",
        "homepage": "..."
    }
}
```

When describing the format for this instance, you can easily write a schema for the parent format:

``` json
{
    "title": "Programming project",
    "description": "A description of a programming project",
    "type": "object",
    ...
}
```

... and for the child format:

``` json
{
    "title": "Person"
    "description": "A representation of a person",
    "type": "object",
    ...
}
```

These are completely accurate descriptions of the _format_, but there is no way to express anything about the relationship between the two - considered on its own, the entry in `"author"` is indeed a "Person", but its relationship to the parent is more than that.

One current hack is to extend the "Person" format, so you can give it a title/whatever.  However, that isn't really accurate - nothing has changed about the format at all, it's the parent-child link that's the interesting part.
### Values

The value of `propertyLinks` would be an object.  The values would themselves be objects, containing zero or more of the following properties:
- `title` - a name for the parent/child relationship
- `description` - a more detailed description of the parent/child relationship
- `rel` - a link relation (URI) representing the parent/child relationship
### Example

Extending the "Motivating example" above:

``` json
{
    "title": "Programming project",
    "description": "A description of a programming project",
    "type": "object",
    "properties": {
        ...,
        "author": {"$ref": "/schemas/user"}
    },
    "propertyLinks": {
        "author": {
            "title": "Author",
            "rel": "http://schema.org/author"
        }
    }
}
```
##### Duplicated keys

In that example, you end up listing `"author"` twice in the schema.

However, the alternatives are either an intermediate object (hard-to-read and not concise) or sticking extra info in the child schema (which requires ugly/awkward `allOf` extension, and still suffers from similar conceptual concerns to the existing workaround).

**Comment by handrews** [comment]
An alternative proposal would be to just use the existing LDO approach with a JSON Pointer fragment URI.  While slightly less clear, it has the advantage of putting all links, local or not, in the same format.  It also avoids the duplication problem.

**Comment by awwright** [comment]
This needs a really good example of why this would be useful.

If you want to express a relationship between the two, you should give the two instances URIs, then create a link using those URIs.

Is there ever a case where we don't want to give the instances URIs, but still allow software to see a relationship? That sounds really far-fetched

**Comment by handrews** [comment]
> Is there ever a case where we don't want to give the instances URIs, but still allow software to see a relationship? That sounds really far-fetched

Not that I can think of.

Are we agreeing on the solution here?  I meant something like:

```JSON
{
    "title": "Programming project",
    "description": "A description of a programming project",
    "type": "object",
    "properties": {
        "id": {"type": "integer", "minimum": 1},
        ...,
        "author": {"$ref": "/definitions/user"}
    },
    "links": [
        {
            "rel": "self",
            "href": "/projects/{id}"
        },
        {
            "title": "Author",
            "rel": "http://schema.org/author",
            "href": "#/author"
        }
    ]
}
```

Which I think says "There is a link from this instance at https://api.example.com/projects/12345 to an author at https://api.example.com/projects/12345/#/author"

Is that what you had in mind?  As much as I hate HTML analogies, I'll make one here- this is the equivalent of `<a href="#foo">link to foo</a>` and `<a name="foo">this is foo</a>`  (or `id` instead of `name` in HTML5).

**Comment by handrews** [comment]
@awwright , @Relequestual , anyone else:  Does anyone want to adopt this proposal?  @awwright and I are both against the proposed solution.  I commented on another approach but if that approach is needed or valid at all, it does not require any changes to the spec.

If no one speaks up within two weeks, I will close this issue.

**Comment by handrews** [comment]
It's been more than two weeks since this was put up for adoption with no takers, and two of us against the proposal.  Closing.
