### ISSUE TITLE
Link header examples are not correct to RFC-5988

### ISSUE THREAD

**Issue by sazzer** [json-schema-org/json-schema-spec#623]
The examples currently in draft-handrews-json-schema-hyperschema-01 are technically wrong as compared to RFC-5988.

The example in Section 9.1 shows a Link header of:
```
   Link: <https://schema.example.com/entry> rel=describedBy
```

Per RFC-5988, the link params should be semi-colon separated and their values should be quoted. Thus that should be:
```
   Link: <https://schema.example.com/entry>;rel="describedBy"
```

Additionally, there is the link param "type" to give a hint as to the media type of the link target. Using that would make the result:
```
Link: <https://schema.example.com/entry>;rel="describedBy";type="application/schema-instance+json"
```

**Comment by dlax** [comment]
Semi-colon is indeed missing. But it seems to me (from https://tools.ietf.org/html/rfc5988#section-5) that link parameter's value (especially relation-type) does not require quotes except when they contain special characters like ";" or "," (and perhaps spaces); we could quote them for better consistency though.
