### ISSUE TITLE
Quantify issues people face around resolving $ref against $id

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-spec#630]
During my attempt to resolve "$ref is delegation", I falsly concluded by #514 (mainly the title) that I should also expand the explanation of how resolution works.

@handrews noted in https://github.com/json-schema-org/json-schema-spec/pull/585#issuecomment-399600275 after an off-github discussion, that I should collate the StackOverflow questions I had seen regarding `$ref` resolution to demonstrate the use case that requires modification to $ref resoultion language in the spec, if any.

> One to address any clarifications on the process of resolving $ref against $id, which is not significantly impacted by #514/#523. @Relequestual I could see this as going back to an issue or just becoming a new PR. Since you have noted that there are a lot of Stack Oveflow questions motivating this work, I would find an issue linking to some typical SO questions to be very helpful in understanding what you're trying to accomplish. I think my confusion over some of your points is due to lacking this context.

The expected resolution of this issue is the creation of another issue, which will reference this one.

As this issue is not asking and specifically does not want comments from people on issues around $ref, it will be locked.

I kinda feel this issue is just for my own personal tracking purposes.

**Comment by handrews** [comment]
@Relequestual any update on this?  If there's anything going into draft-08 it needs to happen very soon.

**Comment by awwright** [comment]
I'm having a difficult time trying to figure out what this issue is asking, in any event.

**Comment by handrews** [comment]
@awwright IIRC, @Relequestual wanted to rewrite part of the text around `$id` and `$ref` while he did the "`$ref` is delegation" change, but I both found the rewrite more confusing than the original (which had barely been published 3 months ago after a large rewrite with many added examples anyway), and thought it was unrelated to the delegation change.

So I asked him to remove it and file an issue to track figuring out exactly what is unclear and needed, rather than just re-re-re-writing it again.  I think it would be at least the fourth time.

**Comment by handrews** [comment]
I haven't seen any complaints or confusion that point to any particular spec wording problem (as opposed to in the past, where specific complaints led to the rewrite in draft-handrews-json-schema-01).  People show up confused on slack, but for those people adding more tutorial to Understanding JSON Schema seems like a better approach to me.  But @Relequestual thought there were some specific things to dig up somewhere.

**Comment by Relequestual** [comment]
Thanks for nudging this issue.
I think I wanted to just look back over a few SO issues and pull out examples of where people found it confusing. The result would live on the UJS site now for sure, and maybe linked to from the main site... I dunno.

I have zero bandwidth on this, and more people come to slack now, so I'll go ahead and close it.
Feel free to open an issue on the UJS site repo and link to this one if anyone would like.
