### ISSUE TITLE
How to validate if a schema has no "type"-field?

### ISSUE THREAD

**Issue by pboettch** [json-schema-org/json-schema-spec#631]
I'm trying to fully absorb the current json-schema-spec. This question is about a part which I thought I understood already, but in fact, no, not really. I think this kind of question has already been answered several times, but I was not able to find anything - probably due to wrong keywords.

I understood that (one of) the `type` imposed by the schema has to match the of the instance. Otherwise validation fails. 

But it seems the other way around. It is the type of the instance which makes the validation fail if it is not listed or set in the type-field of the schema - if the type fields is set.

What if the type-field is not set? 

Imagine the following schema-snippet:

```json
{
  "properties": {
    "bar": { "type": "string" }
   },
   "minimum": 10
}
```
Am I right that the following instances would validate against this schema:

Object:
```json
{"bar":"text"}
```

Number:
```json
11
```

String:
```json
"hello World"
```

Is the last instance is valid because it the type-field is not explicitly limited to numbers and objects?

Is this behavior new since draft4?

**Comment by pboettch** [comment]
Making it clearer works by examples. In fact I stumbled upon this behavior when looking in the draft7-test-suite. My draft-4 validator does not work this way, however it passed all required draft4 tests from the suite.

I assume the same applies to boolean-logic keywords (AllOf, etc), they can be combined with other non boolean-logic-keywords... Yeah I think I get it, lot of freedom in designing a schema.

**Comment by Julian** [comment]
The draft 7 and draft 4 test suite is essentially identical here.

Which part of this does your implementation not satisfy?

**Comment by pboettch** [comment]
I'm in the middle of changing my implementation from an interpreted to a processed/compiled approach and some knots in my heads made me doubt some things I already understood.
