### ISSUE TITLE
Name suggestion for patternProperties

### ISSUE THREAD

**Issue by fkorotkov** [json-schema-org/json-schema-spec#634]
It will be nice to have a way to list some possible options for a pattern property so an IDE can suggest these options for completion.

**Comment by handrews** [comment]
@fkorotkov could you provide some examples of what you mean?

**Comment by fkorotkov** [comment]
Sure! For example in my case, I was working on a schema for Cirrus CI: https://github.com/SchemaStore/schemastore/pull/488

There I have such pattern property:

```json
"patternProperties": {
  "(.*)task": {
    ...
  }
}
```

Which means there can be multiple tasks defined. Tasks like `build_task`, `test_task`, `lint_task`, `deploy_tasks`. And 99.9% of the users would use only these 4 names.

I would love to add such suggestions within a schema so editors can use them and do suggestions.

```json
"patternPropertyExamples": ["build_task", "test_task", "lint_task", "deploy_task"],
"patternProperties": {
  "(.*)task": {
    ...
  }
}
```

I created this issue just for a record of my use case. Maybe some other people will find it useful too. It's  not something very important, but can definitely be useful for schemas that use `patternProperties`.

**Comment by fkorotkov** [comment]
Is there an issue to support `keywords`? Didn't find with a quick search. I'll close this issues and link to the keywords one.

**Comment by gregsdennis** [comment]
The primary one would probably be #602 right now.  It links to a bunch of other issues that relate to it.

**Comment by fkorotkov** [comment]
Thank you, all! Closing this issue. Will watch #602
