### ISSUE TITLE
"single line" format ?

### ISSUE THREAD

**Issue by kapouer** [json-schema-org/json-schema-spec#637]
This is very naive proposal but it makes sense for me, so why not for the spec...
format: singleline
pattern: `/^[^\n\r]*$/`

The idea is to be able to tell when a string is supposed to not be a multiline string.

**Comment by handrews** [comment]
This should just be done with `pattern`, and if you want to name it, you can make a definition under `definitions` (current) or `$defs` (future).  `format` is for things that have semantic meaning that isn't apparent from a regex (how many of us would recognize an email address regex if we saw one? they're absurdly complex if they're even useful at all).
