### ISSUE TITLE
if/then/else & error messages

### ISSUE THREAD

**Issue by delmu** [json-schema-org/json-schema-spec#638]
Hi experts,

I would like to customize some error message in the if/then/else logic. But it seems that ajv is not support that or I make some mistakes. Does anyone know how to do it? Thanks in advance.

Following is a example... 

Example: 

const schema_motor = {
  if: {
    properties: {
      dad_phone_number: {
        type: 'number',
      }
    },
    errorMessage: {
      properties: {
        dad_phone_number: 'Dad's phone number is incorrect.'
      }
    }
  },
  then: true,
  else: {
    properties: {
      mum_phone_number: {
        type: 'number'
      }
    },
    errorMessage: {
      properties: {
        mum_phone_number: 'Mum's phone number is incorrect.'
      }
  }

@epoberezkin

**Comment by Relequestual** [comment]
There is currently no standard for outputting error messages, or defining error messages.
For discussion on adding this to the spec, please follow https://github.com/json-schema-org/json-schema-spec/issues/396

For questions regarding the ajv implementation specifically, please file an issue on the associated project at https://github.com/epoberezkin/ajv/issues

Thanks.
