### ISSUE TITLE
Add `description` (peer to `title`) to all schemas

### ISSUE THREAD

**Issue by retrosight** [json-schema-org/json-schema-spec#640]
It would be very nice to have a brief human readable description for each of these.

http://json-schema.org/draft-08/hyper-schema-output
http://json-schema.org/draft-08/hyper-schema#
http://json-schema.org/draft-08/hyper-schema#
http://json-schema.org/draft-08/schema#

**Comment by handrews** [comment]
We decided to remove the property descriptions a while back because the spec is normative, while the schemas are not.  And the minor differences in wording (and drift over time) was confusing people.

**Comment by retrosight** [comment]
Sounds good.
