### ISSUE TITLE
Make ordering of keys consistent

### ISSUE THREAD

**Issue by retrosight** [json-schema-org/json-schema-spec#641]
It's the little details that matter in life -- we love consistency, so let's bring it to all of the schemas.

One example of many...

```
"$schema": "http://json-schema.org/draft-08/hyper-schema#",     "$id": "http://json-schema.org/draft-08/hyper-schema-output",
"$id": "http://json-schema.org/draft-08/hyper-schema#",         "$schema": "http://json-schema.org/draft-08/schema#",
"title": "JSON Hyper-Schema",                                   [Missing]
...
```

**Comment by awwright** [comment]
It would seem to me that, if order matters, `$schema` should go first, since that's the key that gives all the others their meaning.

... with the exception of $id, so I could be persuaded otherwise.

**Comment by gregsdennis** [comment]
While I understand the motivation of this (and agree somewhat), it feels weird to me that the sequence of keys in a key-value pair collection matters.  The entire purpose of having the key-value paradigm is to get around requiring order and allow easy access to the values.

Furthermore JSON declares that while arrays are to be considered "ordered" (or, more properly, "sequenced"), objects are not.  This may cause confusion with authors and consumers.

---

@retrosight are you asking for this to help with schema equality comparisons, or do you have another purpose?

**Comment by gregsdennis** [comment]
See also #538 & #475

**Comment by retrosight** [comment]
Yes, I understand order does not matter to the computers. ;-) I'm looking for the consistency to aid learning while reading between different schemas. The reader doesn't have to context switch the order.

**Comment by Relequestual** [comment]
I have no issue with ordering the meta schemas we provide.
They ARE intended to be read by humans, and so we should make that as easy as possible, where possible.

PR welcome.

**Comment by handrews** [comment]
I'm fine with this- order (as it relates to our published meta-schemas and whatnot) should be:

1. `$schema`
1. `$id`
1. `$vocabulary`
1. `$recursiveAnchor`
1. `$title`
1. `$ref`, `$recursiveRef`, or an `allOf` of those things
1. `type`
1. type-specific validation and applicator keywords
1. `default` and `examples`

I just updated all of the meta-schemas in a PR.  I'm not 100% sure I got all of them in the same order, it's late so I'll look at it tomorrow or anyone else feel free to comment on PR #714
