### ISSUE TITLE
Can you define subschemas and recycle parent schemas?

### ISSUE THREAD

**Issue by adjenks-p** [json-schema-org/json-schema-spec#668]
Is it possible to specify a schema and then specify another schema which uses that schema as a parent class? For example, a particular property could be labeled a slot in the parent and the child schema could be defined as a Parent with a list of variations in particular slot properties? Or is there another way to achieve a similar effect?

The reason I am asking is because I was trying to create a general purpose "HTTPResponse" schema for an HTTP request responses. It might contain a data property, which can contain anything.
I was hoping I could define a schema, let's say a "Human" and then define a "HumanResponse" where I would specify `parentSchema: "HTTPResponse"`, and then specify `"slots": {"data": "Human"}`

If some sort of feature like this does not exist and if I wanted to define a Mouse, Cat, Dog and a Human schema, I would have to describe everything about what it means to be a mammal four times.

I know that I could define a Leg schema, and a Tail schema and an Eye schema and then create a Cat schema and specify an array of "BodyParts" and specify that it must contain, a tail or legs or whatever else, but I cannot seem to see a way of inheriting features and specifying variants.

In the same way that JavaScript has a prototypical inheritance model instead of a class based model, perhaps I just don't understand how to do what I am trying to accomplish and there is another way? Or is it impossible to create a Dog by defining it as a subschema of a Mammal schema, without typing out the whole mammal schema all over again?

**Comment by handrews** [comment]
@adjenks-p have you tried something like this:

```JSON
{
    "definitions": {
        "HTTPResponse": {
            "type": "object",
            "required": ["data"]
        },
        "ArrayDataHTTPResponse": {
            "allOf": [
                {"$ref": "#/definitions/HTTPResponse"},
                {
                    "properties": {
                        "data": {"type": "array"}
                    }
                }
            ]
        }
    }
}
```

Note that JSON Schema is a constraint system, not a class definition system.  In a class system, the empty class has no data and no functionality.  In a schema constraint system, the empty schema (`{}` or `true`) allows **anything**.

This is why the example above uses `"required": ["data"]` in the "HTTPResponse" schema and does not bother to define it in `"properties"`.  You specified that the generic HTTP response schema can contain anything, so we don't need to constrain it in "HTTPResponse", we just need to ensure that it is present.

Later, in ArrayDataHTTPResponse, we constrain "data" to be an array.

There are code generation tools based on JSON Schema (you can find links to some on json-schema.org), and many of them have some way to use `allOf` to implement inheritance, but it's usually awkward.  We hope to add a code generation vocabulary in the future that would build on the validation vocabulary but be more suitable for defining data structures.  Many validation keywords are too ambiguous to be easily used for code generation.

**Comment by adjenks-p** [comment]
Oh wow! `allOf`... That makes sense. That does indeed seem like an effective but awkward way to describe an inheritance model. It's not beautiful but it will do for now. I understand it isn't technically meant to be a class/inheritance model, but I believe JSON-Schema should be able to represent any data model without excessive redundancy. This seems to sort of achieve that.

**Comment by handrews** [comment]
@adjenks-p Yeah it basically gets close enough that you can kinda duct-tape over the rest of it.  Like I mentioned, we're aware of the mismatch and hope to add a new keywords set to fill in the gaps properly.

Sit it sounds like you got what you needed for now, I'm going to close this, but feel free to re-open if you were not done.

**Comment by drdavella** [comment]
@adjenks-p thanks for the question, and @handrews thanks for the useful example. Do you have an issue or a document that outlines the ideas you have about future keywords?
