### ISSUE TITLE
Downloading $ref'd schemas

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#68]
Section 7 of the current draft of JSON Schema Core on 'master' reads:

> The URI is not a network locator, only an identifier. A schema need not be downloadable from the address if it is a network-addressible URL, and implementations MUST NOT assume they should perform a network operation when they encounter a network-addressible URI.

This positions the `$ref` URI as analogous to the `profile` URI.  That feels correct- you should be `$ref`'ing the canonical URI, which is subject to the exact same considerations as the canonical URI used in `profile`.

However, I need to be able to specify download locations when a user-agent encounters a previously unknown canonical URI.  What is the equivalent of `describedBy` for `$ref` URIs?

**Comment by awwright** [comment]
I'd think it's safe to say that if you downloaded the schema, then any $ref links in the document can be downloaded too. Same as HTML.

Saying "MUST NOT assume" (as if you can get permission to violate the MUST NOT requirement level) _is_ weird though. Maybe just make that whole phrase "SHOULD NOT" or "SHOULD NOT assume"

**Comment by handrews** [comment]
@awwright I would be more comfortable with SHOULD NOT.  I think what I'm looking for is "It's OK for a schema author to *not* make this downloadable, as that does not break the spec, but it's also OK for an implementation to try downloading it, as that is not an abuse of the spec."  Does SHOULD NOT convey something like that, in your opinion?

Of course, whoever owns the server can consider a user-agent that keeps downloading all the things to be bad and block them or whatever, as discussed in the general section on downloading schemas.  I don't think we're required to prevent bad behavior with the standard, we just need to write the standard such that a schema author/distributor can refuse to serve the schemas an still be in compliance.

This means that:

* If you are packaging schemas for deployment in a restricted environment like a secure datacenter, you need to package up all schemas that will be needed.
* All `$ref` URIs in such a case must be relative so that they do not need to change based on who is hosting the schema.  This was already true for schemas that may be hosted on multiple boxes, e.g. the multiple-product-instances-in-a-secure-datacenter scenario.

Does that make sense?  While it is a restriction on deployment, it does not seem entirely unreasonable- as you note, if someone wants to run a web site in a secure network they can't just pull in the HTML and then link to other stuff outside, they have to pull in the whole site/page/whatever.

**Comment by handrews** [comment]
Looks like this got fixed at some point- thanks!
