### ISSUE TITLE
Add JSON Schema media type to mime-db (as a custom type)

### ISSUE THREAD

**Issue by metacubed** [json-schema-org/json-schema-spec#680]
[jshttp/mime-db](https://github.com/jshttp/mime-db) has a PR process to register [custom media types](https://github.com/jshttp/mime-db#adding-custom-media-types).

Until the JSON Schema media-type is registered with IANA (#286), can we add an interim custom media-type with the extension `.schema.json`?

My primary motivation is to serve JSON Schema files directly from GitHub pages with the right media-type headers. @ethanresnick, this will also help json-api/json-api#975.

**Comment by jdesrosiers** [comment]
Closing in favor of https://github.com/json-schema-org/json-schema-spec/issues/1130.

We're working on it.
