### ISSUE TITLE
custom validator constraints

### ISSUE THREAD

**Issue by beyondcreed** [json-schema-org/json-schema-spec#694]
is there support for user defined validators (language neutral), in the validation schema so that values could be validated using custom rules instead of prebuilt constructs like (enum, const, pattern)?

e.g. use case where we need to validate email to make sure another email is not registered in the backend.

**Comment by gregsdennis** [comment]
I think your asking for custom keywords, which is covered by [`$vocabularies`](https://github.com/json-schema-org/json-schema-spec/pull/671). It basically lets users define their own keywords and add them to the implementation via some sort of plug-in mechanism (whatever makes sense for the implementation).

**Comment by handrews** [comment]
@beyondcreed this is one of the main features of the forthcoming draft (maybe in January if the holidays aren't too distracting?  I'd intended to publish it in October but... um... life and stuff).

The main PR is up for review right now- #651.  It is mostly about how an implementation would recognize that you are using a custom vocabulary (set of one or more custom keywords), and potentially load a plugin to handle it.  There will be enough in the next draft to test this out, but there are a number of ideas that we are not pursuing yet as we want to see if/how people use the initial features.

You can see all issues and PRs for this at https://github.com/json-schema-org/json-schema-spec/labels/vocabulary

**Comment by handrews** [comment]
@gregsdennis hah! jinx

**Comment by handrews** [comment]
@beyondcreed Doing things with a "back end" is outside of the general scope of JSON Schema, because not all uses of JSON Schema involve network communication.  But in theory you could probably make a custom keyword of some sort that works in the context of back-end communication.  That sort of thing has always been a bit controversial, but one reason to add vocabulary support is so that people outside of the standards group can experiment with more approaches.

**Comment by gregsdennis** [comment]
@beyondcreed what implementation are you using? I wrote Manatee.Json which currently allows you to add custom keywords in a way similar to what `$vocabularies` does, and I believe AJV does as well.  You can play around with that too see if you can create a keyword that does what you need.

**Comment by beyondcreed** [comment]
> @beyondcreed Doing things with a "back end" is outside of the general scope of JSON Schema, because not all uses of JSON Schema involve network communication. But in theory you could probably make a custom keyword of some sort that works in the context of back-end communication. That sort of thing has always been a bit controversial, but one reason to add vocabulary support is so that people outside of the standards group can experiment with more approaches.

@handrews backend was just an example. I understand the definitions remain language, network or implementation neutral. However I strongly feel that there should be some way of saying how field is to be processed or handled using custom rule, instead of pre-built constructs you have now. I'll look into custom keywords @gregsdennis. I am developing several light weight schemas targeted specifically towards REST, web components and so on. It seems there is two choices, I can continue with custom keywords and extend the schema or define a brand new spec. Thanks.

**Comment by handrews** [comment]
@beyondcreed did you look at the `$vocabulary` PR that I linked?  Do you understand that it is about supporting custom keywords?  Technically custom keywords have always been allowed, just somewhat awkward to work with before now.

**Comment by beyondcreed** [comment]
@handrews have not looked yet, but I will. I understand that custom keywords have always been allowed, but as alluded to in previous post, I still strongly feel that custom validators/handlers should have been baked in the validation core, since we already have primitive types such as pattern, etc.

**Comment by handrews** [comment]
@beyondcreed Please take a look at what we are doing before lecturing us on what we should do, or particularly what the project already should have done.  We are a volunteer effort with a complex history, and telling people that you think they've been doing a bad job is not an effective way to get your requests prioritized.

**Comment by beyondcreed** [comment]
@handrews not lecturing anyone or demanding anything, but simply alluding to what I feel should have been added. If you feel it's not a priority or something that should not be done at this time that is ok with me. just don't over react to feedback from someone who is trying to provide you with one.
