### ISSUE TITLE
Should unknown keywords be collected as annotations?

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#698]
Assuming you support annotations (which is related to what output format(s) you support, now that I think of it), should unknown keywords be collected as annotations instead of ignored?

I think we will see more annotations (we've had several requested that don't clearly meet the significance criteria to be added to the standard), and it's an easy default behavior to add.

I don't feel strongly about this, just wondering if this is a sensible default option.

**Comment by gregsdennis** [comment]
If this is the direction you want to go, then why have annotation keywords at all?

**Comment by pboettch** [comment]
While preparing support for draft7 (and soon 8?) for my implementation I stumbled (again) across this test from the test-suite (draft7)

```JSON
{
    "tilda~field": {"type": "integer"},
    "slash/field": {"type": "integer"},
    "percent%field": {"type": "integer"},
    "properties": {
        "tilda": {"$ref": "#/tilda~0field"},
        "slash": {"$ref": "#/slash~1field"},
        "percent": {"$ref": "#/percent%25field"}
     }
}
```
In this schema we see the property `tilda` referring to `#/tilda~0field`, for example.

Why are the properties not inside `definitions`?
Is this what you call a "unknown keyword"? 
Is this an annotation? 
How should `tilda` be considered? 
Where in the current draft (7) is this case described?

In my schema-implementation I ignore these unknown keywords and thus the `$ref`-field is referencing to an unknown schema in my case.

(hoping this comment is not off-topic).

**Comment by pboettch** [comment]
I just saw that there is #687 ... My bad.

**Comment by gregsdennis** [comment]
So the benefit to having annotation keywords is that it constrains the acceptable values for them (e.g. objects aren't allowed in `title`), not that it produces an annotation.

That's fair. Just wanted the clarity.

**Comment by handrews** [comment]
That is not how I look at it at all, but I guess the outcome is the same?  I really don't know what to say here.

**Comment by plankthom** [comment]
I would say that it is an optional feature of a parser/validator implementation that should be configurable by the user.
If supported, a user can configure upfront any additional keywords that need to be collected as annotation, maybe with a reducer strategy (remove duplicates, ordering, first-by-priority, boolean aggregation, uniqueness per location/schema fragment/schema path) that is supported by (or plugged into) the parser/validator.

The parser/validator may by default collect all unknown keywords, but if it does, the user must be allowed to disable it. 
The parser/validator would probably reuse the infrastructure for generic support for vocabularies (e.g. as a runtime implicit vocabulary, with reducer mapping)

**Comment by shusson** [comment]
I can see generic annotations being useful for applications that need to generate different outputs. I'm imagining using the annotations as part of the generation logic, e.g this property should not be generated for a particular output.

**Comment by handrews** [comment]
@shusson yes, annotations are particularly useful for generative use cases.  And we expect a lot of extension vocabulary work to be done for generative cases, as support for that is currently weak.

So setting a default behavior of treating things as annotations would make such vocabularies work without needing a custom plugin.

Granted, generative tooling will read the schema without an instance so, but there are also uses of annotations with instances (e.g. the way most people end up using `format` since validation support is so unreliable).

**Comment by Relequestual** [comment]
I think we can RECOMMEND that unknown keywords are collected as annotations, and applications SHOULD provide a means to turn it on or off if they do collect annotations for unknown keywords.

**Comment by handrews** [comment]
Yeah, this makes sense.  I'd like to RECOMMEND that it be on by default, but perhaps allow that an implementation MAY decline to collect a very large value?  I think the main concern is that an unknown applicator being treated as an annotation could cause the output to balloon to problematic sizes.
