### ISSUE TITLE
[Question] Automatic fix of incorrect JSON files

### ISSUE THREAD

**Issue by scriptPilot** [json-schema-org/json-schema-spec#702]
Is there any node package to fix unconformities automatically, using schema defaults? Something similar like 'eslint --fix'? Many thanks for your ideas.

**Comment by Relequestual** [comment]
The intended use of `default` is for annotation purpose only, so there is no official or recomended library for doing what you want.

ajv can do this by changing a config option as documented: https://github.com/epoberezkin/ajv#assigning-defaults

**Comment by scriptPilot** [comment]
@Relequestual - Thanks for your answer. It seems AJV does "only" completion, but not fixing in that way.

**Comment by scriptPilot** [comment]
@Relequestual - In case anybody else is interested - I published my solution as package:
https://github.com/scriptPilot/json-schema-fix
