### ISSUE TITLE
[Question] Automatic documentation creation

### ISSUE THREAD

**Issue by scriptPilot** [json-schema-org/json-schema-spec#703]
Is there any node package which creates a markdown documentation file out of a schema?

**Comment by Relequestual** [comment]
@scriptPilot Hello.
I'm sorry that we don't have an issues template to explain how we wish people to use issues for this repo.
We would rather you don't ask general questions here, but please feel free to join us on Slack (Discussion link via the website).

The implementations page has a list of libaries or tools we know about http://json-schema.org/implementations.html

Thanks.

**Comment by scriptPilot** [comment]
@Relequestual - OK, I thought it was appreciated to raise questions here (saw hint on website). Thank you anyway.

![bildschirmfoto 2019-01-04 um 17 15 02](https://user-images.githubusercontent.com/19615586/50698232-a85d0600-1044-11e9-93ab-f534d901926a.png)

**Comment by scriptPilot** [comment]
In case anybody else is interested - I published my solution as package:
https://github.com/scriptPilot/json-schema-fix/blob/master/README.md#create-markdown-documentation-from-schema

**Comment by scriptPilot** [comment]
@Relequestual - In case anybody else is interested - I published my solution as package:
https://github.com/scriptPilot/json-schema-fix

**Comment by Relequestual** [comment]
Thanks for sharing @scriptPilot 
It looks like you have a very limited use case here. Your implementation only touches a very small subset of JSON Schema.
Still, hopefully it's useful for some peoples use cases =]
