### ISSUE TITLE
Have a property define the type in an array?

### ISSUE THREAD

**Issue by dbarros** [json-schema-org/json-schema-spec#709]
Given this example JSON:

```
{
  "type": "number",
  "values": [ 34, 42, 99 ]
}
```

Is it possible to define a schema that makes sure that the contents of the `values` array are of the type specified in another property (in this example `type`)?

Or: 

```
{
  "type": "string",
  "values": [ "hello", "world" ]
}
```

**Comment by awwright** [comment]
This issue needs a detailed description?

**Comment by ucarion** [comment]
Yes, this can be done, assuming you know in advance all of the types you're interested in:

```json
{
  "oneOf": [
    { "properties": { "type": { "const": "number" }, "values": { "items": { "type": "number" }}}},
    { "properties": { "type": { "const": "string" }, "values": { "items": { "type": "string" }}}}
  ]
}
```

If you wish to make additional constraints, such as having `type` and `values` be required, or force `values` to be an array in all cases, you can do so as well, but I hope this gets the idea across.

**Comment by handrews** [comment]
Answered 8 months ago, no further questions, closing.
