### ISSUE TITLE
"Understanding JSON Schema" guide is not reachable on the site directly

### ISSUE THREAD

**Issue by artyomsafronov** [json-schema-org/json-schema-spec#711]
I don't see a link to ["Understanding JSON Schema"](https://json-schema.org/understanding-json-schema/index.html) guide on the site. The only way to get it it is find it using Google. :)

**Comment by awwright** [comment]
There seems to be an open issue at the Website repository: https://github.com/json-schema-org/json-schema-org.github.io/issues/233
I'll close this out since it seems to be a duplicate, let me know if you've got any comments. (I'll have a PR for this in a moment too.)
