### ISSUE TITLE
Meta-schema for enum should allow empty and non-unique arrays

### ISSUE THREAD

**Issue by Zac-HD** [json-schema-org/json-schema-spec#717]
Currently, the meta-schemas for (at least) drafts 3, 4, 6, and 7 contain the following:

https://github.com/json-schema-org/json-schema-spec/blob/4e016d927839ed264f8d182abe9dc18a7e7a2c62/schema.json#L139-L144

However, the prose specification says:

> The value of this [i.e. the "enum"] keyword MUST be an array.  
> This array SHOULD have at least one element.  Elements in the array SHOULD be unique.

Validation therefore ought to allow schema authors to use empty or non-unique arrays, because the RFC 2119 definition of `SHOULD` explicitly permits ignoring such clauses after considering the circumstances.  Alternatively, the specification could replace `SHOULD` with `MUST` for the relevant constraints.

Possibly related to #618?  First reported at Julian/jsonschema#529, via [`hypothesis-jsonschema`](https://github.com/Zac-HD/hypothesis-jsonschema).

**Comment by handrews** [comment]
For such short documents, the number of meta-schema bugs is astounding :-/
(I say that having been responsible for a fair number of them, sadly).

Certainly related to #618 in that it would be fantastic if someone implemented #618.

I supposed we should update them for this (and I think `writeOnly` is missing from draft-07 as well, although I can't find a bug on it).  Which will annoy some people and please others- next draft we move to date-based versioning for meta-schemas (#714) so we can just add new versions with less confusion.  Hopefully.

The good news is that the meta-schemas are not normative, so feel free to edit your local copy.

**Comment by Relequestual** [comment]
@Zac-HD Correctness is good, but I have to ask, do you have a use case for this?
I can think of one, but it's not very strong.

**Comment by Zac-HD** [comment]
I have `hypothesis-jsonschema`, which takes a schema and produces documents that validate against it. I would like to generate schemas from the meta-schemas.

More generally though, the sole purpose of validation libraries is correctness. If we can't implement the spec that actually exists, why would anyone choose to use jsonschema?

**Comment by Relequestual** [comment]
Ah OK, yup that makes sense.

And yes, of course, I agree. I wasn't suggesting we don't fix the issue (I made a PR and it's merged already before my comment). I was more asking, should we change the spec to require this or not.

The meta-schemas are always informative as opposed to normative, so if the meta-schema doesn't line up with the spec, we have a problem, and should fix it.

**Comment by Relequestual** [comment]
@Zac-HD Given #739 is merged, can we close this issue as resolved? =D

**Comment by Zac-HD** [comment]
Yep, I'd certainly consider this closed by #739.  Thanks so much for your work!

**Comment by Relequestual** [comment]
Minor fix. More than welcome!
Feel free to come back the JSON Schema slack!
I also have a tip jar link on my github profile.

**Comment by Julian** [comment]
For breadcrumbs for future-us in case this ever comes up again (and I'm today finding this issue again during some livestream archaeology) --

This is something that *changed* in Draft 6, so only part of what's here is/was correct -- Specifically, in Draft 4 (and 3), the quoted language is *not* there, it indeed says MUST. From [§5.5.1.1](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.5.1.1):

> The value of this keyword MUST be an array.  This array MUST have at least one element. Elements in the array MUST be unique.

Compared to Draft 6 and later which have the [quoted language](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-6.1.2), i.e. SHOULD not MUST.

This seems to have changed in https://github.com/json-schema-org/json-schema-spec/commit/cf0ec7210011272f4e95f70f8c1374593e13c8c5

It somehow looked from the above like we'd concluded to change the Draft 3 and 4 metaschemas as well (to not contain `uniqueItems`) although at least as of today (2022/11/1) they still do, which is correct given the MUST language in those drafts. So... I think nothing is broken here, just leaving the above in case 5 years down the line I end up on this same issue :)

**Comment by erohmensing** [comment]
Looks like the proposed changes were made in #739, but the meta-schema listed on [json-schema.org](https://github.com/python-jsonschema/jsonschema/issues/529#issuecomment-1299173111) still contains the restraints. Wanted to put that on your radar since that is how I ended up in the rabbit hole that landed me on this issue!

**Comment by handrews** [comment]
@erohmensing those changes went into the meta-schema for the draft that changed the syntax.  The older drafts do not change, so their meta-schemas don't either.
