### ISSUE TITLE
How do I find the language of a particular JSON Schema?

### ISSUE THREAD

**Issue by epicfaace** [json-schema-org/json-schema-spec#728]
Sometimes, it is useful to know what language of a particular JSON Schema is, i.e., the set of values that it accepts.

For example, we have created a function [here](https://github.com/mozilla-services/react-jsonschema-form/pull/1194) called `schemaRequiresTrueValue` that decides whether _only_ `true` can be accepted by a particular JSON Schema. https://github.com/mozilla-services/react-jsonschema-form/pull/1194/files#diff-54fa674ce399e14c8ad3e72e64e2eed9R6

Is there a better, more standardized way to do this, for any arbitrary value?

**Comment by awwright** [comment]
It took me a few re-reads, but I take it the question is about how can we use JSON Schema to reason about the range of permitted values.

It's not one-or-two-lines simple, but it is somewhat straightforward via _set algebra_; consider that JSON Schema allows any value by default, then limits permitted values through assertions (i.e. keywords).

For what you're trying to do, it seems like you're on the right track. Go through all the keywords and keep track of how they modify the permitted range. If the permitted range ends up being a single value, then apply changes accordingly.

In more complicated cases, this first involves keeping track of the permitted types. "const", "enum", "type" (including their appearances inside "allOf") all limit the set of allowed types (object/array/string/number/boolean/null). If exactly one of the types is permitted, then look to see if there's only one permitted value within that type:

* object: additional properties not allowed & all properties have exactly one allowed value
* array: array length is exactly one value & all items have exactly one allowed value
* string/number/boolean/null: value exactly matches a single allowed instance

**Comment by awwright** [comment]
@epicfaace Does this satisfy you?

**Comment by epicfaace** [comment]
Thanks @awwright for the explanation, that makes sense! I'll try implementing the method that you described into an algorithm that transforms a JSON schema -> range of allowed values. Will follow up if I see any problems here.

**Comment by handrews** [comment]
Given that it's been seven months since the answer was accepted, I'm going to close this.

If we want to document some advice on this topic, that should be filed as an issue on the Understanding JSON Schema repository.
