### ISSUE TITLE
How to Mark a Node Deprecated In Json Schema ?

### ISSUE THREAD

**Issue by Sanjay007** [json-schema-org/json-schema-spec#730]
I want to know if Deprecated Support is available in JSON Schema , to mark any field as deprecated .

**Comment by awwright** [comment]
Also, I removed an "@" character so we're not tagging the poor user

**Comment by awwright** [comment]
@Sanjay007 Is https://github.com/json-schema-org/json-schema-spec/issues/74 the issue you're looking for?

**Comment by Relequestual** [comment]
Closing in favour of #74
