### ISSUE TITLE
Format attributes 

### ISSUE THREAD

**Issue by KayEss** [json-schema-org/json-schema-spec#732]
It isn't totally clear that a validator should ignore any format attribute it can't check/doesn't understand. The closest the wording comes is in 7.2:

> Implementations MAY add custom format attributes

I think this implies that the validator is likely to come across format attributes it won't understand, but it probably ought to be explicit. Maybe something like:

> A validator MUST ignore any format attribute which it cannot check.

Or under the other two points:

> they SHOULD ignore any attribute value they don't validate

**Comment by vearutop** [comment]
https://github.com/santhosh-tekuri/jsonschema/issues/21 here is a relevant issue for one of validators.

**Comment by handrews** [comment]
I'll deal with this at the same time as #646.
