### ISSUE TITLE
Question: Are multiple base type validation keywords allowed

### ISSUE THREAD

**Issue by maldimirov** [json-schema-org/json-schema-spec#733]
My question is twofold:
1. Is a JSON schema valid if it contains more than one base type validation keywords?
Example:
```
{
    "type": "object",
    "oneOf": [
        {"$ref": "#/definitions/reference1"},
        {"$ref": "#/definitions/reference2"},
    ],
}
```
My assumption is that it is allowed, since I have not found any restrictions in the documentation. And the meta-schema doesn't disallow it.

2. If the above is allowed, what should be the behavior of a validator when using such a schema?
My assumption is it should validate against all keywords independently. Is this what [keyword independence](https://json-schema.org/latest/json-schema-validation.html#rfc.section.3.1.1) means?

**Comment by awwright** [comment]
It sounds like you have the right idea. Lacking a better term for the
principle, we say the keywords are independent to mean the instance is
valid if all the keywords are valid, and the instance is invalid if at
least one of the keywords is invalid.

Is there a reason it might work differently?

I'm not sure what you mean by "base type", but there's no restriction on
how you may combine keywords (aside from the JSON limitation of no repeated
keys, in this case put the second keyword inside an allOf).

Have you tried it yet? Did you get what you expected?

**Comment by awwright** [comment]
Or: There's no two keywords that validate successfully when tested
separately, but fail validation when put together (there's a couple
well-noted exceptions for authoring convenience, but you can think of these
as one keyword with multiple arguments).

**Comment by maldimirov** [comment]
My idea, with the 'base types' is that, e.g. the `required` keyword is an extension for the `type: object` keyword. So `type`, `oneOf`, `enum`, `const` appear on the same level as `maximum`, `minimum`, `maxLength`, etc. but the latter are like extensions.*

> There's no two keywords that validate successfully when tested
separately, but fail validation when put together
This sounds right, and it's was not what I assumed. My idea is that if you have the schema below, it will evaluate any value as `invalid`.
```
{
    "type": "object",
    "const": 1,
}
```
My initial thought when I see it is: "that schema does not make sense, it must be invalid". And this brings me to two possibilities:
1. The schema is not a valid JSON schema and should be rejected by a validator implementing JSON schema.
2. The schema is valid. It's just badly written and all values will be rejected by a validator implementing JSON schema.

* I start to get the feeling that I am not right about this. Is it allowed to have a schema like `{"maxLength": 5}` without specifying a `"type": "string"`? And it would validate everything passed (objects, numbers, etc), except for strings that are longer than 5 symbols.

**Comment by awwright** [comment]
@maldimirov That's an example of two keywords that one _or_ the other always fails; there's no instance where both will be valid at the same time (and therefore, there's no instance that will be valid).

You can put together schemas that don't make any sense, including combinations of assertions that always fail. A validator isn't going to do anything special in this case, you're just going to have a difficult time finding a valid instance for it. But we don't assume it's wrong, sometimes you do want cases where a schema always fails, there's even a special schema that always fails (the boolean `false`).

> Is it allowed to have a schema like {"maxLength": 5} without specifying a "type": "string"? And it would validate everything passed (objects, numbers, etc), except for strings that are longer than 5 symbols.
No keywords are required; this is correct. Consider if you want to allow a value to be a string or a number; we wouldn't want "maxLength" to prohibit numbers, and we wouldn't want "minimum" to exclude strings; so permitted types are tested with a separate, third keyword.

**Comment by maldimirov** [comment]
@awwright thank you very much. My questions have been answered. Closing this.
