### ISSUE TITLE
Format byte and format binary

### ISSUE THREAD

**Issue by fmvilas** [json-schema-org/json-schema-spec#750]
Hi! Just saw that formats `byte` and `binary` don't exist in Draft 07. Are they going to be included in Draft 08? Is there any alternative I should consider aside from a custom format?

Thanks!

**Comment by gregsdennis** [comment]
The will not be included as defined `format` options for draft 8.

There are, however, `contentEncoding` and `contentMediaType`.  These are annotations and don't provide any validation (by the spec).  The implementation you're using may provide some additional functionality though.

**Comment by ucarion** [comment]
Just for clarity, what is meant by a "byte" or "binary" format? Could you give an example of JSON with such data?

**Comment by fmvilas** [comment]
Sorry, I should have made it clear. I meant the same meaning as in OpenAPI: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#data-types.

Not sure about binary example but byte is a common data type, especially byte arrays. I'm asking because I'm working on the [AsyncAPI specification](https://github.com/asyncapi/asyncapi) and we're planning to default to Draft 07 for schemas.

**Comment by handrews** [comment]
@fmvilas we've been working with the OpenAPI folks on getting their approach to `format` in alignment with ours, and with our `content*` keywords which are a much more flexible way to solve the byte/binary use cases.  The `alternativeSchemas` proposal for OAS 3.1 will obviously cover it- it's a little less clear what to do with the traditional OAS Schema Object, but that's generally true of the Schema Object.

There is at least one proposal to bring it into compatibility (or at least really, really close to full compatibility) with more recent drafts, but I don't think there's a lot of momentum behind that option.  `alternativeSchemas` is probably the thing to keep an eye on.

**Comment by fmvilas** [comment]
Thanks, Henry. Will keep an eye on those proposals. If everything goes well, JSON Schema Draft 07 will be the default schema format for AsyncAPI schemas.
