### ISSUE TITLE
Clarification: Does `unevaluatedProperties` know about properties evaluated on parent schemas?

### ISSUE THREAD

**Issue by rjmill** [json-schema-org/json-schema-spec#765]
The section on `unevaluatedProperties` says that its behavior is determined by looking at the "annotation results that apply to the **instance location** being validated."

https://github.com/json-schema-org/json-schema-spec/blob/3c0849506fdf4886762006f08229f8232f8608cb/jsonschema-core.xml#L2366-L2370

As I read this, the validation of `unevaluatedProperties` needs to wait until any parent schemas that apply to the same instance location have been validated (with the exception of their `unevaluatedProperties`.

Is that the intention?

For example, if I have the following JSON schema:
```
{
  "properties": {
    "propOne": true
  },
  "allOf": [
    {
      "properties": {
        "propTwo": true
      }
    },
    {
      "properties": {
        "propThree": true
      },
      "unevaluatedProperties": false
    }
  ]
}
```
and use it to validate this instance:
```
{
  "propOne": "foo",
  "propTwo": "bar",
  "propThree": "baz"
}
```

Is that going to pass, since "propOne", "propTwo", and "propThree" are all getting evaluated at the same instance location?

**Comment by handrews** [comment]
No.  A schema object's results may only depend on the keywords in that schema object (including applicators, whose results come from their subschema(s)).  A schema object's result can never be affected* by parent or sibling schema objects.

*aside from how `$id` and relative `$ref` values are resolved, but that is not directly part of producing the validation or annotation results.

There is nothing special about `unevaluatedProperties` in this regard.

The way to use `unevaluatedProperties` is always to put it as far out/up as possible.  You pretty much never want to put it in a schema intended for re-use.  But when you reference a bunch of re-usable schemas, *then* you apply `unevaluatedProperties` on top of whatever combination you referenced.

**Comment by rjmill** [comment]
Ah, that makes sense. Thanks for the quick/clear response!
