### ISSUE TITLE
Clarify: all applicators collect annotations, including "contains"

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#768]
As noted in #766, we need to emphasize how applicators and annotation collection works, in particular that an applicator like `contains` does collect annotations, which means that when annotation collection is enabled, you cannot short-circuit the evaluation.  I think we note this with `anyOf` but not `contains`.  Those are the only two applicators that combine validation results with OR and could therefore be short-circuited when not collecting annotations.

**Comment by gregsdennis** [comment]
**All** annotations? What about `not`? It's been made clear that it will _never_ return annotations due to its nature.

**Comment by handrews** [comment]
@gregsdennis annotations are still dropped whenever validation fails (and it's impossible to evaluate `not` without either failing the subschema, before `not` passes, or passing the subschema, in which case `not` inverts the validation result to fail)- this is a note to myself to fix a thing, don't treat it as spec.  NOTHING IS CHANGING HERE.

**Comment by handrews** [comment]
@gregsdennis ok apparently I'm a lying lier who lies because `contains` currently says it does not collect annotations 😮 

I'm 99% sure that is because we didn't have any sort of output format when I first wrote the spec for that keyword, and it wasn't clear how to make use of them if they were collected.  That is no longer the case, so I'm writing the PR to change it to collect annotations and be a "normal" applicator.

We can debate whether that is the right option on the PR 😄

**Comment by karenetheridge** [comment]
clerical error? This issue is in milestone draft-09, but the PR that closed it is in milestone draft-08 (which maybe should be subtitled `".. (2019-09)"`).
