### ISSUE TITLE
writeOnly missing in draft-07?

### ISSUE THREAD

**Issue by jackwootton** [json-schema-org/json-schema-spec#770]
Why is the `writeOnly` property missing from http://json-schema.org/draft-07/schema?

`readOnly` is defined:

```json
"readOnly": {
    "type": "boolean",
    "default": false
},
```

Both `readOnly` and `writeOnly` are included in the vocabulary: https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-10.3

**Comment by Relequestual** [comment]
We will get that fixed! Thanks!

**Comment by Relequestual** [comment]
[x] checking out the draft-07 branch of the spec repo, and fixing the problem there with a PR
[] checking out the master branch of the web site repo, updating the draft-07 submodule, and committing that and pushing the result

**Comment by Relequestual** [comment]
I comitted directly to the branch rather than making a PR for the draft-7 branch. Oops.
Given it's SUCH a minor change, guess that's OK.
I'll make sure I do a PR for the site... =]

/cc @handrews

**Comment by handrews** [comment]
@Relequestual all good!  Thanks for commenting on it here.

Since it's just a submodule update I don't think you need a PR on the web site repo- I'm not sure that even works.  Happy to review one if it does work, but feel free to just push the submodule change if you'd like.

**Comment by philsturgeon** [comment]
@Relequestual bump :D

**Comment by handrews** [comment]
PR was merged and deployed- thanks, @Relequestual !
