### ISSUE TITLE
Standardize handling of overlapping defaults

### ISSUE THREAD

**Issue by epicfaace** [json-schema-org/json-schema-spec#786]
We've been working with handling defaults in react-jsonschema-form and the logic seems more complicated than one might initially expect. https://github.com/mozilla-services/react-jsonschema-form/pull/1376

Here are some examples of the scenarios we've come across:
- Imagine your schema is:
```
{
          type: "object",
          default: {
            level1: { level2: ["root-default-1", "root-default-2"] },
          },
          properties: {
            level1: {
              type: "object",
              properties: {
                level2: {
                  type: "array",
                  items: [
                    {
                      type: "string",
                      default: "child-default-1",
                    },
                    {
                      type: "string",
                    },
                  ],
                },
              },
            },
          },
        }
```

Then the default value should (probably, intuitively) be `{level1: {level2: { ["child-default-1", "root-default-2"] } }` instead of `{level1: {level2: { ["root-default-1", "root-default-2"] } }`.

- Another schema:
```
{
          type: "object",
          properties: {
            level1: {
              type: "array",
              default: [
                {
                  item: "property-default-1",
                },
                {},
              ],
              additionalItems: {
                type: "object",
                properties: {
                  item: {
                    type: "string",
                    default: "additional-default",
                  },
                },
              },
              items: [
                {
                  type: "object",
                  properties: {
                    item: {
                      type: "string",
                    },
                  },
                },
              ],
            },
          },
        }
```
Here, because the length of `items` is 1, the default should probably be `          level1: [
            { item: "property-default-1" },
            { item: "additional-default" },
          ]` rather than `          level1: [
            { item: "property-default-1" },
            {}
          ]`

You can see more examples at https://github.com/mozilla-services/react-jsonschema-form/pull/1376/files#diff-0de170772e45d2602c103dd916607787.

I was wondering if there might be some value in standardizing this behavior, perhaps in the JSON Schema spec.

The [spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.10.2) says:
> There are no restrictions placed on the value of this keyword. When multiple occurrences of this keyword are applicable to a single sub-instance, implementations SHOULD remove duplicates.

Perhaps it would be good to more clearly define what "removing duplicates" is, and define an algorithm for doing so. It's true that `default` has no effect on validation, though, but it might still be good to somehow standardize how to handle overlapping defaults.

**Comment by handrews** [comment]
@epicfaace in the forthcoming draft (all required PRs have been posted for review, with one last optional one to be posted this week which, if we can't agree on quickly will be punted to the draft after this), there is a recommended output format for working with annotations (`default`, `examples`, `title`, `readOnly`, `writeOnly`, etc.)

You can see details in the pre-publication review copy at http://json-schema.org/work-in-progress/WIP-jsonschema-core.html#rfc.section.10 (feedback welcome, although at this stage our priority is publishing, so anything that's not a major problem will get deferred to the next draft).

The more detailed output formats provide enough information for an application to decide how to handle cases like this.  There is no universal approach (some people want the deepest value to win, some people want the highest value to win, some people want both to be retained in some way), so we have focused on ensuring that applications have a standard set of information that they can consume and use to implement whichever approach works for them.

That wording is a bit out of date, and we should probably tweak it, so I'll leave this open (oof, I guess that's one more required PR that needs writing this week).
