### ISSUE TITLE
Instance validation/Format types into main specification

### ISSUE THREAD

**Issue by zeth** [json-schema-org/json-schema-spec#8]
https://groups.google.com/forum/#!searchin/json-schema/format/json-schema/WInNIGWSL4U/UtTl29b-3GIJ
https://groups.google.com/forum/#!searchin/json-schema/format/json-schema/74XLt7R4ISE/FPOnAh6rq_UJ

I agree with the comment in the first post, it is too confusing; may I suggest for draft 5 or 6, JSON Schema goes back to one specification document with instance validation and format types inside it?

**Comment by zeth** [comment]
A Date (date-time) object is not part of the original JSON spec. But
it is such a fundamental type that a lot of JSON parsers/serializers
add it anyway.

For example, in most Javascript implementations, using the .toJSON()
on a date object produces an ISO 8601 date:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toJSON

Python's datetime object also produces the same format when using the
.isoformat() method. As do some other languages.

Of course, once an extended type section is added, one might want in
the future to add other unambiguous commonly used types such as an
email address, IP address, URL etc. However, for now my question
focuses just on the date type.

**Comment by zeth** [comment]
If we imagine the definition of a date property in a JSON Schema. There is more than one way this could be achieved:

Simple approach:

```json
"created": {
			"type": "date"
		},
```

More explicit approach would be something like:

```json
"created": {
			"type": "string",
			"extended": "date"
		},
```

The latter is slightly uglier but I guess would be kinder on existing JSON Schema software which can fall back to validating a simple string.

**Comment by zeth** [comment]
Oh how ironic, it was in draft 3 but fell out in draft 4, see section 5.23:
http://tools.ietf.org/html/draft-zyp-json-schema-03

```

   date-time  This SHOULD be a date in ISO 8601 format of YYYY-MM-
      DDThh:mm:ssZ in UTC time.  This is the recommended form of date/
      timestamp.

   date  This SHOULD be a date in the format of YYYY-MM-DD.  It is
      recommended that you use the "date-time" format instead of "date"
      unless you need to transfer only the date part.

   time  This SHOULD be a time in the format of hh:mm:ss.  It is
      recommended that you use the "date-time" format instead of "time"
      unless you need to transfer only the time part.

   utc-millisec  This SHOULD be the difference, measured in
      milliseconds, between the specified time and midnight, 00:00 of
      January 1, 1970 UTC.  The value SHOULD be a number (integer or
      float).
```

I think four date/time formats is a bit overkill. Simple ISO 8601 Date (datetime) is enough. The minority use case where applications do not want a particular part of the ISO 8601 can zero it and explain itself accordingly.

**Comment by handrews** [comment]
Just to be contrary ;-) as someone who started using JSON Schema with draft 4, I don't find the three-document approach confusing, and in fact appreciate having the aspects of the system split up in that way to produce smaller, more cohesive documents.

**Comment by awwright** [comment]
I know a few people weren't too thrilled about splitting the documents up, but the way I re-arranged it I think makes a lot more sense than the three documents did before, and as far as I can tell people think this makes sense:

1. JSON Schema core defines the application/schema+json media type and the bare minimum of how to handle it
2. Additional documents define vocabularies that you can use in an application/schema+json document

So this is much more modular than it is in draft-04.

I'll hopefully publish a draft soon here, and if it still doesn't make as much sense let's investigate how we can improve the new draft.
