### ISSUE TITLE
Complex if/then fails checking deep schema locations

### ISSUE THREAD

**Issue by bpalm2006** [json-schema-org/json-schema-spec#807]
I have a complex schema and need to apply a validation rule at a high level the references code data at a much lower level and it is failing.  For example: here is what I'm trying:
============================
example schema
============================
{
    "$comment" : "Genarated with 'https://www.jsonschema.net/'",
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/root.json",
    "type": "array",
    "title": "The Root Schema",
    "minItems": 1,
    "items": {
        "$id": "#/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
            "id",
            "fileId",
            "childrenWorks",
            "workMedia",
            "publicationType",
            "title",
            "speaker"
        ],
        "properties": {
            "id": {
                "$id": "#/items/properties/id",
                "type": "integer",
                "title": "The Id Schema",
                "default": 0,
                "examples": [
                    304
                ]
            },
            "fileId": {
                "$id": "#/items/properties/fileId",
                "type": "string",
                "title": "The Fileid Schema",
                "default": "",
                "examples": [
                    "PD60007135_000_11nelson"
                ],
                "pattern": "(\\w*_\\w*_\\w+)"
            },
            "childrenWorks": {
                "$id": "#/items/properties/childrenWorks",
                "type": [
                    "array",
                    "null"
                ],
                "title": "The Childrenworks Schema",
                "default": null,
                "examples": [
                    null
                ]
            },
            "workMedia": {
                "$id": "#/items/properties/workMedia",
                "type": "array",
                "title": "The Workmedia Schema",
                "items": {
                    "$id": "#/items/properties/workMedia/items",
                    "type": "object",
                    "title": "The Items Schema",
                    "required": [
                        "mediaType",
                        "files"
                    ],
                    "properties": {
                        "mediaType": {
                            "$id": "#/items/properties/workMedia/items/properties/mediaType",
                            "type": "string",
                            "enum": [
                                "video",
                                "audio",
                                "image",
                                "caption",
                                "print"
                            ],
                            "title": "The Mediatype Schema",
                            "default": "",
                            "examples": [
                                "audio"
                            ],
                            "pattern": "^(.*)$"
                        },
                        "files": {
                            "$id": "#/items/properties/workMedia/items/properties/files",
                            "type": "array",
                            "title": "The Files Schema",
                            "items": {
                                "$id": "#/items/properties/workMedia/items/properties/files/items",
                                "type": "object",
                                "title": "The Items Schema",
                                "properties": {
                                    "audioVoiceType": {
                                        "$id": "#/items/properties/workMedia/items/properties/files/items/properties/audioVoiceType",
                                        "type": "string",
                                        "title": "The Audiovoicetype Schema",
                                        "default": "",
                                        "examples": [
                                            "male"
                                        ],
                                        "pattern": "^(.*)$"
                                    },
                                    "audioBitRate": {
                                        "$id": "#/items/properties/workMedia/items/properties/files/items/properties/audioBitRate",
                                        "type": "integer",
                                        "title": "The Audiobitrate Schema",
                                        "default": 0,
                                        "examples": [
                                            0
                                        ]
                                    },
                                    "fileTypeId": {
                                        "$id": "#/items/properties/workMedia/items/properties/files/items/properties/fileTypeId",
                                        "type": "integer",
                                        "title": "The Filetypeid Schema",
                                        "default": 0,
                                        "examples": [
                                            4
                                        ]
                                    },
                                    "fileType": {
                                        "$id": "#/items/properties/workMedia/items/properties/files/items/properties/fileType",
                                        "type": [
                                            "string",
                                            "null"
                                        ],
                                        "title": "The Filetype Schema",
                                        "default": "",
                                        "enum": [
                                            "text/vtt",
                                            "image/jpeg",
                                            "audio/mpeg",
                                            "audio/mp4",
                                            "audio/x-aac",
                                            "audio/m4b",
                                            "video/mp4",
                                            "application/zip",
                                            "video/x-ms-wmv",
                                            "application/pdf",
                                            "application/epub+zip",
                                            "application/x-mobipocket-ebook",
                                            "application/x-zip-compressed",
                                            "application/octet-stream"
                                        ],
                                        "examples": [
                                            "audio/mpeg"
                                        ],
                                        "pattern": "^(.*)$"
                                    },
                                    "subFileType": {
                                        "$id": "#/items/properties/workMedia/items/properties/files/items/properties/subFileType",
                                        "type": [
                                            "string",
                                            "null"
                                        ],
                                        "title": "The Subfiletype Schema",
                                        "default": "",
                                        "examples": [
                                            "application/json",
                                            "mp3",
                                            "mp4",
                                            "daisy",
                                            "braille",
                                            "lse-mandarin",
                                            "lse-cantonese"
                                        ],
                                        "pattern": "^(.*)$"
                                    },
                                    "locations": {
                                        "$id": "#/items/properties/workMedia/items/properties/files/items/properties/locations",
                                        "type": "array",
                                        "title": "The Locations Schema",
                                        "items": {
                                            "$id": "#/items/properties/workMedia/items/properties/files/items/properties/locations/items",
                                            "type": "object",
                                            "title": "The Items Schema",
                                            "required": [
                                                "locationType",
                                                "path",
                                                "stream"
                                            ],
                                            "properties": {
                                                "locationType": {
                                                    "$id": "#/items/properties/workMedia/items/properties/files/items/properties/locations/items/properties/locationType",
                                                    "type": "string",
                                                    "title": "The Locationtype Schema",
                                                    "default": "",
                                                    "examples": [
                                                        "download"
                                                    ],
                                                    "pattern": "^(.*)$"
                                                },
                                                "path": {
                                                    "$id": "#/items/properties/workMedia/items/properties/files/items/properties/locations/items/properties/path",
                                                    "type": [
                                                        "string",
                                                        "null"
                                                    ],
                                                    "title": "The Path Schema",
                                                    "default": "",
                                                    "pattern": "^https:\\/\\/.+$"
                                                },
                                                "stream": {
                                                    "$id": "#/items/properties/workMedia/items/properties/files/items/properties/locations/items/properties/stream",
                                                    "type": [
                                                        "object",
                                                        "null"
                                                    ],
                                                    "title": "The Stream Schema",
                                                    "default": null
                                                }
                                            }
                                        }
                                    }
                                },
                                "required": [
                                    "fileTypeId",
                                    "fileType",
                                    "locations"
                                ]
                            }
                        }
                    },
                    "allOf": [
                        {
                            "if": {
                                "properties": {
                                    "mediaType" : {
                                        "enum": ["print"]
                                    },
                                    "files" : {
                                        "items" : {
                                            "properties" : {
                                                "fileType": {
                                                    "enum": [
                                                        "application/pdf"
                                                    ]
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            "then": {
                                "required": [
                                    "fred"
                                ]
                            }
                        }
                    ]
                }
            },
            "publicationType": {
                "$id": "#/items/properties/publicationType",
                "type": "string",
                "title": "The Publicationtype Schema",
                "default": "",
                "enum": [
                    "ComplexTest",
                    "Broadcast"
                ],
                "pattern": "^(.*)$"
            },
            "title": {
                "$id": "#/items/properties/title",
                "type": "string",
                "title": "The Title Schema",
                "default": "",
                "pattern": "^(.*)$"
            },
            "speaker": {
                "$id": "#/items/properties/speaker",
                "type": [
                    "string",
                    "null"
                ],
                "title": "The Speaker Schema",
                "description": "Who did the speaking",
                "default": "",
                "pattern": "^(.*)$"
            }
        }
    }
}

============================
example data
============================
[
  {
    "id":22508,
    "fileId":"03990_000_test_000",
    "childrenWorks":[

    ],
    "workMedia":[
      {
        "mediaType":"print",
        "files":[
          {
            "fileTypeId":11,
            "fileType":"application/pdf",
            "subFileType":"application/pdf",
            "locations":[
              {
                "locationType":"download",
                "path":"https://some_url",
                "stream":null
              }
            ]
          },
          {
            "fileTypeId":12,
            "fileType":"application/epub+zip",
            "subFileType":"application/epub+zip",
            "locations":[
              {
                "locationType":"download",
                "path":"https://some_url",
                "stream":null
              }
            ]
          },
          {
            "fileTypeId":13,
            "fileType":"application/x-mobipocket-ebook",
            "subFileType":"application/x-mobipocket-ebook",
            "locations":[
              {
                "locationType":"download",
                "path":"https://some_url",
                "stream":null
              }
            ]
          }
        ]
      },
      {
        "mediaType":"image",
        "files":[

        ]
      }
    ],
    "publicationType":"ComplexTest",
    "title":"test_000",
    "speaker":null
  }
]

Why does my validation check in the "allOf" section not show a failure?

**Comment by Relequestual** [comment]
Hi @bpalm2006 
Please try to tidy up your code here so we can try to help.
Also please provide a https://jsonschema.dev link so we can see your Schema and JSON data in action.

Thanks

**Comment by bpalm2006** [comment]
Ok, 
I've scaled my example down and now have a jsonschema.dev link:

Validation passes even though it shouldn't...

https://jsonschema.dev/s/N4IgziBcLAOgdgAmY2IAkBjA9gW1wKbwAuakqIA4kQIYBONxBAJogO4CWxAFogOTdixAA5hIAenFtpAOgBWYbPDCZuBXDRnwCxcXzQAaBCgrMCAMw7wuHJWDKJgAXyNIUadCrUaHaQSIlxBSUAWi91TWw6AHNxZgZzYhCABgB2cXCNAGJDY3cMDmZfEH9hQIIADxpcYQAbAhkcXHE6bGxieUV4XLdkNGIAT2ECYvoGAZ6Tfq564oAVNUQAJTbiRABlVQjJ-NwrAEkmXHsoRABGVymQLnUT8jhekwp0QuKs8RvjnaeKQeHi7AAIzkBEwpBAlx+vxmI1OaAWBEQh1uGy2PgheR+aDoBAAjgBXDg4oqnADamKhfWuJMhlKpbCiAGsALIsDg0NAUkwAXVpTzQwlawzoxA4BDuji5ULQr1ODzp0oKJPIaHenzA4kF2GFovFHxpUoV-SGsJV1xIBGiBDonMelJchv5IAZdBZbI5csdlI8srNaqOGq1OrFGpdbuY7O+Cvyf1NFDGNAmGLt0emxFmcJACMQAHUmYQIzRUd4PXzoxR1Q55eXFS9lRR-bdNULrbrQ0zWYWPgGozWYyaAcDQeCy32KDiCUSWA5ySmx7t3XMB8n596QJZ6icvdHedujSAg62Q1W9zW0AX2Uv-p656urrHimBiHQrNFe3enUR8bgZ6ePxQADdCgIbB33-LEQBofEI1AldwP3QUrHBP8x25FCFQdW95zQDdxRPLCP2Na8zQTJNR3gmUexveD9wfTMgRBMEwJoqlDxFY9qJY1N1w4eorzjasuLPJU3m7Js2LbKQO3dMTjmbbUjz1XCNXVeTgyU3iCH45ihIgujyFnXTVzQJ8X3gN84KMvs0HgfFalqW0rJ3cinPyL8fzJdCrLQGhhDqDhMEYWx4E1ZhzB01yrl8-zAtFJRxAIYR8UBABqAAvDhhEcyKoTQgihMwnL8jAZKADFNO0ziiquOtRNUiSQyk11O3ZWTAxbdiNM3Nq1MUjUSsBcq+OXFzIqIuNDOqtdTNfCKipsuyHJALyWLyqanBWscNvy1dtpYvaP0KwjIPsgB5cLPJ28tBK4mULvuTbrIPDq23wqbz0XZcHqu3S0Hc38fqcgUzOQwGuLW6qjvmnjNzeqb8krKr4auBq8KR5GINwyrvox4T-su3HsMgvzagCoL4sS5L0sy7LCbpCG6ZMA66eZ+HWci9ndM5+CodukAeCIOGgeehTOolG6xphtGcYxyjbiFwngdF170cZkyyoqr7JTB96QHxgzHvhv6ksBAA1GhanxWFDcihnGeQbm2Ztw7nb7R39tdp53a20axwlmi7oVoylfU8XPfLD7C2x7Xcb+2yPINnXfuepDafhu2Od9oScM0sOk4o64qJlumQ76oO1al6P-ftql9cQSaa7pHySbJuKQuEMK08b5AM8Z72iv7qzB49-Oa2Hn3w5jNRulV7ORdD8vheUxecrlr5Z6N+ey432PwA14biJj7urjrhvj6daI2mYc3Let0fbcnnnH925-y3Hp-7+jd+x897+eS8wejtWbbScBCa4UAQBn2rhWesAAmWBABWZIAAOFyaBVC8XiEQPMroJSkl3LeNAYYWoekTtdLykdLxa2BqnSywll4Ew-NAomWMTT7HrGcC4nsc4HzjM3GK5N26dzof+dWg1NaHzQICGgzAAAKYV1jJTolnYStRsCxWCng5+zCA4gDURopQ0c0DMGwGweAaiZFzXAgKRg3BiilDEJIRQhAAD6+I6BLRUaI8Az4CDVAcLZeyz8-65UNrzecOinqsOGOwhwZxYFeO4tEvhxMBFtwSibamWURHHQGkNLS1CQDSOYAAURNoowElVEn7n0YIrRn8fiROsXo9RgijEgBMWYixBoGlNwPLY+xQhRCBGcQQNxHirHeNMn4hOiBAkOV6UzT2vc3ZeRWV7R0dttrchAE4IAA

**Comment by bpalm2006** [comment]
I just removed on of the file instances on the JSON instance side and now the validation is working...  So, it fails if it is being applied to more than one array instance?

https://jsonschema.dev/s/N4IgziBcLAOgdgAmY2IAkBjA9gW1wKbwAuakqIA4kQIYBONxBAJogO4CWxAFogOTdixAA5hIAenFtpAOgBWYbPDCZuBXDRnwCxcXzQAaBCgrMCAMw7wuHJWDKJgAXyNIUadCrUaHaQSIlxBSUAWi91TWw6AHNxZgZzYhCABgB2cXCNAGJDY3cMDmZfEH9hQIIADxpcYQAbAhkcXHE6bGxieUV4XLdkNGIAT2ECYvoGAZ6Tfq564oAVNUQAJTbiRABlVQjJ-NwrAEkmXHsoRABGVymQLnUT8jhekwp0QuKs8RvjnaeKQeHi7AAIzkBEwpBAlx+vxmI1OaAWBEQh1uGy2PgheR+aDoBAAjgBXDg4oqnADamKhfWuJMhlKpbCiAGsALIsDg0NAUkwAXVpTzQwlawzoxA4BDuji5ULQr1ODzp0oKJPIaHenzA4kF2GFovFHxpUoV-SGsJV1xIBGiBDonMelJchv5IAZdBZbI5csdlI8srNaqOGq1OrFGpdbuY7O+Cvyf1NFDGNAmGLt0emxFmcJACMQAHUmYQIzRUd4PXzoxR1Q55eXFS9lRR-bdNULrbrQ0zWYWPgGozWYyaAcDQeCy32KDiCUSWA5ySmx7t3XMB8n596QJZ6icvdHedujSAg62Q1W9zW0AX2Uv-p656urrHimBiHQrNFe3enUR8bgZ6ePxQADdCgIbB33-LEQBofEI1AldwP3QUrHBP8x25FCFQdW95zQDdxRPLCP2Na8zQTJNR3gmUexveD9wfTMgRBMEwJoqlDxFY9qJY1N1w4eorzjasuLPJU3m7Js2LbKQO3dMTjmbbUjz1XCNXVeTgyU3iCH45ihIgujyFnXTVzQJ8X3gN84KMvs0HgfFalqW0rJ3cinPyL8fzJdCrLQGhhDqDhMEYWx4E1ZhzB01yrl8-zAtFJRxAIYR8UBABqAAvDhhEcyKoTQgihMwnL8jAZKADFNO0ziiquOtRNUiSQyk11O3ZWTAxbdiNM3Nq1MUjUSsBcq+OXFzIqIuNDOqtdTNfCKipsuyHJALyWLyqanBWscNvy1dtpYvaP0KwjIPsgB5cLPJ28tBK4mULvuTbrIPDq23wqbz0XZcHqu3S0Hc38fqcgUzOQwGuLW6qjvmnjNzeqb8krKr4auBq8KR5GINwyrvox4T-su3HsMgvzagCoL4sS5L0sy7LCbpCG6ZMA66eZ+HWci9ndM5+CodukAeCIOGgeehTOolG6xphtGcYxyjbiFwngdF170cZkyyoqr7JTB96QHxgzHvhv6ksBAA1GhanxWFDcihnGeQbm2Ztw7nb7R39tdp53a20axwlmi7oVoylfU8XPfLD7C2x7Xcb+2yPINnXfuepDafhu2Od9oScM0sOk4o64qJlumQ76oO1al6P-ftql9cQSaa7pHySbJuKQuEMK08b5AM8Z72iv7qzB49-Oa2Hn3w5jNRulV7ORdD8vheUxecrlr5Z6N+ey432PwA14biJj7urjrhvj6daI2mYc3Let0fbcnnnH925-y3Hp-7+jd+x897+eS8wejtWbbScBCa4UAQBn2rhWesAAmWBABWZIAAOFyaBVC8XiEQPMroJSkl3LeNAYYWoekTtdLykdLxa2BqnSywll4Ew-NAomWMTT7HrGcC4nsc4HzjM3GK5N26dzof+dWg1NaHzQICGgzAAAKYV1jJTolnYStRsCxWCng5+zCA4gDURopQ0c0DMGwGweAaiZFzXAgKRg3BiilDEJIRQhAAD6+I6BLRUaI8Az4CDVAcLZeyz8-65UNt-XuPxHZ222tyEATggA

**Comment by Relequestual** [comment]
I don't know about the second instance (I'm going to dig into it), but you need to set `"else": false` on your `allOf` subschemas. like this: 

https://jsonschema.dev/s/N4IgziBcLAOgdgAkbEASAxgewLY4KbwAuqkKIA4oQIYBO1R+AJogO4CWRAFogORdEiABzCQA9GNZSAdACswWeGAxd8OatPj4iY3qgA0CZKib4AZu3id2isKUTAAvoaTk0y1evuoBw8WPlFAFoPNQ0sWgBzMSZ6MyIggAYAdjFQ9QBiAyM3diZvEF8hf3wAD2ocIQAbfGlsHDFaLCwiOQV4bNdUIgBPIXwCunoezuMQIk4agoAVVUQAJWaiRABlFTDR8hxLAElGHDsoRABGFzHONUOyOFcxtDyCjLELg82x3v6CrAAjWXwMEggM7IcgTIhTI6oWb4RB7S6rdZeIE5Ma0fAARwAruw0fkjgBtFEg1APZG3YkgVgRADWAFlmOxqKgiQBdYFjIRNfq0Cb4K4OInnPHXQUU+7C8hPF5gMScrDc3ky0nskHvPoDSEgSyMSL4WjM8nIZyi1BU2h0hlMo43VWq1Dix7PfYyuUK9h8yQ0+lMRlvW3ddWDWjDP128aTDVkKFzADqNIIPuoCM8VpVYel9httrDDs1Uudsq5esVnvN3sZTsuof940Dmp+fwB1bDaKxOOY9kJhuzW0t0zraZ7qAsNUOotVbPHFNdxfd-KzPYpCcZ-c+1qn2YDa6j4CItEskWbQ5AhExOE7G+PADc8vgsEfF6hqJiffeyYvHyBOdqDR-bSzLyNQdNxAEc+UzQCKQ+SNyCGagRnfP8KQzdduz-LcYNQBt-kBYCP1QGceTnCC0KQ4d2BqVcYIXJCQNzHd80uQt5VnD0zQtRNKwOZi3Q9MClQLQiSzAqiHzI2tt0QLtaPQ3d93gQ9EJk494ExKoql-ZT-zw2jUFPc8CUg2TqCEap2AwBgbHgWUmDMMTdJAEyzIsiZFDEfAhExb4AGoAC92CETStJBADSL-Y0wvw8AvIAMQo-BRNQ4Kc1JBiuJdIsiLYr1LXSnjWJlfi8qEuc0li+LEp08ToIvSKHLAPcD3s8TVPUoLktC5LEEcIyQR6uq+sg-rwqqp91IAeTswyBpo2T2CmkUBrDErwKS5LUGXahEsWrqxn02rduneTAV67NOuSiKuvI0cSMOklnVuw7yBW+dTqikS6x2p6w326bvpApyqnMyy3I8ry-IC9rvvO77hqeuGuoRrSkdolGP0umTulUDo1uUgjMsVR7guu1avqurUHtx3b8ZYrLXqW8SwHKyjPoFBmHN+shpP+n7PO+AA1agqkxDU3r-GH4bF200eUmWkLlxcFelqqfqqMAYLMIX1aGlW2bxrUFr1rSad4+nyc27ajfJzmpKl5bjqhrSJdl3WQP4on1opqsqfJl6Pbu0CKtZ2anr01SDK5u2osB4HXOsoRbMdw7nd2pXUajtOe0z1Vs+613QWx-3xL9n3McDm7S-1lCyepr8CeIyvPaZ744pZySQ4Dm3uZ5sZImaJhBeF0X2aQlPEajo0M6l3PJ4ZjGObVjWtYGAalbH7rRSRuH+scIEtSgEBuZokkJQAJlPgBWRIAA4VVQFQKNiQg43Nfl8UnclTRyxMDttDve0TJbfGP4lI1ndn9D8-8wwfX6DsCUxxTiQRJkAxypkgYuSsjZKautUDN1bglVmqBvjUCYAABVsisLyNVQGfiqFgDBthf60SgceOhDD4AoKYFgVg8A6EkOastBgXAChFFEBIBQBAAD6mJaAaRoYzPc+AKj2FahpOekF15AUvCwsYMD8BwPsMcU+ODy4EMkk+NBsdMFgx8v5QK8iQJ4KDuYkAxCmAAFE+aUO+JVJBIA2EgyUEwpCOiawBLjpw7hvCsD8IcVFIQQiRGCBEP4CR+BpGyIERSBqaJlFHFUb1TOmiN6kRTkjc6-UWQgEcEAA

**Comment by Relequestual** [comment]
In response to your earlier...

> I just removed on of the file instances on the JSON instance side and now the validation is working... So, Schema validation doesn't work if it is being applied to more than one array instance?

This is because the `if` on line 108, followed by `files` and `items` means that ALL the files have to match that schema for the if condition to be true.

To be honest, you'd be FAR better off starting this from scratch and not using a generator. That way you can break up your schema into separated definitions and it becomes much easier to manage.

**Comment by Relequestual** [comment]
I'm going to close this issue on the basis that I've answered your questions, suggested an alternative approach, and you haven't cleaned up your question.

If you have any specific questions like this, they are best to post on StackOverflow using the `jsonschema` tag rather than post here. We also have a slack server.

**Comment by bpalm2006** [comment]
It looks like validation quits working when the "if" conditions extend outside the current branch (even if looking at a child branch)

Here is an example of validation showing an appropriate error (validates at the same level as value it is checking): [jsonschema.dev](https://jsonschema.dev/s/N4IgziBcLAOgdgAmY2IAkBjA9gW1wKbwAuakqIA4kQIYBONxBAJogO4CWxAFogOTdixAA5hIAenFtpAOgBWYbPDCZuBXDRnwCxcXzQAaBCgrMCAMw7wuHJWDKJgAXyNIUadCrUaHaQSIlxBSUAWi91TWw6AHNxZgZzYhCABgB2cXCNAGJDY3cMDmZfEH9hQIIADxpcYQAbAhkcXHE6bGxieUV4XLdkNGIAT2ECYvoGAZ6TNFwrAEkmXHsoRABGVymQLnUl8jhekwp0QuKs8S3FyYO+kEHh4uwAIzkCTFIQdauKOgIARwBXDjfIrLADaeU++TYUQA1gBZFgcGhocEHAC6HyuaGErWGdGIHAIO0cKIhaGOyz2ENJNyGI2WZJIBGiBDoyP2EJcJM+aChdDhCKRFK5VIotzp5DQYxoE3ewqpZIWRMpIvlNLu9JAj2er0uKu5IG+-0BLAcYPZev1hGYiIAKrTdRbqZZ6ks5Xr0W6VVicSz8YSHMrHdSrbb7ULzUH9WLimBiHQrNEHZHqUQ-rhTZ7kwdvVY3pnk6j83rORHk2hnf7w1mRf0wxKQFKZRjq5jNoqA0Xq7X1fWtS83s2W9TsdhcX6lZ2hxQK3ae8TS1Oa2rxYgzYuh2hY-H4InZQv116QPA-rVamyD0GPfuLxtU+nQZOb9caMI6hxMIxbPBxMJmOYk0+h4vm+H74ko4gEMIfwPAA1AAXhwwjnoBIqFteB4lihrZgNBABiHD1LOK6BlhrbRg+6GkZucYJgBpGtsep7IfRaKPi2ThsUGmFYZKp4APL-hRLHICRwkUBwgm7JxF7eqOvoEhOlHCeWBEEERHZKWJ1x3hmmlaRswG1O+n7gb+gnSfRaH6SKHF6U+tnWYg3H6f0ajdFWjn5COY4KRpnn6jhDz4YRdbzv5S46UJ4V6mg0RtMwABqNC1H8dIWaRVnRSgDnhTl+l5fRzn0aJymbJJYXhbJPmVlJdk8SAM6hSVWUUJF5Bri1qqGcZYHfghSF7p1XWvkZoFfhBUGwf1dFDRQ3VjeBFQhP1IRNNihJgCaIDpVhmUtQVjkHcJRVia5RB+ZVIDefJNUVS1m54ap6kebNrXHve7U7SxaCQdBSUpWldUsXtWVHflX3JmDgFQ+uV5UQavwAkCumnQ1T1hhDEIg+uMNcRZuNXATTlygVtlOO8mxQCAHUiXKZLAuQABMjMAKzJAAHIO+SqAR8REAA6jCRIgnD+q8vy1qCp96HNaqIY0M99bYrmM1OqpwsWbLkYqSFwyzAzqxrBDOtqaFkojT141marQYPUF6NzmgDw0MwAAKf4AMrQeRXNZmgtTYAtygozeWuLv7gcmfAiumNgbDwAHLs21OWKMNwxSlGIkiKIQAD6fx0Geg31VuBDVA4jFnkDVJE+6+O+xaYeOibRH6w4KyMw32to7rK7myBUcTdB8GIcnFp28FpuOyAzvMAAopNXsPM9Xe2yAAdBxr1cQk3G7r5HvUx2gzBxwn2BJ8XKGpzwGdCKIgQ5wQ+eF2PLbUd85fLJXmPZRD2N43pf+hM5Qg1sqiEATggA)

Here is an example of validation succeeding inappropriately (validates at a higher level and includes additional check on mediaType): [jsonschema.dev](https://jsonschema.dev/s/N4IgziBcLAOgdgAmY2IAkBjA9gW1wKbwAuakqIA4kQIYBONxBAJogO4CWxAFogOTdixAA5hIAenFtpAOgBWYbPDCZuBXDRnwCxcXzQAaBCgrMCAMw7wuHJWDKJgAXyNIUadCrUaHaQSIlxBSUAWi91TWw6AHNxZgZzYhCABgB2cXCNAGJDY3cMDmZfEH9hQIIADxpcYQAbAhkcXHE6bGxieUV4XLdkNGIAT2ECYvoGAZ6TNFwrAEkmXHsoRABGVymQLnUl8jhekwp0QuKs8S3FyYO+kEHh4uwAIzkCTFIQdauKOgIARwBXDjfIrLADaeU++TYUQA1gBZFgcGhocEHAC6HyuaGErWGdGIHAIO0cKIhaGOyz2ENJNyGI2WZJIBGiBDoyP2EJcJM+aChdDhCKRFK5VIotzp5DQYxoE3ewqpZIWRMpIvlNLu9JAj2er0uKu5IG+-0BLAcYPZev1hGYiIAKrTdRbqZZ6ks5Xr0W6VVicSz8YSHMrHdSrbb7ULzUH9WLimBiHQrNEHZHqUQ-rhTZ7kwdvVY3pnk6j83rORHk2hnf7w1mRf0wxKQFKZRjq5jNoqA0Xq7X1fWtS83s2W9TsdhcX6lZ2hxQK3ae8TS1Oa2rxYgzYuh2hY-H4InZQv116QPA-rVamyD0GPfuLxtU+nQZOb9caMI6hxMIxbPBxMJmOYk0+h4vm+H74ko4gEMIfwPAA1AAXhwwjnoBIqFteB4lihrZgNBABiHD1LOK6BlhrbRg+6GkZucYJgBpGtsep7IfRaKPi2ThsUGmFYZKp4APL-hRLHICRwkUBwgm7JxF7eqOvoEhOlHCdMApER2Slidcd4ZhpmkbNiubMXpKpocZVLcWZrYVoplmHucNm2Rasljgp6mOWWIAznW87uS2aDaUJvlTpKr61O+n7gb+gnSb5plBRaHG6WZiXxQcKXxeltmZZpFmaf0ajdFWjnOfJlZSUlPGeQRZU+al+T2W5dWtiOLk1aJTXZuAeHVWpRUdYeAXkGu-VBmg0RtMwABqNC1H8dIxe5cUjWlC3CdlqXrY5m16dt9G7U+uWke1LFkpJtW2SVeKuX1vkqdaNC9eV-X+ce95DatJ0gAZJBGalS2+YdxVVS6jVNQq2ygyNl3jpDy3XF5c7HXDWmvTpyN6iFIERd+kHQfBiG-ejyD-cj+0ZR9gFkztFPsTTXGDspNwFbDxnQ9dT3xeW1UOWDbYQzdz1fT6V1tXTn04Q8+GEd5SPIy9aZo0Tqq4w802zfNFVBSTcNUwDYsYfrtOawbxtG2JustleVEGr8AJAorn0IxrpHa1OFsqu7Vye4guu7dliVOO8mxQCAw0iXKZLAuQABM0cAKzJAAHAz1yqAR8REAA6jCRIglb+q8vy90O1SsuWqp3k5j9e6RlzIOBVmZeOnXBBEbMUerGsFMt49FDAWFoFfj+f50R5EtS63lcgA8NDMAACn+ADK0HkSnHm1Ngg92CX65NxuIAb1v8C92gzDYGw8Ab7Po-rlijDcMUpRiJIiiEAA+n8dBnjXlVbgQ1QOEYmeU2nxvYQldglNeeo94Y2BpPYY7cHArGjlA0acCT4NlCuFMCOMoKwQQkhH+wUuqSx6lPGezAACieDl4PF6qg5uB9N7Y1zvrGBXYmFHwwWfC+V9gQMP3sIe+j8hCiECK-AgH8v430XNRb4ADlhAP1mAz4EDiyPjUSgXa-1EqohAE4IAA)

using "else": false does not correct the validation and breaks the case where it works.
