### ISSUE TITLE
Discussion about the next draft

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#81]
https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-validation.xml

@awwright What is the format you would prefer: single issue or multiple issues (probably it's better, then based on the result of the discussion I can make PRs)?

**Comment by awwright** [comment]
@epoberezkin There should probably be an issue for every particular problem, feature, or question we have. I don't see any problem with how things have been working so far.

Unless maybe it's something like typos or whatever else that is trivially aggregated.
