### ISSUE TITLE
Is it possible to define an "inverse" dependency?

### ISSUE THREAD

**Issue by renancouto** [json-schema-org/json-schema-spec#811]
I have two fields, both required. But if one of them is filled, then the other is not required anymore. Is this supported by `json-schema-spec`?

**Comment by Relequestual** [comment]
There's always `not`, which takes the value of a schema, and inverst the assertion result.

**Comment by renancouto** [comment]
Cool, thanks! I didn't know that.

**Comment by Relequestual** [comment]
Understanding JSON Schema isn't always easy. We tried to make a thing to make that easier: http://json-schema.org/understanding-json-schema/ - It's not perfect, but it beats reading RFC documents for most people. =]
Feel free to also join our slack. And note we monitor the json-schema tag on stackoverflow.
