### ISSUE TITLE
Tighten spec for regex patterns, to improve interoperability

### ISSUE THREAD

**Issue by Zac-HD** [json-schema-org/json-schema-spec#816]
My work on [`hypothesis-jsonschema`](https://pypi.org/project/hypothesis-jsonschema/), the upstream test suite, and [`js-regex`](https://pypi.org/project/js-regex/) for the Python `jsonschema` library have shown me a few sharp corners on [the current spec for `pattern` validation](https://github.com/json-schema-org/json-schema-spec/blob/b47f567e1ef87ae16b69aeb8c3084729a22c9bce/jsonschema-validation.xml#L351-L362), where the very short spec has led to interoperability problems between e.g. JS and Python - i.e. schemas being valid or not, and instances valid or invalid for a schema, depending on the language.

I'd be keen to add some additional points to the next draft, with a quick sketch below.  In particular I've optimised for interoperability, reduction of ambiguity for schema authors, and compatibility with current practice.  

CC @handrews @Relequestual @Julian - I'd be particularly interested in your comments!

------------

> The value of this keyword MUST be a string. This string SHOULD be a valid regular expression, according to the ECMA 262 regular expression dialect.
>
> A string instance is considered valid if the regular expression matches the instance successfully. Recall: regular expressions are not implicitly anchored.

First, while the string SHOULD be a valid regex pattern, it is unclear what should be done if it is not.  I propose to clarify that "implementations MUST NOT validate any string against an invalid pattern, and SHOULD emit a warning or an error if an invalid pattern is used".

Second, and more importantly, the status quo for regex interoperation is quite poor - essentially, everyone uses their native regex engine and hopes that users stick to the compatible subset of ECMA262 syntax described in [the core spec](https://github.com/json-schema-org/json-schema-spec/blob/b47f567e1ef87ae16b69aeb8c3084729a22c9bce/jsonschema-core.xml#L526-L557).  Suffice to say that they do not; for example the `\w` ("word") metacharacter is in common usage - but in JS it means `[A-Za-z]`, while in Python it matches any Unicode character in a Letter category.  This and several other issues can be patched over by e.g. my [`js-regex` library](https://pypi.org/project/js-regex/), but the only full solution is to use an ECMA regex engine which may be very difficult from other languages.  I therefore have two proposals:

- add a link to the core spec from the validation spec and note that "schema authors SHOULD stick to the compatible subset of regex syntax"
- specify that "validation tools MUST match the semantics of ECMA 262 regex, including the lack of implicit anchoring.  Validation tools MAY treat regex patterns as invalid if they use features outside the compatible syntax subset such that the tool cannot match ECMA 262 behaviour.  In this case the tool [MUST emit a warning or error](https://tools.ietf.org/id/draft-thomson-postel-was-wrong-03.html)."

Without this last point, I am concerned that almost all non-Javascript implementations will have subtly incompatible handling of regex patterns; and that this will undermine the important value proposition that your front-end and back-end validation logic can be shared.

**Comment by handrews** [comment]
@Zac-HD thanks for digging into this.

> add a link to the core spec from the validation spec and note that "schema authors SHOULD stick to the compatible subset of regex syntax"

This is [already present](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.6.4), with [the link you're asking for](http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.4.3).

regarding:
> "implementations MUST NOT validate any string against an invalid pattern, and SHOULD emit a warning or an error if an invalid pattern is used".

and 

> specify that "validation tools MUST match the semantics of ECMA 262 regex, including the lack of implicit anchoring. Validation tools MAY treat regex patterns as invalid if they use features outside the compatible syntax subset such that the tool cannot match ECMA 262 behaviour. In this case the tool MUST emit a warning or error."

This puts an overly large burden on validators to detect things that are very hard to detect.  which is why the "regex" format is one of many formats that is almost never validated fully.  

In practice, most people know their interoperability targets, if any.  And many people don't care and want to make use of their chosen language's features.

For `pattern` and `patternProperties`, my view is that this is both too difficult and likely to produce unwanted behavior.  A linter (or if you can come up with a regex for your valid set of regexes, a meta-schema) is a better solution.  JSON Schema should err on the side of permissiveness rather than block useful functionality in the name of saving people from themselves.

If someone wants a mandatory-strict version of regex-based keywords, that would be a good use case for an extension keyword.  Extension keywords can demand complex computation like validating a regex that are too heavyweight for general-purpose implementations (which need to be possible in constrained resource environments like IoT).

This is my personal opinion, we'll see what other folks say.

**Comment by Julian** [comment]
> First, while the string SHOULD be a valid regex pattern, it is unclear what should be done if it is not. I propose to clarify that "implementations MUST NOT validate any string against an invalid pattern, and SHOULD emit a warning or an error if an invalid pattern is used".

Just to be sure, we all read this that the SHOULD means "SHOULD be ECMA 262" yes? Not "SHOULD be valid"? That's clear to me, that it already says "you pick a dialect, and then it has to be valid under that dialect, and that dialect SHOULD be ECMA 262"? But if that's part of what's unclear I think that's just a wording thing.

Having anytime the spec says "valid regular expression" or whatever be a hyperlink to that section on the recommended subset seems like a minor nice thing certainly, so +1 for that at least.

But beyond those two things I want to make sure I'm following the nuance of the proposed change, so let me try to repeat it back to make sure I follow -- is it adding to the spec that it's OK for validators to explicitly *reject* non ECMA 262 patterns? If so I think that's already covered by the spec saying you SHOULD use ECMA 262, isn't it?

If you instead mean to say that ECMA 262 should be changed to required, that I don't think I agree with -- I mean, my own validator is probably a good example -- your change is awesome :), but if you hadn't come along, regardless of how easy it is to do, I never would have bothered sitting down to do it (not to mention I am already bracing for someone asking to be able to inject in different regex engines so that they can continue using Python regexes). So it's hard to think it's something that can be enforced on all validators.

But yeah want to make sure I'm following the proposed change, so let me know if I missed the point.

**Comment by johandorland** [comment]
The reality is that there are a lot of regex flavours out there and for an implementation the most straightforward way to handle regexes is to use the regex flavour their language provides. Of course this  leads to interoperability problems. However if you require that my implementation has to support ECMA-262 regex I suddenly have to implement a ECMA-262 regex engine as one does not exist for my language. Maintaining a JSON schema implementation is hard enough already, maintaining a separate regex engine is beyond my ability. 

In reality I'm not sure how much of a difference this is going to make, people won't read the spec to see what flavour of regex they have to write. If someone is writing a schema that has to be used across different implementations I think it's not unreasonable to put the burden on them to make sure their regexes work with all the flavours the implementations use, but I could be overestimating the intelligence of the average software developer.

It would be wonderful to change a few words in the spec that would magically solve all problems, but I'm skeptical that such a phrasing exists.

**Comment by Zac-HD** [comment]
> Just to be sure, we all read this that the SHOULD means "SHOULD be ECMA 262" yes? Not "SHOULD be valid"? That's clear to me, that it already says "you pick a dialect, and then it has to be valid under that dialect, and that dialect SHOULD be ECMA 262"? But if that's part of what's unclear I think that's just a wording thing.

@Julian - that's not entirely clear to me, and presumably others, so rephrasing it with more detail could be helpful.  For example:

>> ~~These regular expressions SHOULD be valid according to the regular expression dialect described in ECMA 262, section 15.10.1.~~
>>
>> These regular expressions MUST be valid according to the regular expression dialect used by the implementation, which SHOULD be the dialect described in ECMA 262 section 15.10.1.

and my argument is basically that we should then add a further clause:

>> When use of the ECMA-262 dialect is not practical, implementations MAY reject regular expressions that are not limited to the widely compatible tokens listed below.

--------

> However if you require that my implementation has to support ECMA-262 regex I suddenly have to implement a ECMA-262 regex engine as one does not exist for my language.

That would be *way* too much to force on implementers!  What I want is to give you the option of rejecting anything outside of the 'compatible subset' that behaves the same in ECMA-262 as it does in every other regex engine I know of.  (with the exception of Python's unusual handling of `$`, but I'm dealing with that...)

> If someone is writing a schema that has to be used across different implementations I think it's not unreasonable to put the burden on them to make sure their regexes work with all the flavours the implementations use, but I could be overestimating the intelligence of the average software developer.

I'd phrase it as "underestimating the volume of documentation required to be aware of all the edge cases", but that's why I want to allow tools to bring potentially-incompatible patterns to users' attention.

**Comment by Julian** [comment]
Ah, cool, ok! I think that makes a lot more sense to me now, thanks -- I think then it sounds like we're not really talking about a change of *behavior* of the spec, just a clarification on wording?

At least if you read the spec the way I already do today.

@handrews / @johandorland was that your understanding of the proposal too and you still disagree with changing the wording, or were you thinking this proposal was about mandating ECMA 262?

**Comment by Zac-HD** [comment]
> Ah, cool, ok! I think that makes a lot more sense to me now, thanks -- I think then it sounds like we're not really talking about a change of behavior of the spec, just a clarification on wording?

I think I'm proposing two small semantic changes to the spec:

1. Split "This string SHOULD be a valid regular expression, according to the ECMA 262 regular expression dialect." to specify that the string MUST be a valid regex pattern, and SHOULD use ECMA-262 syntax.  This basically recognises existing practice, I think.
2. Explicitly allow implementations to reject non-ECMA-262-compatible regex.  IMO this is technically allowed by the above, but the purpose is to raise this to the attention of schema authors who do desire wide compatibility.

Plus some cross-references so readers reliably find the relevant sections on regex interoperation (it took me a while to realise they existed when I started).  But they're very small changes even so 😄

**Comment by handrews** [comment]
I'm strongly against adding any MUST here.  There is no universal notion of what a "valid regex pattern" is so it's unenforceable.  Any syntax chosen as the most permissive will no doubt be contradicted.  I'm not sure even the Perl maintainers could tell you exactly what constitutes a valid Perl regular expression.

I'm also against explicitly allowing implementations to reject non-ECMA-262.  @Zac-HD you said that you:

> personally value interoperability more highly and in the case of validation that requires consistent behaviour across languages. 

And that's just it.  That's your _personal_ opinion.  Do you have any idea how many people propose putting their personal opinions in the spec?  ***Many.*** 😄 They frequently are in direct opposition.

In this case, many other people value flexibility.  It's easier to extend a spec by restricting it than by loosening it, *and* the current behavior has been part of the spec for longer than I've been aware of the project (much less involved with it).  You can get what you want with an extension, and we've made that easier to do.

For that matter, you can get what you want with a preprocessor/linter which is really what I would recommend.  Specifications are not there to hold your hand.  They're there to get things into a reasonably practical balance between an interoperable core and not trying to solve all problems in computer science.

Regular expression interoperability is a completely orthogonal problem to JSON Schema.  There is nothing special going on here.  It is not our problem, and we're not going to impose a solution.  We've specified a core requirement, and given how rarely we get complaints about this I don't think it's a significant problem in practice.  Or if it is, people understand that it's not JSON Schema specifically that is the problem.

I guarantee you that a lot of people rely on the current behavior.  I see no upside in encouraging implementations to break their expectations.  I'm sorry to be negative, but this just does not seem like a problem for our spec to solve.

**Comment by handrews** [comment]
Regarding cross-references, there's already a "Regular Expressions" section in each document.  Specifications are not tutorials and people are expected to at least read the table of contents and figure out what is relevant.

I'm not really against it, but the spec is getting bloated and needs trimming as it is (given that I'm personally responsible for most of the bloat, I feel comfortable making that judgement).  There's a whole lot of stuff that should really be in tutorials and guides, if we could ever find anyone with time to write them.

**Comment by Zac-HD** [comment]
Closing this issue as it seems unlikely to get agreement.
