### ISSUE TITLE
Fix awkward paragraph in 8.2.4.5 "Loading a Reference Schema"

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#817]
In [section 8.2.4.5](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-8.2.4.5), the 2nd paragraph reads:

> When schemas are downloaded, for example by a generic user-agent that doesn't know until runtime which schemas to download, see Usage for Hypermedia ([Section 11](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-11)).

which I had trouble parsing just now while referring someone to that section.  I _think_ what's going on here is that:

* We want to acknowledge that while implementations are not required to automatically fetch referenced schemas, sometimes that will be a thing that happens.
* In particular, acknowledging systems where the exact schemas needed are only known at runtime.
* Section 11 is specifically about ways to fetch schemas that allow meta-data that can work with RFC 8288 links and/or media types and their parameters.  This is relevant, but not the only option- loading from files is also common, for example.

We should figure out what we're trying to say here and say it more clearly, without assuming HTTP or similar protocols.

**Comment by Relequestual** [comment]
@handrews Had a go at fixing this.
To be honest, I didn't find it confusing at first read anyway, but hey ho.

**Comment by Relequestual** [comment]
Closed in favour of #849
