### ISSUE TITLE
Named Constants?

### ISSUE THREAD

**Issue by davaya** [json-schema-org/json-schema-spec#819]
I'd like to, for example, define an object whose keys are phone numbers and values are URIs, using a named reusable value for a regular expression:
```
{
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "$ref": {
      "#/definitions/Phone": {
        "type": "string",
        "format": "uri"
      }
    }
  },
  "definitions": {
    "Phone": {
      "type": "string",
      "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
    }
  }
}
```
But Section 9.3.2.2 says "The value of "patternProperties" MUST be an object.  Each property name of this object SHOULD be a valid regular expression.", i.e., the property name cannot be a schema for a regular expression, it (apparently) must be a literal regular expression.

The schema is valid (for something unknown), but it doesn't validate the desired data:
```
{
  "(202)555-1234": "http://www.example.com"
}
```
Is there a way in JSON Schema to define and reference named literal values?  If not, are named constants on the development roadmap?

**Comment by gregsdennis** [comment]
You're on the right track.  In order to use the `patternProperties`, you have to define an object.  The keys are the regex's that match to the property names, and the value is the schema that such a property should adhere to.

So in your case, you'd want to do something like this:

```json
{
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$" : {
      "$comment": "Phone-number-named properties should have URI strings for values",
      "type": "string",
      "format": "uri"
    }
  }
}
```

(You can move the subschema for the phone number into a definition if you like.)

**Comment by gregsdennis** [comment]
The downside to this is that you can't reuse the regex.  If you'd like to re-use data like that, I'd suggest you browse through the [$data](https://github.com/json-schema-org/json-schema-spec/labels/%24data) label issues.  There's a lot of discussion.

**Comment by jdesrosiers** [comment]
@davaya This can be done with `propertyNames` + `patternProperties`.

```json
{
  "type": "object",
  "propertyNames": { "$ref": "#/definitions/Phone" },
  "patternProperties": {
    "": {
      "type": "string",
      "format": "uri"
    }
  },
  "definitions": {
    "Phone": {
      "type": "string",
      "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
    }
  }
}
```

**Comment by awwright** [comment]
As @jdesrosiers points out, the `"propertyNames"` keyword is probably most suitable for this. That way, the object takes meaning as a generic key-value map. The property keys are more meaningful this way (with e.g. "format", although there's no "phone" format at this time).

Aside: if you're storing phone numbers, you will want to normalize them in an international format. In my understanding, parenthesis in phone numbers is only a US convention; make sure the phone number includes the country code, and has no punctuation. Additionally, you may need to store other information, such as extensions, or written instructions (e.g. a person to ask for).

**Comment by davaya** [comment]
@gregsdennis @awwright: thanks for the insight.  I need to re-use the same regex in two schemas, one for an object with keys constrained by a pattern and the other for a string with the identical pattern (so that it can be validated as a key to the object).  It looks like propertyNames will do the trick nicely.

The phone number was just an example to illustrate the question, not the actual pattern of interest.
