### ISSUE TITLE
Validating data against other data

### ISSUE THREAD

**Issue by brean** [json-schema-org/json-schema-spec#820]
Hi,

A Problem that I have quite often is that I have 2 datasets that have data that is dependent on each other. Mostly in databases - one dataset has the primary key and the other has the foreign key. I like to model this in my schema so that valid options for the foreign keys should only be the primary keys in my other database, but I don't know how to do this, I have not found a good example for this although I think it is a pretty common use case.

If I understand anchorPointer correctly this could be used but then I need to have a special microservice providing the data as links?

**Comment by Relequestual** [comment]
Hey @brean, sorry JSON Schema doesn't facilitate this use case.
draft 2019-09 intruduced the concept of vocabularies, which allows groups to create and publish extensions in an interoperable way.
We want to engage with this use case, probably through MongoDB, to help a databases type vocabulary to develop.
Unfortunatly, we don't have the people power to do this ourselves, and it's work that should be driven by those who would implement it anyway.

If you're thinking about databases in terms of Mongo or just any referencial integrity, Mogno have the most incentive to participate, given they already implement a flavour of JSON Schema for validation. It couldn't hurt to contact them yourself and suggest they engage with us =]

Closing for now as there's no action from our side, but please feel free to join or slack commuity! =]
