### ISSUE TITLE
Are there any standard or norms for case/format for schema names?

### ISSUE THREAD

**Issue by goldingdamien** [json-schema-org/json-schema-spec#822]
In the examples below under the "definitions" key, the names are in lowercase. Is this a standard of json-schema? If so, where is it stated? Is it a norm of schemas in general? If so, where is it stated?
https://json-schema.org/understanding-json-schema/structuring.html

Regards.

**Comment by Relequestual** [comment]
Nope. and Nope.
There's no defined "best practice". It's something I personally want to work on through 2020.
Feel free to come join our slack server to keep up to date

**Comment by gregsdennis** [comment]
> There's no defined "best practice".

While true, a *common* practice I've seen for JSON in general is camelCase naming for keys.  But again, nothing official or declared "best practice;" this is just my experience as a primarily .Net developer.

**Comment by handrews** [comment]
In general, JSON inherited a tendency towards camelCase from JavaScript, and JSON Schema inherited that from JSON.  But that's all there is to it.

I'm going to close this as it's been more than a month since the last comment so I'm assuming the answer was sufficient.  Please comment if not.
