### ISSUE TITLE
How do we handle keyword requests that should be considered for vocabularies?

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#836]
Adding vocabularies in draft 2019-09 was done so that we can finally draw a line and stop adding keywords to the core and validation specifications indefinitely.

We have a whole lot of issues requesting relatively niche keywords, and I would very much like to close them out unless we expect to implement them.  Or at least expect someone to make a compelling case for them.

We want to show progress towards completion and reducing the open issue count will be one sign of that.

How should we go about this?

**Comment by awwright** [comment]
JSON Schema validation keywords are somewhat maturing, so perhaps we can write up some sort of process for determining if a keyword would be well received by implementors  and users.

One requirement could be writing and implementing meta-schema with the proposed keyword.

The risk here is scaring off new users who want to be helpful and contribute. Raising the cost is _sort of_ the point, but more accurately, the point of this should be that there's a clear threshold to cross in order to add a keyword; not to scare off contributors with arcane and arbitrary procedure.

**Comment by handrews** [comment]
@awwright all good points!

One option might be to have an informal registry (like on the wiki) of vocabularies and keywords that people are working on, or would like to see someone work on.  Maybe be able to vote for them or something.  If a vocabulary or keyword gets enough interest and meets the threshold (which we would still need to define), it can be "promoted" to a github issue on the spec.

We do have the Vocabularies repo, which stalled when it became apparent that we really needed to develop the vocabulary concept more before we could push those.  We could clear out the outdated stuff there and use that (including its issue tracker) if the wiki on the spec repo doesn't seem suitable.

Either approach would meet my goal of moving the plethora of too-interesting-to-close but not-compelling-enough-to-add keyword proposals out of the main spec repo.  Without needing to close them entirely.

The theme here and with #838 is really to distill this repo down to "things that need to be done to finalize Core and Validation."  I hadn't thought of it when I was filing this, but that's really the point.  Not so much "close the issues" but "get them out of the way however we can."

**Comment by philsturgeon** [comment]
I'll go hunting for things which look like they could be moved over to the vocabs repo.

**Comment by handrews** [comment]
I updated the title to be a bit more accurate.  Note that I consider more or less all keyword requests to be better handled by vocabularies at this point, although it's possible one might prove itself worth promoting.

**Comment by handrews** [comment]
Over a month, no responses.  Sorry for the delay @philsturgeon feel free to move things (except don't move `requiredProperties` as it's under active consideration for main spec inclusion).
