### ISSUE TITLE
Address base URI for JSON Schema embedded in other documents 

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#837]
In the discussions around JSON Schema and OpenAPI Specification 3.1, we need to clarify the determination of the base URI for each of the embedded JSON Schema resources.

The OAS document has its own media type, and its own rules for determining a base URI.  These fall under RFC 3986's "base URI embedded in the document" approach.  We should probably update our own section [8.2.1 Initial Base URI](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.1) to note that, in the case of a JSON Schema resource embedded in a document of another media type, the initial base URI is determined according to the rules of that media type.

This is philosophically consistent with what's already there, I believe, and would clarify an important use case.  And would mean that specifications like OAS 3.1 would not have to call it out as a special case.

Also paging @webron @darrelmiller @philsturgeon

**Comment by Relequestual** [comment]
To confirm, this is in the case where the JSON Schema object doesn't define its own `$id`?

If the goal is making sure "insert this json schema here and it works", then JSON Schema has to still be allowed to define its own base URI.

Assuming I'm correct here, are we just reitterating what's already in RFC 3986?
https://tools.ietf.org/html/rfc3986#section-5.1.2 ?

OR, are we saying this is two cases of "5.1.1.  Base URI Embedded in Content", and we need to determine if the JSON Schema `$id` or the base URI as determined by OAS is the one by which relative references should be resolved?

I think I'm clear that it's the first, but we need to specify that the initial base URI is defined by the enclosing document should it not be defined by the JSON Schema document object (which I read as per RFC 3986 5.1.2 anyway).

**Comment by handrews** [comment]
I'm going to cover this as part of the rework described in #849.
