### ISSUE TITLE
spec: add the paragraph about the properties in JSON instance being unordered  (by JSON spec)

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#84]
In this section: https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L92

I hope that may reduce the number of suggestions to validate the order of properties.

EDIT: also order of property being formatting detail can be added here: https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L134

**Comment by awwright** [comment]
The text for "object" already says:

> An unordered set of properties mapping a string to an instance, from the JSON "object" production

If this weren't enough, the equality algorithm was painstakingly defined to avoid any dependence on order:

> [or] both are objects, and each property in one has exactly one property with an equal key the other, and that other property has an equal value.

Is something more necessary, do you think?

**Comment by epoberezkin** [comment]
I would replace

> objects must have the same number of members,

with something like

> objects must have the same number of members and the order in which they appear is not significant,

**Comment by awwright** [comment]
Paragraph now looks like this:

> Implied in this definition is that arrays must be the same length,
   objects must have the same number of members, properties in objects
   are unordered, there is no way to define multiple properties with the
   same key, and that mere formatting differences (indentation,
   placement of commas, trailing zeros) are insignificant.

**Comment by awwright** [comment]
@epoberezkin Is "Evgeny Poberezkin" good for an acknowledgement?

**Comment by epoberezkin** [comment]
Yes, thank you :)

**Comment by handrews** [comment]
@epoberezkin can this be closed now?
