### ISSUE TITLE
Proofread schema document vs resource for consistency and correctness.

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#847]
It's not entirely consistent as it was a late change.

In most cases, we want to be talking about schema resources, and the root object within a schema resource.  We only want to talk about documents when we mean the actual text (or octet stream, I suppose is what it technically is), no matter how many resources are contained in it.

We should also make sure that keywords confined to a root object (`$schema`, `$recursiveAnchor`, `$vocabulary`) are confined to the root of the correct thing.  I _think_  that should be the resource root, not the document root, even if (as is currently the case) we note that switching the `$schema` value within the same document does not have well-defined behavior (that's in a CREF).

**Comment by handrews** [comment]
We want to do this after other major work on this draft is complete, but it should be part of a holistic wording review.

**Comment by ssilverman** [comment]
Looking through this now, using the following definitions:
1. A "schema document" is the whole resource, per the "actual text" definition above, and
2. A "schema resource" is an object having an $id.

**Comment by ssilverman** [comment]
I went through every "schema document" and every "schema resource" search result and made sure they all made sense.

**Comment by Relequestual** [comment]
Super. In that case, we can close out this issue! 🚀
Many thanks!
