### ISSUE TITLE
Allow different $schema values in same document if different resources

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#850]
Currently, you can put `$schema` in a **resource** root object, which means you can have multiple `$schema` keywords in the same document.  Currently [we say](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.1.1) that schema authors SHOULD only have `$schema` in the document root, and we say that if multiple resources in the same schema have different `$schema` values, the meta-schema is undefined.  There's a CREF giving some of the backstory.

Before the schema resource concept was introduced, and tied to the updated `$id` keyword, there was concern about allowing `$schema` to be dropped into any random schema object.

But now we have two types of schema objects: schema resource root objects, and schema objects within a resource.  The document root object is a special case of the schema root object.

Schema resource roots are easily detected (`$id` means its a schema resource root), and we already do special processing of them.  Allowing the `$schema` to change there makes sense, as we want schema resources to behave the same whether they are linked with `$ref` (in which case you can definitely change `$schema`) or not (which is currently undefined).

I think we should go ahead and define this behavior.  It also fits in with #849 (clarifying and consolidating the schema loading process), where we will talk about how to load embedded schema resources within a single document.

**Comment by Relequestual** [comment]
Splitting up `$id` into two use cases ( now with `$anchor`) was a great idea.
Yup. I'm all for the above!

**Comment by karenetheridge** [comment]
It should also be possible (thank you `$recursiveRef`!) to make this restriction explicit in the metaschema with a rule "if the `$id` property appears, `$schema` is allowed; else, `$schema` is prohibited".

**Comment by handrews** [comment]
@karenetheridge we've generally avoided enforcing those things in the meta-schemas because they are technically not forbidden.  They just have "undefined" behavior.

Due to `$recursiveRef` and `$recursiveAnchor`, though, you can write your own strict meta-schema with the same standard vocabularies to enforce whatever makes sense to you.

I agree that this is a gray area, (as opposed to people wanting us to, say, forbid `properties` unless `type` is object), and I could be convinced that we should enforce resource roots vs subschemas in the meta-schema.  But I'm not yet convinced of that.  I kind of want to see what people do in practice with making custom meta-schemas now that we've made that easier and more effective.
