### ISSUE TITLE
Default 'null' value is not applied to a field with type ["null", "object"]

### ISSUE THREAD

**Issue by IrinaBadiginaEpam** [json-schema-org/json-schema-spec#851]
**GIVEN**: a property of type `["null", "object"]` **AND** default value is `null`
**EXPECTED**: default value is `null`
**ACTUAL**: default value is an empty object `{}`

Though it works fine for `["null", "string"]` and `["null", "number"]` types.

[Playground with example](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJudWxsYWJsZU9iamVjdCI6e30sIm51bGxhYmxlU3RyaW5nIjpudWxsLCJudWxsYWJsZU51bWJlciI6bnVsbH0sInNjaGVtYSI6eyJ0aXRsZSI6IkZvcm0gd2l0aCBudWxhbGJsZSBmaWVsZHMgd2hpY2ggYXJlIG51bGwgYnkgZGVmYXVsdCIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im51bGxhYmxlT2JqZWN0Ijp7InRpdGxlIjoiTnVsbGFibGUgT2JqZWN0IiwidHlwZSI6WyJudWxsIiwib2JqZWN0Il0sImRlZmF1bHQiOm51bGx9LCJudWxsYWJsZVN0cmluZyI6eyJ0aXRsZSI6Ik51bGxhYmxlIFN0cmluZyIsInR5cGUiOlsibnVsbCIsInN0cmluZyJdLCJkZWZhdWx0IjpudWxsfSwibnVsbGFibGVOdW1iZXIiOnsidGl0bGUiOiJOdWxsYWJsZSBOdW1iZXIiLCJ0eXBlIjpbIm51bGwiLCJudW1iZXIiXSwiZGVmYXVsdCI6bnVsbH19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiJ9LCJhZ2UiOnsidWk6d2lkZ2V0IjoidXBkb3duIiwidWk6dGl0bGUiOiJBZ2Ugb2YgcGVyc29uIiwidWk6ZGVzY3JpcHRpb24iOiIoZWFydGhpYW4geWVhcikifSwiYmlvIjp7InVpOndpZGdldCI6InRleHRhcmVhIn0sInBhc3N3b3JkIjp7InVpOndpZGdldCI6InBhc3N3b3JkIiwidWk6aGVscCI6IkhpbnQ6IE1ha2UgaXQgc3Ryb25nISJ9LCJkYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRldGltZSJ9LCJ0ZWxlcGhvbmUiOnsidWk6b3B0aW9ucyI6eyJpbnB1dFR5cGUiOiJ0ZWwifX19LCJsaXZlU2V0dGluZ3MiOnsidmFsaWRhdGUiOnRydWUsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOmZhbHNlfX0=)

**Comment by Relequestual** [comment]
Hi @IrinaBadiginaEpam 
This repository is for the specification, not any implementation of JSON Schema.
You will need to file the issue on the repository which hosts the library in question. It may be https://github.com/rjsf-team/react-jsonschema-form ?

**Comment by IrinaBadiginaEpam** [comment]
my mistake, thanks!

**Comment by Relequestual** [comment]
No problem. Feel free to join our slack server should you need help with JSON Schema not related to form generation.
