### ISSUE TITLE
spec: maybe always use MUST and not SHALL?

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-spec#87]
Although SHALL is defined as an synonym to MUST I always confuse it with SHOULD that means a different thing.

This line, e.g.: https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-core.xml#L289

I was about to ask why ignoring other keywords when $ref is used became optional only to realise it didn't...

Just an idea, not that important really...

**Comment by awwright** [comment]
Yeah, I can see that.

I think I wrote that... Yeah, yeah I did.
