### ISSUE TITLE
Question: Can I use one of the schemas defined in the file to validate an arbitrary json schema

### ISSUE THREAD

**Issue by ab320012** [json-schema-org/json-schema-spec#870]
Hey is it possible to use one of the files in meta to validate an arbirtrary json schema?

**Comment by handrews** [comment]
The meta-schema URIs for each draft of the schema are provided in the relevant draft.  The "meta" directory in this repository is just the working space for the next draft.  You should not get meta-schemas from this repository.  You should get them from json-schema.org (which lives at https://github.com/json-schema-org/json-schema-org.github.io in GitHub, although be sure to check out the submodules if you try to get the meta-schemas there.
