### ISSUE TITLE
MultipleOf Not supporting more than 12 digits of precision?

### ISSUE THREAD

**Issue by andrewkarcher** [json-schema-org/json-schema-spec#873]
I am not sure whether this is a specification issue or an implementation in Newtonsoft. Is there a specification for the number of digits of precision the multipleOf attribute supports? In testing on the site here: https://www.jsonschemavalidator.net/

If this is my schema:

Schema: "multipleOf":0.000001,
Value: "MyNumber": 1.1111
Result: Valid

Schema: "multipleOf":0.000001,
Value: "MyNumber": 1.111111111
Result: Invalid

Schema: "multipleOf":0.000000000000001,
Value: "MyNumber": 1.11111111111111111111111
Result: Valid

Schema: "multipleOf":0.000000000001,
Value: "MyNumber": 1.11111111111111111111111
Result: Invalid

It appears that more than twelve digits of precision in the mulitpleOf property is breaking. Is this in the specification how many digits of precision should be supported or is this just an issue with the NewsoftJSON validator that is powering the site?

**Comment by awwright** [comment]
@andrewkarcher This is an implementation issue. JSON technically supports arbitrary precision, and JSON Schema implementations are supposed to support that too, but the majority of implementations just read numbers into a 64-bit IEEE float.

**Comment by handrews** [comment]
@andrewkarcher also, while JSON technically supports arbitrary precision, it only [_interoperably_](https://tools.ietf.org/html/rfc8259#section-6) supports up to IEEE 754 binary64 double-precision floats.  Which is not something JSON Schema can change.

Additionally, as JSON Schema is defined over a data model, not the JSON text, JSON Schema implementations cannot work with the original JSON text, only the parsed value.

**Comment by Relequestual** [comment]
No requirements are placed in the JSON spec... =/
Should we RECOMMEND something for interoperability?

**Comment by handrews** [comment]
@Relequestual no, because this is covered by JSON's RFC.  We should not be repeating things in the JSON RFC.

**Comment by awwright** [comment]
At _most_, I would write an informative guideline like "Implementations ought to note if they do not support arbitrary precision, such as using an IEEE float instead." Though I've never seen this become an issue in production.
@andrewkarcher Were you considering using this much precision in an application, in some fashion?

**Comment by handrews** [comment]
@awwright given that very few people write new JSON parsers as part of JSON Schema implementations, I would be opposed to cluttering our spec with this.  It is thoroughly covered in the JSON RFC, and there are other RFCs dedicated to how to declare interoperability subsets.  This is out of scope for us, I'd say.

**Comment by awwright** [comment]
It doesn't seem there's anything to do here, so I'll close this out. Please keep us posted if you see any usage "in the wild" that expects more than 12 digits of precision.
