### ISSUE TITLE
Inline `required` keyword on properties

### ISSUE THREAD

**Issue by timkindberg** [json-schema-org/json-schema-spec#878]
Would it be possible/feasible to allow `required` to be "inline" in property declaration objects? It's always kind of bugged me that you can just do it right next to the type, title, etc.

e.g.
```
thing: {
  type: "object",
  properties: {
    foo: {
      type: 'string',
      required: true <--- THIS
    }
  }
}
```

**Comment by Relequestual** [comment]
It used to be this way, but it got changed. There are a number of reasons for this including the way you can combine schemas to require keywords but don't want them to be defined in `properties`.

I can go into detail if it's helpful, but essentially we are extreamly unlikely to revert this change.

**Comment by timkindberg** [comment]
Yeah I stumbled across this: https://github.com/json-schema-org/json-schema-spec/issues/846

Which makes sense... a bit of a bummer, but understandable. Thanks.

**Comment by timkindberg** [comment]
Couldn't the same be said of `readOnly`?

**Comment by Relequestual** [comment]
`readOnly` is only an annotation and has no impact on the construction of a schema in the same way.

**Comment by Relequestual** [comment]
Appreciate your understanding. We have an active slack if you'd like to join us =]
Link found on the main site.
