### ISSUE TITLE
Would be useful to include common properties across multiple object definitions

### ISSUE THREAD

**Issue by ssilverman** [json-schema-org/json-schema-spec#882]
As far as I'm finding, there's no way to share common properties across two object definitions. For example, `object1` has properties "name" and "reference". `object2` also has these defined.

It would be nice to have the concept of a "property set" that an object could use as an "include". Or, maybe there could be a way to have an object be able to inherit the properties of another. Composition vs. inheritance, that is.

I'm trying to figure out reuse where multiple objects are similar enough to want to share things, but different enough that they need their own custom attributes in addition.

**Comment by karenetheridge** [comment]
You can do that with definitions.

```
definitions:
  property_set_a:
    a:
      type: string
    b:
      type: integer
    ... etc
  property_set_b:
    ...
type: object
allOf:
  - $ref: "#/definitions/property_set_a"
  - $ref: "#/definitions/property_set_b"
```

**Comment by ssilverman** [comment]
Ah, much obliged. "allOf" and related keywords have been slightly confusing to me as to where they can be used. I was under the impression they couldn't co-exist with sibling properties because "allOf" replaced a whole schema for an object. Apparently, they _can_ coexist with sibling values.

**Comment by ssilverman** [comment]
I'll add: I was thinking along the lines of:
```
properties:
  ref-to-set-a
  property-name1
```

**Comment by handrews** [comment]
@ssilverman `$ref` cannot be used with sibling properties up through and including draft-07.  In draft 2019-09 (which is draft-08, but we went to date-based versioning) that restriction is lifted.  The result of `$ref` is the result of the referenced schema, and it's combined with other keyword results in the usual way (e.g. all keyword validation results are ANDed and that's the validation result of the schema object).

So hopefully this gets less confusing soon!

**Comment by ssilverman** [comment]
So I have this, does this look correct?
```
"$defs": {
  "commonProps": {
    "properties": {
      "prop1": {
        "description": "xxx",
        "type": "string"
      }
    }
    "obj1": {
      "allOf": {
        "$ref": "#/$defs/commonProps",
        "properties": {
          "prop2": {
            "description": "yyy",
            "type": "string"
          }
        }
      }
    }
  }
}

**Comment by ssilverman** [comment]
Oh, wait. Maybe that's too complex (for draft 2019-09, will the previous comment work for draft-07?). Maybe this is the correct one for draft 2019-09?
```
"$defs": {
  "commonProps": {
    "prop1": {
      "description": "xxx",
      "type": "string"
    },
    "prop2": {
      "description": "yyy",
      "type": "string"
    }
  }
  "obj1": {
    "type": "object",
    "properties": {
      "$ref": "#/$defs/commonProps",
      "prop3": {
        "description": "zzz",
        "type": "string"
      }
    },
    "additionalProperties": false
  }
}
```

**Comment by ssilverman** [comment]
@karenetheridge Thanks for the response. I tried it, but that technique doesn't seem to work (well, with https://www.jsonschemavalidator.net) with `"additionalProperties"` set to `false`.

**Comment by handrews** [comment]
For more interactive help, please go to json-schema.org and click "Join our Slack" and ask on the slack channel.  GitHub issues aren't great for a lot of back-and-forth.
