### ISSUE TITLE
$ref property inheritance

### ISSUE THREAD

**Issue by B-Teague** [json-schema-org/json-schema-spec#892]
**Please see second comment below for more relevant question regarding json-schema**

I would like to create a schema that leverages shared objects, but at the same time describes the different nuances between instances of those shared objects.

Unfortunately, there are limitations within the schema specifications that prevent this flexibility.

Below is a sample openapi schema I have created where I have both a shared object, but different lengths, descriptions, and examples for different instances of the shared object.

Ideally, a client could generate a class for the shared object based on their host language, but the json schema can be more exact for each instance of a shared object.

Your thoughts?

```json
{
"country": {
   "type": "#components/schemas/CodeDesc",
   "properties": {
      "code": {
         "type": "$ref/#components/schemas/CodeDesc/code",
         "description": "A unique value for the different countries on planet Earth",
         "maxLength": 3,
         "example": "USA"
      },
      "description": {
         "type": "$ref/#components/schemas/CodeDesc/description",
         "description": "The full name of the given country code",
         "maxLength": 100,
         "example": "The United States of America"
      },
   } 
},
"state": {
   "type": "#components/schemas/CodeDesc",
   "properties": {
      "code": {
         "type": "$ref/#components/schemas/CodeDesc/code",
         "description": "A unique value for a given state",
         "maxLength": 2,
         "example": "TX"
      },
      "description": {
         "type": "$ref/#components/schemas/CodeDesc/description",
         "description": "The full name of the given state code",
         "maxLength": 15,
         "example": "Texas"
      },
   } 
},
"CodeDesc": {
   "type": "object",
   "properties": {
      "code": {
         "type": "string",
         "description": "A unique value with a specific business meaning",
         "minLength": 1
      },
      "description": {
         "type": "string",
         "description": "A business description describing the unique code value",
         "minLength": 1
      },
   } ,
   "required": [
      "code",
      "description"
   ]
}
}
```

**Comment by Relequestual** [comment]
For OpenAPI 3.1, you will be able to use `$ref` in the same schema object as other keywords.
FYI JSON Schema and OpenAPI are different projects. OpenAPI, does not yet, use pure JSON Schema as is, although it looks to support in the upcoming release 3.1.

`type` accepts the primitive types. I'm not sure what you've done in your schema here. Is this what you would LIKE to be able to do?

Class generation is outside of the scope of JSON Schema.
When / if others make / formalise a vocabulary for class generation, it might be interesting, but that is also outside of the scope of the JSON Schema project.

Having said that, we can migrate this issue to the "vocabularies" repo, so others who may wish to create a vocabulary can still find it, should you wish.

**Comment by B-Teague** [comment]
So, I reformatted the schema to something that makes more sense.
This issue is with the understanding that OpenAPI 3.1 will support full JSON schema specs.

Is it valid to use ```$ref``` on individual properties of a definition ```"#components/schemas/CodeDesc/properties/code"```?

Are we allowed to use $ref and properties together?

Basically, I am trying to get the schema to say, "The ```country.code``` comes from the ```CodeDesc.code``` common object model, but it has a maximum length of 3 bytes"

```json
{
"country": {
   "$ref": "#components/schemas/CodeDesc",
   "properties": {
      "code": {
         "$ref": "#components/schemas/CodeDesc/code",
         "description": "A unique value for the different countries on planet Earth",
         "maxLength": 3,
         "example": "USA"
      },
      "description": {
         "$ref": "#components/schemas/CodeDesc/description",
         "description": "The full name of the given country code",
         "maxLength": 100,
         "example": "The United States of America"
      },
   } 
},
"state": {
   "$ref": "#components/schemas/CodeDesc",
   "properties": {
      "code": {
         "$ref": "#components/schemas/CodeDesc/code",
         "description": "A unique value for a given state",
         "maxLength": 2,
         "example": "TX"
      },
      "description": {
         "$ref": "#components/schemas/CodeDesc/description",
         "description": "The full name of the given state code",
         "maxLength": 15,
         "example": "Texas"
      },
   } 
},
"CodeDesc": {
   "type": "object",
   "properties": {
      "code": {
         "type": "string",
         "description": "A unique value with a specific business meaning",
         "minLength": 1
      },
      "description": {
         "type": "string",
         "description": "A business description describing the unique code value",
         "minLength": 1
      },
   } ,
   "required": [
      "code",
      "description"
   ]
}
}
```

**Comment by handrews** [comment]
@B-Teague no, not for `maxLength`.  This is not how JSON Schema validation assertions work.  JSON Schema validation is a constraint system.  Constraints can be added by combining schemas, but never removed (although you can end up with complex behavior with `if`, `oneOf`, etc. that conditionally decides which constraints to combine).

Annotations like `description` are up to the application (e.g. an OpenAPI code generator) to decide how to handle.  We just specify that their value is associated with the relevant location(s) in the instance.

For solving the general code generation problem for OO languages, that is of intense interest to OpenAPI and we are working with them on how to make that happen.  That work will likely take place in the OpenAPI Specification repository, or in the repository of whichever tool wants to take a shot at designing a vocabulary for it.
