### ISSUE TITLE
spec: be clear that `rel` is a URI (hyper-schema)

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#90]
This line:

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-hyperschema.xml#L567

describes the `rel` LDO keyword as:

> The value of the "rel" property indicates the name of the relation to the target resource. 

While RFC 5988 explains how "rel" works as a concept, the casual phrase "name of the relation" encourages people who might not read RFCs for fun to think this is a free-form namespace.  This can be seen as I muddle through this in issue #47 (Note: I do read RFCs for fun, had read RFC 5988, and knew that unregistered link rels should be URIs, and I still confused myself.  This may say more about me than about the spec's wording, but it's a data point).

We shouldn't duplicate RFC 5988, but a brief mention of the URI-ness and an example of a proper extension URI would help.  Instead, we go on to use an unregistered `rel` of "children" in a later example, with no indication that it is or should be considered differently from the other `rel` in the example, "up" (which is registered):

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-hyperschema.xml#L590

**Comment by awwright** [comment]
Made edits in master, you can close this out if that works for you

**Comment by handrews** [comment]
Is there a reason for saying

> or a normalized URI following the <xref target="RFC3986">URI production of RFC 3986</xref>

instead of just following the bit about RFC 5988 registered relations with a mention of RFC 5988 extension relations?  I know that what you are saying with the RFC3986 reference is the same thing (I think), but offloading the whole concept to RFC 5988 feels cleaner.

I am also curious about the change from "SHOULD NOT be media type dependent" to the much weaker "are not normally media type dependent"; are there signifiant accepted relationships that are media type dependent for anything other than grandfathered reasons?

**Comment by awwright** [comment]
> instead of just following the bit about RFC 5988 registered relations with a mention of RFC 5988 extension relations?

I suppose we could just import the production

> I am also curious about the change from "SHOULD NOT be media type dependent" to the much weaker "are not normally media type dependent"

Because that's a pre-existing fact, and using SHOULD NOT would create a normative statement that isn't ours to make.

**Comment by handrews** [comment]
> Because that's a pre-existing fact, and using "SHOULD NOT" would create a normative statement that isn't ours to make.

Makes sense, thanks!  I don't feel at all strongly about the RFC 5988 vs 3986 thing, so I'll close this.
