### ISSUE TITLE
Why doesn't the applicator meta-schema define "type"?

### ISSUE THREAD

**Issue by ssilverman** [json-schema-org/json-schema-spec#900]
It seems like `"type": ["object", "boolean"]` is missing.

**Comment by Julian** [comment]
Which one? Looks present [here](https://github.com/json-schema-org/json-schema-spec/blob/master/meta/validation.json#L10)

**Comment by ssilverman** [comment]
Oops. I don't know why I put "validator". I meant "applicator".

**Comment by handrews** [comment]
@ssilverman it was either an accident, or I decided that I wanted the vocabulary schemas to constrain the keywords but not the overall type (deferring that to the dialect meta-schema, meaning the schemas that are not under `/meta/` but are instead alongside it).  I don't remember, and either way it's not consistent.

**Comment by Relequestual** [comment]
Given the other schemas in `/meta/` have it defined, it makes sense to add it ot the validation vocabulary meta-schema also.
@ssilverman Feel free to PR this.

**Comment by Relequestual** [comment]
This update needs to be also made for the 2019-09 schemas, and then released to the website.

**Comment by karenetheridge** [comment]
PR created in #968.

**Comment by ssilverman** [comment]
@Relequestual I’m confused. This is already a 2019-09 schema? What else needs to change?

**Comment by ssilverman** [comment]
Ok, I've sorted this out. It's a different branch.

**Comment by Relequestual** [comment]
This is now resolved.
This change along with a few others have been cherrypicked into a PR against the 2019-09 branch.
Then the 2019-09 submodule for the website has been updated to the latest branch, so everyone can get the new meta-schemas.

**Comment by ssilverman** [comment]
I believe this issue can be closed.
