### ISSUE TITLE
Refer to collections of vocabularies as described by meta-schemas as dialects

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#902]
A _dialect_ is a collection of vocabularies plus a set of validation rules for that collection.

A meta-schema that uses `$vocabulary` describes a dialect, and is considered a "dialect meta-schema."  `https://json-schema.org/draft/2019-09/schema` and `https://json-`schema.org/draft/2019-09/meta-schema` are dialect meta-schemas.

A meta-schema describing a dialect consisting of a single vocabulary and its standard syntax is considered to be a "vocabulary meta-schema" as well as being a "dialect meta-schema." `https://json-schema.org/draft/2019-09/meta/validation` and `https://json-schema.org/draft/2019-09/meta/hyper-schema` are vocabulary meta-schemas.

We should make this clear in the spec as the "dialect" terminology has proven helpful in discussions elsewhere.

**Comment by Relequestual** [comment]
Relevent: 

I note that while we talk about how `$schema` represents an identifier for a "feature set", we don't define what that phrase actually means. https://github.com/json-schema-org/json-schema-spec/blob/b615488327ede58b52d21360865714b50e141969/jsonschema-core.xml#L1156-L1158

**Comment by Relequestual** [comment]
Also relevant https://github.com/json-schema-org/json-schema-spec/blob/b615488327ede58b52d21360865714b50e141969/jsonschema-core.xml#L2096-L2097

**Comment by handrews** [comment]
@Relequestual 

> I note that while we talk about how $schema represents an identifier for a "feature set", we don't define what that phrase actually means.

Yup, that's exactly what this is about!  We should say "dialect" rather than "feature set", although the phrase "feature set" may be useful in explaining what a dialect is.  But obviously it is not sufficient on its own to explain it.

I have a spreadsheet of dialect vs vocabulary and I have no idea why I didn't link it when I filed this.

https://docs.google.com/spreadsheets/d/18SIXnzyjXTJZgqeo5W-qIEwq-bNKXb5M76Pq_47r2Is/edit?usp=sharing

**Comment by Relequestual** [comment]
I expect this will be one of the later issues to get closed out when most others for the milestone are done.
Part of a final pass, if you like.

**Comment by Relequestual** [comment]
I can't quite decide if the PR was enough.
I guess all we can ask is we try to confirm this with a final pass.

**Comment by handrews** [comment]
@Relequestual the important thing was to get the term in there at all, so it's "official".  We should definitely look for it in the final pass, but it doesn't have much practical effect if it's missing in a few places.  "dialect" is defined because in my experience it's a good word for a concept that didn't have a word, not because it changes any implementations.
