### ISSUE TITLE
spec: 3rd link in example removed but still referenced

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-spec#91]
This line:

https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-hyperschema.xml#L298

references a third link in the example immediately above.  However, there are only two links (but there was a third in Draft 04).  The link should either be added back or the reference removed.

**Comment by handrews** [comment]
If the third link is restored, then it would need to change its `method` value from "POST" to "post", and the reference would need to be more clear that "post" does not indicate that an HTTP POST should necessarily be used.

**Comment by awwright** [comment]
Check that this seems fixed in master

**Comment by handrews** [comment]
I see that you removed the entire example?  That does fix this problem, although I think that having examples of some sort would be useful.  I need to read through all of the changes so if I still think it needs an example after I do that I can open a new issue.

**Comment by awwright** [comment]
I mean, it's a link relation. How many examples do we need?

**Comment by handrews** [comment]
> I mean, it's a link relation. How many examples do we need?

Good point, we really don't need that many in the spec.  We could develop the examples on the web site further but that's not urgent, and would be a separate issue anyway.
