### ISSUE TITLE
boolean exact value validation

### ISSUE THREAD

**Issue by kwikwag** [json-schema-org/json-schema-spec#919]
According to the specs, it is currently possible to match for exact value for all primitives except bool (string, number and null), and for all constructs (array via tuple validation and object via properties). 

This ability is important when validating in (unit) tests where you would expect exactly a certain value. 

I suggest adding a key ("value" or "exactly") to {"type": "boolean"} to support this.

**Comment by notEthan** [comment]
I think the `const` keyword is what you are looking for.

**Comment by kwikwag** [comment]
Yup!
