### ISSUE TITLE
Link to enumNames proposal is dead

### ISSUE THREAD

**Issue by epicfaace** [json-schema-org/json-schema-spec#921]
We'd like to link to the enumNames proposal because react-jsonschema-form ended up supporting it.

However, this link is dead (https://github.com/rjsf-team/react-jsonschema-form/pull/1752):

https://github.com/json-schema/json-schema/wiki/enumNames-(v5-proposal)

I also can't find it anywhere, not even on http://web.archive.org/. I get how the wiki is outdated now, but it would be good to keep the original links for documentation purposes -- now I don't know if there's any record of the enumNames proposal anymore. Is there one?

(Also, it appears that https://github.com/json-schema-org/json-schema-spec/issues/57 also links to the dead wiki link)

**Comment by awwright** [comment]
You can check out commit 5593a570 on that wiki, which is the last time it was edited. But we more or less lost control of that repo a long time ago, so there's not too much we can do about it.

#57 is probably a better place to link to.

**Comment by handrews** [comment]
@epicfaace we don't maintain old proposals as references, and don't guarantee that #57 will stick around.  If you want to specify that behavior, you should incorporate it into your own project, and/or make it a 3rd-party vocabulary plugin once you get to 2019-09 or later (we'll probably encourage folks to go straight to 2020-06 and skip 2019-09 as 2019-09 hasn't bee widely deployed and 2020-06 will fix some loose ends related to that).
