### ISSUE TITLE
Annotations for un-applied "additional" Items/Properties not consistent

### ISSUE THREAD

**Issue by ssilverman** [json-schema-org/json-schema-spec#927]
For "additionalItems", the spec states:
> If the "additionalItems" subschema is applied to any positions within the instance array, it produces an annotation result of boolean true

For "additionalProperties", the spec states:
> The annotation result of this keyword is the set of instance property names validated by this keyword's subschema.

To me, this implies that "additionalItems" is only applied if there are things to apply it to, and if that set is empty, there's no "additionalItems" annotation. On the other hand, "additionalProperties" seems to imply that it produces an annotation even if the set is empty.

If the keyword is present, and both return `true` for empty sets, I'd like to see these behave the same with regards to annotations. i.e. we either choose to add an annotation or we don't. Since section [10.3.4 Error or Anotation](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10.3.4) states that an "annotation" annotation can be produced for a successful validation, that would seem to lend weight to the preference to produce an annotation for both keywords when they operate on an empty set. Thoughts?

**Comment by ssilverman** [comment]
Also note that both "items" and "properties" seem to add annotations even for empty sets.

**Comment by handrews** [comment]
See PR #925 - `additionalItems` has been removed.

I'm going to close it as the focus on `additionalItems` in that context is confusing and it would be best not to have an issue open that mentions it so prominently.  However...

@ssilverman If you would like to analyze the annotations for all Core/Validation keywords and propose consistent behavior in a new issue, that would be welcome.  You may want to talk with @notEthan who has some concerns around annotations as well, although they're probably different enough that you'll end up filing separate issues.

Generally, when keywords aren't applied they shouldn't produce annotations, but I completely made that up right now on the spot so I'm not at all attached to it.  I'd be inclined to accept any consistent proposal.
