### ISSUE TITLE
Required one of array

### ISSUE THREAD

**Issue by ChildishGiant** [json-schema-org/json-schema-spec#934]
I didn't really know how to phrase the title but the idea is that one should be able to require an array like this:
`"required": [["a","b"], "c"]`
This'd mean the at least one of a or b need to be present but c would always be required. This would add more flexibility to the requirements whilst keeping the syntax tidy

**Comment by karenetheridge** [comment]
You can express that now, a bit more verbosely, with:

    { "anyOf": [ {"required": ["a","c"]}, {"required": ["b","c"]} ] }

**Comment by handrews** [comment]
@ChildishGiant I agree with @karenetheridge here.

As for more concise syntax (whether that's tidier or not is something of a matter of aesthetics), we are not adding such keywords to the main specification.  We have added the ability for 3rd-parties to design and share extension vocabularies.  Keywords that merely simplify syntax are a good candidate for such things, but that is outside of the scope of the Core and Validation specifications, and therefore outside of the scope of this repository.
