### ISSUE TITLE
`"$id"` and `"$ref": "#"` in the same schema

### ISSUE THREAD

**Issue by rjmill** [json-schema-org/json-schema-spec#944]
It might be helpful to add a note in the spec, allowing implementations to raise an error when one schema includes both an `"$id"` and a `"$ref": "#"`. If I understand correctly, this combination will always lead to infinite recursion.

Aside from being helpful to implementers, I think this would be helpful in communicating how "$id" affects the base URI. It could also help illustrate the usefulness of $recursiveRef and $recursiveAnchor.

**Comment by handrews** [comment]
This does not always lead to infinite recursion, and in fact in most cases does not, as instance documents are finite.  All of the meta-schemas did this until we added `$recursiveRef` (and `"$ref": "#"` is still a valid way to write meta-schemas, it just gets complicated to combine meta-schemas that way because you have to re-state things, as shown in the draft-07 hyper-schema meta-schema).

If this isn't clear, I'd recommend raising the question on the slack.

**Comment by notEthan** [comment]
I think the case raised here is not the same as that seen in metaschemas. metaschemas use `$ref: #` but not on the same schema with an `$id`, only subschemas. in the _same_ schema a `$ref: #` adjacent to an absolute `$id` will result in infinite recursion.

as for communicating this, I think it's sufficiently addressed in [core 8.2.4.3. Guarding Against Infinite Recursion
](https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.8.2.4.3)

**Comment by karenetheridge** [comment]
This is an example of a recursive schema back to the root that does not recurse infinitely.

```
{
  "type": ["object", "string"],
  "properties": {
    "child": { "$ref": "#" }
  },
  "maxLength": 10
}
```

example data that all validate:

    "hello"

    { "child": "hello" }

    { "child": { "child": { "child": "hello" } } }


```

**Comment by rjmill** [comment]
@handrews  @karenetheridge Sorry, my original comment was ambiguous. I was was referring to the scenario @notEthan described:

>in the *same* schema a `$ref: #` adjacent to an absolute `$id` will result in infinite recursion.

My question is about **adjacent** `$ref: #` and `$id`.

Using a slightly modified version of @karenetheridge's example:

```
{
  "$id": "http://www.example.com/schemas/",
  "type": ["object", "string"],
  "properties": {
    "child": {
      "$id": "child.json",
      "$ref": "#",
      "$comment": "This $ref would result in infinite recursion, correct?"
    }
  },
  "maxLength": 10
}
```

The interaction between `$ref`/`$id` was confusing to me when I first started transitioning from the OpenAPI "extended subset" of JSON Schema to 2019-09 JSON Schema.

Seeing examples like the one above helped clear up my initial misunderstandings. I thought it was worth bringing up in case it would help other newcomers :slightly_smiling_face:

**Comment by handrews** [comment]
@rjmill yes, that case will recurse infinitely, as will many other less obvious arrangements.  This is the sort of thing that would be great content for a tutorial (either on the json-schema.org web site proper, or as an update to Understanding JSON Schema- I'm not sure where the thought is right now on updating UJS vs starting a new tutorial from scratch, paging @Relequestual ).

The specification itself should contain enough information to allow it to be successfully implemented, and ideally no more.  TBH, the current spec should be trimmed and some of its information moved to a tutorial, but in the past we have not had anywhere else to put it (UJS was maintained elsewhere until recently, and we don't have enough volunteers to keep lots of web site content up to date).
