### ISSUE TITLE
clarification request: "duration" format

### ISSUE THREAD

**Issue by karenetheridge** [json-schema-org/json-schema-spec#947]
cross-reference: https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/402#discussion_r441047373

The spec for the "duration" format (https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.3.1) cites the source as "The duration format is from the ISO 8601 ABNF as given in Appendix A of RFC 3339. "  -- but this document does not contain the revisions from the last 20 years to ISO-8601.  https://en.wikipedia.org/wiki/ISO_8601 gives history here.  Is the intention that the format should be restricted solely to the original standard as summarized in RFC3339, or include the current state of ISO 8601?

**Comment by karenetheridge** [comment]
see also https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/416

**Comment by Relequestual** [comment]
What are the implications of either?

**Comment by karenetheridge** [comment]
@Relequestual the question is arising because we are unsure over in the JSON-Schema-Test-Suite which tests are valid to be included -- and therefore what support we expect from implementations that support formats-as-validations.  The point is we *want* test coverage, but won't add it if it is considered to be out of scope.

Wearing my validator-consumer hat, I would prefer implementations be using the latest standard for a particular format, not an earlier one, as that provides the most utility to me when writing schemas.

Wearing my implementor-author hat (and also JSON-Schema-Test-Suite-member hat), I want the specification to be clear, whichever way that's decided.

**Comment by Relequestual** [comment]
Thanks @karenetheridge 
Are there plenty of readily available libraries for rfc8601?

If so, I'll agree to this change, and recommend it moves to awaiting PR.

Obviously this doesn't effect tests for 2019-09, but will for the next draft. IMHO the spec is clear that it's currently the restricted version found in the RFC. Why that was decided as opposed to the current ISO, I do not know.

Would be interested as an aside if anyone can determine which draft this reference first appeared in. Pre draft 5 and it's anyone's guess.

**Comment by karenetheridge** [comment]
>  Are there plenty of readily available libraries for rfc8601 \[sic\]?

ISO8601 is a *hugely* popular date format, so yes very much so, I would be highly surprised if any language with a JSON Schema implementation would have a hard time dealing with ISO8601 durations.

> Would be interested as an aside if anyone can determine which draft this reference first appeared in. Pre draft 5 and it's anyone's guess.

This isn't difficult - the `duration` format is new in draft2019-09. See commit f0f802f21f. As to why it was written that way, that's on @handrews to explain :)

**Comment by handrews** [comment]
@Relequestual because you have to pay money to be able to read ISO 8601 and not RFC 3339.  That's why RFC 3339 includes that whole appendix in the first place.  To make it accessible to people who don't / can't pay.

**Comment by Julian** [comment]
I don't know about durations specifically, but just on the ISO8601 specifically piece... ISO8601 is a beast. It may be the case that for durations I can find a thing, but for arbitrary parts of ISO8601, it's essentially impossible to find a fully working / spec-compliant parser even in e.g. Python. Everything just parses kind of arbitrary subsets of the most common things, at least in Python.

E.g., `dateutil` is the most common library for some of these things, and its ISO8601 parser doesn't support...: https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.isoparse

(But yeah for durations who knows, I didn't look carefully yet).

**Comment by karenetheridge** [comment]
@handrews RFC3339's Appendix A grammar is 20 years out of date. That's what this whole issue is about.

I found that the [wikipedia page](https://en.wikipedia.org/wiki/ISO_8601) was complete enough for an implementation to write a full parser, and there are some excerpts of the ISO document itself out there available for free (I didn't bookmark them because I found the wikipedia page captured all of the technical details).

**Comment by Relequestual** [comment]
Unless you can see ISO8601, there's no way to tell if the wiki page is enough, or accurate.
It also seems there's an issue over implementations being fully compliant.

Given you have to pay to see ISO8601, it makes writing an implementation (and indeed using said specification) burdensome, and impossible for many.

No, I don't feel this would be a reasonable thing to do.
This will be left as is.

**Comment by karenetheridge** [comment]
I'm surprised to see this closed, given

> Are there plenty of readily available libraries for ISO8601?
> If so, I'll agree to this change, and recommend it moves to awaiting PR.

The additions from the 1989 spec are not complicated. I found them simple enough that my implementation doesn't even call out to an external library to do the parsing; a few small modifications to a regex were all that were needed. Nevertheless, I picked half a dozen popular languages and quickly found ISO8601 libraries for each of them. It's one of the, if not *the*, most common date formats in usage.

> Unless you can see ISO8601, there's no way to tell if the wiki page is enough, or accurate.

Why then is this not used as a justification for not implementing it (or even using it) elsewhere? [As I stated above](https://github.com/json-schema-org/json-schema-spec/issues/947#issuecomment-663877850), there are other sources that copy the relevant details from the official spec that are wholly sufficient for an implementation to be written.

**Comment by handrews** [comment]
@karenetheridge this is `format`.  It's a confusing, poorly-implemented keyword that hardly ever does what people want anyway.  Anyone can add formats or better yet, add keywords that aren't stapled to this particular mess.

**Comment by karenetheridge** [comment]
@handrews I'm not sure where this is best put, but much future wailing and gnashing of teeth might be saved if you posted somewhere that the 'format' keyword is not ever going to see future development (or any changes at all other than deprecation).

**Comment by karenetheridge** [comment]
FWIW, I wasn't necessarily asking for a *change* to the spec, but rather a clarification of the existing spec language. "We aren't changing formats ever" isn't really providing the clarification that I sought.

**Comment by handrews** [comment]
Nothing about `format`'s future is set in stone.  I just think it's a mess that doesn't work and therefore I _personally_ prefer to actively discourage it in favor of other options.  But we can't dump it until there are other, obviously superior options.

**Comment by Relequestual** [comment]
My expectation is to at a later point remove it from validation in favour of its own formal vocabulary.
But, we can't even make the time to lay out a recomended process for defining a vocabulary right now.

We COULD re-open it I guess, but I'm not going to do anything with it for quite some time.
If that's OK with you, we can re-open it.

**Comment by Relequestual** [comment]
@karenetheridge How about duration as per defined in https://www.w3.org/TR/xmlschema11-2/#duration ?
Based on iso8601, but a few deviations.
I do note that XML Schema only references iso8601 as normative. I guess for similar reasons.

Stumbled onto https://github.com/OAI/OpenAPI-Specification/issues/845#issuecomment-378139730

**Comment by Relequestual** [comment]
Talking to the OAS TSC call members, no one was in favour of referencing the ISO.
The consensus was it would create a bad user experience and was against the spirit of an open specification.
