### ISSUE TITLE
Some inconsistencies in output schema

### ISSUE THREAD

**Issue by stan-sb** [json-schema-org/json-schema-spec#949]
https://github.com/json-schema-org/json-schema-spec/blob/master/output/schema.json
https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.10

1. "basic", "detailed" and "verbose" are defined exactly the same, which means, if output is valid for one of them, it is valid for all of them. This means that, unless the output format is flag, the "oneOf" validation would always fail.

2. 
-- Output schema requires "errors" key in case "valid" is false;
-- "errors" is recursively defined as array of "outputUnit"
-- "valid" is required
This means the only way to terminate recursion in case of "valid": false is to include "errors": [], which is misleading.
On the other hand, the output examples sometimes contain "error" key and not "errors". Although not strictly necessary, it'd be good to have "error" defined in the schema.

**Comment by gregsdennis** [comment]
I put in the output schema as kind of a bonus to that section of the spec. It's more of an afterthought than anything. Correct away!

**Comment by gregsdennis** [comment]
This will be addressed by #1285.  The output format has changed considerably anyway, and the associated schema needed to be rewritten.
