### ISSUE TITLE
Spec disagrees with meta-schema for "items" minimum size

### ISSUE THREAD

**Issue by ssilverman** [json-schema-org/json-schema-spec#953]
The meta-schema limits "schemaArray" to have a minimum of 1 element. This applies to "items", "allOf", "anyOf", and "oneOf". However, the specification does not limit to a 1 element minimum. Either the spec should change or the meta-schemas should change.

Update: I'm wrong about "allOf", "anyOf", and "oneOf". The spec DOES say these must be non-empty. Only "items" doesn't appear to specify a minimum size in the spec.

**Comment by karenetheridge** [comment]
I lean towards the schema being more correct here, as it is not useful to have a zero-element schema array. I agree that the spec should explicitly state all restrictions that the schema chooses to enforce. (The reverse is not always possible, e.g. that certain URIs must be normalized.)

**Comment by ssilverman** [comment]
I'm so wrong about "allOf", "anyOf", and "oneOf". The spec DOES say those arrays must be empty. Only "items" seems to disagree.

**Comment by handrews** [comment]
Closing in favor of #975 (decision of which to close was arbitrary)
