### ISSUE TITLE
Specify field is required based on value of another field

### ISSUE THREAD

**Issue by vvksahoo** [json-schema-org/json-schema-spec#955]
I have mentioned two scenarios below, for which i want to generate a jsonschema. If the ```color``` value is ```red``` then  ```redQuote``` will be the required filed in the jsonschema. If it is ```black``` then ```blackQuote``` be the required filed. So required filed of the jsonschema is depend on color value. Let me know how we can achieve this?
Example-1
````
{
 "color": "red",
  "quote": {
                "is_apply": True,
               "redQuote": "something"
               }
}
````
Example-2
````
{
 "color": "black",
  "quote": {
                 "is_apply": True,
               "blackQuote": "something"
               }
}
````

**Comment by karenetheridge** [comment]
See the 'if'/'then'/'else' keywords, or 'dependencies' in draft-07 and 'dependentRequired' in draft2019-09.

**Comment by handrews** [comment]
@vvksahoo what @karenetheridge said :-)

If you want more assistance, you'll most easily find it on our Slack.  There's a join link in the upper right corner of json-schema.org
