### ISSUE TITLE
How to conditionally validate based on the values of external variables or fields in parent json objects?

### ISSUE THREAD

**Issue by HansBrende** [json-schema-org/json-schema-spec#957]
I have posted a bounty on this stackoverflow question: https://stackoverflow.com/questions/54099692/using-if-then-else-schema-validation-conditional-on-values-in-other-json-objects

Essentially, I need conditional validation (if-then-else) where the `if` schema can refer to either some sort of external variable or a field in the parent object. 

I have a postgres table with, for example, the following columns:
```
task_type TEXT
task_partition TEXT
task_payload JSONB
```

Users supply a schema for the `task_payload` on a per-`task_type` basis (in a separate schema table). However, the schema should be able to also refer to the `task_partition` when validating the payload. I do _not_ want users to have to supply a schema that validates the entire row in the postgres table (that would be completely out of scope for the schema they are supplying), _only_ the task_payload. Is there a way to do this?

I was thinking I would construct a schema based off of the user-supplied schema like this:
```
{
    "type": "object",
    "properties": {
        "task_partition: {"type": "string"},
        "task_payload": [insert user-supplied schema for the given task_type here, 
                         which needs to be able to reference the task_partition in its "if"-schemas somehow]
    }
}
```

**Comment by karenetheridge** [comment]
I think you would do something like:

```
{
  type: "object",
  required: [ "task_partition", "task_payload" ],
  if: {
    properties: {
      task_partition: "partition_type_1",
    }
  },
  then: {
    properties: {
      task_payload: {
        ... schema for this payload type...
      }
    }
  }
  { else: .. test for other partition types here, as needed... }
}

```

**Comment by HansBrende** [comment]
@karenetheridge thanks. Unfortunately I don't think that strategy will work however, because that would require the api itself to have knowledge about what subschemas to apply to which sorts of task partitions, which it does not.

Ideally, I'd like to have the user provide a single subschema for the task payload that can simply refer to the task partition of the parent in its "if"-schemas if it wants to, or not, if it doesn't want to.

**Comment by HansBrende** [comment]
Addendum: I just realized that my first syntax proposal is actually no less powerful than the 2nd and 3rd, since you could then specify nested parents to walk your way up the hierarchy (e.g., `"if": {"parent": {"parent": {"properties": {"foo": {"const": "bar"}}}}}` would evaluate to true if the _grandparent_ of the current json object had a `"foo": "bar"` entry.)

**Comment by Relequestual** [comment]
From your linked SO question...

> Jason D: JSON Schema keywords can never access data up the hierarchy, only down. You have to move your if/then up to a level where it can access both values.

It's a philosophical processing model limitation.

The first thing that happens is a Schema is applied to an Instance.
Subschemas are then applied to the correct instance locations.

If you want to allow referenced or resource schemas to "see above" their applicability level, you'll have to come up with some novel way to merge schemas.

Maybe your `then` schema could reference a user provided schema?

Regardless, I'm closing this question.
Happy to try and help you find a solution if you'd like to discuss further. (You'll find me on slack.)
