### ISSUE TITLE
Specification disagrees with schema for exclusiveMinimum and exclusiveMaximum

### ISSUE THREAD

**Issue by Bikeman868** [json-schema-org/json-schema-spec#961]
According to https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.1.3 the exclusiveMinimum and exclusiveMaximum are both boolean, but in http://json-schema.org/draft-07/schema# they are both defined as numbers and http://json-schema.org/draft-08/schema# and http://json-schema.org/draft-09/schema# do not exist.

**Comment by karenetheridge** [comment]
The semantics for exclusiveMaximum and exclusiveMinimum changed between draft-04 and draft-06.

The latest draft is https://json-schema.org/draft/2019-09/schema, defined at https://json-schema.org/specification.html.

**Comment by Relequestual** [comment]
@Bikeman868 you may find this page useful: http://json-schema.org/specification-links.html
It lists all published drafts of JSON Schema and their associated documents, as well as quick links to the associated list of changes (not nessecerily a fully changelog).

Please feel free to come by our super friendly slack server if you have further questions =]
