### ISSUE TITLE
Validation of properties not defined in the schema

### ISSUE THREAD

**Issue by abunuwas** [json-schema-org/json-schema-spec#962]
Given a certain schema, should we invalidate payloads which contain keywords which are not defined in the schema? 

For example, given a schema with the following property:

```json
{
    "properties": {
        "property": {
            "type": "string"
        }
    }
}
```

Is the following payload acceptable or should be invalidated due to the presence of a property which is not defined in the schema?

```
{
    "property": "property",
    "invalid": "invalid"
}
```

**Comment by karenetheridge** [comment]
Take a look at 'required': https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.5.3

**Comment by abunuwas** [comment]
@karenetheridge that's for your detailed answer! `additionalProperties` is actually what I was looking for. This is now resolved so I'm closing the comment

**Comment by Relequestual** [comment]
@abunuwas I see this is closed, but just a pointer...
JSON Schema is a constraints based language. If it's not specifically disallowed, it's allowed.
A Schema of `{}` allows everything.

**Comment by abunuwas** [comment]
@Relequestual thanks for the additional clarification - that makes it all clear!
