### ISSUE TITLE
GeoJson Support

### ISSUE THREAD

**Issue by xyz-mtl** [json-schema-org/json-schema-spec#969]
Hi,
Is there an official standard for geojson objects?

{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[102,0.5]},"properties":{"prop0":"value0"}},{"type":"Feature","geometry":{"type":"LineString","coordinates":[[102,0],[103,1],[104,0],[105,1]]},"properties":{"prop0":"value0","prop1":0}},{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[100,0],[101,0],[101,1],[100,1],[100,0]]]},"properties":{"prop0":"value0","prop1":{"this":"that"}}}]}

**Comment by Relequestual** [comment]
I believe you have the wrong organisation here. JSON Schema just defines JSON Schema.
I think you can find a schema provided by the geojson team at https://github.com/geojson
