### ISSUE TITLE
specification doesn't state if 'prefixItems' array can be empty

### ISSUE THREAD

**Issue by karenetheridge** [json-schema-org/json-schema-spec#975]
The metaschema (meta/applicator.json) specifies that `prefixItems` (formerly the array form of `items`) must have at least one element. However, the specification text does not explicitly state this. It does make this explicit for schema-array keywords such as allOf, e.g. "This keyword's value MUST be a non-empty array." so it should do so here as well.

**Comment by Relequestual** [comment]
Agreed.

**Comment by Relequestual** [comment]
Re-opening because I assume the meta-schema also needs to be updated, and I'm off to sleep now!

**Comment by handrews** [comment]
@Relequestual the meta-schema already required one element, we just needed to make the spec consistent.

**Comment by Relequestual** [comment]
I could have, you know, checked... -_-
