### ISSUE TITLE
Extend enums

### ISSUE THREAD

**Issue by AmjadHD** [json-schema-org/json-schema-spec#979]
This is more of a question, i already searched for a good while but can't come up with an answer.
```json
{
  "type": "object",
  "properties": {
    "class": {
      "enum": [
        "tab_control",
        "sidebar_container",
        "sidebar_label"
      ],
      "attributes": {
        "enum": [
          "hover"
        ]
      }
    }
  },
  "if": {
    "properties": {
      "class": {
        "const": "tab_control"
      }
    }
  },
  "then": {
    "properties": {
      "attributes": {
        "enum": [
          "file_light",
          "file_medium",
          "file_medium_dark",
          "file_dark"
        ]
      }
    }
  }
}
```
How can i make "tab_control" inherit the "hover" attribute in addition to the "file_*" attributes ?

**Comment by Relequestual** [comment]
There's no notion of extending.
You can achive what you want by means of duplication and wrapping in an `anyOf`.
And then, de-duplication by convering the root object properties into `$defs`.

If that's not enough to get you going, do shout, and I can probably help more later. (@ me).

**Comment by Relequestual** [comment]
I'll get back to you during my break =]

**Comment by Relequestual** [comment]
Here we go...

```
{
  "$schema": "http://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "class":{
      "enum": [
        "tab_control",
        "sidebar_container",
        "sidebar_label"
      ]
    },
    "attributes": {
      "enum": [
        "hover"
      ]
    },
    "attributes_tab_control": {
      "enum": [
        "file_light",
        "file_medium",
        "file_medium_dark",
        "file_dark"
      ]
    }
  },
  "type": "object",
  "properties": {
    "class": {
      "$ref": "#/$defs/class"
    }
  },
  "if": {
    "properties": {
      "class": {
        "const": "tab_control"
      }
    }
  },
  "then": {
    "properties": {
      "attributes": {
        "anyOf": [
          { "$ref": "#/$defs/attributes" },
          { "$ref": "#/$defs/attributes_tab_control" }
        ]
      }
    }
  },
  "else":{
    "properties": {
      "attributes": {
        "$ref": "#/$defs/attributes"
      }
    }
  }
}
```

You can test it here: https://jsonschema.dev/s/ZMUQ9
Note, that site doesn't yet support draft 2019-09, but in this situation, you're not using any keywords which differ from draft-07 anyway, so it's functionally the same.

This works in terms of validation. If you were using this to generate a form, you may need to look at the specific library you're using to determine if they support conditional validation (many do not when generating forms from JSON Schema).

**Comment by handrews** [comment]
@AmjadHD I'm assuming this answers the question since you have not asked for further clarification in the past two weeks- if not please re-open or comment further here.
