### ISSUE TITLE
support schemas for empty arrays

### ISSUE THREAD

**Issue by mfulton26** [json-schema-org/json-schema-spec#980]
I need to validate that an array is present and empty under certain scenarios. I tried `"items": []` but that produces and "invalid" schema: `data.items should NOT have fewer than 1 items` (AJV errorsText)

i.e. I'd like to do the following:
```json
{ "type": "array", "items": [] }
```
or maybe:
```json
{ "type": "array", "items": false }
```

But I had to do this instead (maybe there is a better way?):
```json
{ "type": "array", "maxItems": 0 }
```

**Comment by Relequestual** [comment]
What's wrong with `maxItems`?

**Comment by notEthan** [comment]
`"items": false` does what you want. you could also do `"const": []` or maxItems.

**Comment by mfulton26** [comment]
hmmm, `const` seems nice

I suppose nothing is really wrong with `maxItems: 0` it just wasn't what I thought of first and I was surprised when I was informed that `items: []` wasn't valid

**Comment by mfulton26** [comment]
`[1, 2, 3]` validates for me against `items: []` using `ajv`

**Comment by Relequestual** [comment]
That's strange... Looks like `items: false` against `[1,2,3]` works for me.
https://jsonschema.dev/s/SEUZM

The instance would be valid if the array was empty, because the subschema value of `items` is applied to each value in the applicable array.

**Comment by Relequestual** [comment]
`const` may also be a good option, as without it, you'll need to define `type` in order to make the value IS an array in the first place, as you have done.

**Comment by mfulton26** [comment]
this might be a bug in Ajv

https://github.com/ajv-validator/ajv/issues/1270

thanks

**Comment by Relequestual** [comment]
OK. Weird. My site uses a version of ajv, but probably not the latest... =/

**Comment by mfulton26** [comment]
@Relequestual it only seems to be an issue when Ajv is configured with `strictKeywords: true`
