### ISSUE TITLE
Question: Json Schema Draft 2019-09 examples / Use of $vocabulary

### ISSUE THREAD

**Issue by tomsfernandez** [json-schema-org/json-schema-spec#989]
Hi! Awesome work. Is there a place with examples of the use of the $vocabulary keyword in json-schema and a full explanation? I find the spec not very beginner-friendly and these examples could help understand the use case.

**Comment by Relequestual** [comment]
Hey @tomsfernandez - I'm afraid not that I know of.
While the spec document isn't beginner friendly, the APPENDIX in the spec document SHOULD be beginner friendly!

Check out http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.appendix.D
Please do reply with any further questions or if you'd like clarification on anything in that appendix (or just anything).
Also, come by our slack for pretty speedy support! =D

**Comment by Relequestual** [comment]
We'd LOVE to have better documentation on how to do vocabularies, but we've prioritised what little time we have on other things.

Most of the implementers have come by our slack for clarifications, and end up helping with the spec itself! or at least the tests.

**Comment by tomsfernandez** [comment]
Great, thanks! Im closing the issue.

**Comment by gregsdennis** [comment]
@tomsfernandez, I have (what I think is) a pretty good example in my library docs: https://gregsdennis.github.io/json-everything/usage/schema/vocabs.html
