### ISSUE TITLE
Question about section 8.2.4.6. Dereferencing; is the reference to $id incorrect? Should be $anchor?

### ISSUE THREAD

**Issue by jimblackler** [json-schema-org/json-schema-spec#990]
I'm trying to update my validator to 2019-09 and looking for precise info about how to handle new keyword $anchor.

I searched for $ahcnor references in the 2019-09 spec that I have.

"When an implementation encounters the <#/$defs/single> schema, it resolves the "$id" URI reference against the current base URI to form <https://example.net/root.json#item>."

https://github.com/json-schema-org/json-schema-spec/blob/30f315877b47c5b8ee250675a30f1cc77e63ce67/jsonschema-core.xml#L1712

However the snippet above does not include an $id property at defs/single; it has an $anchor property. 

Is that incorrect or have I misunderstood?

**Comment by jdesrosiers** [comment]
Yeah, that looks wrong. Probably something that slipped through the cracks when `$anchor` was split off of `$id`.

Prior to draft 2019-09, `"$anchor": "item"` from that example would have been `"$id": "#item"`. In that form, the description makes sense. `$anchor` should behave exactly like an `$id` starting with a fragment did in previous drafts. The only difference is that the leading `#` is no longer used.
